"""Batch 3: Operations and HR dashboards (numbers 26 to 35)."""

B3 = []

B3.append(dict(
    num=26, slug="crew", brand="Crew", category="HR and Employees", org="Lantern Labs", currency="$",
    tagline="People, teams, time off and reviews for a growing company.",
    auth_line="Look after your people, not paperwork.", user="Hana Ibrahim", user_role="People lead",
    theme=dict(fonts=["Instrument Sans", "Instrument Sans", "JetBrains Mono"], accent="#1e3a8a", layout="tint", card="shadow", radius="12px",
               c2="#93c5fd", c3="#f59e0b", c4="#10b981"),
    kpis=[("Headcount", "int", 248, "users"), ("Open roles", "int", 14, "briefcase"), ("Out today", "int", 9, "calendar"), ("Staff happiness", "pct", 82.4, "heart")],
    chart=dict(title="Headcount", names=["Headcount", "Leavers"], base=220),
    mix=dict(title="People by department", parts=["Engineering", "Sales", "Operations", "Design", "Other"]),
    activity=["Wen Zhang started in Engineering", "Leave approved for Marco Rossi", "Review cycle opened for Q3", "Policy updated: remote work", "Onboarding checklist finished for 3 people", "Birthday today: Sara Silva"],
    entities=[
        dict(singular="Employee", plural="Employees", prefix="", icon="users", desc="Everyone who works here.",
             fields=[("Employee", "person"), ("Department", "choice:Engineering|Sales|Operations|Design|Finance"), ("Role", "words:Engineer|Designer|Account executive|Analyst|Team lead|Support specialist"), ("Start date", "date"), ("Status", "status:Active|On leave|Onboarding")]),
        dict(singular="Team", plural="Teams", prefix="", icon="layers", desc="Teams and who leads them.",
             fields=[("Team", "words:Platform|Growth|Customer success|Brand|Data|Finance ops"), ("Lead", "person"), ("People", "int:3-24"), ("Location", "city"), ("Status", "status:Hiring|Stable")]),
        dict(singular="Time off", plural="Time off", slug="time-off", prefix="", icon="calendar", desc="Holiday and leave requests.",
             fields=[("Employee", "person"), ("Type", "choice:Holiday|Sick|Parental|Personal"), ("From", "date:future"), ("Days", "int:1-14"), ("Status", "status:Approved|Pending|Declined")]),
        dict(singular="Review", plural="Reviews", prefix="", icon="star", desc="Performance reviews this cycle.",
             fields=[("Employee", "person"), ("Reviewer", "person"), ("Cycle", "choice:Q3 2026|Mid-year|Probation"), ("Score", "rating"), ("Status", "status:Done|In progress|Not started")]),
        dict(singular="Document", plural="Documents", prefix="", icon="folder", desc="Contracts and policies.",
             fields=[("Document", "words:Employment contract|Handbook|Remote work policy|NDA|Benefits guide|Offer letter"), ("Employee", "person"), ("Updated", "date"), ("Pages", "int:1-40"), ("Status", "status:Signed|Waiting|Expired")]),
    ],
    specials=[
        dict(title="Org chart", type="ranking", icon="layers", desc="Teams by size.", items=["Platform", "Growth", "Customer success", "Brand", "Data", "Finance ops"], metric="People", scale=0.25),
        dict(title="Leave calendar", type="calendar", icon="calendar", desc="Who is out and when.", items=["Holiday", "Sick day", "Parental leave", "Company offsite", "Public holiday"]),
        dict(title="Onboarding", type="kanban", icon="kanban", desc="New starters from offer to first week.", items=["Offer signed", "Laptop ordered", "First day", "First week", "Done"], cards=["Engineer", "Designer", "Account executive", "Analyst"]),
        dict(title="People report", type="report", icon="chart", desc="Headcount, turnover and happiness.", items=["Headcount", "Turnover", "Time to hire", "Happiness"], rows=["Engineering", "Sales", "Operations", "Design", "Finance"]),
        dict(title="Offices", type="map", icon="map", desc="Where your people work.", items=["London", "Berlin", "Lisbon", "Remote", "New York"]),
        dict(title="Announcements", type="timeline", icon="bell", desc="News shared with the company.", items=["New parental leave policy", "Office closed on Friday", "Welcome to our new starters", "Q3 review cycle is open"]),
        dict(title="HR settings", type="config", icon="settings", desc="Rules for leave and reviews.", items=["Give 25 days of holiday a year", "Carry over up to 5 unused days", "Ask managers to approve leave", "Remind people about reviews every week"]),
    ],
))

B3.append(dict(
    num=27, slug="hireloop", brand="Hireloop", category="Recruitment", org="Kestrel Robotics", currency="$",
    tagline="Jobs, candidates and interviews in one hiring pipeline.",
    auth_line="Hire the right people, faster.", user="Leila Haddad", user_role="Talent partner",
    theme=dict(fonts=["Hanken Grotesk", "Hanken Grotesk", "IBM Plex Mono"], accent="#b45309", layout="light", card="shadow", radius="14px",
               bg="#fbfaf7", surface2="#f5f1ea", line="#ebe4d8", c2="#fcd34d", c3="#0ea5e9", c4="#16a34a"),
    kpis=[("Open jobs", "int", 18, "briefcase"), ("Candidates", "int", 642, "users"), ("Interviews this week", "int", 34, "calendar"), ("Offers accepted", "pct", 86.0, "check")],
    chart=dict(title="Applications", names=["Applications", "Hires"], base=160),
    mix=dict(title="Candidates by source", parts=["Job boards", "Referrals", "LinkedIn", "Careers page", "Agencies"]),
    activity=["Offer accepted by Tomas Novak", "Interview booked for Senior Engineer", "32 new applications for Designer", "Job posted: Product Manager", "Feedback added by Kenji", "Candidate moved to Final round"],
    entities=[
        dict(singular="Job", plural="Jobs", prefix="", icon="briefcase", desc="Roles you are hiring for.",
             fields=[("Job", "words:Senior engineer|Product designer|Product manager|Sales lead|Data analyst|Support specialist"), ("Team", "choice:Engineering|Design|Product|Sales|Support"), ("Applicants", "int:12-240"), ("Posted", "date"), ("Status", "status:Open|On hold|Closed")]),
        dict(singular="Candidate", plural="Candidates", prefix="", icon="user", desc="People who applied.",
             fields=[("Candidate", "person"), ("Job", "words:Senior engineer|Product designer|Product manager|Sales lead"), ("Source", "choice:Referral|LinkedIn|Job board|Careers page"), ("Applied", "date"), ("Stage", "status:Screening|Interview|Offer|Rejected")]),
        dict(singular="Interview", plural="Interviews", prefix="", icon="calendar", desc="Upcoming and past interviews.",
             fields=[("Candidate", "person"), ("Type", "choice:Phone screen|Technical|Culture|Final"), ("Date", "date:future"), ("Time", "time"), ("Status", "status:Scheduled|Done|Cancelled")]),
        dict(singular="Offer", plural="Offers", prefix="OF-", icon="file", desc="Offers you made.",
             fields=[("Offer", "id"), ("Candidate", "person"), ("Salary", "money:45000-160000"), ("Sent", "date"), ("Status", "status:Accepted|Sent|Declined")]),
        dict(singular="Referral", plural="Referrals", prefix="", icon="users", desc="People your team recommended.",
             fields=[("Candidate", "person"), ("Referred by", "person"), ("Job", "words:Senior engineer|Product designer|Sales lead|Data analyst"), ("Date", "date"), ("Status", "status:Hired|Interviewing|New")]),
    ],
    specials=[
        dict(title="Hiring pipeline", type="kanban", icon="kanban", desc="Candidates for every role, stage by stage.", items=["Applied", "Screening", "Interview", "Final round", "Offer"], cards=["Senior engineer", "Product designer", "Product manager", "Sales lead"]),
        dict(title="Interview calendar", type="calendar", icon="calendar", desc="Interviews booked this month.", items=["Phone screen", "Technical interview", "Culture chat", "Final round", "Debrief"]),
        dict(title="Hiring report", type="report", icon="chart", desc="Speed and quality of hiring.", items=["Hires", "Time to hire", "Cost per hire", "Offer acceptance"], rows=["Engineering", "Design", "Product", "Sales", "Support"]),
        dict(title="Top sources", type="ranking", icon="trend", desc="Where your best hires come from.", items=["Referrals", "LinkedIn", "Careers page", "Job boards", "Agencies", "Events"], metric="Hires", scale=0.4),
        dict(title="Candidate messages", type="split", icon="inbox", desc="Emails with candidates.", items=["Thank you for the interview", "Can we reschedule?", "Question about the salary", "I accept the offer!", "Portfolio link"]),
        dict(title="Offer letter", type="document", icon="file", desc="A printable offer letter.", doc="Offer of employment", num="OF-1061", items=["Base salary", "Signing bonus", "Stock options", "Equipment budget"], note="This offer is subject to reference checks. Please reply within 7 days."),
        dict(title="Hiring rules", type="config", icon="settings", desc="How your team hires.", items=["Require two interviews before an offer", "Send rejection emails automatically after 5 days", "Hide candidate names during screening", "Ask interviewers for feedback within 24 hours"]),
    ],
))

B3.append(dict(
    num=28, slug="milestone", brand="Milestone", category="Project Management", org="Arcfield Studio", currency="$",
    tagline="Projects, tasks, budgets and deadlines for client work.",
    auth_line="Deliver projects on time and on budget.", user="Marco Silva", user_role="Delivery director",
    theme=dict(fonts=["Inter Tight", "Inter", "JetBrains Mono", "Inter Tight"], accent="#0e7490", layout="dark", card="border", radius="10px", sidebar="#0f172a",
               c2="#67e8f9", c3="#f97316", c4="#a3e635"),
    kpis=[("Active projects", "int", 24, "folder"), ("Tasks due this week", "int", 118, "check"), ("Budget used", "pct", 64.2, "pie"), ("On-time delivery", "pct", 91.0, "clock")],
    chart=dict(title="Tasks completed", names=["Completed", "Created"], base=320),
    mix=dict(title="Hours by project type", parts=["Websites", "Apps", "Branding", "Content", "Support"]),
    activity=["Milestone reached: Beta launch", "Task moved to Review by Hana", "Budget alert on Harbor app", "New project: Cedar rebrand", "Client approved designs", "Sprint 14 started"],
    entities=[
        dict(singular="Project", plural="Projects", prefix="PRJ-", icon="folder", desc="Every project in progress.",
             fields=[("Project", "words:Harbor app|Cedar rebrand|Maple website|Atlas dashboard|Beacon campaign|Oak intranet"), ("Client", "company"), ("Budget", "money:8000-240000"), ("Due", "date:future"), ("Status", "status:On track|At risk|Delayed|Done")]),
        dict(singular="Task", plural="Tasks", prefix="T-", icon="check", desc="Work to be done.",
             fields=[("Task", "words:Design home page|Write API docs|Set up analytics|Fix login bug|Client review|Prepare demo"), ("Project", "words:Harbor app|Cedar rebrand|Maple website|Atlas dashboard"), ("Owner", "person"), ("Due", "date:future"), ("Status", "status:To do|In progress|Review|Done")]),
        dict(singular="Milestone", plural="Milestones", prefix="", icon="star", desc="Big moments in each project.",
             fields=[("Milestone", "words:Kick-off|Design sign-off|Beta launch|Go live|Handover"), ("Project", "words:Harbor app|Cedar rebrand|Maple website|Atlas dashboard"), ("Date", "date:future"), ("Tasks left", "int:0-40"), ("Status", "status:On track|At risk|Done")]),
        dict(singular="Client", plural="Clients", prefix="", icon="building", desc="Who you are working for.",
             fields=[("Client", "company"), ("Contact", "person"), ("Projects", "int:1-6"), ("Billed", "money:10000-400000"), ("Status", "status:Active|Paused")]),
        dict(singular="Risk", plural="Risks", prefix="R-", icon="alert", desc="Things that could go wrong.",
             fields=[("Risk", "words:Client feedback delayed|Key developer on leave|Scope creep|Third-party API change|Budget overrun"), ("Project", "words:Harbor app|Cedar rebrand|Maple website"), ("Impact", "choice:High|Medium|Low"), ("Raised", "date"), ("Status", "status:Open|Mitigated|Closed")]),
    ],
    specials=[
        dict(title="Board", type="kanban", icon="kanban", desc="Tasks across all projects.", items=["Backlog", "To do", "In progress", "Review", "Done"], cards=["Design home page", "Write API docs", "Fix login bug", "Client review", "Prepare demo"]),
        dict(title="Timeline", type="timeline", icon="clock", desc="Key milestones for the Harbor app.", items=["Kick-off with the client", "Design sign-off", "Development sprint 1 to 6", "Beta launch", "Go live"]),
        dict(title="Deadlines", type="calendar", icon="calendar", desc="Due dates and client meetings.", items=["Client review", "Sprint demo", "Milestone due", "Invoice", "Team retro"]),
        dict(title="Budget report", type="report", icon="chart", desc="Budget used versus planned.", items=["Budget used", "Hours logged", "Profit margin", "Forecast"], rows=["Harbor app", "Cedar rebrand", "Maple website", "Atlas dashboard", "Beacon campaign"]),
        dict(title="Workload", type="ranking", icon="users", desc="Open tasks per person.", items=["Marco Silva", "Hana Sato", "Isaac Chen", "Julia Walsh", "Kenji Rossi", "Leila Okafor"], metric="Open tasks", scale=0.3),
        dict(title="Status report", type="document", icon="file", desc="A weekly update for the client.", doc="Weekly status report", num="Harbor app, week 38", items=["Design hours", "Development hours", "Testing hours", "Project management"], note="All milestones are on track. Next review is on Thursday."),
        dict(title="Project settings", type="config", icon="settings", desc="How projects work in your team.", items=["Warn at 80 percent of budget", "Ask for time logs every Friday", "Share status reports with clients", "Archive projects 30 days after handover"]),
    ],
))

B3.append(dict(
    num=29, slug="taskboard", brand="Taskboard", category="Kanban Tasks", org="Pebble Games", currency="$",
    tagline="Simple boards and task lists for small teams that ship every week.",
    auth_line="Less planning. More doing.", user="Noah Kim", user_role="Team lead",
    theme=dict(fonts=["Karla", "Karla", "Space Mono"], accent="#059669", layout="accent", card="flat", radius="12px",
               surface2="#eef2ef", c2="#6ee7b7", c3="#f59e0b", c4="#8b5cf6"),
    kpis=[("Open tasks", "int", 146, "list"), ("Done this week", "int", 64, "check"), ("Overdue", "int", 7, "alert"), ("Cycle time days", "int", 3, "clock")],
    chart=dict(title="Tasks done per week", names=["Done", "Added"], base=60),
    mix=dict(title="Tasks by label", parts=["Bug", "Feature", "Art", "Sound", "Chore"]),
    activity=["Task 'Boss fight music' moved to Done", "New board created: Launch", "Comment on 'Menu bug'", "Due date changed on 'Trailer cut'", "Checklist finished: Level 3", "Label added: Bug"],
    entities=[
        dict(singular="Task", plural="Tasks", prefix="#", icon="check", desc="Every task on every board.",
             fields=[("Task", "words:Boss fight music|Fix menu bug|Level 3 art|Trailer cut|Save system|Tutorial text|Steam page"), ("Board", "choice:Game|Launch|Art|Sound"), ("Assignee", "person"), ("Due", "date:future"), ("Status", "status:To do|Doing|Review|Done")]),
        dict(singular="Board", plural="Boards", prefix="", icon="kanban", desc="Boards for each kind of work.",
             fields=[("Board", "words:Game|Launch|Art|Sound|Marketing|Bugs"), ("Tasks", "int:10-90"), ("Members", "int:2-9"), ("Updated", "date"), ("Status", "status:Active|Archived")]),
        dict(singular="Sprint", plural="Sprints", prefix="", icon="zap", desc="Weekly goals.",
             fields=[("Sprint", "words:Week 36|Week 37|Week 38|Week 39|Week 40"), ("Goal", "words:Playable demo|Level 3 done|Trailer ready|Bug bash|Steam page live"), ("Tasks", "int:12-40"), ("Done", "pct:30-100"), ("Status", "status:Active|Done|Planned")]),
        dict(singular="Member", plural="Members", prefix="", icon="users", desc="People on the team.",
             fields=[("Member", "person"), ("Role", "choice:Programmer|Artist|Sound|Producer|Writer"), ("Open tasks", "int:1-20"), ("Done this week", "int:0-14"), ("Status", "status:Available|Busy|Away")]),
        dict(singular="Label", plural="Labels", prefix="", icon="tag", desc="Tags for sorting tasks.",
             fields=[("Label", "words:Bug|Feature|Art|Sound|Chore|Blocked|Quick win"), ("Tasks", "int:2-60"), ("Color", "choice:Red|Green|Blue|Yellow|Purple"), ("Created", "date"), ("Status", "status:Active|Hidden")]),
    ],
    specials=[
        dict(title="Main board", type="kanban", icon="kanban", desc="This week's work.", items=["To do", "Doing", "Review", "Done"], cards=["Boss fight music", "Fix menu bug", "Level 3 art", "Trailer cut", "Save system"]),
        dict(title="Launch board", type="kanban", icon="zap", desc="Everything for launch day.", items=["Ideas", "Ready", "In progress", "Shipped"], cards=["Steam page", "Press kit", "Launch trailer", "Discord event"]),
        dict(title="Calendar", type="calendar", icon="calendar", desc="Due dates at a glance.", items=["Demo build", "Trailer due", "Playtest", "Sprint review", "Steam sale"]),
        dict(title="Progress", type="report", icon="chart", desc="How much the team gets done.", items=["Tasks done", "Cycle time", "Bugs fixed", "Overdue"], rows=["Game", "Launch", "Art", "Sound", "Bugs"]),
        dict(title="Most active", type="ranking", icon="star", desc="Tasks done this month.", items=["Noah Kim", "Amara Diaz", "Ben Tanaka", "Chloe Varga", "Dina Young"], metric="Tasks", scale=0.5),
        dict(title="Recent changes", type="timeline", icon="activity", desc="What changed on your boards.", items=["Boss fight music moved to Done", "Menu bug assigned to Ben", "Trailer cut due date moved", "Level 3 art checklist finished"]),
        dict(title="Board settings", type="config", icon="settings", desc="How your boards behave.", items=["Limit Doing to 3 tasks per person", "Archive done tasks after 14 days", "Post daily summary in chat", "Ask for a reviewer before Done"]),
    ],
))

B3.append(dict(
    num=30, slug="hourglass", brand="Hourglass", category="Time Tracking", org="Fieldnote Agency", currency="$",
    tagline="Track hours, bill clients and see where the week went.",
    auth_line="Know where every hour goes.", user="Paula Ferreira", user_role="Operations manager",
    theme=dict(fonts=["Work Sans", "Work Sans", "Roboto Mono"], accent="#9a3412", layout="light", card="flat", radius="8px",
               bg="#fbf9f6", surface2="#f3eee7", line="#e7dfd3", c2="#fdba74", c3="#0f766e", c4="#6366f1"),
    kpis=[("Hours this week", "int", 612, "clock"), ("Billable", "pct", 78.4, "dollar"), ("Unbilled amount", "money", 24800, "receipt"), ("People tracking", "int", 21, "users")],
    chart=dict(title="Hours tracked", names=["Billable", "Non-billable"], base=540),
    mix=dict(title="Hours by client", parts=["Maple Foods", "Harbor Health", "Oak Studio", "Internal", "Other"]),
    activity=["Timesheet approved for week 38", "Paula tracked 7h 20m", "Invoice created from 42 hours", "Reminder sent to 3 people", "Project budget 90 percent used", "New task added: Workshop prep"],
    entities=[
        dict(singular="Time entry", plural="Time entries", slug="time-entries", prefix="", icon="clock", desc="Every block of time tracked.",
             fields=[("Task", "words:Design|Meeting|Development|Research|Admin|Writing"), ("Project", "words:Maple website|Harbor app|Oak brand|Internal"), ("Person", "person"), ("Time", "duration"), ("Status", "status:Billable|Non-billable|Approved")]),
        dict(singular="Timesheet", plural="Timesheets", prefix="", icon="list", desc="Weekly timesheets.",
             fields=[("Person", "person"), ("Week", "words:Week 36|Week 37|Week 38|Week 39"), ("Hours", "int:20-48"), ("Billable", "pct:40-95"), ("Status", "status:Approved|Submitted|Missing")]),
        dict(singular="Project", plural="Projects", prefix="", icon="folder", desc="Projects you track time against.",
             fields=[("Project", "words:Maple website|Harbor app|Oak brand|Cedar campaign|Internal"), ("Client", "company"), ("Hours", "int:40-900"), ("Budget used", "pct:10-110"), ("Status", "status:Active|Over budget|Done")]),
        dict(singular="Client", plural="Clients", prefix="", icon="building", desc="Clients and their rates.",
             fields=[("Client", "company"), ("Rate", "money:60-180"), ("Hours this month", "int:10-300"), ("Unbilled", "money:0-18000"), ("Status", "status:Active|Paused")]),
        dict(singular="Invoice", plural="Invoices", prefix="INV-", icon="file", desc="Invoices made from tracked time.",
             fields=[("Invoice", "id"), ("Client", "company"), ("Hours", "int:8-160"), ("Amount", "money:800-24000"), ("Status", "status:Paid|Sent|Draft")]),
    ],
    specials=[
        dict(title="Week view", type="calendar", icon="calendar", desc="Tracked time on the calendar.", items=["Design", "Client meeting", "Development", "Admin", "Workshop"]),
        dict(title="Time report", type="report", icon="chart", desc="Billable time by client and person.", items=["Hours", "Billable rate", "Revenue", "Utilisation"], rows=["Maple Foods", "Harbor Health", "Oak Studio", "Cedar Works", "Internal"]),
        dict(title="Utilisation", type="ranking", icon="users", desc="Billable share for each person.", items=["Paula Ferreira", "Omar Jensen", "Nadia Chen", "Luis Walsh", "Kavya Adams", "Ben Morris"], metric="Billable hours", scale=1.2),
        dict(title="Approvals", type="kanban", icon="kanban", desc="Timesheets waiting for approval.", items=["Missing", "Submitted", "Approved", "Invoiced"], cards=["Week 38", "Week 37", "Week 36"]),
        dict(title="Invoice from time", type="document", icon="receipt", desc="An invoice built from tracked hours.", doc="Invoice", num="INV-2026-0418", items=["Design, 24 hours", "Development, 36 hours", "Project management, 8 hours", "Workshop"]),
        dict(title="Live timers", type="monitor", icon="monitor", desc="Who is tracking right now.", items=["Paula: Maple website", "Omar: Harbor app", "Nadia: Oak brand", "Luis: Internal", "Kavya: Research", "Ben: Admin"], unit=" min"),
        dict(title="Tracking rules", type="config", icon="settings", desc="How time is tracked and approved.", items=["Remind people who have not tracked by 5pm", "Round entries to 15 minutes", "Lock timesheets after approval", "Stop timers running over 10 hours"]),
    ],
))

B3.append(dict(
    num=31, slug="stockroom", brand="Stockroom", category="Inventory and Warehouse", org="Brightline Home Goods", currency="$",
    tagline="Stock levels, purchase orders and warehouse moves in real time.",
    auth_line="The right stock, in the right place.", user="Tomas Novak", user_role="Warehouse manager",
    theme=dict(fonts=["Barlow", "Barlow", "IBM Plex Mono"], accent="#1d4ed8", layout="dark", card="border", radius="6px", sidebar="#111827",
               c2="#93c5fd", c3="#f59e0b", c4="#10b981"),
    kpis=[("Stock value", "money", 1840000, "box"), ("Items low on stock", "int", 38, "alert"), ("Orders to pick", "int", 214, "cart"), ("Fill rate", "pct", 97.2, "check")],
    chart=dict(title="Stock value", names=["Stock value", "Sold"], base=1600000),
    mix=dict(title="Stock by category", parts=["Kitchen", "Bedding", "Lighting", "Storage", "Decor"]),
    activity=["Purchase order PO-5521 received", "Low stock: linen duvet cover", "Cycle count finished in aisle 4", "Transfer sent to Leeds warehouse", "Returned items put away", "New supplier added"],
    entities=[
        dict(singular="Product", plural="Products", prefix="SKU-", icon="box", desc="Everything you stock.",
             fields=[("Product", "words:Linen duvet cover|Ceramic mug set|Oak shelf|Table lamp|Storage basket|Wool throw"), ("SKU", "code:SKU-"), ("On hand", "int:0-900"), ("Value", "money:200-40000"), ("Status", "status:In stock|Low|Out of stock")]),
        dict(singular="Purchase order", plural="Purchase orders", slug="purchase-orders", prefix="PO-", icon="file", desc="Stock you ordered from suppliers.",
             fields=[("Order", "id"), ("Supplier", "company"), ("Items", "int:10-900"), ("Value", "money:1000-80000"), ("Status", "status:Received|Ordered|Delayed")]),
        dict(singular="Location", plural="Locations", prefix="", icon="pin", desc="Warehouses and bins.",
             fields=[("Location", "words:Aisle 1 bay A|Aisle 2 bay C|Aisle 4 bay B|Mezzanine|Returns area|Leeds warehouse"), ("Items", "int:40-2000"), ("Capacity used", "pct:20-98"), ("Last count", "date"), ("Status", "status:Normal|Nearly full|Blocked")]),
        dict(singular="Supplier", plural="Suppliers", prefix="", icon="building", desc="Who you buy from.",
             fields=[("Supplier", "company"), ("Country", "choice:Portugal|India|Vietnam|UK|Turkey"), ("Lead time days", "int:5-60"), ("On-time", "pct:70-99"), ("Status", "status:Approved|On review")]),
        dict(singular="Stock movement", plural="Stock movements", slug="stock-movements", prefix="MV-", icon="truck", desc="Everything that came in or went out.",
             fields=[("Movement", "id"), ("Product", "words:Linen duvet cover|Ceramic mug set|Oak shelf|Table lamp"), ("Type", "choice:Received|Picked|Transferred|Returned|Adjusted"), ("Quantity", "int:1-400"), ("Status", "status:Done|In progress")]),
    ],
    specials=[
        dict(title="Reorder list", type="kanban", icon="kanban", desc="Items to reorder, from alert to arrival.", items=["Low stock", "Draft order", "Ordered", "In transit", "Received"], cards=["Linen duvet cover", "Ceramic mug set", "Table lamp", "Wool throw"]),
        dict(title="Warehouse map", type="map", icon="map", desc="How full each area is.", items=["Aisle 1", "Aisle 2", "Aisle 3", "Aisle 4", "Mezzanine"]),
        dict(title="Stock report", type="report", icon="chart", desc="Value, turnover and waste.", items=["Stock value", "Turnover", "Days of stock", "Write-offs"], rows=["Kitchen", "Bedding", "Lighting", "Storage", "Decor"]),
        dict(title="Fast movers", type="ranking", icon="trend", desc="Products selling the fastest.", items=["Ceramic mug set", "Linen duvet cover", "Wool throw", "Table lamp", "Storage basket", "Oak shelf"], metric="Units sold", scale=12),
        dict(title="Dock schedule", type="calendar", icon="calendar", desc="Deliveries arriving at the dock.", items=["Delivery", "Collection", "Cycle count", "Returns pickup", "Audit"]),
        dict(title="Packing slip", type="document", icon="receipt", desc="A printable slip for an outgoing order.", doc="Packing slip", num="Order #48211", items=["Linen duvet cover, double", "Ceramic mug set", "Wool throw, grey"]),
        dict(title="Stock rules", type="config", icon="settings", desc="Automatic stock settings.", items=["Alert when stock falls below 20 units", "Draft purchase orders automatically", "Count each aisle every 30 days", "Reserve stock for paid orders"]),
    ],
))

B3.append(dict(
    num=32, slug="convoy", brand="Convoy", category="Logistics and Fleet", org="Swiftline Freight", currency="$",
    tagline="Vehicles, drivers, routes and deliveries for a freight company.",
    auth_line="Every truck, every route, on one screen.", user="Victor Walsh", user_role="Fleet manager",
    theme=dict(fonts=["Montserrat", "Open Sans", "Roboto Mono", "Montserrat"], accent="#ea580c", layout="light", card="shadow", radius="10px",
               c2="#fdba74", c3="#2563eb", c4="#16a34a"),
    kpis=[("Deliveries today", "int", 842, "truck"), ("On-time", "pct", 94.6, "clock"), ("Vehicles on the road", "int", 64, "map"), ("Fuel cost this week", "money", 18400, "zap")],
    chart=dict(title="Deliveries", names=["Delivered", "Planned"], base=780),
    mix=dict(title="Fleet by vehicle", parts=["Vans", "Box trucks", "Articulated", "Refrigerated", "Cars"]),
    activity=["Route 14 finished early", "Vehicle TX-221 due for service", "Driver checked in: Omar", "Delivery failed: customer not home", "Fuel card used in Denver", "New route planned for Monday"],
    entities=[
        dict(singular="Delivery", plural="Deliveries", slug="deliveries", prefix="DL-", icon="box", desc="Parcels and loads on the move.",
             fields=[("Delivery", "id"), ("Customer", "company"), ("City", "city"), ("Driver", "person"), ("Status", "status:Delivered|Out for delivery|Delayed|Failed")]),
        dict(singular="Vehicle", plural="Vehicles", prefix="TX-", icon="truck", desc="Your fleet.",
             fields=[("Vehicle", "id"), ("Type", "choice:Van|Box truck|Articulated|Refrigerated"), ("Mileage", "int:12000-340000"), ("Next service", "date:future"), ("Status", "status:On the road|Available|Maintenance")]),
        dict(singular="Driver", plural="Drivers", prefix="", icon="user", desc="Drivers and their hours.",
             fields=[("Driver", "person"), ("Licence", "choice:Van|Rigid|Articulated"), ("Hours this week", "int:10-48"), ("Rating", "rating"), ("Status", "status:Driving|Resting|Off duty")]),
        dict(singular="Route", plural="Routes", prefix="R-", icon="map", desc="Planned runs.",
             fields=[("Route", "id"), ("Start", "city"), ("Stops", "int:6-40"), ("Distance km", "int:40-900"), ("Status", "status:Done|In progress|Planned")]),
        dict(singular="Fuel log", plural="Fuel logs", slug="fuel-logs", prefix="", icon="zap", desc="Fuel bought for each vehicle.",
             fields=[("Vehicle", "code:TX-"), ("Station", "city"), ("Date", "date"), ("Cost", "money:60-900"), ("Status", "status:Approved|Review")]),
    ],
    specials=[
        dict(title="Live map", type="map", icon="map", desc="Where your vehicles are right now.", items=["North depot", "City centre", "Airport zone", "Industrial park", "South depot"], dots=22),
        dict(title="Dispatch board", type="kanban", icon="kanban", desc="Jobs from booked to delivered.", items=["Booked", "Assigned", "Loading", "On the road", "Delivered"], cards=["Pallet delivery", "Multi-drop run", "Cold chain load", "Express parcel"], who="company"),
        dict(title="Fleet health", type="monitor", icon="activity", desc="Live checks on each vehicle.", items=["TX-201", "TX-208", "TX-214", "TX-221", "TX-230", "TX-236", "TX-240", "TX-247"], unit="%"),
        dict(title="Delivery report", type="report", icon="chart", desc="Speed, cost and failures.", items=["On-time rate", "Cost per drop", "Failed deliveries", "Kilometres"], rows=["North depot", "South depot", "City", "Airport", "Industrial"]),
        dict(title="Service schedule", type="calendar", icon="calendar", desc="Vehicle services and inspections.", items=["Service", "MOT", "Tyre change", "Inspection", "Driver training"]),
        dict(title="Top drivers", type="ranking", icon="star", desc="Most on-time drivers this month.", items=["Omar Jensen", "Liam Costa", "Maya Rossi", "Noah Patel", "Sara Kim", "Yusuf Ali"], metric="Drops", scale=6),
        dict(title="Delivery note", type="document", icon="file", desc="A proof of delivery.", doc="Delivery note", num="DL-1047", items=["Pallet, household goods", "Pallet, electrical", "Loose cartons"], note="Signed by the customer at 10:42. Photo proof is stored with the delivery."),
    ],
))

B3.append(dict(
    num=33, slug="supplyline", brand="Supplyline", category="Supply Chain", org="Verde Foods Group", currency="$",
    tagline="Suppliers, shipments and demand planning across the whole chain.",
    auth_line="From farm to shelf, with no surprises.", user="Elena Moreau", user_role="Supply chain director",
    theme=dict(fonts=["Cabin", "Cabin", "Fira Code"], accent="#0d9488", layout="tint", card="border", radius="10px",
               c2="#99f6e4", c3="#f59e0b", c4="#6366f1"),
    kpis=[("Shipments in transit", "int", 126, "truck"), ("Supplier on-time", "pct", 92.4, "clock"), ("Stock cover days", "int", 21, "box"), ("Spend this quarter", "money", 6420000, "dollar")],
    chart=dict(title="Demand and supply", names=["Supply", "Demand"], base=4200),
    mix=dict(title="Spend by category", parts=["Fresh produce", "Packaging", "Dairy", "Logistics", "Other"]),
    activity=["Shipment SH-882 cleared customs", "Supplier risk raised for Delta Farms", "Forecast updated for October", "New contract signed with Cedar Packaging", "Delay reported at Lisbon port", "Quality check passed for 12 pallets"],
    entities=[
        dict(singular="Supplier", plural="Suppliers", prefix="", icon="building", desc="Farms, factories and partners.",
             fields=[("Supplier", "company"), ("Category", "choice:Fresh produce|Packaging|Dairy|Logistics|Ingredients"), ("Country", "choice:Spain|Kenya|Netherlands|Brazil|Poland"), ("Score", "pct:60-99"), ("Risk", "status:Low|Medium|High")]),
        dict(singular="Shipment", plural="Shipments", prefix="SH-", icon="truck", desc="Goods on the way.",
             fields=[("Shipment", "id"), ("From", "city"), ("Mode", "choice:Sea|Road|Air|Rail"), ("Arrives", "date:future"), ("Status", "status:On time|Delayed|Customs|Delivered")]),
        dict(singular="Order", plural="Purchase orders", slug="purchase-orders", prefix="PO-", icon="file", desc="Orders placed with suppliers.",
             fields=[("Order", "id"), ("Supplier", "company"), ("Value", "money:4000-400000"), ("Ordered", "date"), ("Status", "status:Confirmed|Pending|Cancelled")]),
        dict(singular="Forecast", plural="Forecasts", prefix="", icon="trend", desc="Expected demand by product.",
             fields=[("Product", "words:Tomatoes|Avocados|Oat milk|Salad bags|Berries|Cheese"), ("Next month", "int:200-9000"), ("Accuracy", "pct:70-98"), ("Updated", "date"), ("Status", "status:On track|Watch|Shortage")]),
        dict(singular="Contract", plural="Contracts", prefix="CT-", icon="briefcase", desc="Supplier agreements.",
             fields=[("Contract", "id"), ("Supplier", "company"), ("Value", "money:20000-2000000"), ("Ends", "date:future"), ("Status", "status:Active|Renewal due|Expired")]),
    ],
    specials=[
        dict(title="Shipment map", type="map", icon="globe", desc="Shipments moving around the world.", items=["Europe", "Africa", "South America", "Asia", "North America"], dots=18),
        dict(title="Supplier risk", type="monitor", icon="shield", desc="Live risk signals from key suppliers.", items=["Delta Farms", "Cedar Packaging", "Summit Dairy", "Atlas Logistics", "Maple Growers", "River Ingredients"], unit=" score"),
        dict(title="Planning board", type="kanban", icon="kanban", desc="Demand plans from draft to confirmed.", items=["Draft", "Sales review", "Supplier check", "Confirmed"], cards=["Tomatoes October", "Berries winter", "Oat milk promo", "Salad bags"]),
        dict(title="Supply report", type="report", icon="chart", desc="Cost, speed and reliability.", items=["Spend", "On-time", "Lead time", "Waste"], rows=["Fresh produce", "Packaging", "Dairy", "Logistics", "Ingredients"]),
        dict(title="Best suppliers", type="ranking", icon="star", desc="Suppliers with the best scores.", items=["Summit Dairy", "Maple Growers", "Cedar Packaging", "Atlas Logistics", "River Ingredients", "Delta Farms"], metric="Score", scale=1),
        dict(title="Delivery windows", type="calendar", icon="calendar", desc="Arrivals at distribution centres.", items=["Sea freight", "Road delivery", "Air cargo", "Quality check", "Supplier visit"]),
        dict(title="Issue log", type="timeline", icon="alert", desc="Problems and how they were solved.", items=["Port strike delayed 4 containers", "Temperature alarm on truck 12", "Wrong labels on 2 pallets", "Supplier switched for berries"]),
    ],
))

B3.append(dict(
    num=34, slug="forge", brand="Forge", category="Manufacturing", org="Ridgeway Components", currency="$",
    tagline="Machines, work orders and quality on the factory floor.",
    auth_line="Keep the line running.", user="Kenji Evans", user_role="Plant manager",
    theme=dict(fonts=["Chakra Petch", "Inter", "Share Tech Mono", "Chakra Petch"], accent="#f59e0b", on_accent="#111827", layout="dark", card="border", radius="4px", sidebar="#0b0f14",
               c2="#94a3b8", c3="#ef4444", c4="#22c55e"),
    kpis=[("Units today", "int", 18420, "box"), ("Line efficiency", "pct", 87.6, "activity"), ("Scrap rate", "pct", 1.8, "alert"), ("Machines running", "int", 42, "tool")],
    chart=dict(title="Units produced", names=["Produced", "Target"], base=16000),
    mix=dict(title="Downtime causes", parts=["Changeover", "Breakdown", "Material", "Quality", "Other"]),
    activity=["Line 3 back online", "Work order WO-7712 finished", "Quality hold on batch B-219", "Maintenance done on press 7", "Shift B started", "Material shortage: steel coil"],
    entities=[
        dict(singular="Work order", plural="Work orders", slug="work-orders", prefix="WO-", icon="file", desc="Jobs scheduled on the floor.",
             fields=[("Work order", "id"), ("Part", "words:Bracket A12|Housing C4|Gear set G2|Valve body V9|Shaft S7"), ("Quantity", "int:200-9000"), ("Due", "date:future"), ("Status", "status:Running|Queued|Done|On hold")]),
        dict(singular="Machine", plural="Machines", prefix="M-", icon="tool", desc="Presses, lathes and robots.",
             fields=[("Machine", "id"), ("Type", "choice:Press|Lathe|Robot arm|Welder|CNC mill"), ("Line", "choice:Line 1|Line 2|Line 3|Line 4"), ("Uptime", "pct:70-99"), ("Status", "status:Running|Idle|Maintenance|Down")]),
        dict(singular="Batch", plural="Batches", prefix="B-", icon="layers", desc="Production batches and quality.",
             fields=[("Batch", "id"), ("Part", "words:Bracket A12|Housing C4|Gear set G2|Valve body V9"), ("Units", "int:100-5000"), ("Defects", "int:0-80"), ("Status", "status:Passed|Hold|Failed")]),
        dict(singular="Material", plural="Materials", prefix="", icon="box", desc="Raw materials in stock.",
             fields=[("Material", "words:Steel coil|Aluminium bar|Plastic pellets|Bolts M8|Paint|Copper wire"), ("On hand", "int:10-4000"), ("Reorder at", "int:50-800"), ("Supplier", "company"), ("Status", "status:In stock|Low|Out of stock")]),
        dict(singular="Maintenance job", plural="Maintenance", slug="maintenance", prefix="MJ-", icon="settings", desc="Planned and urgent repairs.",
             fields=[("Job", "id"), ("Machine", "code:M-"), ("Type", "choice:Planned|Urgent|Inspection"), ("Date", "date:future"), ("Status", "status:Scheduled|In progress|Done")]),
    ],
    specials=[
        dict(title="Floor monitor", type="monitor", icon="monitor", desc="Live status of every line.", items=["Line 1 press", "Line 1 robot", "Line 2 lathe", "Line 2 welder", "Line 3 CNC", "Line 3 robot", "Line 4 press", "Paint booth"]),
        dict(title="Production plan", type="kanban", icon="kanban", desc="Work orders by stage.", items=["Planned", "Material ready", "Running", "Quality check", "Shipped"], cards=["Bracket A12", "Housing C4", "Gear set G2", "Valve body V9"]),
        dict(title="Quality report", type="report", icon="chart", desc="Defects and scrap by part.", items=["First pass yield", "Scrap cost", "Defects", "Returns"], rows=["Bracket A12", "Housing C4", "Gear set G2", "Valve body V9", "Shaft S7"]),
        dict(title="Shift calendar", type="calendar", icon="calendar", desc="Shifts and planned stops.", items=["Shift A", "Shift B", "Night shift", "Planned stop", "Safety drill"]),
        dict(title="Downtime", type="ranking", icon="alert", desc="Machines with the most downtime.", items=["Press 7", "Robot 3", "Lathe 2", "Welder 5", "CNC 1", "Press 2"], metric="Minutes", scale=4),
        dict(title="Shift log", type="timeline", icon="clock", desc="What happened on the last shift.", items=["Line 3 stopped for material", "Changeover on press 7 took 22 minutes", "Batch B-219 put on hold", "Line 3 restarted"]),
        dict(title="Safety rules", type="config", icon="shield", desc="Safety and quality settings.", items=["Stop the line when a guard is open", "Require sign-off after maintenance", "Hold batches with over 2 percent defects", "Alert the supervisor on long stops"]),
    ],
))

B3.append(dict(
    num=35, slug="groundwork", brand="Groundwork", category="Construction", org="Stonebridge Builders", currency="$",
    tagline="Sites, schedules, costs and safety for a building contractor.",
    auth_line="Build on time. Build safe.", user="Ethan Mensah", user_role="Project director",
    theme=dict(fonts=["Oswald", "Source Sans 3", "Source Code Pro", "Oswald"], accent="#ca8a04", on_accent="#1c1917", layout="light", card="border", radius="4px",
               bg="#fafaf9", surface2="#f5f5f4", line="#e7e5e4", c2="#78716c", c3="#dc2626", c4="#2563eb"),
    kpis=[("Active sites", "int", 12, "building"), ("Contract value", "money", 48600000, "dollar"), ("Days without incident", "int", 64, "shield"), ("Budget used", "pct", 58.4, "pie")],
    chart=dict(title="Cost to date", names=["Actual cost", "Planned cost"], base=3800000),
    mix=dict(title="Cost by trade", parts=["Groundworks", "Structure", "Mechanical", "Electrical", "Finishes"]),
    activity=["Concrete pour done at Riverside", "Safety inspection passed", "Change order approved: extra windows", "Crane booked for Tuesday", "Delivery of steel beams", "Snag list updated for Oak Court"],
    entities=[
        dict(singular="Project", plural="Projects", prefix="", icon="building", desc="Every site you are building.",
             fields=[("Project", "words:Riverside flats|Oak Court homes|Harbor offices|Maple school|City library|Park warehouse"), ("Client", "company"), ("Value", "money:800000-18000000"), ("Completion", "date:future"), ("Status", "status:On track|At risk|Delayed")]),
        dict(singular="Task", plural="Tasks", prefix="", icon="check", desc="Work planned on site.",
             fields=[("Task", "words:Foundations|Steel frame|Roofing|Plumbing first fix|Electrics|Plastering|Landscaping"), ("Site", "words:Riverside flats|Oak Court homes|Harbor offices|Maple school"), ("Crew", "choice:Groundworks|Steel|Roofing|Plumbing|Electrical"), ("Due", "date:future"), ("Status", "status:Done|In progress|Planned|Blocked")]),
        dict(singular="Subcontractor", plural="Subcontractors", prefix="", icon="users", desc="Trades working on your sites.",
             fields=[("Company", "company"), ("Trade", "choice:Groundworks|Steel|Roofing|Plumbing|Electrical|Glazing"), ("Sites", "int:1-5"), ("Contract", "money:40000-2400000"), ("Status", "status:Approved|On review")]),
        dict(singular="Change order", plural="Change orders", slug="change-orders", prefix="CO-", icon="file", desc="Changes to the original plan.",
             fields=[("Change", "id"), ("Site", "words:Riverside flats|Oak Court homes|Harbor offices"), ("Reason", "choice:Client request|Design change|Site condition|Material swap"), ("Cost", "money:2000-240000"), ("Status", "status:Approved|Pending|Rejected")]),
        dict(singular="Inspection", plural="Inspections", prefix="", icon="shield", desc="Safety and quality checks.",
             fields=[("Inspection", "words:Scaffold check|Fire safety|Electrical test|Concrete test|Site audit"), ("Site", "words:Riverside flats|Oak Court homes|Harbor offices|Maple school"), ("Date", "date"), ("Issues", "int:0-8"), ("Status", "status:Passed|Actions needed|Failed")]),
    ],
    specials=[
        dict(title="Programme", type="timeline", icon="clock", desc="Key stages for Riverside flats.", items=["Site set up and fencing", "Foundations and groundworks", "Steel frame complete", "Roof on and watertight", "Fit out and handover"]),
        dict(title="Site board", type="kanban", icon="kanban", desc="Work packages by stage.", items=["Planned", "Materials ordered", "In progress", "Snagging", "Complete"], cards=["Foundations", "Steel frame", "Roofing", "Electrics", "Plastering"]),
        dict(title="Site map", type="map", icon="map", desc="Your active sites.", items=["Riverside", "Oak Court", "Harbor", "Maple", "Park"]),
        dict(title="Cost report", type="report", icon="chart", desc="Budget, actual cost and forecast.", items=["Cost to date", "Forecast final cost", "Margin", "Change orders"], rows=["Groundworks", "Structure", "Mechanical", "Electrical", "Finishes"]),
        dict(title="Site diary", type="calendar", icon="calendar", desc="Deliveries, pours and inspections.", items=["Concrete pour", "Crane booked", "Steel delivery", "Inspection", "Client visit"]),
        dict(title="Daily report", type="document", icon="file", desc="A printable daily site report.", doc="Daily site report", num="Riverside flats, 23 September 2026", items=["Groundworks crew, 8 people", "Steel crew, 6 people", "Plant hire", "Materials delivered"], note="Weather dry, 17 degrees. No incidents. Next pour booked for Thursday."),
        dict(title="Safety checks", type="config", icon="shield", desc="Safety rules for every site.", items=["Daily toolbox talk before work", "Stop work in winds over 40 mph", "Log every visitor at the gate", "Weekly scaffold inspection"]),
    ],
))
