"""Batch 1: Finance and business dashboards (numbers 6 to 15)."""

B1 = []

B1.append(dict(
    num=6, slug="tally", brand="Tally", category="Accounting", org="Brightwater Accounting", currency="$",
    tagline="Books, bills and bank feeds for a small accounting practice, all in one place.",
    auth_line="Keep every client's books in order.", user="Maya Patel", user_role="Senior accountant",
    theme=dict(fonts=["Manrope", "Inter", "IBM Plex Mono"], accent="#0f766e", layout="light", card="border", radius="8px",
               c2="#94a3b8", c3="#f59e0b", c4="#6366f1"),
    kpis=[("Money in this month", "money", 184000, "trend"), ("Money out", "money", 121000, "dollar"),
          ("Unpaid invoices", "money", 38400, "file"), ("Clients", "int", 142, "users")],
    chart=dict(title="Income and expenses", names=["Income", "Expenses"], base=150000),
    mix=dict(title="Expenses by type", parts=["Payroll", "Rent", "Software", "Travel", "Other"]),
    activity=["Reconciled 42 bank transactions", "Sent invoice INV-1188 to Maple Foods", "Approved expense claim",
              "Closed the August books for Oak Studio", "Added a new client", "Uploaded 12 receipts"],
    entities=[
        dict(singular="Client", plural="Clients", prefix="CL-", icon="users", desc="Businesses whose books you manage.",
             fields=[("Client", "company"), ("Contact", "person"), ("Plan", "choice:Monthly books|Payroll only|Year end|Full service"),
                     ("Monthly fee", "money:150-2400"), ("Status", "status:Active|Onboarding|Paused"), ("Since", "date")]),
        dict(singular="Invoice", plural="Invoices", prefix="INV-", icon="file", desc="Invoices you sent to clients.",
             fields=[("Invoice", "id"), ("Client", "company"), ("Issued", "date"), ("Amount", "money:200-9000"), ("Status", "status:Paid|Due|Overdue|Draft")]),
        dict(singular="Bill", plural="Bills", prefix="BL-", icon="receipt", desc="Bills your clients need to pay to suppliers.",
             fields=[("Bill", "id"), ("Supplier", "company"), ("Due", "date:future"), ("Amount", "money:80-6000"), ("Status", "status:Scheduled|Paid|Overdue")]),
        dict(singular="Transaction", plural="Transactions", prefix="TX-", icon="card", desc="Bank feed lines waiting to be matched.",
             fields=[("Reference", "id"), ("Description", "words:Card payment|Transfer in|Direct debit|Cash deposit|Standing order"),
                     ("Account", "choice:Business current|Savings|Credit card"), ("Amount", "money:10-12000"), ("Status", "status:Matched|Unmatched|Review")]),
        dict(singular="Account", plural="Chart of accounts", slug="chart-of-accounts", prefix="", icon="book", desc="The accounts every transaction is posted to.",
             fields=[("Account", "words:Sales|Cost of sales|Rent|Utilities|Software|Wages|VAT control|Bank"), ("Code", "code:"),
                     ("Type", "choice:Income|Expense|Asset|Liability"), ("Balance", "money:500-90000"), ("Status", "status:Active|Archived")]),
    ],
    specials=[
        dict(title="Profit and loss", type="report", icon="chart", desc="How much each client made and spent this period.", items=["Revenue", "Gross profit", "Operating costs", "Net margin"], rows=["Sales", "Cost of sales", "Wages", "Rent", "Software", "Marketing"]),
        dict(title="Balance sheet", type="report", icon="layers", desc="Assets, liabilities and equity at a glance.", items=["Total assets", "Liabilities", "Equity", "Current ratio"], rows=["Cash at bank", "Receivables", "Equipment", "Payables", "Loans", "Retained earnings"]),
        dict(title="Reconciliation", type="kanban", icon="check", desc="Match bank lines to invoices and bills.", items=["To match", "Suggested match", "Needs review", "Done"], cards=["Card payment", "Transfer in", "Direct debit", "Supplier refund"], money=True, who="company"),
        dict(title="Tax deadlines", type="calendar", icon="calendar", desc="VAT, payroll and year-end dates for every client.", items=["VAT return", "Payroll filing", "Year-end accounts", "Client call", "Tax payment"]),
        dict(title="Client invoice", type="document", icon="receipt", desc="A printable invoice for your monthly fee.", doc="Invoice", num="INV-2026-1188", items=["Monthly bookkeeping", "Payroll for 12 staff", "VAT return", "Year-end advice call"]),
        dict(title="Receipts inbox", type="split", icon="inbox", desc="Receipts clients emailed you, ready to file.", items=["Receipt from Harbor Office Supply", "Fuel receipt, 3 items", "Software subscription invoice", "Train tickets for client visit", "Coffee with supplier"]),
        dict(title="Automation rules", type="config", icon="zap", desc="Rules that file transactions for you.", items=["Match card payments under $50 to Office costs", "Send overdue reminders after 7 days", "Tag Uber rides as Travel", "Email clients when books are closed"]),
    ],
    faq=[("How do I add a new client?", "Open Clients, click New client and fill in their details and plan.")],
))

B1.append(dict(
    num=7, slug="nestegg", brand="Nestegg", category="Personal Finance", org="Household budget", currency="$",
    tagline="Track spending, set budgets and grow savings for your household.",
    auth_line="See where your money goes, then decide where it should.", user="Daniel Okafor", user_role="Household admin",
    theme=dict(fonts=["Fraunces", "Nunito Sans", "JetBrains Mono", "Nunito Sans"], accent="#c2410c", layout="tint", card="shadow", radius="16px",
               bg="#fbf8f4", surface2="#f6efe7", line="#ece3d8", c2="#84a98c", c3="#e9c46a", c4="#577590"),
    kpis=[("Spent this month", "money", 3240, "cart"), ("Left in budget", "money", 1180, "pie"), ("Saved this year", "money", 8420, "trend"), ("Savings rate", "pct", 18.4, "heart")],
    chart=dict(title="Spending and income", names=["Income", "Spending"], base=5200),
    mix=dict(title="Where your money went", parts=["Home", "Food", "Transport", "Fun", "Other"]),
    activity=["Grocery shop added to Food", "Moved $200 to Holiday fund", "Electricity bill paid", "New budget set for Transport", "Salary received", "Gym membership renewed"],
    entities=[
        dict(singular="Transaction", plural="Transactions", prefix="", icon="card", desc="Everything you spent and received.",
             fields=[("Payee", "words:Fresh Market|City Transit|Netflix|Corner Cafe|Power Co.|Salary|Pharmacy|Bookshop"), ("Category", "choice:Food|Home|Transport|Fun|Health|Income"),
                     ("Date", "date"), ("Amount", "money:3-900"), ("Status", "status:Cleared|Pending")]),
        dict(singular="Budget", plural="Budgets", prefix="", icon="pie", desc="Monthly limits for each kind of spending.",
             fields=[("Budget", "words:Groceries|Eating out|Rent|Transport|Streaming|Clothes|Gifts|Health"), ("Limit", "money:50-1600"), ("Spent", "money:20-1500"), ("Used", "pct:20-110"), ("Status", "status:On track|At risk|Over")]),
        dict(singular="Goal", plural="Savings goals", slug="savings-goals", prefix="", icon="star", desc="What you are saving for.",
             fields=[("Goal", "words:Emergency fund|Summer holiday|New laptop|House deposit|Wedding|Car"), ("Target", "money:800-30000"), ("Saved", "money:100-12000"), ("Deadline", "date:future"), ("Status", "status:On track|Behind|Done")]),
        dict(singular="Bill", plural="Bills", prefix="", icon="receipt", desc="Regular bills and when they are due.",
             fields=[("Bill", "words:Rent|Electricity|Water|Internet|Phone|Insurance|Council tax"), ("Due", "date:future"), ("Amount", "money:20-1400"), ("Pay from", "choice:Joint account|Credit card"), ("Status", "status:Scheduled|Paid|Overdue")]),
        dict(singular="Account", plural="Accounts", prefix="", icon="building", desc="Bank accounts, cards and savings.",
             fields=[("Account", "words:Joint current|Easy saver|Credit card|Kids savings|Pension|Investment ISA"), ("Bank", "company"), ("Balance", "money:100-45000"), ("Type", "choice:Current|Savings|Credit|Investment"), ("Status", "status:Connected|Needs login")]),
    ],
    specials=[
        dict(title="Monthly review", type="report", icon="chart", desc="How this month compares with the last one.", items=["Total spending", "Savings rate", "Biggest category", "Money left"], rows=["Groceries", "Rent", "Transport", "Eating out", "Streaming", "Gifts"]),
        dict(title="Bill calendar", type="calendar", icon="calendar", desc="Every bill and payday this month.", items=["Rent", "Payday", "Electricity", "Phone bill", "Insurance", "Streaming"]),
        dict(title="Net worth", type="report", icon="trend", desc="What you own minus what you owe.", items=["Net worth", "Debt paid off", "Assets", "Change this year"], rows=["Current account", "Savings", "Pension", "Investments", "Credit card", "Car loan"]),
        dict(title="Subscriptions", type="ranking", icon="list", desc="Your repeat payments, from most to least expensive.", items=["Gym", "Streaming bundle", "Mobile plan", "Cloud storage", "Music", "News app", "Meal kit"], metric="Per year", scale=5),
        dict(title="Spending by place", type="map", icon="pin", desc="Where you spend money around town.", items=["City centre", "Near home", "Near work", "Online", "Travel"]),
        dict(title="Money tips", type="timeline", icon="help", desc="Small changes that add up.", items=["Your streaming costs went up 12 percent this year", "You spent less on eating out than last month", "Your emergency fund covers 3 months", "A cheaper phone plan could save $120 a year"]),
        dict(title="Alerts", type="config", icon="bell", desc="Choose what Nestegg tells you about.", items=["Warn me at 80 percent of a budget", "Tell me when a bill is 3 days away", "Weekly spending summary", "Large purchase over $300"]),
    ],
    faq=[("Is my bank login stored?", "No. In a real version you would connect through your bank's secure link. This template only shows demo data.")],
))

B1.append(dict(
    num=8, slug="harbor", brand="Harbor", category="Banking", org="Harbor Community Bank", currency="$",
    tagline="Branch and back-office view for a community bank: accounts, loans and risk.",
    auth_line="Banking operations, clearly organised.", user="Grace Hughes", user_role="Operations manager",
    theme=dict(fonts=["Sora", "Sora", "Roboto Mono", "Sora"], accent="#1d4ed8", layout="dark", card="shadow", radius="12px", sidebar="#0b1b3f",
               c2="#93c5fd", c3="#f59e0b", c4="#10b981"),
    kpis=[("Total deposits", "money", 48200000, "building"), ("Loans outstanding", "money", 31600000, "briefcase"), ("New accounts", "int", 412, "users"), ("Flagged payments", "int", 17, "shield")],
    chart=dict(title="Deposits and loans", names=["Deposits", "Loans"], base=42000000),
    mix=dict(title="Customers by segment", parts=["Personal", "Small business", "Corporate", "Students", "Other"]),
    activity=["Approved a mortgage for Oak Group", "Flagged a transfer for review", "Opened 12 new savings accounts", "Updated the daily cash position", "Closed a dormant account", "Raised the card fraud rule score"],
    entities=[
        dict(singular="Customer", plural="Customers", prefix="C-", icon="users", desc="People and businesses who bank with you.",
             fields=[("Customer", "person"), ("Segment", "choice:Personal|Small business|Corporate|Student"), ("Branch", "city"), ("Balance", "money:500-900000"), ("KYC", "status:Verified|Review|Expired")]),
        dict(singular="Account", plural="Accounts", prefix="AC-", icon="card", desc="Current, savings and business accounts.",
             fields=[("Account", "id"), ("Holder", "person"), ("Type", "choice:Current|Savings|Business|Fixed deposit"), ("Balance", "money:100-500000"), ("Status", "status:Active|Dormant|Frozen")]),
        dict(singular="Loan", plural="Loans", prefix="LN-", icon="briefcase", desc="Loan applications and active loans.",
             fields=[("Loan", "id"), ("Borrower", "person"), ("Product", "choice:Mortgage|Car loan|Personal|Business line"), ("Amount", "money:5000-750000"), ("Status", "status:Approved|In review|Declined|Active")]),
        dict(singular="Payment", plural="Payments", prefix="PY-", icon="zap", desc="Transfers moving in and out today.",
             fields=[("Payment", "id"), ("From", "person"), ("To", "company"), ("Amount", "money:20-250000"), ("Status", "status:Settled|Pending|Flagged|Failed")]),
        dict(singular="Branch", plural="Branches", prefix="", icon="building", desc="Your branches and how busy they are.",
             fields=[("Branch", "city"), ("Manager", "person"), ("Customers", "int:800-24000"), ("Deposits", "money:900000-9000000"), ("Status", "status:Open|Limited hours|Closed")]),
    ],
    specials=[
        dict(title="Risk and fraud", type="monitor", icon="shield", desc="Live checks on payments, logins and cards.", items=["Card fraud score", "Login anomalies", "Large transfers", "Sanctions screening", "Chargebacks", "ATM network", "Online banking", "Wire queue"]),
        dict(title="Loan pipeline", type="kanban", icon="kanban", desc="Every loan from application to payout.", items=["Applied", "Documents", "Underwriting", "Approved", "Paid out"], cards=["Mortgage", "Car loan", "Personal loan", "Business line"], money=True),
        dict(title="Cash position", type="report", icon="chart", desc="Liquidity and reserves for today.", items=["Cash on hand", "Reserve ratio", "Net outflow", "Loan to deposit"], rows=["Main vault", "ATMs", "Central bank", "Correspondent banks", "Branch tills"]),
        dict(title="Branch map", type="map", icon="map", desc="Deposits and visits by branch.", items=["Downtown", "Riverside", "Airport", "University", "Old Town"]),
        dict(title="Compliance tasks", type="calendar", icon="calendar", desc="Regulatory reports and audits.", items=["Liquidity report", "AML review", "Audit visit", "Board meeting", "Stress test"]),
        dict(title="Account statement", type="document", icon="file", desc="A monthly statement ready to print.", doc="Account statement", num="AC-1047 September 2026", items=["Opening balance", "Salary credit", "Card spending", "Standing orders", "Interest earned"], note="This statement is a demo. Balances are made up."),
        dict(title="Customer messages", type="split", icon="message", desc="Secure messages from customers.", items=["Question about my mortgage rate", "Card blocked while travelling", "Change of address", "Business account documents", "Dispute a payment"]),
    ],
))

B1.append(dict(
    num=9, slug="mintline", brand="Mintline", category="Crypto Portfolio", org="Personal portfolio", currency="$",
    tagline="Follow your coins, wallets and trades in one clear portfolio view.",
    auth_line="Your whole crypto portfolio, in one calm view.", user="Kenji Tanaka", user_role="Portfolio owner",
    theme=dict(fonts=["Space Grotesk", "Inter", "Space Mono", "Space Grotesk"], accent="#7c3aed", layout="dark", card="border", radius="14px", sidebar="#120d24",
               c2="#22d3ee", c3="#f59e0b", c4="#10b981"),
    kpis=[("Portfolio value", "money", 86400, "trend"), ("24h change", "money", 2140, "activity"), ("Realised profit", "money", 12800, "dollar"), ("Assets held", "int", 14, "layers")],
    chart=dict(title="Portfolio value", names=["Portfolio", "Deposits"], base=62000),
    mix=dict(title="Holdings", parts=["BTC", "ETH", "SOL", "Stablecoins", "Other"]),
    activity=["Bought 0.12 BTC", "Moved USDC to cold wallet", "Staking reward received", "Price alert: ETH above target", "Sold 40 SOL", "Connected a new exchange"],
    entities=[
        dict(singular="Asset", plural="Assets", prefix="", icon="layers", desc="Every coin and token you hold.",
             fields=[("Asset", "words:Bitcoin|Ether|Solana|USD Coin|Chainlink|Polygon|Cardano|Avalanche"), ("Holding", "pct:0.1-40"), ("Price", "money:0.5-68000"), ("Value", "money:200-40000"), ("24h", "status:Up|Flat|Down")]),
        dict(singular="Trade", plural="Trades", prefix="T-", icon="activity", desc="Buys, sells and swaps.",
             fields=[("Trade", "id"), ("Pair", "words:BTC/USD|ETH/USD|SOL/USDC|ETH/BTC|LINK/USD"), ("Side", "choice:Buy|Sell|Swap"), ("Amount", "money:50-9000"), ("Status", "status:Filled|Open|Cancelled")]),
        dict(singular="Wallet", plural="Wallets", prefix="", icon="key", desc="Hardware, exchange and software wallets.",
             fields=[("Wallet", "words:Cold storage|Exchange main|Mobile wallet|DeFi wallet|Savings vault"), ("Network", "choice:Bitcoin|Ethereum|Solana|Polygon"), ("Balance", "money:100-50000"), ("Last used", "date"), ("Status", "status:Synced|Syncing|Offline")]),
        dict(singular="Transfer", plural="Transfers", prefix="TR-", icon="zap", desc="Deposits and withdrawals between wallets.",
             fields=[("Transfer", "id"), ("Asset", "choice:BTC|ETH|SOL|USDC"), ("Direction", "choice:In|Out"), ("Amount", "money:20-15000"), ("Status", "status:Confirmed|Pending|Failed")]),
        dict(singular="Alert", plural="Price alerts", slug="price-alerts", prefix="", icon="bell", desc="Get told when prices move.",
             fields=[("Alert", "words:BTC above 70k|ETH below 2.5k|SOL up 10% in a day|Portfolio down 5%|Gas fees low"), ("Asset", "choice:BTC|ETH|SOL|All"), ("Created", "date"), ("Triggered", "int:0-9"), ("Status", "status:Active|Paused|Triggered")]),
    ],
    specials=[
        dict(title="Performance", type="report", icon="chart", desc="Returns over time for your whole portfolio.", items=["Total return", "Best asset", "Fees paid", "Win rate"], rows=["Bitcoin", "Ether", "Solana", "Chainlink", "Stablecoins"]),
        dict(title="Market watch", type="monitor", icon="monitor", desc="Live prices for coins you follow.", items=["BTC", "ETH", "SOL", "LINK", "AVAX", "MATIC", "ADA", "DOT"], unit="%"),
        dict(title="Top movers", type="ranking", icon="trend", desc="The biggest moves in your portfolio this week.", items=["Solana", "Chainlink", "Ether", "Avalanche", "Bitcoin", "Polygon", "Cardano"], metric="Gain", scale=1),
        dict(title="Staking rewards", type="timeline", icon="star", desc="Rewards paid into your wallets.", items=["0.42 SOL reward paid", "0.01 ETH reward paid", "Validator changed", "Reward rate updated to 5.1 percent", "0.39 SOL reward paid"]),
        dict(title="Tax report", type="document", icon="receipt", desc="Gains and losses for this tax year.", doc="Capital gains summary", num="Tax year 2025 to 2026", items=["Bitcoin disposals", "Ether disposals", "Solana disposals", "Staking income", "Fees"]),
        dict(title="Trading calendar", type="calendar", icon="calendar", desc="Planned buys and important dates.", items=["Monthly buy", "Token unlock", "Rebalance", "Tax deadline", "Earnings call"]),
        dict(title="Security", type="config", icon="shield", desc="Keep your accounts safe.", items=["Require a code for every withdrawal", "Allow withdrawals only to saved addresses", "Email me on new sign-ins", "Lock the app after 5 minutes"]),
    ],
    faq=[("Is this financial advice?", "No. This is a dashboard template with made-up numbers.")],
))

B1.append(dict(
    num=10, slug="ticker", brand="Ticker", category="Stock Trading", org="Ticker Brokerage", currency="$",
    tagline="Watchlists, orders and positions for an active trader.",
    auth_line="Trade with a clear head and clear numbers.", user="Sofia Rossi", user_role="Trader",
    theme=dict(fonts=["IBM Plex Sans", "IBM Plex Sans", "IBM Plex Mono", "IBM Plex Mono"], accent="#15803d", layout="light", card="flat", radius="6px",
               c2="#64748b", c3="#dc2626", c4="#2563eb"),
    kpis=[("Account value", "money", 248000, "briefcase"), ("Today", "money", 3120, "activity"), ("Buying power", "money", 41200, "dollar"), ("Open positions", "int", 23, "layers")],
    chart=dict(title="Account value", names=["Account", "S and P 500"], base=210000),
    mix=dict(title="Allocation", parts=["Tech", "Health", "Energy", "Finance", "Cash"]),
    activity=["Bought 20 shares of NVTR", "Limit order placed on HLTH", "Dividend received from ENRG", "Stop loss triggered on RETL", "Added FINX to watchlist", "Deposited $5,000"],
    entities=[
        dict(singular="Position", plural="Positions", prefix="", icon="layers", desc="Stocks you own right now.",
             fields=[("Symbol", "words:NVTR|HLTH|ENRG|FINX|RETL|CLDX|AUTO|FOOD"), ("Shares", "int:5-900"), ("Avg cost", "money:12-640"), ("Value", "money:800-60000"), ("Day", "status:Up|Flat|Down")]),
        dict(singular="Order", plural="Orders", prefix="O-", icon="list", desc="Market, limit and stop orders.",
             fields=[("Order", "id"), ("Symbol", "words:NVTR|HLTH|ENRG|FINX|RETL|CLDX"), ("Type", "choice:Market|Limit|Stop|Stop limit"), ("Value", "money:300-20000"), ("Status", "status:Filled|Working|Cancelled|Rejected")]),
        dict(singular="Watchlist", plural="Watchlists", prefix="", icon="star", desc="Stocks you are keeping an eye on.",
             fields=[("List", "words:Tech leaders|Dividend picks|Earnings this week|Small caps|Energy|Healthcare"), ("Symbols", "int:4-30"), ("Change", "pct:-4-6"), ("Updated", "date"), ("Status", "status:Active|Archived")]),
        dict(singular="Dividend", plural="Dividends", prefix="", icon="dollar", desc="Payouts from companies you own.",
             fields=[("Symbol", "words:ENRG|FINX|FOOD|HLTH|AUTO"), ("Ex date", "date"), ("Per share", "money:0.1-3"), ("Total", "money:8-900"), ("Status", "status:Paid|Scheduled")]),
        dict(singular="Transfer", plural="Transfers", prefix="TF-", icon="zap", desc="Money in and out of your account.",
             fields=[("Transfer", "id"), ("Method", "choice:Bank transfer|Card|Wire"), ("Date", "date"), ("Amount", "money:100-25000"), ("Status", "status:Completed|Pending|Failed")]),
    ],
    specials=[
        dict(title="Market overview", type="monitor", icon="monitor", desc="Indexes and sectors, updated live.", items=["S and P 500", "Nasdaq", "Dow", "Tech sector", "Energy sector", "Health sector", "10 year yield", "Gold"]),
        dict(title="Earnings calendar", type="calendar", icon="calendar", desc="When your companies report results.", items=["NVTR earnings", "HLTH earnings", "FINX dividend", "Fed decision", "Jobs report"]),
        dict(title="Performance", type="report", icon="chart", desc="Returns compared with the market.", items=["Total return", "Win rate", "Best month", "Fees"], rows=["Tech", "Health", "Energy", "Finance", "Consumer"]),
        dict(title="Top gainers", type="ranking", icon="trend", desc="Your best performing stocks this month.", items=["NVTR", "CLDX", "HLTH", "FINX", "AUTO", "ENRG", "FOOD"], metric="Gain in $", scale=40),
        dict(title="Trade journal", type="timeline", icon="book", desc="Notes on why you made each trade.", items=["Bought NVTR after strong earnings", "Trimmed ENRG after a 20 percent run", "Stopped out of RETL", "Started a position in CLDX"]),
        dict(title="Trade confirmation", type="document", icon="file", desc="Printable confirmation for a filled order.", doc="Trade confirmation", num="O-1054", items=["NVTR bought at market", "Commission", "Regulatory fee"]),
        dict(title="Risk settings", type="config", icon="shield", desc="Limits that protect your account.", items=["Block orders over 10 percent of the account", "Ask before trading on margin", "Warn me before earnings", "Daily loss limit of $2,000"]),
    ],
))

B1.append(dict(
    num=11, slug="shieldpoint", brand="Shieldpoint", category="Insurance", org="Shieldpoint Insurance Agency", currency="$",
    tagline="Policies, claims and renewals for an independent insurance agency.",
    auth_line="Every policy and claim, looked after.", user="Omar Haddad", user_role="Agency principal",
    theme=dict(fonts=["Outfit", "Outfit", "DM Mono", "Outfit"], accent="#0369a1", layout="accent", card="shadow", radius="12px",
               c2="#7dd3fc", c3="#f59e0b", c4="#16a34a"),
    kpis=[("Written premium", "money", 1240000, "dollar"), ("Active policies", "int", 3860, "shield"), ("Open claims", "int", 74, "alert"), ("Renewal rate", "pct", 91.2, "check")],
    chart=dict(title="Premium written", names=["This year", "Last year"], base=980000),
    mix=dict(title="Policies by line", parts=["Auto", "Home", "Business", "Life", "Travel"]),
    activity=["New auto policy bound for Chen family", "Claim CLM-1122 approved", "Renewal reminder sent to 40 clients", "Quote requested for a bakery", "Payment received for policy HM-2231", "Adjuster assigned to storm claim"],
    entities=[
        dict(singular="Policy", plural="Policies", prefix="POL-", icon="shield", desc="Policies you have placed for clients.",
             fields=[("Policy", "id"), ("Holder", "person"), ("Line", "choice:Auto|Home|Business|Life|Travel"), ("Premium", "money:300-12000"), ("Status", "status:Active|Renewal due|Lapsed")]),
        dict(singular="Claim", plural="Claims", prefix="CLM-", icon="alert", desc="Claims your clients have made.",
             fields=[("Claim", "id"), ("Claimant", "person"), ("Type", "choice:Car accident|Water damage|Theft|Storm|Medical"), ("Amount", "money:400-80000"), ("Status", "status:Approved|Investigating|Submitted|Declined")]),
        dict(singular="Client", plural="Clients", prefix="", icon="users", desc="Households and businesses you insure.",
             fields=[("Client", "person"), ("Policies", "int:1-6"), ("City", "city"), ("Lifetime premium", "money:500-60000"), ("Status", "status:Active|Prospect|Inactive")]),
        dict(singular="Quote", plural="Quotes", prefix="Q-", icon="file", desc="Quotes waiting for a decision.",
             fields=[("Quote", "id"), ("Prospect", "company"), ("Line", "choice:Business|Home|Auto|Liability"), ("Premium", "money:400-15000"), ("Status", "status:Sent|Accepted|Expired|Draft")]),
        dict(singular="Carrier", plural="Carriers", prefix="", icon="building", desc="Insurance companies you work with.",
             fields=[("Carrier", "company"), ("Lines", "choice:Auto and home|Business|Life|All lines"), ("Policies", "int:40-900"), ("Commission", "pct:8-18"), ("Status", "status:Appointed|Pending")]),
    ],
    specials=[
        dict(title="Claims board", type="kanban", icon="kanban", desc="Every claim from first notice to payout.", items=["New", "Assigned", "Investigating", "Approved", "Paid"], cards=["Car accident", "Water damage", "Theft", "Storm damage"], money=True),
        dict(title="Renewals", type="calendar", icon="calendar", desc="Policies renewing this month.", items=["Auto renewal", "Home renewal", "Business review", "Client call", "Carrier meeting"]),
        dict(title="Commission report", type="report", icon="chart", desc="What you earned from each carrier.", items=["Commission earned", "New business", "Renewals", "Average rate"], rows=["Auto", "Home", "Business", "Life", "Travel"]),
        dict(title="Claims map", type="map", icon="map", desc="Where claims are coming from.", items=["North district", "Coast", "City centre", "Suburbs", "Farmland"]),
        dict(title="Policy document", type="document", icon="file", desc="A printable summary of cover.", doc="Policy summary", num="POL-1061", items=["Buildings cover", "Contents cover", "Accidental damage", "Legal expenses"]),
        dict(title="Top agents", type="ranking", icon="star", desc="Who wrote the most premium this quarter.", items=["Amara Silva", "Ben Walsh", "Chloe Chen", "Daniel Diaz", "Elena Fischer", "Farid Khan"], metric="Premium", scale=4000),
        dict(title="Client messages", type="split", icon="message", desc="Questions from clients.", items=["Is my windscreen covered?", "Update my address", "When is my renewal?", "Add my son to the car policy", "Claim update please"]),
    ],
))

B1.append(dict(
    num=12, slug="stub", brand="Stub", category="Freelancer Invoicing", org="Studio of Lena Park", currency="$",
    tagline="Invoices, time and clients for freelancers who want to get paid on time.",
    auth_line="Send the invoice. Get paid. Get back to work.", user="Lena Park", user_role="Designer and owner",
    theme=dict(fonts=["Bricolage Grotesque", "DM Sans", "DM Mono", "Bricolage Grotesque"], accent="#e11d48", layout="light", card="border", radius="14px",
               c2="#fda4af", c3="#0ea5e9", c4="#22c55e"),
    kpis=[("Earned this month", "money", 9400, "dollar"), ("Waiting to be paid", "money", 5200, "clock"), ("Hours tracked", "int", 128, "clock"), ("Active clients", "int", 9, "users")],
    chart=dict(title="Income", names=["Paid", "Invoiced"], base=7800),
    mix=dict(title="Income by client", parts=["Maple Foods", "Oak Studio", "River Health", "Summit Labs", "Others"]),
    activity=["Invoice INV-221 paid by Oak Studio", "Reminder sent to River Health", "Tracked 3h 20m on brand guide", "New project added for Maple Foods", "Expense added: font licence", "Quote accepted by Summit Labs"],
    entities=[
        dict(singular="Invoice", plural="Invoices", prefix="INV-", icon="file", desc="Invoices you sent.",
             fields=[("Invoice", "id"), ("Client", "company"), ("Sent", "date"), ("Amount", "money:300-6000"), ("Status", "status:Paid|Sent|Overdue|Draft")]),
        dict(singular="Client", plural="Clients", prefix="", icon="users", desc="People and companies you work for.",
             fields=[("Client", "company"), ("Contact", "person"), ("Rate", "money:45-160"), ("Billed this year", "money:900-40000"), ("Status", "status:Active|Paused")]),
        dict(singular="Project", plural="Projects", prefix="", icon="folder", desc="Work you are doing now.",
             fields=[("Project", "words:Brand guide|Website redesign|Packaging|Pitch deck|Social templates|Annual report"), ("Client", "company"), ("Hours", "int:4-120"), ("Budget", "money:800-15000"), ("Status", "status:In progress|Review|Done")]),
        dict(singular="Time entry", plural="Time entries", slug="time-entries", prefix="", icon="clock", desc="Hours you tracked.",
             fields=[("Task", "words:Design|Client call|Revisions|Research|Admin|Presentation"), ("Project", "words:Brand guide|Website redesign|Packaging|Pitch deck"), ("Date", "date"), ("Time", "duration"), ("Status", "status:Billed|Unbilled")]),
        dict(singular="Expense", plural="Expenses", prefix="EX-", icon="receipt", desc="Costs you can bill back or claim.",
             fields=[("Expense", "words:Font licence|Stock photos|Printing|Travel|Software|Coworking day"), ("Project", "words:Brand guide|Packaging|Pitch deck|General"), ("Date", "date"), ("Amount", "money:5-600"), ("Status", "status:Billed|To bill|Personal")]),
    ],
    specials=[
        dict(title="Invoice preview", type="document", icon="receipt", desc="How your invoice looks to clients.", doc="Invoice", num="INV-2026-221", items=["Brand guide design", "Two revision rounds", "Social media templates", "Font licence"], note="Payment due within 14 days. Thank you for working with me."),
        dict(title="Payment tracker", type="kanban", icon="kanban", desc="Where every invoice stands.", items=["Draft", "Sent", "Viewed", "Overdue", "Paid"], cards=["Brand guide", "Website pages", "Packaging", "Pitch deck"], money=True, who="company"),
        dict(title="Income report", type="report", icon="chart", desc="What you earned and when.", items=["Income", "Average invoice", "Days to get paid", "Hourly rate"], rows=["Maple Foods", "Oak Studio", "River Health", "Summit Labs", "Bright Media"]),
        dict(title="Schedule", type="calendar", icon="calendar", desc="Deadlines and client calls.", items=["Client call", "Deadline", "Invoice due", "Workshop", "Tax payment"]),
        dict(title="Best clients", type="ranking", icon="star", desc="Who you earned the most from this year.", items=["Oak Studio", "Maple Foods", "Summit Labs", "River Health", "Bright Media", "Cedar Works"], metric="Earned", scale=300),
        dict(title="Client messages", type="split", icon="message", desc="Emails about your projects.", items=["Can we move the deadline?", "Feedback on round two", "Invoice question", "New project idea", "Thanks for the files"]),
        dict(title="Reminders", type="config", icon="bell", desc="Automatic nudges so you get paid.", items=["Remind clients 3 days before the due date", "Send a reminder when an invoice is 7 days late", "Thank clients when they pay", "Add late fees after 30 days"]),
    ],
))

B1.append(dict(
    num=13, slug="wagewise", brand="Wagewise", category="Payroll", org="Cedar Works Ltd", currency="$",
    tagline="Run payroll, track leave and keep tax filings on time.",
    auth_line="Payroll that runs on time, every time.", user="Priya Nair", user_role="Payroll lead",
    theme=dict(fonts=["Plus Jakarta Sans", "Plus Jakarta Sans", "Fira Code", "Plus Jakarta Sans"], accent="#4f46e5", layout="tint", card="border", radius="10px",
               c2="#a5b4fc", c3="#f59e0b", c4="#10b981"),
    kpis=[("Next payroll", "money", 412000, "dollar"), ("Employees paid", "int", 186, "users"), ("Taxes due", "money", 96400, "receipt"), ("Leave requests", "int", 12, "calendar")],
    chart=dict(title="Payroll cost", names=["Gross pay", "Employer taxes"], base=390000),
    mix=dict(title="Cost by department", parts=["Engineering", "Sales", "Operations", "Support", "Other"]),
    activity=["September payroll approved", "Leave approved for Tomas Silva", "Tax filing submitted", "New starter added: Wen Zhang", "Bonus added for the sales team", "Payslips emailed to 186 people"],
    entities=[
        dict(singular="Employee", plural="Employees", prefix="E-", icon="users", desc="Everyone on the payroll.",
             fields=[("Employee", "person"), ("Department", "choice:Engineering|Sales|Operations|Support|Finance"), ("Salary", "money:28000-140000"), ("Start date", "date"), ("Status", "status:Active|On leave|Leaving")]),
        dict(singular="Pay run", plural="Pay runs", slug="pay-runs", prefix="PR-", icon="dollar", desc="Each time you pay your team.",
             fields=[("Pay run", "id"), ("Period", "words:September 2026|August 2026|July 2026|June 2026"), ("People", "int:170-190"), ("Net pay", "money:280000-330000"), ("Status", "status:Paid|Approved|Draft")]),
        dict(singular="Payslip", plural="Payslips", prefix="PS-", icon="file", desc="Individual payslips.",
             fields=[("Payslip", "id"), ("Employee", "person"), ("Gross", "money:2400-11000"), ("Net", "money:1800-8000"), ("Status", "status:Sent|Viewed|Held")]),
        dict(singular="Leave request", plural="Leave requests", slug="leave-requests", prefix="", icon="calendar", desc="Holidays and time off.",
             fields=[("Employee", "person"), ("Type", "choice:Holiday|Sick|Parental|Unpaid"), ("From", "date:future"), ("Days", "int:1-15"), ("Status", "status:Approved|Pending|Declined")]),
        dict(singular="Benefit", plural="Benefits", prefix="", icon="heart", desc="Pension, health and other perks.",
             fields=[("Benefit", "words:Pension|Health cover|Gym|Cycle to work|Life cover|Dental"), ("Provider", "company"), ("Members", "int:20-186"), ("Monthly cost", "money:400-24000"), ("Status", "status:Active|Renewal due")]),
    ],
    specials=[
        dict(title="Run payroll", type="kanban", icon="kanban", desc="The steps for this month's payroll.", items=["Collect hours", "Check changes", "Approve", "Pay", "File taxes"], cards=["Overtime", "New starter", "Leaver", "Bonus", "Pay rise"]),
        dict(title="Payslip preview", type="document", icon="receipt", desc="How a payslip looks to your team.", doc="Payslip", num="PS-1047 September 2026", items=["Basic salary", "Overtime", "Bonus", "Pension contribution", "Health cover"], note="Deductions for income tax and social security are shown on the full payslip."),
        dict(title="Leave calendar", type="calendar", icon="calendar", desc="Who is off and when.", items=["Holiday", "Sick day", "Parental leave", "Training", "Public holiday"]),
        dict(title="Payroll report", type="report", icon="chart", desc="Costs by team and month.", items=["Gross pay", "Employer taxes", "Pension", "Overtime"], rows=["Engineering", "Sales", "Operations", "Support", "Finance"]),
        dict(title="Tax filings", type="timeline", icon="book", desc="Filings sent to the tax office.", items=["September payroll filing submitted", "Quarterly return accepted", "Year-end forms sent to staff", "Pension report uploaded"]),
        dict(title="Headcount by office", type="map", icon="map", desc="Where your people work.", items=["London", "Berlin", "Lisbon", "Remote", "Dublin"]),
        dict(title="Payroll rules", type="config", icon="settings", desc="How pay is calculated.", items=["Pay overtime at 1.5 times the hourly rate", "Enrol new starters in the pension", "Email payslips on payday", "Hold pay for unapproved hours"]),
    ],
))

B1.append(dict(
    num=14, slug="tender", brand="Tender", category="Payment Gateway", org="Tender Payments", currency="$",
    tagline="Payments, payouts and disputes for an online business.",
    auth_line="Accept payments. Watch them land.", user="Rafael Costa", user_role="Finance lead",
    theme=dict(fonts=["Figtree", "Figtree", "JetBrains Mono", "Figtree"], accent="#0891b2", layout="dark", card="shadow", radius="10px", sidebar="#0b1220",
               c2="#67e8f9", c3="#f97316", c4="#a3e635"),
    kpis=[("Gross volume", "money", 1840000, "dollar"), ("Successful payments", "int", 24100, "check"), ("Disputes", "int", 18, "alert"), ("Payout balance", "money", 214000, "building")],
    chart=dict(title="Payment volume", names=["This period", "Previous period"], base=1500000),
    mix=dict(title="Payment methods", parts=["Cards", "Wallets", "Bank debit", "Buy now pay later", "Other"]),
    activity=["Payout of $48,200 sent", "Dispute opened on PAY-3310", "New webhook endpoint added", "Refund issued to Maple Foods", "Card declined: insufficient funds", "API key rotated"],
    entities=[
        dict(singular="Payment", plural="Payments", prefix="PAY-", icon="card", desc="Every payment your customers made.",
             fields=[("Payment", "id"), ("Customer", "email"), ("Method", "choice:Visa|Mastercard|Wallet|Bank debit"), ("Amount", "money:5-2400"), ("Status", "status:Succeeded|Refunded|Failed|Disputed")]),
        dict(singular="Customer", plural="Customers", prefix="", icon="users", desc="People who paid you.",
             fields=[("Customer", "person"), ("Email", "email"), ("Payments", "int:1-80"), ("Total spent", "money:20-18000"), ("Status", "status:Active|New|Blocked")]),
        dict(singular="Payout", plural="Payouts", prefix="PO-", icon="building", desc="Money sent to your bank.",
             fields=[("Payout", "id"), ("Bank", "choice:Business current|Savings"), ("Arrives", "date:future"), ("Amount", "money:4000-90000"), ("Status", "status:Paid|In transit|Failed")]),
        dict(singular="Dispute", plural="Disputes", prefix="DP-", icon="alert", desc="Chargebacks you need to answer.",
             fields=[("Dispute", "id"), ("Reason", "choice:Fraud|Not received|Duplicate|Not as described"), ("Opened", "date"), ("Amount", "money:20-1800"), ("Status", "status:Needs response|Under review|Won|Lost")]),
        dict(singular="Subscription", plural="Subscriptions", prefix="SUB-", icon="clock", desc="Customers paying you every month.",
             fields=[("Subscription", "id"), ("Customer", "person"), ("Plan", "choice:Starter|Growth|Pro"), ("Monthly", "money:9-299"), ("Status", "status:Active|Trial|Past due|Cancelled")]),
    ],
    specials=[
        dict(title="System status", type="monitor", icon="monitor", desc="Live health of payment services.", items=["Card processing", "Wallet payments", "Bank debits", "Payouts", "Webhooks", "Dashboard API", "Fraud checks", "Refunds"]),
        dict(title="Revenue report", type="report", icon="chart", desc="Volume, fees and refunds.", items=["Net volume", "Fees", "Refund rate", "Success rate"], rows=["Visa", "Mastercard", "Wallets", "Bank debit", "Buy now pay later"]),
        dict(title="Payments by country", type="map", icon="globe", desc="Where your customers pay from.", items=["United States", "United Kingdom", "Germany", "Canada", "Australia"]),
        dict(title="Dispute queue", type="kanban", icon="kanban", desc="Answer disputes before the deadline.", items=["Needs response", "Evidence sent", "Under review", "Closed"], cards=["Fraud claim", "Not received", "Duplicate charge", "Not as described"], money=True),
        dict(title="Developer logs", type="timeline", icon="tool", desc="Recent API requests and webhooks.", items=["POST /v1/payments 200", "Webhook payment.succeeded delivered", "POST /v1/refunds 200", "Webhook dispute.created delivered", "GET /v1/payouts 200"]),
        dict(title="Payout statement", type="document", icon="file", desc="What was included in a payout.", doc="Payout statement", num="PO-1068", items=["Card payments", "Wallet payments", "Refunds", "Processing fees"]),
        dict(title="Fraud rules", type="config", icon="shield", desc="Block risky payments automatically.", items=["Block payments with a high risk score", "Ask for 3D Secure on payments over $500", "Block cards from blocked countries", "Review first payments over $1,000"]),
    ],
))

B1.append(dict(
    num=15, slug="deduct", brand="Deduct", category="Tax Preparation", org="Northside Tax Services", currency="$",
    tagline="Client returns, documents and deadlines for a tax preparation office.",
    auth_line="Every return filed on time.", user="Victor Mensah", user_role="Enrolled agent",
    theme=dict(fonts=["Libre Franklin", "Libre Franklin", "Source Code Pro", "Libre Franklin"], accent="#9a3412", layout="light", card="border", radius="4px",
               bg="#fafaf9", surface2="#f5f5f4", line="#e7e5e4", c2="#a8a29e", c3="#0f766e", c4="#1d4ed8"),
    kpis=[("Returns filed", "int", 842, "check"), ("In progress", "int", 126, "clock"), ("Fees billed", "money", 214000, "dollar"), ("Refunds found", "money", 1480000, "trend")],
    chart=dict(title="Returns filed", names=["This season", "Last season"], base=90),
    mix=dict(title="Return types", parts=["Individual", "Self-employed", "Small business", "Rental", "Other"]),
    activity=["Return filed for the Garcia family", "Documents uploaded by Jonah Walsh", "Extension requested for Oak Studio", "Refund accepted for Amara Silva", "Missing W-2 flagged", "Appointment booked for Friday"],
    entities=[
        dict(singular="Client", plural="Clients", prefix="", icon="users", desc="Individuals and businesses you file for.",
             fields=[("Client", "person"), ("Type", "choice:Individual|Self-employed|Business|Rental owner"), ("Returns", "int:1-12"), ("Fee", "money:120-2400"), ("Status", "status:Active|New|Inactive")]),
        dict(singular="Return", plural="Returns", prefix="RT-", icon="file", desc="Tax returns for this season.",
             fields=[("Return", "id"), ("Client", "person"), ("Form", "choice:Individual|Business|Partnership|Amended"), ("Refund", "money:100-9000"), ("Status", "status:Filed|In progress|Waiting on client|Rejected")]),
        dict(singular="Document", plural="Documents", prefix="", icon="folder", desc="Forms and receipts clients sent.",
             fields=[("Document", "words:W-2|1099|Mortgage statement|Charity receipt|Bank interest|Childcare receipt"), ("Client", "person"), ("Received", "date"), ("Pages", "int:1-18"), ("Status", "status:Checked|New|Missing")]),
        dict(singular="Appointment", plural="Appointments", prefix="", icon="calendar", desc="Meetings with clients.",
             fields=[("Client", "person"), ("Type", "choice:First meeting|Review|Signing|Planning"), ("Date", "date:future"), ("Time", "time"), ("Status", "status:Booked|Confirmed|Cancelled")]),
        dict(singular="Payment", plural="Payments", prefix="PAY-", icon="card", desc="Fees clients paid you.",
             fields=[("Payment", "id"), ("Client", "person"), ("Date", "date"), ("Amount", "money:120-2400"), ("Status", "status:Paid|Due|Refunded")]),
    ],
    specials=[
        dict(title="Return pipeline", type="kanban", icon="kanban", desc="Every return from documents to filing.", items=["Documents needed", "Preparing", "Review", "Client signing", "Filed"], cards=["Individual return", "Self-employed return", "Business return", "Amended return"]),
        dict(title="Deadlines", type="calendar", icon="calendar", desc="Filing dates and client meetings.", items=["Filing deadline", "Client meeting", "Estimated tax due", "Extension deadline", "Team review"]),
        dict(title="Season report", type="report", icon="chart", desc="How this season compares with last year.", items=["Returns filed", "Average fee", "Average refund", "Rejection rate"], rows=["Individual", "Self-employed", "Business", "Rental", "Amended"]),
        dict(title="Engagement letter", type="document", icon="file", desc="Printable fee agreement for a client.", doc="Engagement letter and fees", num="Season 2026", items=["Individual return", "Self-employment schedule", "Rental income schedule", "State return"]),
        dict(title="Document requests", type="split", icon="inbox", desc="Messages asking clients for missing forms.", items=["We still need your W-2", "Please sign the e-file form", "Mortgage statement received", "Question about childcare costs", "Your refund was accepted"]),
        dict(title="Preparer workload", type="ranking", icon="users", desc="Returns each preparer has filed.", items=["Victor Mensah", "Hana Sato", "Isaac Moreau", "Julia Larsen", "Kavya Rahman"], metric="Returns", scale=3),
        dict(title="Office settings", type="config", icon="settings", desc="How your office works during tax season.", items=["Send clients a document checklist when they book", "Remind clients 2 days before meetings", "Require a second review for business returns", "Text clients when their return is filed"]),
    ],
))
