"""Batch 9: Sports, vehicles, weather, property and finance ops dashboards (numbers 86 to 95)."""

B9 = []

B9.append(dict(
    num=86, slug="matchday", brand="Matchday", category="Sports Team", org="Millbrook Rovers FC", currency="$",
    tagline="Squad, fixtures, training and fitness for a football club.",
    auth_line="Everything the club needs before kick-off.", user="Marco Bennett", user_role="Head coach",
    theme=dict(fonts=["Teko", "Inter", "JetBrains Mono", "Teko"], accent="#1e3a8a", layout="accent", card="shadow", radius="8px",
               c2="#93c5fd", c3="#dc2626", c4="#16a34a"),
    kpis=[("League position", "int", 3, "star"), ("Points", "int", 42, "trend"), ("Fit players", "int", 22, "users"), ("Season tickets sold", "int", 8400, "tag")],
    chart=dict(title="Points through the season", names=["This season", "Last season"], base=30),
    mix=dict(title="Goals by type", parts=["Open play", "Set pieces", "Penalties", "Counter attacks", "Other"]),
    activity=["Team sheet published for Saturday", "Jonah Silva back in full training", "Scouting report added: Harbor United", "Match tickets 80 percent sold", "Recovery session moved to 10am", "New signing: Wen Okafor"],
    entities=[
        dict(singular="Player", plural="Squad", slug="squad", prefix="", icon="users", desc="Players in the first team squad.",
             fields=[("Player", "person"), ("Position", "choice:Goalkeeper|Defender|Midfielder|Forward"), ("Appearances", "int:0-32"), ("Goals", "int:0-18"), ("Status", "status:Fit|Injured|Suspended")]),
        dict(singular="Fixture", plural="Fixtures", prefix="", icon="calendar", desc="Matches this season.",
             fields=[("Opponent", "words:Harbor United|Oakfield Town|Riverside Athletic|Summit City|Cedar Park Rangers"), ("Venue", "choice:Home|Away"), ("Date", "date:future"), ("Competition", "choice:League|Cup|Friendly"), ("Status", "status:Scheduled|Won|Drawn|Lost")]),
        dict(singular="Training session", plural="Training", slug="training", prefix="", icon="activity", desc="Sessions planned this week.",
             fields=[("Session", "words:Pressing drills|Set pieces|Recovery|Tactical shape|Finishing|Small sided games"), ("Coach", "person"), ("Date", "date:future"), ("Duration", "duration"), ("Status", "status:Planned|Done|Cancelled")]),
        dict(singular="Injury", plural="Injuries", prefix="", icon="alert", desc="Player injuries and return dates.",
             fields=[("Player", "person"), ("Injury", "choice:Hamstring|Ankle|Knee|Groin|Illness"), ("Since", "date"), ("Days out", "int:3-90"), ("Status", "status:Rehab|Back in training|Fit")]),
        dict(singular="Scouting report", plural="Scouting", slug="scouting", prefix="", icon="search", desc="Players and opponents you are watching.",
             fields=[("Name", "person"), ("Club", "words:Harbor United|Oakfield Town|Riverside Athletic|Summit City"), ("Position", "choice:Defender|Midfielder|Forward"), ("Rating", "rating"), ("Status", "status:Watching|Shortlist|Not suitable")]),
    ],
    specials=[
        dict(title="Match calendar", type="calendar", icon="calendar", desc="Matches, training and travel.", items=["League match", "Cup match", "Training", "Recovery", "Travel"]),
        dict(title="Team selection", type="kanban", icon="kanban", desc="Pick the squad for Saturday.", items=["Starting eleven", "Bench", "Not selected", "Unavailable"], cards=["Goalkeeper", "Centre back", "Midfielder", "Winger", "Striker"]),
        dict(title="Top scorers", type="ranking", icon="star", desc="Goals this season.", items=["Jonah Silva", "Leo Costa", "Omar Diaz", "Ben Walsh", "Kenji Ito", "Sam Evans"], metric="Goals", scale=0.18),
        dict(title="Performance", type="report", icon="chart", desc="Goals, possession and fitness.", items=["Goals scored", "Possession", "Clean sheets", "Distance run"], rows=["Open play", "Set pieces", "Penalties", "Counter attacks", "Long shots"]),
        dict(title="Fitness monitor", type="monitor", icon="activity", desc="Player load from today's session.", items=["Jonah Silva", "Leo Costa", "Omar Diaz", "Ben Walsh", "Kenji Ito", "Sam Evans", "Wen Okafor", "Tom Rossi"], unit="%"),
        dict(title="Match report", type="document", icon="file", desc="A printable report after the match.", doc="Match report", num="Rovers 2, Harbor United 1", items=["Goals scored", "Shots on target", "Corners", "Fouls"], note="Demo layout only. The Qty column shows match numbers. Price columns are not used."),
        dict(title="Squad rules", type="config", icon="settings", desc="Settings for the coaching team.", items=["Share team sheets 1 hour before kick-off", "Flag players over 90 percent training load", "Remind players about medical checks", "Lock the squad list on match day"]),
    ],
))

B9.append(dict(
    num=87, slug="respawn", brand="Respawn", category="Esports", org="Nova Esports", currency="$",
    tagline="Rosters, matches, streams and sponsors for an esports team.",
    auth_line="Win the match. Grow the team.", user="Kenji Park", user_role="Team manager",
    theme=dict(fonts=["Orbitron", "Exo 2", "Share Tech Mono", "Exo 2"], accent="#a855f7", layout="dark", card="border", radius="6px", sidebar="#0b0614",
               c2="#d8b4fe", c3="#22d3ee", c4="#f43f5e"),
    kpis=[("Win rate", "pct", 64.0, "trend"), ("Matches this month", "int", 38, "zap"), ("Stream viewers", "int", 48200, "monitor"), ("Sponsor revenue", "money", 42000, "dollar")],
    chart=dict(title="Stream viewers", names=["Viewers", "Last season"], base=40000),
    mix=dict(title="Wins by game mode", parts=["Ranked", "Tournament", "Scrims", "Showmatch", "Other"]),
    activity=["Won the semi-final 3 to 1", "Scrim booked with Zenith Gaming", "New sponsor: Volt Energy Drinks", "Stream peaked at 62k viewers", "Bootcamp dates confirmed", "Player contract extended"],
    entities=[
        dict(singular="Player", plural="Roster", slug="roster", prefix="", icon="users", desc="Players and substitutes.",
             fields=[("Player", "words:Nyx|Blaze|Echo|Viper|Atlas|Rook|Kite"), ("Role", "choice:Captain|Entry|Support|Sniper|Sub"), ("Rating", "rating"), ("Matches", "int:10-120"), ("Status", "status:Active|Benched|Trial")]),
        dict(singular="Match", plural="Matches", prefix="M-", icon="zap", desc="Official matches and results.",
             fields=[("Match", "id"), ("Opponent", "words:Zenith Gaming|Pulse Five|Ironclad|Night Owls|Red Comet"), ("Event", "choice:League|Cup|Qualifier|Showmatch"), ("Date", "date"), ("Status", "status:Won|Lost|Scheduled")]),
        dict(singular="Scrim", plural="Scrims", prefix="", icon="activity", desc="Practice matches.",
             fields=[("Opponent", "words:Zenith Gaming|Pulse Five|Ironclad|Night Owls"), ("Date", "date:future"), ("Time", "time"), ("Maps", "int:2-5"), ("Status", "status:Booked|Played|Cancelled")]),
        dict(singular="Stream", plural="Streams", prefix="", icon="monitor", desc="Team and player streams.",
             fields=[("Stream", "words:Match day watch party|Nyx ranked grind|Team Q and A|Bootcamp vlog|Blaze coaching"), ("Peak viewers", "int:800-62000"), ("Hours", "int:1-10"), ("Date", "date"), ("Status", "status:Live|Ended|Scheduled")]),
        dict(singular="Sponsor", plural="Sponsors", prefix="", icon="briefcase", desc="Brands that back the team.",
             fields=[("Sponsor", "words:Volt Energy Drinks|Apex Chairs|Swift Mice|Nimbus Internet|Pixel Headsets"), ("Deal", "money:4000-120000"), ("Ends", "date:future"), ("Deliverables", "int:2-24"), ("Status", "status:Active|Renewal due|Proposal")]),
    ],
    specials=[
        dict(title="Tournament bracket", type="kanban", icon="kanban", desc="Where the team stands in the cup.", items=["Group stage", "Quarter-final", "Semi-final", "Final"], cards=["Nova vs Pulse Five", "Nova vs Ironclad", "Zenith vs Night Owls", "Nova vs Zenith"]),
        dict(title="Player stats", type="ranking", icon="star", desc="Best performers this month.", items=["Nyx", "Blaze", "Echo", "Viper", "Atlas"], metric="Score", scale=30),
        dict(title="Team report", type="report", icon="chart", desc="Wins, maps and stream growth.", items=["Win rate", "Round difference", "Stream hours", "Followers"], rows=["Ranked", "Tournament", "Scrims", "Showmatch", "Bootcamp"]),
        dict(title="Schedule", type="calendar", icon="calendar", desc="Matches, scrims and streams.", items=["Official match", "Scrim", "Stream", "Review session", "Travel"]),
        dict(title="Live match", type="monitor", icon="activity", desc="Live stats during a match.", items=["Nyx", "Blaze", "Echo", "Viper", "Atlas", "Team economy"], unit=""),
        dict(title="Fan map", type="map", icon="globe", desc="Where viewers watch from.", items=["North America", "Europe", "South America", "Asia", "Oceania"]),
        dict(title="Sponsor invoice", type="document", icon="receipt", desc="Invoice for a sponsor deal.", doc="Sponsorship invoice", num="Volt Energy Drinks, Q4", items=["Jersey logo", "Stream overlays", "Social posts", "Event appearance"]),
    ],
))

B9.append(dict(
    num=88, slug="showroom", brand="Showroom", category="Car Dealership", org="Crestline Motors", currency="$",
    tagline="Stock, leads, test drives and sales for a car dealership.",
    auth_line="Sell more cars, faster.", user="Rafael Adams", user_role="Sales director",
    theme=dict(fonts=["Kanit", "Kanit", "Roboto Mono"], accent="#b91c1c", layout="light", card="border", radius="6px",
               c2="#fca5a5", c3="#0f172a", c4="#0ea5e9"),
    kpis=[("Cars in stock", "int", 214, "truck"), ("Sold this month", "int", 64, "check"), ("Test drives booked", "int", 38, "calendar"), ("Gross profit", "money", 186000, "dollar")],
    chart=dict(title="Cars sold", names=["This year", "Last year"], base=58),
    mix=dict(title="Stock by type", parts=["SUV", "Hatchback", "Saloon", "Electric", "Van"]),
    activity=["Car sold: family SUV to the Chen family", "Test drive booked for Saturday", "Trade-in valued at $9,400", "Finance approved for Maya Rossi", "New stock arrived: 12 cars", "Price dropped on 3 older cars"],
    entities=[
        dict(singular="Vehicle", plural="Stock", slug="stock", prefix="STK-", icon="truck", desc="Cars on the forecourt.",
             fields=[("Stock", "id"), ("Model", "words:Family SUV|City hatchback|Executive saloon|Electric crossover|Sports coupe|Cargo van"), ("Year", "int:2019-2026"), ("Price", "money:9000-68000"), ("Status", "status:Available|Reserved|Sold|In prep")]),
        dict(singular="Lead", plural="Leads", prefix="", icon="user", desc="People interested in a car.",
             fields=[("Lead", "person"), ("Interested in", "words:Family SUV|Electric crossover|City hatchback|Executive saloon"), ("Source", "choice:Website|Walk-in|Phone|Marketplace"), ("Received", "date"), ("Status", "status:New|Contacted|Test drive|Lost")]),
        dict(singular="Test drive", plural="Test drives", slug="test-drives", prefix="", icon="calendar", desc="Drives booked with customers.",
             fields=[("Customer", "person"), ("Car", "words:Family SUV|Electric crossover|Sports coupe|City hatchback"), ("Date", "date:future"), ("Time", "time"), ("Status", "status:Booked|Done|No show")]),
        dict(singular="Deal", plural="Deals", prefix="DL-", icon="briefcase", desc="Sales in progress and closed.",
             fields=[("Deal", "id"), ("Customer", "person"), ("Salesperson", "person"), ("Price", "money:9000-68000"), ("Status", "status:Sold|Finance pending|Negotiating|Lost")]),
        dict(singular="Trade-in", plural="Trade-ins", slug="trade-ins", prefix="", icon="zap", desc="Part exchange cars.",
             fields=[("Customer", "person"), ("Car", "words:2018 hatchback|2017 SUV|2020 saloon|2016 estate"), ("Mileage", "int:20000-140000"), ("Offer", "money:2000-18000"), ("Status", "status:Accepted|Offered|Declined")]),
    ],
    specials=[
        dict(title="Sales pipeline", type="kanban", icon="kanban", desc="Customers from enquiry to keys.", items=["Enquiry", "Test drive", "Negotiation", "Finance", "Delivered"], cards=["Family SUV", "Electric crossover", "City hatchback", "Executive saloon"], money=True),
        dict(title="Test drive calendar", type="calendar", icon="calendar", desc="Drives and handovers.", items=["Test drive", "Handover", "Service", "Valuation", "Stock arrival"]),
        dict(title="Sales report", type="report", icon="chart", desc="Units, profit and finance.", items=["Units sold", "Gross profit", "Finance take-up", "Days in stock"], rows=["SUV", "Hatchback", "Saloon", "Electric", "Van"]),
        dict(title="Top sellers", type="ranking", icon="star", desc="Salespeople this month.", items=["Rafael Adams", "Nadia Costa", "Ben Walsh", "Sara Kim", "Omar Novak"], metric="Cars sold", scale=0.2),
        dict(title="Stock gallery", type="gallery", icon="grid", desc="Cars on the forecourt.", items=["Family SUV", "City hatchback", "Executive saloon", "Electric crossover", "Sports coupe", "Cargo van"]),
        dict(title="Sales invoice", type="document", icon="receipt", desc="A printable invoice for a car sale.", doc="Vehicle invoice", num="DL-1047", items=["Family SUV, 2024", "Paint protection", "Extended warranty", "Trade-in allowance"]),
        dict(title="Dealer settings", type="config", icon="settings", desc="Rules for sales and stock.", items=["Reply to website leads within 1 hour", "Drop prices after 60 days in stock", "Require a manager for discounts over 5 percent", "Text customers the day before a test drive"]),
    ],
))

B9.append(dict(
    num=89, slug="plugpark", brand="Plugpark", category="Parking and EV Charging", org="Plugpark Networks", currency="$",
    tagline="Car parks, chargers, sessions and payments for a parking operator.",
    auth_line="Park, plug in, pay. Simple.", user="Liam Ibrahim", user_role="Network manager",
    theme=dict(fonts=["Ubuntu", "Ubuntu", "Ubuntu Mono"], accent="#16a34a", layout="tint", card="shadow", radius="14px",
               c2="#86efac", c3="#0ea5e9", c4="#f59e0b"),
    kpis=[("Spaces in use", "pct", 72.4, "grid"), ("Charging sessions today", "int", 1840, "zap"), ("Energy delivered kWh", "int", 28400, "activity"), ("Revenue today", "money", 18400, "dollar")],
    chart=dict(title="Charging sessions", names=["Sessions", "Last month"], base=1600),
    mix=dict(title="Revenue by type", parts=["Parking", "Fast charging", "Standard charging", "Permits", "Fines"]),
    activity=["Charger C-14 back online", "Car park B reached 95 percent", "New site opened: Harbour Retail", "Payment app updated", "Faulty barrier fixed at Station car park", "Monthly permit renewals sent"],
    entities=[
        dict(singular="Car park", plural="Car parks", slug="car-parks", prefix="", icon="building", desc="Every site you run.",
             fields=[("Car park", "words:Station car park|Harbour Retail|City centre multi-storey|Hospital car park|Airport long stay"), ("Spaces", "int:80-1200"), ("In use", "pct:30-99"), ("Chargers", "int:4-60"), ("Status", "status:Open|Full|Closed")]),
        dict(singular="Charger", plural="Chargers", prefix="C-", icon="zap", desc="Charging points.",
             fields=[("Charger", "id"), ("Type", "choice:Fast 150 kW|Rapid 50 kW|Standard 22 kW|Standard 7 kW"), ("Site", "words:Station car park|Harbour Retail|City centre|Airport"), ("Sessions today", "int:0-40"), ("Status", "status:Available|Charging|Fault|Offline")]),
        dict(singular="Session", plural="Sessions", prefix="S-", icon="activity", desc="Parking and charging sessions.",
             fields=[("Session", "id"), ("Plate", "code:MB "), ("Duration", "duration"), ("Energy kWh", "int:0-80"), ("Status", "status:Active|Paid|Unpaid")]),
        dict(singular="Permit", plural="Permits", prefix="PR-", icon="card", desc="Monthly and resident permits.",
             fields=[("Permit", "id"), ("Holder", "person"), ("Type", "choice:Monthly|Resident|Staff|Blue badge"), ("Expires", "date:future"), ("Status", "status:Active|Expiring|Expired")]),
        dict(singular="Payment", plural="Payments", prefix="PAY-", icon="dollar", desc="Payments from drivers.",
             fields=[("Payment", "id"), ("Method", "choice:App|Card|Contactless|Permit"), ("Site", "words:Station car park|Harbour Retail|City centre|Airport"), ("Amount", "money:2-60"), ("Status", "status:Paid|Refunded|Failed")]),
    ],
    specials=[
        dict(title="Charger map", type="map", icon="map", desc="Charging points and their status.", items=["Station", "Harbour", "City centre", "Hospital", "Airport"], dots=22),
        dict(title="Live occupancy", type="monitor", icon="activity", desc="Spaces in use right now.", items=["Station car park", "Harbour Retail", "City centre", "Hospital", "Airport long stay", "Airport short stay", "Park and ride", "Stadium"], unit="%"),
        dict(title="Network report", type="report", icon="chart", desc="Use, energy and revenue.", items=["Occupancy", "Energy delivered", "Revenue", "Charger uptime"], rows=["Station car park", "Harbour Retail", "City centre", "Hospital", "Airport"]),
        dict(title="Busiest chargers", type="ranking", icon="trend", desc="Chargers with the most sessions.", items=["C-14 Station", "C-02 Harbour", "C-31 Airport", "C-08 City centre", "C-22 Hospital", "C-17 Station"], metric="Sessions", scale=4),
        dict(title="Fault queue", type="kanban", icon="kanban", desc="Broken chargers and barriers.", items=["Reported", "Engineer booked", "On site", "Fixed"], cards=["Charger not starting", "Card reader fault", "Barrier stuck", "Cable damaged"]),
        dict(title="Charging receipt", type="document", icon="receipt", desc="A receipt for a charging session.", doc="Charging receipt", num="S-1047, Harbour Retail", items=["Parking, 2 hours", "Energy, 38 kWh", "Idle fee"], note="Thank you for charging with Plugpark."),
        dict(title="Pricing rules", type="config", icon="settings", desc="How parking and charging is priced.", items=["Charge an idle fee 30 minutes after charging ends", "Free parking for the first 20 minutes", "Cheaper night rates after 10pm", "Alert engineers when a charger goes offline"]),
    ],
))

B9.append(dict(
    num=90, slug="stratus", brand="Stratus", category="Weather Station", org="Millbrook Weather Network", currency="$",
    tagline="Stations, live readings, forecasts and warnings for a weather network.",
    auth_line="Local weather, measured right here.", user="Hana Walsh", user_role="Meteorologist",
    theme=dict(fonts=["Questrial", "Inter", "IBM Plex Mono", "Inter"], accent="#0284c7", layout="dark", card="shadow", radius="16px", sidebar="#0c1624",
               c2="#7dd3fc", c3="#f59e0b", c4="#a78bfa"),
    kpis=[("Temperature now", "int", 18, "sun"), ("Rain today mm", "int", 6, "activity"), ("Wind km/h", "int", 22, "zap"), ("Stations online", "int", 48, "monitor")],
    chart=dict(title="Temperature this year", names=["Average", "Record high"], base=16),
    mix=dict(title="Weather this month", parts=["Sunny", "Cloudy", "Rain", "Storms", "Fog"]),
    activity=["Rain warning issued for the hills", "Station W-12 back online", "Record wind gust at the harbour", "Forecast updated for the weekend", "New station installed at the airport", "Frost alert cleared"],
    entities=[
        dict(singular="Station", plural="Stations", prefix="W-", icon="monitor", desc="Weather stations in the network.",
             fields=[("Station", "id"), ("Location", "choice:Harbour|Hills|City centre|Airport|Valley|Coast"), ("Temperature", "int:4-28"), ("Battery", "pct:20-100"), ("Status", "status:Online|Offline|Maintenance")]),
        dict(singular="Reading", plural="Readings", prefix="", icon="activity", desc="The latest measurements.",
             fields=[("Station", "code:W-"), ("Measure", "choice:Temperature|Rain|Wind|Pressure|Humidity"), ("Value", "int:0-1020"), ("Time", "time"), ("Status", "status:Normal|High|Low")]),
        dict(singular="Forecast", plural="Forecasts", prefix="", icon="sun", desc="Forecasts for the next days.",
             fields=[("Day", "words:Today|Tomorrow|Friday|Saturday|Sunday|Monday"), ("High", "int:10-28"), ("Low", "int:2-16"), ("Rain chance", "pct:0-95"), ("Outlook", "status:Sunny|Cloudy|Rain|Storms")]),
        dict(singular="Warning", plural="Warnings", prefix="WN-", icon="alert", desc="Public weather warnings.",
             fields=[("Warning", "id"), ("Type", "choice:Heavy rain|Strong wind|Frost|Fog|Heat"), ("Area", "choice:Hills|Coast|City|Valley"), ("From", "date:future"), ("Status", "status:Active|Planned|Cleared")]),
        dict(singular="Maintenance job", plural="Maintenance", slug="maintenance", prefix="MJ-", icon="tool", desc="Station repairs and checks.",
             fields=[("Job", "id"), ("Station", "code:W-"), ("Task", "choice:Clean rain gauge|Replace battery|Calibrate sensor|Replace mast"), ("Date", "date:future"), ("Status", "status:Scheduled|Done|In progress")]),
    ],
    specials=[
        dict(title="Live readings", type="monitor", icon="activity", desc="Right now across the network.", items=["Harbour", "Hills", "City centre", "Airport", "Valley", "Coast", "Forest", "Reservoir"], unit=" C"),
        dict(title="Station map", type="map", icon="map", desc="Stations and today's rain.", items=["Harbour", "Hills", "City centre", "Airport", "Valley"], dots=20),
        dict(title="Climate report", type="report", icon="chart", desc="Temperature, rain and wind by month.", items=["Average temperature", "Total rain", "Sunshine hours", "Windiest day"], rows=["Harbour", "Hills", "City centre", "Airport", "Valley"]),
        dict(title="Records", type="ranking", icon="star", desc="Highest readings this year.", items=["Highest temperature", "Strongest gust", "Wettest day", "Coldest night", "Longest dry spell"], metric="Value", scale=1),
        dict(title="Warning history", type="timeline", icon="bell", desc="Recent public warnings.", items=["Heavy rain warning for the hills", "Strong wind warning for the coast", "Frost alert for the valley", "All warnings cleared"]),
        dict(title="Maintenance calendar", type="calendar", icon="calendar", desc="Station checks and repairs.", items=["Calibration", "Battery swap", "New station", "Rain gauge clean", "Data audit"]),
        dict(title="Alert settings", type="config", icon="settings", desc="When warnings are sent.", items=["Warn when rain passes 20 mm in 3 hours", "Warn when gusts pass 70 km/h", "Send frost alerts to farmers", "Publish warnings on the website"]),
    ],
))

B9.append(dict(
    num=91, slug="streaks", brand="Streaks", category="Habit Tracker", org="Personal habits", currency="$",
    tagline="Habits, streaks, goals and reflections in one friendly tracker.",
    auth_line="Show up a little every day.", user="Priya Morris", user_role="Personal account",
    theme=dict(fonts=["Varela Round", "Varela Round", "Roboto Mono"], accent="#f97316", layout="light", card="shadow", radius="24px",
               c2="#fdba74", c3="#8b5cf6", c4="#14b8a6"),
    kpis=[("Longest streak days", "int", 48, "star"), ("Done today", "pct", 80.0, "check"), ("Habits active", "int", 8, "list"), ("Days tracked", "int", 214, "calendar")],
    chart=dict(title="Habits done per week", names=["Done", "Planned"], base=44),
    mix=dict(title="Time by habit area", parts=["Health", "Learning", "Mind", "Home", "Money"]),
    activity=["Read 20 pages, day 48 in a row", "Morning walk done", "New habit: no phone after 10pm", "Weekly review written", "Missed yesterday's journal", "Goal reached: 30 days of stretching"],
    entities=[
        dict(singular="Habit", plural="Habits", prefix="", icon="check", desc="Habits you are tracking.",
             fields=[("Habit", "words:Read 20 pages|Morning walk|Drink 8 glasses|Stretch 10 minutes|Journal|Practise Spanish|No phone after 10pm"), ("Area", "choice:Health|Learning|Mind|Home"), ("Streak", "int:0-60"), ("This week", "pct:20-100"), ("Status", "status:On track|Slipping|Paused")]),
        dict(singular="Goal", plural="Goals", prefix="", icon="star", desc="Bigger things you are working towards.",
             fields=[("Goal", "words:Read 24 books this year|Run a 10k|Save for a holiday|Learn basic Spanish|Sleep 7 hours a night"), ("Progress", "pct:5-100"), ("Deadline", "date:future"), ("Habits linked", "int:1-4"), ("Status", "status:On track|Behind|Done")]),
        dict(singular="Check-in", plural="Check-ins", prefix="", icon="list", desc="Every tick you made.",
             fields=[("Habit", "words:Read 20 pages|Morning walk|Journal|Stretch 10 minutes|Practise Spanish"), ("Date", "date"), ("Time", "time"), ("Note", "words:Felt good|Hard today|Quick one|Great session|Almost skipped"), ("Status", "status:Done|Skipped")]),
        dict(singular="Reflection", plural="Journal", slug="journal", prefix="", icon="book", desc="Short notes about your week.",
             fields=[("Entry", "words:A calm week|Busy but kept going|Missed two days|Best week so far|Back on track"), ("Date", "date"), ("Mood", "choice:Great|Good|Okay|Low"), ("Words", "int:40-600"), ("Status", "status:Written|Draft")]),
        dict(singular="Reminder", plural="Reminders", prefix="", icon="bell", desc="Nudges during the day.",
             fields=[("Reminder", "words:Morning walk|Drink water|Read before bed|Weekly review|Stretch"), ("Time", "time"), ("Days", "choice:Every day|Weekdays|Weekends"), ("Snoozed", "int:0-12"), ("Status", "status:On|Off")]),
    ],
    specials=[
        dict(title="Streak calendar", type="calendar", icon="calendar", desc="Your habits this month.", items=["Read", "Walk", "Journal", "Stretch", "Spanish"]),
        dict(title="Today", type="kanban", icon="kanban", desc="What is left for today.", items=["To do", "Done", "Skipped"], cards=["Read 20 pages", "Morning walk", "Journal", "Stretch", "Spanish lesson"]),
        dict(title="Best streaks", type="ranking", icon="star", desc="Your longest streaks.", items=["Read 20 pages", "Morning walk", "Drink 8 glasses", "Stretch 10 minutes", "Journal", "Practise Spanish"], metric="Days", scale=0.6),
        dict(title="Weekly review", type="report", icon="chart", desc="How your week went.", items=["Habits done", "Best day", "Missed days", "Streaks alive"], rows=["Monday", "Tuesday", "Wednesday", "Thursday", "Friday"]),
        dict(title="Progress timeline", type="timeline", icon="clock", desc="Milestones you reached.", items=["30 days of stretching", "10 books read this year", "First month of journaling", "100 Spanish lessons"]),
        dict(title="Habit ideas", type="gallery", icon="grid", desc="Ideas for new habits.", items=["Walk after lunch", "Five minute tidy", "Gratitude list", "Cook at home", "Screen-free hour", "Call a friend"]),
        dict(title="Tracker settings", type="config", icon="settings", desc="How the tracker works.", items=["Allow one rest day a week without breaking streaks", "Send a weekly summary on Sunday", "Remind me in the evening if habits are left", "Start the week on Monday"]),
    ],
))

B9.append(dict(
    num=92, slug="openhouse", brand="Openhouse", category="Real Estate Agency", org="Harper and Stone Estate Agents", currency="$",
    tagline="Listings, viewings, buyers and offers for an estate agency.",
    auth_line="Every listing sold, every buyer looked after.", user="Grace Moreau", user_role="Branch manager",
    theme=dict(fonts=["Playfair Display", "Inter", "DM Mono", "Inter"], accent="#854d0e", layout="light", card="flat", radius="8px",
               bg="#faf8f5", surface2="#f3efe8", line="#e6dfd4", c2="#d6b98a", c3="#0f766e", c4="#1d4ed8"),
    kpis=[("Active listings", "int", 86, "building"), ("Viewings this week", "int", 64, "calendar"), ("Offers received", "int", 18, "file"), ("Sales this month", "money", 8400000, "dollar")],
    chart=dict(title="Sales value", names=["This year", "Last year"], base=7200000),
    mix=dict(title="Listings by type", parts=["Flats", "Houses", "Townhouses", "New builds", "Land"]),
    activity=["Offer accepted on 14 Oak Lane", "Viewing booked at the Riverside flat", "New listing: 3 bed house on Elm Road", "Price reduced on 22 Harbour View", "Buyer finance confirmed", "Photos uploaded for 8 Maple Close"],
    entities=[
        dict(singular="Listing", plural="Listings", prefix="", icon="building", desc="Homes for sale.",
             fields=[("Property", "words:14 Oak Lane|22 Harbour View|8 Maple Close|Riverside flat 4B|3 Elm Road|The Old Mill"), ("Type", "choice:Flat|House|Townhouse|New build"), ("Price", "money:180000-1400000"), ("Listed", "date"), ("Status", "status:For sale|Under offer|Sold|Withdrawn")]),
        dict(singular="Buyer", plural="Buyers", prefix="", icon="users", desc="People looking to buy.",
             fields=[("Buyer", "person"), ("Budget", "money:150000-1200000"), ("Wants", "choice:Flat|2 bed house|3 bed house|Family home"), ("Registered", "date"), ("Status", "status:Active|Offer made|Bought")]),
        dict(singular="Viewing", plural="Viewings", prefix="", icon="calendar", desc="Viewings booked.",
             fields=[("Property", "words:14 Oak Lane|22 Harbour View|8 Maple Close|Riverside flat 4B"), ("Buyer", "person"), ("Date", "date:future"), ("Time", "time"), ("Status", "status:Booked|Done|Cancelled")]),
        dict(singular="Offer", plural="Offers", prefix="OF-", icon="file", desc="Offers from buyers.",
             fields=[("Offer", "id"), ("Property", "words:14 Oak Lane|22 Harbour View|3 Elm Road|The Old Mill"), ("Buyer", "person"), ("Amount", "money:170000-1300000"), ("Status", "status:Accepted|Pending|Rejected")]),
        dict(singular="Seller", plural="Sellers", prefix="", icon="user", desc="Homeowners selling with you.",
             fields=[("Seller", "person"), ("Property", "words:14 Oak Lane|22 Harbour View|8 Maple Close|3 Elm Road"), ("Fee", "pct:1-2"), ("Since", "date"), ("Status", "status:Listed|Under offer|Completed")]),
    ],
    specials=[
        dict(title="Sales progression", type="kanban", icon="kanban", desc="Sales from offer to keys.", items=["Offer accepted", "Survey", "Legal work", "Exchange", "Completed"], cards=["14 Oak Lane", "3 Elm Road", "The Old Mill", "Riverside flat 4B"], money=True),
        dict(title="Viewing diary", type="calendar", icon="calendar", desc="Viewings and valuations.", items=["Viewing", "Valuation", "Open house", "Photo shoot", "Completion"]),
        dict(title="Area map", type="map", icon="map", desc="Listings around town.", items=["Old Town", "Riverside", "Harbour", "Hillcrest", "New estate"]),
        dict(title="Listings gallery", type="gallery", icon="grid", desc="Current homes for sale.", items=["14 Oak Lane", "22 Harbour View", "8 Maple Close", "Riverside flat 4B", "3 Elm Road", "The Old Mill"]),
        dict(title="Market report", type="report", icon="chart", desc="Prices, time to sell and fees.", items=["Average price", "Days to sell", "Asking price achieved", "Fees earned"], rows=["Flats", "Houses", "Townhouses", "New builds", "Land"]),
        dict(title="Property brochure", type="document", icon="file", desc="A printable property brochure layout.", doc="14 Oak Lane", num="3 bedroom family home", items=["Guide price", "Stamp duty estimate", "Legal fees estimate", "Survey estimate"], note="Demo brochure. Prices and costs are invented."),
        dict(title="Buyer enquiries", type="split", icon="message", desc="Messages from buyers.", items=["Is 14 Oak Lane still available?", "Can I view on Saturday?", "Is the price negotiable?", "Question about the garden", "We would like to make an offer"]),
    ],
))

B9.append(dict(
    num=93, slug="rentwise", brand="Rentwise", category="Property Management", org="Northgate Lettings", currency="$",
    tagline="Properties, tenants, rent and repairs for a letting agency.",
    auth_line="Rent collected. Repairs handled.", user="Owen Haddad", user_role="Property manager",
    theme=dict(fonts=["Heebo", "Heebo", "Roboto Mono"], accent="#2563eb", layout="accent", card="border", radius="10px",
               c2="#93c5fd", c3="#f59e0b", c4="#10b981"),
    kpis=[("Properties managed", "int", 342, "building"), ("Occupancy", "pct", 96.4, "check"), ("Rent collected this month", "money", 486000, "dollar"), ("Open repairs", "int", 28, "tool")],
    chart=dict(title="Rent collected", names=["Collected", "Due"], base=470000),
    mix=dict(title="Portfolio by type", parts=["Flats", "Houses", "Student lets", "Commercial", "Other"]),
    activity=["Rent received from 184 tenants", "Boiler repair booked at Flat 12", "New tenancy signed at 8 Elm Road", "Inspection done at Riverside Court", "Deposit returned to the Silva family", "Late rent reminder sent"],
    entities=[
        dict(singular="Property", plural="Properties", prefix="", icon="building", desc="Homes you manage.",
             fields=[("Property", "words:Flat 12, Riverside Court|8 Elm Road|22 Harbour View|Flat 3, Mill House|14 Oak Lane|Studio 7, The Works"), ("Landlord", "person"), ("Rent", "money:600-3200"), ("Bedrooms", "int:1-5"), ("Status", "status:Let|Vacant|Under repair")]),
        dict(singular="Tenant", plural="Tenants", prefix="", icon="users", desc="People renting your properties.",
             fields=[("Tenant", "person"), ("Property", "words:Flat 12, Riverside Court|8 Elm Road|22 Harbour View|Flat 3, Mill House"), ("Moved in", "date"), ("Rent", "money:600-3200"), ("Status", "status:Paid|Due|Late")]),
        dict(singular="Rent payment", plural="Rent", slug="rent", prefix="RP-", icon="dollar", desc="Rent due and received.",
             fields=[("Payment", "id"), ("Tenant", "person"), ("Due", "date"), ("Amount", "money:600-3200"), ("Status", "status:Paid|Partial|Late")]),
        dict(singular="Repair", plural="Repairs", prefix="RR-", icon="tool", desc="Maintenance requests.",
             fields=[("Repair", "id"), ("Issue", "choice:Boiler|Leak|Broken window|Damp|Electrics|Lock"), ("Property", "words:Flat 12, Riverside Court|8 Elm Road|Flat 3, Mill House"), ("Reported", "date"), ("Status", "status:Open|Contractor booked|Fixed")]),
        dict(singular="Landlord", plural="Landlords", prefix="", icon="user", desc="Owners you work for.",
             fields=[("Landlord", "person"), ("Properties", "int:1-24"), ("Monthly rent", "money:600-60000"), ("Fee", "pct:8-15"), ("Status", "status:Active|Leaving")]),
    ],
    specials=[
        dict(title="Repairs board", type="kanban", icon="kanban", desc="Repairs from report to fixed.", items=["Reported", "Quote", "Contractor booked", "In progress", "Fixed"], cards=["Boiler not working", "Leaking tap", "Broken window", "Damp in bedroom"]),
        dict(title="Inspections", type="calendar", icon="calendar", desc="Property visits and move-ins.", items=["Inspection", "Move in", "Move out", "Gas safety check", "Viewing"]),
        dict(title="Portfolio map", type="map", icon="map", desc="Where your properties are.", items=["Riverside", "Old Town", "Harbour", "University", "Hillcrest"]),
        dict(title="Rent report", type="report", icon="chart", desc="Rent, arrears and void days.", items=["Rent collected", "Arrears", "Void days", "Fees earned"], rows=["Flats", "Houses", "Student lets", "Commercial", "Other"]),
        dict(title="Landlord statement", type="document", icon="receipt", desc="A monthly statement for a landlord.", doc="Landlord statement", num="September 2026", items=["Rent received", "Management fee", "Boiler repair", "Gas safety check"], note="The balance will be paid to your account within 3 working days."),
        dict(title="Tenant messages", type="split", icon="message", desc="Messages from tenants.", items=["Boiler is not working", "Can I pay rent a few days late?", "Moving out in December", "Parcel left with neighbour", "Thanks for the quick repair"]),
        dict(title="Letting rules", type="config", icon="settings", desc="How your agency works.", items=["Send rent reminders 3 days before the due date", "Chase late rent after 5 days", "Inspect every property twice a year", "Book gas safety checks automatically"]),
    ],
))

B9.append(dict(
    num=94, slug="lendly", brand="Lendly", category="Loan Lending", org="Oakridge Credit Union", currency="$",
    tagline="Applications, loans, repayments and risk for a small lender.",
    auth_line="Fair lending, clearly managed.", user="Isaac Novak", user_role="Lending manager",
    theme=dict(fonts=["IBM Plex Serif", "IBM Plex Sans", "IBM Plex Mono", "IBM Plex Sans"], accent="#047857", layout="dark", card="border", radius="6px", sidebar="#04201a",
               c2="#6ee7b7", c3="#f59e0b", c4="#6366f1"),
    kpis=[("Loan book", "money", 42800000, "briefcase"), ("New applications", "int", 214, "file"), ("Approval rate", "pct", 68.4, "check"), ("Late payments", "pct", 2.1, "alert")],
    chart=dict(title="Money lent", names=["Lent", "Repaid"], base=3200000),
    mix=dict(title="Loans by product", parts=["Personal", "Car", "Home improvement", "Small business", "Student"]),
    activity=["Loan LN-4412 approved", "Repayment received from 1,240 members", "Affordability check flagged", "New product: green home loan", "Arrears call made to 12 members", "Monthly risk report shared"],
    entities=[
        dict(singular="Application", plural="Applications", prefix="AP-", icon="file", desc="Loan applications waiting for a decision.",
             fields=[("Application", "id"), ("Applicant", "person"), ("Product", "choice:Personal|Car|Home improvement|Small business"), ("Amount", "money:1000-80000"), ("Status", "status:Approved|In review|Declined|Documents needed")]),
        dict(singular="Loan", plural="Loans", prefix="LN-", icon="briefcase", desc="Active loans.",
             fields=[("Loan", "id"), ("Borrower", "person"), ("Balance", "money:500-75000"), ("Rate", "pct:3-14"), ("Status", "status:On track|Late|Paid off")]),
        dict(singular="Borrower", plural="Borrowers", prefix="", icon="users", desc="Members who borrow.",
             fields=[("Borrower", "person"), ("Loans", "int:1-3"), ("Credit score", "int:480-850"), ("Member since", "date"), ("Status", "status:Good standing|Watch|Arrears")]),
        dict(singular="Repayment", plural="Repayments", prefix="RP-", icon="dollar", desc="Payments due and received.",
             fields=[("Repayment", "id"), ("Borrower", "person"), ("Due", "date"), ("Amount", "money:40-2400"), ("Status", "status:Paid|Due|Missed")]),
        dict(singular="Product", plural="Products", prefix="", icon="layers", desc="Loan products you offer.",
             fields=[("Product", "words:Personal loan|Car loan|Home improvement|Green home loan|Small business loan|Student loan"), ("Rate from", "pct:3-12"), ("Loans", "int:20-2400"), ("Book", "money:100000-14000000"), ("Status", "status:Available|Paused")]),
    ],
    specials=[
        dict(title="Decision queue", type="kanban", icon="kanban", desc="Applications from received to paid out.", items=["Received", "Checks", "Underwriting", "Approved", "Paid out"], cards=["Car loan", "Personal loan", "Home improvement", "Small business"], money=True),
        dict(title="Risk monitor", type="monitor", icon="shield", desc="Live risk signals across the book.", items=["Arrears rate", "Early warning", "Fraud checks", "Affordability flags", "Large loans", "New borrowers"], unit="%"),
        dict(title="Portfolio report", type="report", icon="chart", desc="Lending, repayments and arrears.", items=["Money lent", "Repayments", "Arrears", "Interest earned"], rows=["Personal", "Car", "Home improvement", "Small business", "Student"]),
        dict(title="Payment calendar", type="calendar", icon="calendar", desc="Repayments and reviews.", items=["Repayment run", "Arrears calls", "Credit committee", "Audit", "Rate review"]),
        dict(title="Loan agreement", type="document", icon="file", desc="A printable loan summary.", doc="Loan summary", num="LN-1047, car loan", items=["Loan amount", "Interest over the term", "Arrangement fee", "Payment protection"], note="Demo layout only. Rates and amounts are invented."),
        dict(title="Arrears", type="timeline", icon="alert", desc="Steps taken on a late account.", items=["Payment missed", "Friendly reminder sent", "Phone call and payment plan agreed", "First plan payment received"]),
        dict(title="Lending rules", type="config", icon="shield", desc="Checks every application must pass.", items=["Run an affordability check on every application", "Require two approvers for loans over $25,000", "Offer a payment plan before any fees", "Review rates every quarter"]),
    ],
))

B9.append(dict(
    num=95, slug="procura", brand="Procura", category="Procurement", org="Beacon Manufacturing Group", currency="$",
    tagline="Requests, purchase orders, suppliers and spend for a purchasing team.",
    auth_line="Buy the right things at the right price.", user="Julia Mensah", user_role="Head of procurement",
    theme=dict(fonts=["Overpass", "Overpass", "Overpass Mono"], accent="#7c3aed", layout="light", card="border", radius="8px",
               c2="#c4b5fd", c3="#f59e0b", c4="#10b981"),
    kpis=[("Spend this quarter", "money", 4820000, "dollar"), ("Open purchase orders", "int", 142, "file"), ("Savings found", "money", 312000, "trend"), ("Suppliers", "int", 486, "building")],
    chart=dict(title="Spend", names=["Actual", "Budget"], base=1600000),
    mix=dict(title="Spend by category", parts=["Raw materials", "IT", "Logistics", "Facilities", "Services"]),
    activity=["PO-8812 approved by finance", "Tender closed: packaging supply", "New supplier onboarded", "Savings of $42,000 on steel contract", "Invoice matched to delivery", "Contract renewal due next month"],
    entities=[
        dict(singular="Request", plural="Purchase requests", slug="purchase-requests", prefix="REQ-", icon="inbox", desc="Things teams asked to buy.",
             fields=[("Request", "id"), ("Item", "words:Laptops for new hires|Steel sheets|Office chairs|Packaging boxes|Safety boots|Cloud storage"), ("Requested by", "person"), ("Value", "money:200-80000"), ("Status", "status:Approved|Waiting approval|Rejected|Ordered")]),
        dict(singular="Purchase order", plural="Purchase orders", slug="purchase-orders", prefix="PO-", icon="file", desc="Orders sent to suppliers.",
             fields=[("Order", "id"), ("Supplier", "company"), ("Value", "money:500-200000"), ("Delivery", "date:future"), ("Status", "status:Sent|Confirmed|Delivered|Late")]),
        dict(singular="Supplier", plural="Suppliers", prefix="", icon="building", desc="Companies you buy from.",
             fields=[("Supplier", "company"), ("Category", "choice:Raw materials|IT|Logistics|Facilities|Services"), ("Spend this year", "money:5000-2000000"), ("Score", "pct:60-99"), ("Status", "status:Approved|On review|Blocked")]),
        dict(singular="Contract", plural="Contracts", prefix="CT-", icon="briefcase", desc="Supply agreements.",
             fields=[("Contract", "id"), ("Supplier", "company"), ("Value", "money:20000-3000000"), ("Ends", "date:future"), ("Status", "status:Active|Renewal due|Expired")]),
        dict(singular="Invoice", plural="Invoices", prefix="INV-", icon="receipt", desc="Supplier invoices to match and pay.",
             fields=[("Invoice", "id"), ("Supplier", "company"), ("Amount", "money:300-180000"), ("Received", "date"), ("Status", "status:Matched|Waiting for delivery|Disputed|Paid")]),
    ],
    specials=[
        dict(title="Approval queue", type="kanban", icon="kanban", desc="Requests from submitted to ordered.", items=["Submitted", "Manager", "Finance", "Approved", "Ordered"], cards=["Laptops for new hires", "Steel sheets", "Office chairs", "Safety boots"], money=True),
        dict(title="Spend report", type="report", icon="chart", desc="Spend, savings and compliance.", items=["Spend", "Savings", "Spend under contract", "Late deliveries"], rows=["Raw materials", "IT", "Logistics", "Facilities", "Services"]),
        dict(title="Top suppliers", type="ranking", icon="star", desc="Suppliers by spend this year.", items=["Atlas Steel", "Cedar Packaging", "Summit IT", "Harbor Logistics", "Oak Facilities", "Beacon Services"], metric="Spend", scale=18000),
        dict(title="Tenders", type="timeline", icon="clock", desc="Recent tenders and results.", items=["Packaging tender closed, 6 bids", "Steel supply awarded to Atlas Steel", "IT hardware tender opened", "Cleaning services tender cancelled"]),
        dict(title="Contract renewals", type="calendar", icon="calendar", desc="Contracts ending soon.", items=["Contract renewal", "Supplier review", "Tender deadline", "Budget meeting", "Audit"]),
        dict(title="Purchase order", type="document", icon="file", desc="A printable purchase order.", doc="Purchase order", num="PO-1047", items=["Steel sheets, 2 mm", "Steel sheets, 4 mm", "Delivery charge", "Cutting service"], note="Please quote the PO number on your invoice and delivery note."),
        dict(title="Buying rules", type="config", icon="shield", desc="Controls on spending.", items=["Require 3 quotes for orders over $10,000", "Finance approval for orders over $25,000", "Block payments without a matched delivery", "Remind owners 90 days before contracts end"]),
    ],
))
