"""Batch 8: Public, nonprofit and energy dashboards (numbers 76 to 85)."""

B8 = []

B8.append(dict(
    num=76, slug="letterbox", brand="Letterbox", category="Newsletter", org="The Morning Brief", currency="$",
    tagline="Issues, subscribers, growth and paid plans for an independent newsletter.",
    auth_line="Write every week. Grow every month.", user="Grace Silva", user_role="Writer and publisher",
    theme=dict(fonts=["Literata", "Inter", "JetBrains Mono", "Inter"], accent="#9f1239", layout="light", card="border", radius="8px",
               bg="#fcfbf9", surface2="#f6f3ee", line="#e9e4dc", c2="#fda4af", c3="#1e3a8a", c4="#15803d"),
    kpis=[("Subscribers", "int", 38400, "users"), ("Paid subscribers", "int", 2140, "star"), ("Open rate", "pct", 54.2, "inbox"), ("Monthly revenue", "money", 12800, "dollar")],
    chart=dict(title="Subscriber growth", names=["Free", "Paid x10"], base=34000),
    mix=dict(title="Where readers come from", parts=["Referrals", "Search", "Social", "Other newsletters", "Direct"]),
    activity=["Issue 214 sent to 38,400 readers", "42 new paid subscribers this week", "Referral reward sent", "Guest post scheduled", "Welcome email updated", "Sponsor booked for November"],
    entities=[
        dict(singular="Issue", plural="Issues", prefix="#", icon="inbox", desc="Every issue you sent.",
             fields=[("Issue", "id"), ("Title", "words:The week in five stories|Why prices keep rising|A quiet win for cities|What we got wrong|Reader questions, answered"), ("Sent", "date"), ("Open rate", "pct:38-68"), ("Status", "status:Sent|Scheduled|Draft")]),
        dict(singular="Subscriber", plural="Subscribers", prefix="", icon="users", desc="Everyone on your list.",
             fields=[("Reader", "email"), ("Plan", "choice:Free|Monthly|Yearly|Founding member"), ("Joined", "date"), ("Opens", "pct:0-100"), ("Status", "status:Active|Inactive|Unsubscribed")]),
        dict(singular="Plan", plural="Paid plans", slug="paid-plans", prefix="", icon="card", desc="What paying readers get.",
             fields=[("Plan", "words:Monthly|Yearly|Founding member|Student|Group"), ("Price", "money:4-120"), ("Members", "int:20-1600"), ("Revenue", "money:200-9000"), ("Status", "status:Active|Hidden")]),
        dict(singular="Sponsor", plural="Sponsors", prefix="", icon="briefcase", desc="Brands that sponsor issues.",
             fields=[("Sponsor", "company"), ("Issues", "int:1-8"), ("Rate", "money:400-2400"), ("Next issue", "date:future"), ("Status", "status:Booked|Proposal|Done")]),
        dict(singular="Referral", plural="Referrals", prefix="", icon="zap", desc="Readers who brought friends.",
             fields=[("Reader", "person"), ("Referred", "int:1-60"), ("Reward", "choice:Sticker pack|Free month|Tote bag|Call with the writer"), ("Last referral", "date"), ("Status", "status:Reward sent|Earned|Pending")]),
    ],
    specials=[
        dict(title="Growth report", type="report", icon="chart", desc="Readers, opens and revenue.", items=["New subscribers", "Paid conversion", "Open rate", "Churn"], rows=["Referrals", "Search", "Social", "Other newsletters", "Direct"]),
        dict(title="Writing calendar", type="calendar", icon="calendar", desc="Issues and deadlines.", items=["Weekly issue", "Paid extra", "Guest post", "Sponsor slot", "Reader Q and A"]),
        dict(title="Draft board", type="kanban", icon="kanban", desc="Ideas from note to sent.", items=["Ideas", "Writing", "Editing", "Scheduled", "Sent"], cards=["Five stories this week", "Housing explainer", "Reader questions", "Year in review"]),
        dict(title="Top issues", type="ranking", icon="star", desc="Most opened issues this year.", items=["Why prices keep rising", "What we got wrong", "A quiet win for cities", "Reader questions, answered", "The week in five stories"], metric="Opens", scale=300),
        dict(title="Issue preview", type="document", icon="file", desc="How the next issue will look.", doc="The Morning Brief, issue 215", num="Sending Friday at 7:00", items=["Top story", "Four quick reads", "Chart of the week", "Sponsor note"], note="Preview only. The table lists section costs for the sponsor summary."),
        dict(title="Reader replies", type="split", icon="message", desc="Replies to your issues.", items=["Great issue this week", "I think you got one fact wrong", "Can I share this at work?", "Please cover local news", "Cancel my paid plan"]),
        dict(title="Sending settings", type="config", icon="settings", desc="How issues go out.", items=["Send at 7am in each reader's time zone", "Remove readers who never open after 6 months", "Show a referral link in every issue", "Offer a free week before paid plans"]),
    ],
))

B8.append(dict(
    num=77, slug="brightwork", brand="Brightwork", category="Digital Agency", org="Brightwork Digital", currency="$",
    tagline="Clients, projects, retainers and team time for a digital agency.",
    auth_line="Great work for clients, on time and on budget.", user="Kenji Walsh", user_role="Managing director",
    theme=dict(fonts=["League Spartan", "Inter", "JetBrains Mono", "League Spartan"], accent="#ff5a1f", layout="dark", card="flat", radius="0px", sidebar="#111111",
               c2="#fdba74", c3="#3b82f6", c4="#22c55e"),
    kpis=[("Active clients", "int", 28, "building"), ("Retainer revenue", "money", 184000, "dollar"), ("Team utilisation", "pct", 82.0, "users"), ("Projects due this month", "int", 9, "folder")],
    chart=dict(title="Revenue", names=["Revenue", "Costs"], base=220000),
    mix=dict(title="Revenue by service", parts=["Web design", "SEO", "Paid ads", "Branding", "Content"]),
    activity=["Website launched for Harbor Health", "New retainer signed with Maple Foods", "Pitch sent to Summit Labs", "Monthly reports sent to 12 clients", "Designer hired: Aisha Novak", "Budget alert on Cedar rebrand"],
    entities=[
        dict(singular="Client", plural="Clients", prefix="", icon="building", desc="Businesses you work for.",
             fields=[("Client", "company"), ("Services", "choice:Web and SEO|Paid ads|Branding|Full service"), ("Retainer", "money:1500-24000"), ("Since", "date"), ("Status", "status:Active|Paused|Churn risk")]),
        dict(singular="Project", plural="Projects", prefix="PRJ-", icon="folder", desc="Work in progress.",
             fields=[("Project", "words:Harbor website|Maple SEO audit|Cedar rebrand|Summit ad campaign|Oak app landing page"), ("Client", "company"), ("Budget", "money:4000-120000"), ("Due", "date:future"), ("Status", "status:On track|At risk|Delayed|Done")]),
        dict(singular="Retainer", plural="Retainers", prefix="", icon="clock", desc="Monthly contracts and hours.",
             fields=[("Client", "company"), ("Hours a month", "int:10-160"), ("Hours used", "pct:30-120"), ("Monthly fee", "money:1500-24000"), ("Status", "status:On track|Over hours|Renewal due")]),
        dict(singular="Team member", plural="Team members", slug="team-members", prefix="", icon="users", desc="Designers, developers and marketers.",
             fields=[("Name", "person"), ("Role", "choice:Designer|Developer|SEO|Ads|Account manager"), ("Utilisation", "pct:40-100"), ("Projects", "int:1-6"), ("Status", "status:Available|Busy|Holiday")]),
        dict(singular="Proposal", plural="Proposals", prefix="PR-", icon="file", desc="Pitches to new clients.",
             fields=[("Proposal", "id"), ("Prospect", "company"), ("Value", "money:5000-180000"), ("Sent", "date"), ("Status", "status:Won|Sent|Lost|Draft")]),
    ],
    specials=[
        dict(title="Project board", type="kanban", icon="kanban", desc="Every project, stage by stage.", items=["Brief", "Design", "Build", "Client review", "Launched"], cards=["Harbor website", "Cedar rebrand", "Oak landing page", "Summit campaign"], who="company"),
        dict(title="Agency report", type="report", icon="chart", desc="Revenue, margin and time.", items=["Revenue", "Margin", "Utilisation", "Client retention"], rows=["Web design", "SEO", "Paid ads", "Branding", "Content"]),
        dict(title="Team workload", type="ranking", icon="users", desc="Hours booked per person this week.", items=["Aisha Novak", "Kenji Walsh", "Liam Costa", "Maya Haddad", "Noah Silva", "Priya Khan"], metric="Hours", scale=0.45),
        dict(title="Launch calendar", type="calendar", icon="calendar", desc="Launches, reviews and pitches.", items=["Site launch", "Client review", "Pitch", "Monthly report", "Workshop"]),
        dict(title="Case studies", type="gallery", icon="grid", desc="Work you can show new clients.", items=["Harbor Health website", "Maple Foods SEO", "Cedar rebrand", "Summit ad campaign", "Oak app launch", "Beacon retail"]),
        dict(title="Monthly client report", type="document", icon="file", desc="A printable report for a retainer client.", doc="Monthly report", num="Maple Foods, September 2026", items=["SEO work", "Content writing", "Paid ads management", "Reporting and calls"], note="Organic traffic grew 18 percent this month. Next month we focus on product pages."),
        dict(title="Agency settings", type="config", icon="settings", desc="How the agency runs.", items=["Warn at 80 percent of retainer hours", "Send client reports on the 1st", "Ask for timesheets every Friday", "Require sign-off before launch"]),
    ],
))

B8.append(dict(
    num=78, slug="kindred", brand="Kindred", category="Nonprofit Donations", org="Open Table Food Bank", currency="$",
    tagline="Donors, gifts, campaigns and volunteers for a charity.",
    auth_line="Every gift counts. Every donor matters.", user="Aisha Morris", user_role="Fundraising lead",
    theme=dict(fonts=["Merriweather Sans", "Merriweather Sans", "Roboto Mono"], accent="#e85d04", layout="tint", card="shadow", radius="14px",
               c2="#fdba74", c3="#0ea5e9", c4="#16a34a"),
    kpis=[("Raised this year", "money", 842000, "heart"), ("Donors", "int", 6240, "users"), ("Monthly givers", "int", 1180, "calendar"), ("Meals funded", "int", 214000, "box")],
    chart=dict(title="Donations", names=["This year", "Last year"], base=68000),
    mix=dict(title="Gifts by type", parts=["One-off", "Monthly", "Events", "Grants", "Legacy"]),
    activity=["Winter appeal passed $120,000", "Thank you emails sent to 412 donors", "Grant approved by a city fund", "Volunteer shift filled for Saturday", "Corporate match from Maple Foods", "Gift aid claim sent"],
    entities=[
        dict(singular="Donor", plural="Donors", prefix="", icon="users", desc="People and companies who give.",
             fields=[("Donor", "person"), ("Type", "choice:Individual|Monthly giver|Company|Trust"), ("Given this year", "money:10-20000"), ("Last gift", "date"), ("Status", "status:Active|Lapsed|New")]),
        dict(singular="Gift", plural="Gifts", prefix="G-", icon="heart", desc="Every donation received.",
             fields=[("Gift", "id"), ("Donor", "person"), ("Campaign", "words:Winter appeal|School meals|Summer food drive|General fund"), ("Amount", "money:5-5000"), ("Status", "status:Received|Pledged|Refunded")]),
        dict(singular="Campaign", plural="Campaigns", prefix="", icon="star", desc="Appeals and fundraisers.",
             fields=[("Campaign", "words:Winter appeal|School meals|Summer food drive|Fun run 2026|Holiday hampers"), ("Goal", "money:10000-200000"), ("Raised", "money:2000-180000"), ("Ends", "date:future"), ("Status", "status:Live|Planned|Closed")]),
        dict(singular="Volunteer", plural="Volunteers", prefix="", icon="user", desc="People who give their time.",
             fields=[("Volunteer", "person"), ("Role", "choice:Warehouse|Driver|Kitchen|Events|Office"), ("Hours this year", "int:4-400"), ("Next shift", "date:future"), ("Status", "status:Active|On break|New")]),
        dict(singular="Grant", plural="Grants", prefix="", icon="briefcase", desc="Funding from trusts and councils.",
             fields=[("Funder", "company"), ("Purpose", "words:School meals|New van|Cold storage|Staff costs|Community kitchen"), ("Amount", "money:5000-150000"), ("Decision", "date:future"), ("Status", "status:Awarded|Applied|Declined")]),
    ],
    specials=[
        dict(title="Appeal progress", type="monitor", icon="activity", desc="Live totals for each campaign.", items=["Winter appeal", "School meals", "Summer food drive", "Fun run 2026", "Holiday hampers", "General fund"], unit="%"),
        dict(title="Fundraising report", type="report", icon="chart", desc="Income, donors and retention.", items=["Raised", "New donors", "Donor retention", "Cost to raise $1"], rows=["One-off", "Monthly", "Events", "Grants", "Legacy"]),
        dict(title="Top supporters", type="ranking", icon="star", desc="The biggest supporters this year.", items=["Maple Foods", "City Community Fund", "Harbor Trust", "Olivia Chen", "Beacon Retail", "Cedar Foundation"], metric="Given", scale=700),
        dict(title="Donor path", type="kanban", icon="kanban", desc="Donors from first gift to long-term supporter.", items=["First gift", "Thanked", "Second gift", "Monthly giver", "Champion"], cards=["Winter appeal donor", "Fun run sponsor", "Company match", "Event guest"]),
        dict(title="Volunteer rota", type="calendar", icon="calendar", desc="Shifts and events.", items=["Warehouse shift", "Delivery run", "Kitchen shift", "Collection day", "Volunteer training"]),
        dict(title="Donation receipt", type="document", icon="receipt", desc="A printable receipt for a donor.", doc="Donation receipt", num="G-1047", items=["Winter appeal gift", "Monthly gift, September", "Fun run sponsorship"], note="Thank you. Your gift helps us provide hot meals to families in our city."),
        dict(title="Thank you rules", type="config", icon="heart", desc="How donors are thanked.", items=["Send a thank you email within 24 hours", "Call donors who give over $500", "Send a yearly impact report", "Ask monthly givers before changing their gift"]),
    ],
))

B8.append(dict(
    num=79, slug="gather", brand="Gather", category="Church and Community", org="St. Brendan's Community Church", currency="$",
    tagline="Members, groups, events and giving for a church community.",
    auth_line="Bring your community together.", user="Samuel Okafor", user_role="Community pastor",
    theme=dict(fonts=["EB Garamond", "Source Sans 3", "Source Code Pro", "Source Sans 3"], accent="#4c1d95", layout="light", card="border", radius="8px",
               bg="#faf9fc", surface2="#f3f1f8", line="#e6e2ef", c2="#c4b5fd", c3="#d97706", c4="#0f766e"),
    kpis=[("Members", "int", 842, "users"), ("Sunday attendance", "int", 412, "calendar"), ("Small groups", "int", 36, "layers"), ("Giving this month", "money", 38400, "heart")],
    chart=dict(title="Weekly attendance", names=["In person", "Online"], base=400),
    mix=dict(title="Groups by type", parts=["Bible study", "Youth", "Parents", "Seniors", "Service"]),
    activity=["Volunteer rota filled for Sunday", "New family welcomed: the Diaz family", "Food drive collected 400 items", "Youth trip permission forms sent", "Prayer request shared with the team", "Livestream set up for Christmas"],
    entities=[
        dict(singular="Member", plural="Members", prefix="", icon="users", desc="People in your community.",
             fields=[("Member", "person"), ("Household", "int:1-6"), ("Group", "choice:Bible study|Youth|Parents|Seniors|Choir"), ("Joined", "date"), ("Status", "status:Active|New|Visitor")]),
        dict(singular="Group", plural="Small groups", slug="small-groups", prefix="", icon="layers", desc="Groups that meet during the week.",
             fields=[("Group", "words:Tuesday Bible study|Youth night|Parents and toddlers|Seniors lunch|Choir|Food bank team"), ("Leader", "person"), ("Members", "int:6-40"), ("Meets", "choice:Monday|Tuesday|Wednesday|Thursday|Saturday"), ("Status", "status:Active|Full|Paused")]),
        dict(singular="Event", plural="Events", prefix="", icon="calendar", desc="Services, meals and outings.",
             fields=[("Event", "words:Sunday service|Harvest supper|Youth camp|Christmas carols|Community clean-up"), ("Date", "date:future"), ("Signed up", "int:10-400"), ("Volunteers", "int:2-40"), ("Status", "status:Open|Full|Planning")]),
        dict(singular="Gift", plural="Giving", slug="giving", prefix="", icon="heart", desc="Donations and regular giving.",
             fields=[("Giver", "person"), ("Fund", "choice:General|Building fund|Food bank|Missions|Youth"), ("Amount", "money:5-2000"), ("Date", "date"), ("Status", "status:Received|Monthly|Pledged")]),
        dict(singular="Volunteer", plural="Volunteers", prefix="", icon="user", desc="People who serve.",
             fields=[("Volunteer", "person"), ("Team", "choice:Welcome|Kids|Music|Tech|Cafe"), ("Serves", "choice:Weekly|Monthly|Occasionally"), ("Next date", "date:future"), ("Status", "status:Scheduled|Available|Away")]),
    ],
    specials=[
        dict(title="Church calendar", type="calendar", icon="calendar", desc="Services, groups and events.", items=["Sunday service", "Bible study", "Youth night", "Community meal", "Choir practice"]),
        dict(title="Serving rota", type="kanban", icon="kanban", desc="Sunday teams and who is serving.", items=["Welcome", "Kids", "Music", "Tech", "Cafe"], cards=["Morning service", "Evening service", "Family service", "Special event"]),
        dict(title="Community report", type="report", icon="chart", desc="Attendance, groups and giving.", items=["Attendance", "New visitors", "Group members", "Giving"], rows=["Sunday service", "Youth", "Small groups", "Community meals", "Online"]),
        dict(title="Prayer and care", type="split", icon="message", desc="Requests shared with the care team.", items=["Please pray for my mum's surgery", "New job starting Monday", "Meals needed for a new baby", "Hospital visit request", "Thank you for your support"]),
        dict(title="Announcements", type="timeline", icon="bell", desc="News for the community.", items=["Harvest supper on Saturday", "Youth camp sign-ups open", "Food drive this month", "New Bible study starting"]),
        dict(title="Giving statement", type="document", icon="receipt", desc="A yearly giving statement.", doc="Annual giving statement", num="2026", items=["General fund", "Building fund", "Food bank", "Missions"], note="Thank you for your generosity this year."),
        dict(title="Community settings", type="config", icon="settings", desc="How the church app works.", items=["Welcome new visitors by email", "Remind volunteers 2 days before serving", "Keep prayer requests private to the care team", "Send a weekly newsletter"]),
    ],
))

B8.append(dict(
    num=80, slug="civic", brand="Civic", category="City Services", org="City of Millbrook", currency="$",
    tagline="Service requests, permits, crews and budgets for a city council.",
    auth_line="Fix the pothole. Answer the resident.", user="Maria Lopez", user_role="City services director",
    theme=dict(fonts=["Public Sans", "Public Sans", "Roboto Mono"], accent="#1d4ed8", layout="accent", card="border", radius="4px",
               c2="#93c5fd", c3="#f59e0b", c4="#16a34a"),
    kpis=[("Open requests", "int", 842, "inbox"), ("Solved this week", "int", 614, "check"), ("Average days to fix", "int", 4, "clock"), ("Permits issued", "int", 128, "file")],
    chart=dict(title="Service requests", names=["Received", "Solved"], base=2400),
    mix=dict(title="Requests by type", parts=["Potholes", "Street lights", "Rubbish", "Parks", "Noise"]),
    activity=["Pothole fixed on Oak Street", "Street light repaired in Riverside", "Building permit approved", "Missed bin collection reported", "Park bench replaced", "Snow plan published"],
    entities=[
        dict(singular="Request", plural="Service requests", slug="service-requests", prefix="SR-", icon="inbox", desc="Problems reported by residents.",
             fields=[("Request", "id"), ("Type", "choice:Pothole|Street light|Missed bin|Graffiti|Broken bench"), ("Area", "choice:North|South|Riverside|Old Town|East"), ("Reported", "date"), ("Status", "status:Solved|Assigned|New|On hold")]),
        dict(singular="Permit", plural="Permits", prefix="P-", icon="file", desc="Building, event and parking permits.",
             fields=[("Permit", "id"), ("Type", "choice:Building|Event|Parking|Street works|Food stall"), ("Applicant", "person"), ("Applied", "date"), ("Status", "status:Approved|In review|Rejected")]),
        dict(singular="Crew", plural="Crews", prefix="", icon="truck", desc="Teams out fixing things.",
             fields=[("Crew", "words:Roads team 1|Roads team 2|Lighting team|Parks team|Waste team"), ("Lead", "person"), ("Jobs today", "int:2-24"), ("Area", "choice:North|South|Riverside|Old Town"), ("Status", "status:On a job|Available|Off shift")]),
        dict(singular="Asset", plural="City assets", slug="city-assets", prefix="", icon="building", desc="Street lights, parks and buildings.",
             fields=[("Asset", "words:Street light 1142|Riverside park|Library roof|Oak Street bridge|Bus shelter 22"), ("Type", "choice:Lighting|Park|Building|Road|Transport"), ("Last check", "date"), ("Condition", "choice:Good|Fair|Poor"), ("Status", "status:Working|Needs repair|Closed")]),
        dict(singular="Budget line", plural="Budget", slug="budget", prefix="", icon="pie", desc="Spending by department.",
             fields=[("Department", "words:Roads|Parks|Waste|Lighting|Libraries"), ("Budget", "money:400000-9000000"), ("Spent", "money:200000-8000000"), ("Used", "pct:20-105"), ("Status", "status:On track|At risk|Over")]),
    ],
    specials=[
        dict(title="Request map", type="map", icon="map", desc="Open requests across the city.", items=["North", "South", "Riverside", "Old Town", "East"], dots=26),
        dict(title="Work orders", type="kanban", icon="kanban", desc="Requests from report to fixed.", items=["New", "Assigned", "Crew on site", "Fixed", "Closed"], cards=["Pothole", "Street light out", "Missed bin", "Fallen tree"]),
        dict(title="Service report", type="report", icon="chart", desc="Speed and volume of fixes.", items=["Requests solved", "Days to fix", "Resident rating", "Repeat reports"], rows=["Potholes", "Street lights", "Rubbish", "Parks", "Noise"]),
        dict(title="Council calendar", type="calendar", icon="calendar", desc="Meetings, works and events.", items=["Council meeting", "Road works", "Public hearing", "Street market", "Bin day change"]),
        dict(title="Resident messages", type="split", icon="message", desc="Messages from residents.", items=["Street light out on Elm Road", "Thank you for fixing the pothole", "When is bulk waste pickup?", "Noise from building site", "Question about my permit"]),
        dict(title="Crew status", type="monitor", icon="activity", desc="What each crew is doing right now.", items=["Roads team 1", "Roads team 2", "Lighting team", "Parks team", "Waste team", "Snow team"], unit=" jobs"),
        dict(title="Service rules", type="config", icon="settings", desc="Targets and alerts.", items=["Fix dangerous potholes within 24 hours", "Reply to every resident within 2 days", "Text residents when their request is fixed", "Alert managers when a request is open for 14 days"]),
    ],
))

B8.append(dict(
    num=81, slug="ballot", brand="Ballot", category="Election Results", org="Millbrook Election Office", currency="$",
    tagline="Live results, turnout and counting progress for a local election.",
    auth_line="Clear, accurate results for every voter.", user="Hana Larsen", user_role="Returning officer",
    theme=dict(fonts=["Roboto Slab", "Roboto", "Roboto Mono", "Roboto"], accent="#334155", layout="light", card="border", radius="4px",
               d_accent="#cbd5e1", d_on_accent="#0f172a", c2="#14b8a6", c3="#a855f7", c4="#f59e0b"),
    kpis=[("Votes counted", "int", 84200, "check"), ("Turnout", "pct", 61.4, "users"), ("Districts reporting", "int", 18, "map"), ("Polling stations", "int", 42, "building")],
    chart=dict(title="Votes counted by hour", names=["Counted", "Expected"], base=7000),
    mix=dict(title="Share of the vote", parts=["River Party", "Oakfield Group", "Civic Alliance", "Independent", "Other"]),
    activity=["District 7 finished counting", "Turnout update published", "Recount requested in District 3", "Postal votes added", "Results page updated", "Observers checked in at the count centre"],
    entities=[
        dict(singular="District", plural="Districts", prefix="", icon="map", desc="Results for each district.",
             fields=[("District", "words:District 1|District 2|District 3|District 4|District 5|District 6|District 7"), ("Leading", "choice:River Party|Oakfield Group|Civic Alliance|Independent"), ("Counted", "pct:40-100"), ("Turnout", "pct:45-75"), ("Status", "status:Declared|Counting|Recount")]),
        dict(singular="Candidate", plural="Candidates", prefix="", icon="user", desc="Everyone standing in this election.",
             fields=[("Candidate", "person"), ("Group", "choice:River Party|Oakfield Group|Civic Alliance|Independent"), ("District", "words:District 1|District 2|District 3|District 4"), ("Votes", "int:200-9000"), ("Status", "status:Elected|Counting|Not elected")]),
        dict(singular="Polling station", plural="Polling stations", slug="polling-stations", prefix="PS-", icon="building", desc="Where people voted.",
             fields=[("Station", "id"), ("Location", "words:Library|Primary school|Community hall|Sports centre|Church hall"), ("Voters", "int:400-4000"), ("Turnout", "pct:40-80"), ("Status", "status:Ballots received|In transit|Closed")]),
        dict(singular="Ballot box", plural="Ballot boxes", slug="ballot-boxes", prefix="BB-", icon="box", desc="Boxes being counted.",
             fields=[("Box", "id"), ("Station", "code:PS-"), ("Ballots", "int:200-1800"), ("Counted by", "person"), ("Status", "status:Counted|Counting|Waiting")]),
        dict(singular="Issue", plural="Issues log", slug="issues-log", prefix="", icon="alert", desc="Problems reported on the day.",
             fields=[("Issue", "words:Long queue|Wrong ballot papers|Accessibility request|Late opening|Seal checked"), ("Station", "code:PS-"), ("Reported", "date"), ("Reported by", "person"), ("Status", "status:Resolved|Open")]),
    ],
    specials=[
        dict(title="Results map", type="map", icon="map", desc="Counting progress by district.", items=["District 1", "District 2", "District 3", "District 4", "District 5"], dots=18),
        dict(title="Live count", type="monitor", icon="activity", desc="Counting progress right now.", items=["District 1", "District 2", "District 3", "District 4", "District 5", "District 6", "District 7", "Postal votes"], unit="%"),
        dict(title="Results report", type="report", icon="chart", desc="Votes and seats by group.", items=["Total votes", "Turnout", "Spoilt ballots", "Postal votes"], rows=["River Party", "Oakfield Group", "Civic Alliance", "Independent", "Other"]),
        dict(title="Seats won", type="ranking", icon="star", desc="Seats won by each group so far.", items=["River Party", "Oakfield Group", "Civic Alliance", "Independent"], metric="Seats", scale=0.2),
        dict(title="Count board", type="kanban", icon="kanban", desc="Ballot boxes from arrival to declared.", items=["Arrived", "Verified", "Counting", "Checked", "Declared"], cards=["District 1 boxes", "District 3 boxes", "Postal votes", "District 6 boxes"]),
        dict(title="Declaration", type="document", icon="file", desc="A printable result declaration.", doc="Declaration of result", num="District 7", items=["Candidate A votes", "Candidate B votes", "Candidate C votes", "Spoilt ballots"], note="Demo document. All names, groups and numbers are invented."),
        dict(title="Count rules", type="config", icon="shield", desc="Rules for a fair count.", items=["Two staff must check every box seal", "Observers can watch every table", "Publish results only after sign-off", "Recount if the gap is under 1 percent"]),
    ],
    faq=[("Are these real results?", "No. Every place, group, candidate and number in this template is invented.")],
))

B8.append(dict(
    num=82, slug="clearsky", brand="Clearsky", category="Air Quality", org="Millbrook Environment Team", currency="$",
    tagline="Sensors, pollution levels and alerts for city air quality.",
    auth_line="Clean air, measured street by street.", user="Wen Okafor", user_role="Environmental scientist",
    theme=dict(fonts=["Atkinson Hyperlegible", "Atkinson Hyperlegible", "Roboto Mono"], accent="#0891b2", layout="tint", card="shadow", radius="16px",
               c2="#a5f3fc", c3="#f59e0b", c4="#ef4444"),
    kpis=[("Air quality index", "int", 42, "activity"), ("Sensors online", "int", 86, "monitor"), ("Alerts this week", "int", 3, "alert"), ("Good air days", "pct", 78.0, "check")],
    chart=dict(title="Fine dust levels", names=["This year", "Safe limit"], base=18),
    mix=dict(title="Pollution sources", parts=["Traffic", "Heating", "Industry", "Construction", "Other"]),
    activity=["Sensor 22 back online", "Pollution alert sent for Old Town", "Monthly report published", "New sensor installed at the school", "Traffic scheme reduced levels by 12 percent", "Calibration finished"],
    entities=[
        dict(singular="Sensor", plural="Sensors", prefix="AQ-", icon="monitor", desc="Air sensors across the city.",
             fields=[("Sensor", "id"), ("Location", "words:Main Street|Primary school|Riverside park|Bus station|Hospital|Ring road"), ("Index", "int:10-140"), ("Battery", "pct:20-100"), ("Status", "status:Online|Low battery|Offline")]),
        dict(singular="Reading", plural="Readings", prefix="", icon="activity", desc="Recent measurements.",
             fields=[("Sensor", "code:AQ-"), ("Pollutant", "choice:Fine dust|Nitrogen dioxide|Ozone|Carbon monoxide"), ("Level", "int:4-90"), ("Time", "time"), ("Status", "status:Good|Moderate|Unhealthy")]),
        dict(singular="Zone", plural="Zones", prefix="", icon="map", desc="Areas of the city.",
             fields=[("Zone", "words:Old Town|Riverside|Industrial park|North hills|City centre|Harbour"), ("Average index", "int:15-110"), ("Sensors", "int:3-18"), ("Trend", "status:Improving|Stable|Worsening"), ("Population", "int:4000-90000")]),
        dict(singular="Alert", plural="Alerts", prefix="", icon="bell", desc="Warnings sent to the public.",
             fields=[("Alert", "words:High fine dust|Ozone warning|Smoke from fire|Traffic pollution|Pollen high"), ("Zone", "words:Old Town|Riverside|City centre|Harbour"), ("Sent", "date"), ("People reached", "int:1000-60000"), ("Status", "status:Active|Ended")]),
        dict(singular="Report", plural="Reports", prefix="", icon="file", desc="Published air quality reports.",
             fields=[("Report", "words:September summary|School zones study|Traffic scheme review|Winter heating report"), ("Published", "date"), ("Pages", "int:4-40"), ("Downloads", "int:40-4000"), ("Status", "status:Published|Draft")]),
    ],
    specials=[
        dict(title="Live air map", type="map", icon="map", desc="Air quality at every sensor.", items=["Old Town", "Riverside", "Industrial park", "City centre", "Harbour"], dots=24),
        dict(title="Sensor network", type="monitor", icon="activity", desc="Live readings from key sensors.", items=["Main Street", "Primary school", "Riverside park", "Bus station", "Hospital", "Ring road", "Harbour", "North hills"], unit=" AQI"),
        dict(title="Air report", type="report", icon="chart", desc="Pollution levels over time.", items=["Average index", "Good air days", "Alerts", "Worst zone"], rows=["Old Town", "Riverside", "Industrial park", "City centre", "Harbour"]),
        dict(title="Cleanest zones", type="ranking", icon="star", desc="Zones with the best air this month.", items=["North hills", "Riverside", "Harbour", "City centre", "Old Town", "Industrial park"], metric="Clean air score", scale=1),
        dict(title="Maintenance", type="kanban", icon="kanban", desc="Sensor repairs and checks.", items=["Reported", "Scheduled", "On site", "Done"], cards=["Replace battery", "Calibrate sensor", "Move sensor", "Clean filter"]),
        dict(title="Action log", type="timeline", icon="clock", desc="Steps the city took to cut pollution.", items=["Low traffic zone started in Old Town", "School street closures at drop-off time", "Bus fleet switched to electric", "Tree planting on the ring road"]),
        dict(title="Alert rules", type="config", icon="bell", desc="When the public is warned.", items=["Send an alert when the index passes 100", "Warn schools first", "Post alerts on the city website", "Text residents who signed up"]),
    ],
))

B8.append(dict(
    num=83, slug="sunfield", brand="Sunfield", category="Solar and Energy", org="Sunfield Energy Co-op", currency="$",
    tagline="Solar output, batteries, grid use and savings for an energy co-op.",
    auth_line="Clean power, tracked every hour.", user="Isaac Ferreira", user_role="Energy manager",
    theme=dict(fonts=["Oxanium", "Inter", "Share Tech Mono", "Oxanium"], accent="#eab308", on_accent="#1c1917", layout="dark", card="border", radius="8px", sidebar="#0f1410",
               c2="#22c55e", c3="#3b82f6", c4="#f97316"),
    kpis=[("Generated today kWh", "int", 18400, "zap"), ("Battery level", "pct", 76.0, "activity"), ("Sold to grid kWh", "int", 6200, "trend"), ("Savings this month", "money", 24800, "dollar")],
    chart=dict(title="Energy generated", names=["Generated", "Used"], base=480000),
    mix=dict(title="Where the power went", parts=["Homes", "Batteries", "Grid", "EV charging", "Other"]),
    activity=["Record day: 21,400 kWh generated", "Inverter 4 back online", "Battery bank 2 fully charged", "New member home connected", "Panels cleaned on the school roof", "Grid export payment received"],
    entities=[
        dict(singular="Site", plural="Solar sites", slug="solar-sites", prefix="", icon="building", desc="Roofs and fields with panels.",
             fields=[("Site", "words:School roof|Community field|Warehouse roof|Library roof|Farm barn|Sports hall"), ("Capacity kW", "int:20-1200"), ("Today kWh", "int:40-6000"), ("Efficiency", "pct:70-98"), ("Status", "status:Generating|Low output|Offline")]),
        dict(singular="Battery", plural="Batteries", prefix="BAT-", icon="activity", desc="Storage banks.",
             fields=[("Battery", "id"), ("Site", "words:Community field|School roof|Warehouse roof"), ("Charge", "pct:10-100"), ("Cycles", "int:100-3000"), ("Status", "status:Charging|Discharging|Idle")]),
        dict(singular="Member", plural="Members", prefix="", icon="users", desc="Homes and businesses in the co-op.",
             fields=[("Member", "person"), ("Type", "choice:Home|Business|School|Farm"), ("Used this month kWh", "int:100-9000"), ("Saved", "money:10-900"), ("Status", "status:Connected|Pending|Paused")]),
        dict(singular="Inverter", plural="Inverters", prefix="INV-", icon="tool", desc="Equipment turning sun into power.",
             fields=[("Inverter", "id"), ("Site", "words:School roof|Community field|Warehouse roof|Farm barn"), ("Output kW", "int:0-400"), ("Temperature", "int:20-70"), ("Status", "status:Online|Warning|Offline")]),
        dict(singular="Payment", plural="Grid payments", slug="grid-payments", prefix="GP-", icon="dollar", desc="Money from selling power to the grid.",
             fields=[("Payment", "id"), ("Month", "words:September|August|July|June"), ("Exported kWh", "int:40000-200000"), ("Amount", "money:2000-16000"), ("Status", "status:Paid|Pending")]),
    ],
    specials=[
        dict(title="Live output", type="monitor", icon="zap", desc="Power from every site right now.", items=["School roof", "Community field", "Warehouse roof", "Library roof", "Farm barn", "Sports hall", "Battery bank 1", "Battery bank 2"], unit=" kW"),
        dict(title="Energy report", type="report", icon="chart", desc="Generation, use and savings.", items=["Generated", "Self used", "Exported", "Carbon saved"], rows=["School roof", "Community field", "Warehouse roof", "Library roof", "Farm barn"]),
        dict(title="Site map", type="map", icon="map", desc="Solar sites across the area.", items=["Town centre", "North farms", "Industrial estate", "Schools", "East villages"]),
        dict(title="Top sites", type="ranking", icon="star", desc="Sites that generated the most this month.", items=["Community field", "Warehouse roof", "School roof", "Farm barn", "Sports hall", "Library roof"], metric="MWh", scale=1.2),
        dict(title="Maintenance", type="calendar", icon="calendar", desc="Cleaning and inspections.", items=["Panel cleaning", "Inverter check", "Battery test", "Roof inspection", "Member meeting"]),
        dict(title="Member statement", type="document", icon="receipt", desc="A monthly statement for a member.", doc="Energy statement", num="September 2026", items=["Solar power used", "Grid power used", "Co-op membership", "Export credit"], note="You saved 38 percent compared with standard grid prices this month."),
        dict(title="Energy rules", type="config", icon="settings", desc="How power is shared.", items=["Charge batteries first when the sun is strong", "Sell extra power to the grid after 4pm", "Send members a monthly savings report", "Alert when a site drops below 50 percent output"]),
    ],
))

B8.append(dict(
    num=84, slug="homebase", brand="Homebase", category="Smart Home", org="The Park family home", currency="$",
    tagline="Lights, heating, cameras and energy use for a smart home.",
    auth_line="Your home, in the palm of your hand.", user="Daniel Park", user_role="Home owner",
    theme=dict(fonts=["Comfortaa", "Mulish", "Roboto Mono", "Mulish"], accent="#6366f1", layout="dark", card="shadow", radius="20px", sidebar="#10121f",
               c2="#a5b4fc", c3="#f59e0b", c4="#22c55e"),
    kpis=[("Devices online", "int", 42, "zap"), ("Indoor temperature", "int", 21, "sun"), ("Energy today kWh", "int", 14, "activity"), ("Doors locked", "pct", 100.0, "shield")],
    chart=dict(title="Energy use", names=["This month", "Last month"], base=380),
    mix=dict(title="Energy by device", parts=["Heating", "Kitchen", "Lights", "Laundry", "Other"]),
    activity=["Front door locked at 23:04", "Heating turned down to 18 degrees", "Motion seen on the back camera", "Washing machine finished", "Living room lights turned off", "Good night scene started"],
    entities=[
        dict(singular="Device", plural="Devices", prefix="", icon="zap", desc="Everything connected at home.",
             fields=[("Device", "words:Living room lights|Front door lock|Thermostat|Back camera|Robot vacuum|Kitchen speaker|Garage door"), ("Room", "choice:Living room|Kitchen|Bedroom|Hall|Garden|Garage"), ("Battery", "pct:20-100"), ("Last active", "date"), ("Status", "status:Online|Offline|Updating")]),
        dict(singular="Room", plural="Rooms", prefix="", icon="building", desc="Rooms and their temperature.",
             fields=[("Room", "words:Living room|Kitchen|Main bedroom|Kids room|Office|Hall"), ("Temperature", "int:17-24"), ("Humidity", "pct:30-65"), ("Devices", "int:2-12"), ("Status", "status:Comfortable|Cold|Warm")]),
        dict(singular="Scene", plural="Scenes", prefix="", icon="star", desc="One tap routines.",
             fields=[("Scene", "words:Good morning|Leaving home|Movie night|Good night|Dinner time"), ("Devices", "int:3-18"), ("Runs this week", "int:1-14"), ("Trigger", "choice:Time|Button|Location|Voice"), ("Status", "status:On|Off")]),
        dict(singular="Camera event", plural="Camera events", slug="camera-events", prefix="", icon="monitor", desc="Motion and doorbell events.",
             fields=[("Event", "words:Motion in garden|Doorbell pressed|Parcel delivered|Person at door|Car in drive"), ("Camera", "choice:Front door|Back garden|Drive|Garage"), ("Time", "time"), ("Date", "date"), ("Status", "status:Seen|New")]),
        dict(singular="Automation", plural="Automations", prefix="", icon="settings", desc="Rules that run on their own.",
             fields=[("Automation", "words:Lights on at sunset|Heating off when nobody is home|Lock doors at 11pm|Close blinds when sunny|Alert if a window is open"), ("Runs this week", "int:1-40"), ("Last run", "date"), ("Created by", "person"), ("Status", "status:On|Paused")]),
    ],
    specials=[
        dict(title="Home now", type="monitor", icon="home", desc="Live status of every room.", items=["Living room", "Kitchen", "Main bedroom", "Kids room", "Office", "Garden", "Garage", "Hall"], unit=" C"),
        dict(title="Energy report", type="report", icon="chart", desc="Where your energy goes.", items=["Energy used", "Cost", "Solar made", "Compared with neighbours"], rows=["Heating", "Kitchen", "Lights", "Laundry", "Office"]),
        dict(title="Floor plan", type="map", icon="map", desc="Devices around the house.", items=["Ground floor", "First floor", "Garden", "Garage", "Loft"], dots=16),
        dict(title="Schedules", type="calendar", icon="calendar", desc="Heating and scene schedules.", items=["Heating on", "Heating off", "Holiday mode", "Bin day", "Filter change"]),
        dict(title="Camera timeline", type="timeline", icon="monitor", desc="What the cameras saw today.", items=["Parcel delivered at the front door", "Cat in the back garden", "Car arrived in the drive", "Doorbell pressed by a neighbour"]),
        dict(title="Biggest energy users", type="ranking", icon="zap", desc="Devices that used the most power this week.", items=["Heat pump", "Oven", "Washing machine", "Dryer", "TV", "Fridge"], metric="kWh", scale=0.5),
        dict(title="Home settings", type="config", icon="shield", desc="Safety and comfort settings.", items=["Lock all doors at 11pm", "Tell me when a window is left open", "Turn off heating when everyone leaves", "Record camera clips when away"]),
    ],
))

B8.append(dict(
    num=85, slug="acreage", brand="Acreage", category="Farm and Agriculture", org="Hillside Farm", currency="$",
    tagline="Fields, crops, livestock and machinery for a mixed farm.",
    auth_line="Know your farm, field by field.", user="Tom Evans", user_role="Farm manager",
    theme=dict(fonts=["Alegreya Sans", "Alegreya Sans", "Courier Prime", "Alegreya Sans"], accent="#3f6212", layout="light", card="flat", radius="10px",
               bg="#f8f7f2", surface="#fffefa", surface2="#efeee5", line="#e2e0d3", c2="#a3b86c", c3="#b45309", c4="#0369a1"),
    kpis=[("Hectares farmed", "int", 420, "map"), ("Expected harvest tonnes", "int", 1840, "box"), ("Livestock", "int", 612, "heart"), ("Farm income this year", "money", 486000, "dollar")],
    chart=dict(title="Rainfall", names=["This year", "10 year average"], base=60),
    mix=dict(title="Land use", parts=["Wheat", "Barley", "Grass", "Rapeseed", "Woodland"]),
    activity=["Top field drilled with winter wheat", "Vet visit for the dairy herd", "Tractor 2 back from service", "Grain sold: 120 tonnes of barley", "Soil samples sent to the lab", "Rain gauge read: 18 mm"],
    entities=[
        dict(singular="Field", plural="Fields", prefix="", icon="map", desc="Every field on the farm.",
             fields=[("Field", "words:Top field|Long meadow|River field|Church acre|Hill paddock|Barn field"), ("Crop", "choice:Wheat|Barley|Grass|Rapeseed|Fallow"), ("Hectares", "int:6-60"), ("Soil health", "pct:50-95"), ("Status", "status:Growing|Drilled|Harvested|Resting")]),
        dict(singular="Crop", plural="Crops", prefix="", icon="box", desc="What you grow and expect.",
             fields=[("Crop", "words:Winter wheat|Spring barley|Oilseed rape|Silage grass|Oats"), ("Hectares", "int:10-160"), ("Expected tonnes", "int:40-900"), ("Price per tonne", "money:140-420"), ("Status", "status:On track|At risk|Harvested")]),
        dict(singular="Animal group", plural="Livestock", slug="livestock", prefix="", icon="heart", desc="Herds and flocks.",
             fields=[("Group", "words:Dairy herd|Young stock|Ewes|Lambs|Laying hens"), ("Head", "int:20-300"), ("Field", "words:Long meadow|Hill paddock|Barn field|River field"), ("Last vet check", "date"), ("Status", "status:Healthy|Under treatment|Moving")]),
        dict(singular="Machine", plural="Machinery", slug="machinery", prefix="", icon="truck", desc="Tractors and equipment.",
             fields=[("Machine", "words:Tractor 1|Tractor 2|Combine harvester|Sprayer|Seed drill|Grain trailer"), ("Hours", "int:200-9000"), ("Next service", "date:future"), ("Fuel", "pct:10-100"), ("Status", "status:Working|Available|In workshop")]),
        dict(singular="Sale", plural="Sales", prefix="S-", icon="dollar", desc="Crops and animals sold.",
             fields=[("Sale", "id"), ("Product", "choice:Wheat|Barley|Milk|Lambs|Eggs"), ("Buyer", "company"), ("Amount", "money:800-40000"), ("Status", "status:Paid|Invoiced|Agreed")]),
    ],
    specials=[
        dict(title="Farm map", type="map", icon="map", desc="Fields and what is growing.", items=["Top field", "Long meadow", "River field", "Church acre", "Hill paddock"]),
        dict(title="Season plan", type="kanban", icon="kanban", desc="Field work for the season.", items=["Plan", "Prepare soil", "Drilled", "Growing", "Harvested"], cards=["Top field wheat", "River field barley", "Barn field grass", "Church acre rapeseed"]),
        dict(title="Weather and soil", type="monitor", icon="activity", desc="Live readings from field sensors.", items=["Top field soil", "River field soil", "Rain gauge", "Grain store", "Milk tank", "Frost sensor"], unit=""),
        dict(title="Harvest report", type="report", icon="chart", desc="Yields, prices and income.", items=["Yield per hectare", "Income", "Costs", "Margin"], rows=["Winter wheat", "Spring barley", "Oilseed rape", "Silage grass", "Oats"]),
        dict(title="Farm diary", type="calendar", icon="calendar", desc="Jobs and visits planned.", items=["Drilling", "Spraying", "Vet visit", "Machine service", "Market day"]),
        dict(title="Grain contract", type="document", icon="file", desc="A printable sale contract.", doc="Grain sale contract", num="S-1047", items=["Winter wheat", "Spring barley", "Haulage", "Drying charge"], note="Collection from Hillside Farm by the end of October."),
        dict(title="Farm settings", type="config", icon="settings", desc="Alerts and records.", items=["Alert me if frost is forecast", "Remind me 2 weeks before machine services", "Log every spray on the field record", "Send monthly income summary"]),
    ],
))
