"""Batch 5: Hosting, education and dental dashboards (numbers 46 to 55)."""

B5 = []

B5.append(dict(
    num=46, slug="hostdeck", brand="Hostdeck", category="Web Hosting Panel", org="Nimbus Hosting", currency="$",
    tagline="Websites, servers, email and backups for a hosting customer.",
    auth_line="Everything your websites need, in one panel.", user="Tomas Garcia", user_role="Account owner",
    theme=dict(fonts=["Be Vietnam Pro", "Be Vietnam Pro", "JetBrains Mono"], accent="#4338ca", layout="light", card="border", radius="10px",
               c2="#a5b4fc", c3="#f59e0b", c4="#10b981"),
    kpis=[("Websites", "int", 18, "globe"), ("Monthly visits", "int", 412000, "users"), ("Disk used", "pct", 62.4, "pie"), ("Uptime", "pct", 99.9, "check")],
    chart=dict(title="Bandwidth used", names=["This month", "Last month"], base=820),
    mix=dict(title="Disk by website", parts=["shop.example.com", "blog.example.com", "example.com", "Email", "Backups"]),
    activity=["Backup finished for shop.example.com", "SSL certificate renewed", "New email account created", "PHP version updated to 8.3", "Staging site copied to live", "Invoice paid"],
    entities=[
        dict(singular="Website", plural="Websites", prefix="", icon="globe", desc="Sites hosted on your account.",
             fields=[("Website", "words:example.com|shop.example.com|blog.example.com|studio.dev|clientsite.co|staging.example.com"), ("Type", "choice:WordPress|Static|Node app|Shop"), ("Visits", "int:500-200000"), ("Disk GB", "int:1-60"), ("Status", "status:Online|Maintenance|Suspended")]),
        dict(singular="Server", plural="Servers", prefix="", icon="monitor", desc="Your servers and their load.",
             fields=[("Server", "words:vps-lon-01|vps-fra-02|shared-nyc-14|vps-sgp-01"), ("Plan", "choice:Shared|VPS 2 GB|VPS 8 GB|Dedicated"), ("CPU", "pct:4-90"), ("Memory", "pct:20-92"), ("Status", "status:Running|Restarting|Stopped")]),
        dict(singular="Email account", plural="Email accounts", slug="email-accounts", prefix="", icon="inbox", desc="Mailboxes on your domains.",
             fields=[("Mailbox", "words:hello@example.com|sales@example.com|tomas@example.com|support@shop.example.com|info@studio.dev"), ("Storage used", "pct:5-98"), ("Messages", "int:40-24000"), ("Created", "date"), ("Status", "status:Active|Full|Disabled")]),
        dict(singular="Backup", plural="Backups", prefix="BK-", icon="box", desc="Automatic and manual backups.",
             fields=[("Backup", "id"), ("Website", "words:example.com|shop.example.com|blog.example.com"), ("Taken", "date"), ("Size GB", "int:1-40"), ("Status", "status:Complete|Running|Failed")]),
        dict(singular="Invoice", plural="Invoices", prefix="INV-", icon="file", desc="Your hosting bills.",
             fields=[("Invoice", "id"), ("Service", "words:VPS 8 GB|Shared hosting|Domain renewal|Backup add-on|SSL certificate"), ("Date", "date"), ("Amount", "money:5-240"), ("Status", "status:Paid|Due|Overdue")]),
    ],
    specials=[
        dict(title="Server health", type="monitor", icon="activity", desc="Live load on each server.", items=["vps-lon-01 CPU", "vps-lon-01 memory", "vps-fra-02 CPU", "vps-fra-02 memory", "shared-nyc-14", "vps-sgp-01", "Database", "Mail server"]),
        dict(title="Usage report", type="report", icon="chart", desc="Traffic, disk and bandwidth.", items=["Visits", "Bandwidth", "Disk used", "Email storage"], rows=["example.com", "shop.example.com", "blog.example.com", "studio.dev", "clientsite.co"]),
        dict(title="Security", type="config", icon="shield", desc="Protect your websites.", items=["Force HTTPS on every website", "Block login attempts after 5 failures", "Scan for malware every night", "Turn on the web application firewall"]),
        dict(title="Data centres", type="map", icon="globe", desc="Where your servers live.", items=["London", "Frankfurt", "New York", "Singapore", "Sydney"]),
        dict(title="Deployments", type="timeline", icon="zap", desc="Recent changes to your sites.", items=["Staging copied to live for shop.example.com", "PHP updated to 8.3", "New plugin installed on blog", "Cache cleared for example.com"]),
        dict(title="Hosting invoice", type="document", icon="receipt", desc="Your latest invoice.", doc="Invoice", num="INV-2026-1142", items=["VPS 8 GB, monthly", "Daily backups", "Extra IP address", "Domain renewal"]),
        dict(title="Support tickets", type="split", icon="message", desc="Talk to the hosting support team.", items=["Site is slow since this morning", "Move my site to a bigger plan", "Email not arriving", "SSL error on subdomain", "Restore last night's backup"]),
    ],
))

B5.append(dict(
    num=47, slug="zonefile", brand="Zonefile", category="Domains and DNS", org="Northfold Digital", currency="$",
    tagline="Domains, DNS records, renewals and certificates for an agency.",
    auth_line="Every domain, every record, under control.", user="Wen Larsen", user_role="Technical lead",
    theme=dict(fonts=["IBM Plex Sans Condensed", "IBM Plex Sans", "IBM Plex Mono"], accent="#0f766e", layout="dark", card="border", radius="6px", sidebar="#0b1414",
               c2="#5eead4", c3="#f59e0b", c4="#818cf8"),
    kpis=[("Domains", "int", 142, "globe"), ("Renewing in 30 days", "int", 11, "calendar"), ("DNS queries today", "int", 2840000, "zap"), ("Certificates expiring", "int", 3, "shield")],
    chart=dict(title="DNS queries", names=["Queries", "Blocked"], base=2400000),
    mix=dict(title="Domains by ending", parts=[".com", ".co", ".io", ".org", "Other"]),
    activity=["Domain renewed: clientsite.co", "MX record changed for example.com", "Certificate issued for shop.example.com", "Transfer started: oldbrand.net", "DNSSEC turned on", "Nameservers updated"],
    entities=[
        dict(singular="Domain", plural="Domains", prefix="", icon="globe", desc="Every domain you manage.",
             fields=[("Domain", "words:example.com|clientsite.co|brightline.io|oakstudio.org|maplefoods.com|harborhealth.net"), ("Client", "company"), ("Expires", "date:future"), ("Auto renew", "choice:On|Off"), ("Status", "status:Active|Expiring|Transfer pending")]),
        dict(singular="DNS record", plural="DNS records", slug="dns-records", prefix="", icon="list", desc="Records across your zones.",
             fields=[("Name", "words:@|www|mail|api|shop|_dmarc"), ("Type", "choice:A|CNAME|MX|TXT|AAAA"), ("Value", "words:192.0.2.14|proxy.host.net|mx1.mail.net|v=spf1 include:mail.net|2001:db8::1"), ("TTL", "choice:300|3600|86400"), ("Status", "status:Active|Pending")]),
        dict(singular="Certificate", plural="Certificates", prefix="", icon="shield", desc="SSL certificates.",
             fields=[("Domain", "words:example.com|shop.example.com|api.brightline.io|oakstudio.org"), ("Issuer", "choice:Free CA|Paid CA"), ("Expires", "date:future"), ("Auto renew", "choice:On|Off"), ("Status", "status:Valid|Expiring|Expired")]),
        dict(singular="Transfer", plural="Transfers", prefix="TR-", icon="zap", desc="Domains moving in or out.",
             fields=[("Transfer", "id"), ("Domain", "words:oldbrand.net|clientsite.co|legacy.org"), ("Direction", "choice:In|Out"), ("Started", "date"), ("Status", "status:Completed|Pending|Failed")]),
        dict(singular="Client", plural="Clients", prefix="", icon="users", desc="Who owns each domain.",
             fields=[("Client", "company"), ("Contact", "person"), ("Domains", "int:1-24"), ("Yearly cost", "money:15-900"), ("Status", "status:Active|Paused")]),
    ],
    specials=[
        dict(title="Renewals", type="calendar", icon="calendar", desc="Domains and certificates up for renewal.", items=["Domain renewal", "Certificate renewal", "Transfer deadline", "Client invoice", "DNS audit"]),
        dict(title="DNS health", type="monitor", icon="activity", desc="Live checks on key zones.", items=["example.com", "clientsite.co", "brightline.io", "oakstudio.org", "maplefoods.com", "harborhealth.net"], unit=" ms"),
        dict(title="Query map", type="map", icon="globe", desc="Where DNS queries come from.", items=["North America", "Europe", "Asia", "South America", "Oceania"]),
        dict(title="Change log", type="timeline", icon="clock", desc="Recent DNS changes.", items=["MX record changed for example.com", "New A record for api.brightline.io", "TXT record added for email security", "CNAME removed for old campaign"]),
        dict(title="Busiest domains", type="ranking", icon="trend", desc="Domains with the most queries.", items=["example.com", "maplefoods.com", "brightline.io", "harborhealth.net", "clientsite.co", "oakstudio.org"], metric="Queries", scale=18000),
        dict(title="Renewal invoice", type="document", icon="receipt", desc="Invoice for this year's renewals.", doc="Renewal invoice", num="Maple Foods 2026", items=["maplefoods.com renewal", "maplefoods.co renewal", "Privacy protection", "Premium DNS"]),
        dict(title="Domain settings", type="config", icon="settings", desc="Default settings for new domains.", items=["Turn on auto renew for every domain", "Lock domains against transfers", "Turn on DNSSEC", "Email me 30 days before expiry"]),
    ],
))

B5.append(dict(
    num=48, slug="schoolyard", brand="Schoolyard", category="School Management", org="Brookfield Primary School", currency="$",
    tagline="Pupils, classes, attendance and parents for a primary school.",
    auth_line="Run the school day with less paperwork.", user="Grace Okafor", user_role="Head teacher",
    theme=dict(fonts=["Fredoka", "Nunito Sans", "Roboto Mono"], accent="#f59e0b", on_accent="#1f2937", layout="tint", card="shadow", radius="16px",
               c2="#fcd34d", c3="#3b82f6", c4="#10b981"),
    kpis=[("Pupils", "int", 486, "users"), ("Attendance today", "pct", 96.2, "check"), ("Staff", "int", 42, "briefcase"), ("Fees outstanding", "money", 12400, "dollar")],
    chart=dict(title="Attendance", names=["Present", "Target"], base=460),
    mix=dict(title="Pupils by year", parts=["Reception", "Years 1 and 2", "Years 3 and 4", "Years 5 and 6", "Nursery"]),
    activity=["Year 3 trip letters sent", "Attendance marked for all classes", "New pupil joined Year 2", "Parents evening booked", "Lunch menu updated", "Reading records checked"],
    entities=[
        dict(singular="Pupil", plural="Pupils", prefix="", icon="users", desc="Every child at the school.",
             fields=[("Pupil", "person"), ("Class", "choice:Reception|Year 1|Year 2|Year 3|Year 4|Year 5|Year 6"), ("Attendance", "pct:82-100"), ("Reading level", "choice:Green|Blue|Orange|Purple|Gold"), ("Status", "status:Present|Absent|Late")]),
        dict(singular="Class", plural="Classes", slug="classes", prefix="", icon="layers", desc="Classes and their teachers.",
             fields=[("Class", "words:Reception Robins|Year 1 Owls|Year 2 Foxes|Year 3 Badgers|Year 4 Hawks|Year 5 Otters|Year 6 Eagles"), ("Teacher", "person"), ("Pupils", "int:24-30"), ("Room", "code:R"), ("Status", "status:In lesson|Break|Trip")]),
        dict(singular="Staff member", plural="Staff", slug="staff", prefix="", icon="briefcase", desc="Teachers and support staff.",
             fields=[("Name", "person"), ("Role", "choice:Teacher|Teaching assistant|Office|Caretaker|Cook"), ("Class", "words:Year 1|Year 3|Year 5|Office|Kitchen"), ("Started", "date"), ("Status", "status:In school|Off sick|Training")]),
        dict(singular="Parent", plural="Parents", prefix="", icon="user", desc="Parents and carers.",
             fields=[("Parent", "person"), ("Child", "person"), ("Phone", "phone"), ("App", "choice:Using app|Paper letters"), ("Status", "status:Up to date|Needs contact")]),
        dict(singular="Payment", plural="Payments", prefix="PAY-", icon="card", desc="Trips, lunches and clubs.",
             fields=[("Payment", "id"), ("For", "words:School trip|Lunches|After school club|Uniform|Music lessons"), ("Parent", "person"), ("Amount", "money:5-180"), ("Status", "status:Paid|Due|Overdue")]),
    ],
    specials=[
        dict(title="Timetable", type="calendar", icon="calendar", desc="Lessons, assemblies and trips.", items=["Assembly", "PE lesson", "School trip", "Parents evening", "Staff meeting"]),
        dict(title="Attendance report", type="report", icon="chart", desc="Attendance by class and week.", items=["Attendance", "Late arrivals", "Absences", "Persistent absence"], rows=["Reception", "Year 1", "Year 2", "Year 3", "Year 4"]),
        dict(title="Messages to parents", type="split", icon="message", desc="Letters and replies from parents.", items=["Year 3 trip consent", "Sports day next Friday", "Lunch menu change", "Reply: my child is unwell", "Book fair this week"]),
        dict(title="House points", type="ranking", icon="star", desc="Which house is winning this term.", items=["Oak house", "Ash house", "Willow house", "Birch house"], metric="Points", scale=12),
        dict(title="School report", type="document", icon="file", desc="An end of term report for a pupil.", doc="End of term report", num="Year 3 Badgers, autumn term", items=["Reading", "Writing", "Maths", "Science", "Art"], note="A very kind and hard working member of the class. Keep reading every night."),
        dict(title="Events", type="timeline", icon="bell", desc="Coming up this term.", items=["Harvest assembly", "Year 6 residential trip", "Parents evening", "Christmas play", "Last day of term"]),
        dict(title="School settings", type="config", icon="settings", desc="Rules for the school day.", items=["Text parents if a child is absent by 9:30", "Send weekly newsletters by email", "Lock registers at 9:15", "Remind parents about unpaid trips"]),
    ],
))

B5.append(dict(
    num=49, slug="coursely", brand="Coursely", category="Online Courses", org="Learnwell Academy", currency="$",
    tagline="Courses, students, lessons and sales for an online learning platform.",
    auth_line="Teach online. Grow your academy.", user="Rohan Mensah", user_role="Academy owner",
    theme=dict(fonts=["Sen", "Inter", "Fira Code"], accent="#9333ea", layout="accent", card="border", radius="12px",
               c2="#d8b4fe", c3="#f59e0b", c4="#06b6d4"),
    kpis=[("Students", "int", 12840, "users"), ("Course sales", "money", 48200, "dollar"), ("Completion rate", "pct", 62.8, "check"), ("Average rating", "rating", 4.7, "star")],
    chart=dict(title="Enrolments", names=["Enrolments", "Completions"], base=1400),
    mix=dict(title="Sales by category", parts=["Design", "Coding", "Marketing", "Business", "Photography"]),
    activity=["New course published: Figma basics", "240 students enrolled this week", "Quiz updated in Python 101", "Review: 5 stars for Brand design", "Coupon SPRING25 created", "Certificate issued to 86 students"],
    entities=[
        dict(singular="Course", plural="Courses", prefix="", icon="book", desc="Every course you sell.",
             fields=[("Course", "words:Python 101|Figma basics|Brand design|SEO for beginners|Excel for work|Photo editing"), ("Instructor", "person"), ("Students", "int:120-4000"), ("Price", "money:19-249"), ("Status", "status:Published|Draft|Archived")]),
        dict(singular="Student", plural="Students", prefix="", icon="users", desc="People learning with you.",
             fields=[("Student", "person"), ("Courses", "int:1-8"), ("Progress", "pct:5-100"), ("Joined", "date"), ("Status", "status:Active|Inactive|Completed")]),
        dict(singular="Lesson", plural="Lessons", prefix="", icon="list", desc="Videos and readings in each course.",
             fields=[("Lesson", "words:Welcome|Setting up|Your first project|Working with colours|Quiz one|Final project"), ("Course", "words:Python 101|Figma basics|Brand design|SEO for beginners"), ("Length", "duration"), ("Views", "int:100-9000"), ("Status", "status:Published|Draft")]),
        dict(singular="Instructor", plural="Instructors", prefix="", icon="user", desc="Teachers on your platform.",
             fields=[("Instructor", "person"), ("Courses", "int:1-6"), ("Students", "int:100-9000"), ("Rating", "rating"), ("Status", "status:Active|Invited")]),
        dict(singular="Order", plural="Orders", prefix="ORD-", icon="cart", desc="Course purchases.",
             fields=[("Order", "id"), ("Student", "person"), ("Course", "words:Python 101|Figma basics|Brand design|Excel for work"), ("Amount", "money:19-249"), ("Status", "status:Paid|Refunded|Pending")]),
    ],
    specials=[
        dict(title="Course builder", type="kanban", icon="kanban", desc="New courses from outline to launch.", items=["Outline", "Recording", "Editing", "Review", "Published"], cards=["Figma advanced", "Python for data", "TikTok marketing", "Budgeting basics"]),
        dict(title="Learning report", type="report", icon="chart", desc="Progress, completions and ratings.", items=["Completion rate", "Watch time", "Quiz pass rate", "Rating"], rows=["Python 101", "Figma basics", "Brand design", "SEO for beginners", "Excel for work"]),
        dict(title="Best sellers", type="ranking", icon="star", desc="Courses that sold the most this month.", items=["Python 101", "Figma basics", "Excel for work", "Brand design", "SEO for beginners", "Photo editing"], metric="Sales", scale=90),
        dict(title="Live classes", type="calendar", icon="calendar", desc="Scheduled live sessions.", items=["Live Q and A", "Design critique", "Coding workshop", "Office hours", "Guest talk"]),
        dict(title="Certificate", type="document", icon="file", desc="A course completion certificate.", doc="Certificate of completion", num="Python 101", items=["12 lessons completed", "4 quizzes passed", "Final project approved"], note="Awarded for completing Python 101 on Learnwell Academy."),
        dict(title="Student questions", type="split", icon="message", desc="Questions left under lessons.", items=["Stuck on lesson 4", "Where are the project files?", "Can I get a refund?", "Great course!", "Is there a part two?"]),
        dict(title="Course settings", type="config", icon="settings", desc="How courses work.", items=["Unlock lessons one by one", "Require quizzes to pass lessons", "Give certificates automatically", "Allow refunds within 14 days"]),
    ],
))

B5.append(dict(
    num=50, slug="admitly", brand="Admitly", category="University Admissions", org="Westbrook University", currency="$",
    tagline="Applications, reviews and offers for a university admissions office.",
    auth_line="Find and welcome your next class.", user="Olivia Hughes", user_role="Director of admissions",
    theme=dict(fonts=["Libre Baskerville", "Source Sans 3", "Source Code Pro", "Source Sans 3"], accent="#7f1d1d", layout="light", card="border", radius="4px",
               bg="#fbfaf8", surface2="#f5f2ee", line="#e8e2da", c2="#d6a3a3", c3="#b45309", c4="#1e3a8a"),
    kpis=[("Applications", "int", 18420, "file"), ("Offers made", "int", 6240, "check"), ("Accepted", "int", 2180, "users"), ("International", "pct", 24.6, "globe")],
    chart=dict(title="Applications", names=["This cycle", "Last cycle"], base=1500),
    mix=dict(title="Applications by faculty", parts=["Engineering", "Business", "Arts", "Medicine", "Science"]),
    activity=["120 offers sent for Engineering", "Interview day booked for Medicine", "Scholarship awarded to 14 students", "Application deadline reminder sent", "Transcript received from Ana Silva", "Campus tour booked"],
    entities=[
        dict(singular="Application", plural="Applications", prefix="APP-", icon="file", desc="Every application this cycle.",
             fields=[("Application", "id"), ("Applicant", "person"), ("Programme", "words:Computer science|Business|Medicine|Architecture|Psychology|Law"), ("Submitted", "date"), ("Status", "status:Offer|In review|Interview|Rejected")]),
        dict(singular="Applicant", plural="Applicants", prefix="", icon="user", desc="Students who applied.",
             fields=[("Applicant", "person"), ("Country", "choice:United Kingdom|India|Nigeria|China|Brazil|Canada"), ("Grade average", "pct:60-99"), ("Applications", "int:1-3"), ("Status", "status:Complete|Missing documents|Withdrawn")]),
        dict(singular="Programme", plural="Programmes", prefix="", icon="book", desc="Courses you admit students to.",
             fields=[("Programme", "words:Computer science|Business|Medicine|Architecture|Psychology|Law"), ("Places", "int:40-400"), ("Applications", "int:200-4000"), ("Offers", "int:60-900"), ("Status", "status:Open|Full|Closed")]),
        dict(singular="Interview", plural="Interviews", prefix="", icon="calendar", desc="Interviews with applicants.",
             fields=[("Applicant", "person"), ("Programme", "words:Medicine|Architecture|Law|Music"), ("Date", "date:future"), ("Panel", "person"), ("Status", "status:Booked|Done|Cancelled")]),
        dict(singular="Scholarship", plural="Scholarships", prefix="", icon="star", desc="Funding offered to students.",
             fields=[("Scholarship", "words:Excellence award|International bursary|Sports scholarship|Access fund|Research grant"), ("Awarded", "int:2-60"), ("Value", "money:1000-20000"), ("Deadline", "date:future"), ("Status", "status:Open|Closed")]),
    ],
    specials=[
        dict(title="Review pipeline", type="kanban", icon="kanban", desc="Applications from received to decision.", items=["Received", "Documents check", "Faculty review", "Interview", "Decision"], cards=["Computer science", "Medicine", "Business", "Law"]),
        dict(title="Admissions report", type="report", icon="chart", desc="Applications, offers and yield.", items=["Applications", "Offer rate", "Acceptance rate", "International share"], rows=["Engineering", "Business", "Arts", "Medicine", "Science"]),
        dict(title="Applicants by country", type="map", icon="globe", desc="Where applicants come from.", items=["United Kingdom", "India", "Nigeria", "China", "Brazil"]),
        dict(title="Key dates", type="calendar", icon="calendar", desc="Deadlines, interviews and open days.", items=["Application deadline", "Interview day", "Open day", "Offer release", "Campus tour"]),
        dict(title="Offer letter", type="document", icon="file", desc="A printable offer letter.", doc="Offer of a place", num="APP-1047, Computer science", items=["Tuition, year one", "Accommodation deposit", "Excellence award", "Orientation week"], note="Please accept your offer by 1 May. We look forward to welcoming you."),
        dict(title="Applicant enquiries", type="split", icon="inbox", desc="Questions from applicants.", items=["When will I hear back?", "Can I change my programme?", "Visa letter request", "Accommodation question", "Scholarship eligibility"]),
        dict(title="Decision rules", type="config", icon="settings", desc="How applications are handled.", items=["Send an email when documents are missing", "Require two reviewers for Medicine", "Release offers every Friday", "Remind applicants 7 days before deadlines"]),
    ],
))

B5.append(dict(
    num=51, slug="campusly", brand="Campusly", category="Student Portal", org="Westbrook University", currency="$",
    tagline="Timetable, grades, assignments and fees for university students.",
    auth_line="Your whole student life, in one place.", user="Ana Silva", user_role="Second year student",
    theme=dict(fonts=["Quicksand", "Quicksand", "Space Mono"], accent="#0284c7", layout="light", card="shadow", radius="18px",
               c2="#7dd3fc", c3="#f59e0b", c4="#22c55e"),
    kpis=[("Grade average", "pct", 72.4, "star"), ("Assignments due", "int", 4, "file"), ("Attendance", "pct", 91.0, "check"), ("Fees due", "money", 1240, "dollar")],
    chart=dict(title="Grades this year", names=["Your grades", "Course average"], base=68),
    mix=dict(title="Study time by module", parts=["Algorithms", "Databases", "Web design", "Statistics", "Ethics"]),
    activity=["Grade posted: Databases essay, 74", "New assignment: Web design project", "Library book due tomorrow", "Timetable change for Statistics", "Fee payment received", "Club meeting on Thursday"],
    entities=[
        dict(singular="Module", plural="Modules", prefix="", icon="book", desc="Modules you are taking.",
             fields=[("Module", "words:Algorithms|Databases|Web design|Statistics|Ethics in tech|Networks"), ("Lecturer", "person"), ("Credits", "int:10-30"), ("Grade", "pct:52-92"), ("Status", "status:In progress|Completed")]),
        dict(singular="Assignment", plural="Assignments", prefix="", icon="file", desc="Coursework and deadlines.",
             fields=[("Assignment", "words:Databases essay|Web design project|Algorithms problem set|Statistics lab report|Ethics debate"), ("Module", "words:Algorithms|Databases|Web design|Statistics"), ("Due", "date:future"), ("Weight", "pct:10-50"), ("Status", "status:Submitted|Due|Late")]),
        dict(singular="Grade", plural="Grades", prefix="", icon="star", desc="Your marks so far.",
             fields=[("Work", "words:Midterm exam|Essay one|Lab report|Group project|Quiz three"), ("Module", "words:Algorithms|Databases|Web design|Statistics"), ("Mark", "pct:48-95"), ("Released", "date"), ("Status", "status:Passed|Resit|Pending")]),
        dict(singular="Fee", plural="Fees", prefix="", icon="card", desc="Tuition and other payments.",
             fields=[("Fee", "words:Tuition term 1|Tuition term 2|Accommodation|Library fine|Lab fee"), ("Due", "date:future"), ("Amount", "money:10-4800"), ("Paid", "money:0-4800"), ("Status", "status:Paid|Due|Overdue")]),
        dict(singular="Club", plural="Clubs", prefix="", icon="users", desc="Societies and clubs you joined.",
             fields=[("Club", "words:Coding society|Chess club|Film club|Running club|Debate society"), ("Members", "int:20-400"), ("Next meeting", "date:future"), ("Role", "choice:Member|Committee|Captain"), ("Status", "status:Active|Paused")]),
    ],
    specials=[
        dict(title="Timetable", type="calendar", icon="calendar", desc="Lectures, labs and deadlines.", items=["Algorithms lecture", "Databases lab", "Web design studio", "Statistics seminar", "Deadline"]),
        dict(title="Progress", type="report", icon="chart", desc="Your grades and credits.", items=["Grade average", "Credits earned", "Attendance", "Submitted on time"], rows=["Algorithms", "Databases", "Web design", "Statistics", "Ethics in tech"]),
        dict(title="Study planner", type="kanban", icon="kanban", desc="Plan your coursework.", items=["To start", "Researching", "Writing", "Checking", "Submitted"], cards=["Databases essay", "Web design project", "Statistics lab report", "Ethics debate prep"]),
        dict(title="Campus map", type="map", icon="map", desc="Find your way around.", items=["Library", "Engineering building", "Student union", "Sports centre", "Halls"]),
        dict(title="Transcript", type="document", icon="file", desc="An unofficial transcript.", doc="Unofficial transcript", num="Year 1, 2025 to 2026", items=["Programming basics", "Maths for computing", "Intro to databases", "Web foundations"], note="This is an unofficial copy for your records. Amounts shown are credit fees."),
        dict(title="Announcements", type="timeline", icon="bell", desc="News from your university.", items=["Exam timetable published", "Library open 24 hours in exam weeks", "Career fair next Tuesday", "Wellbeing week starts Monday"]),
        dict(title="Reminder settings", type="config", icon="settings", desc="What the portal reminds you about.", items=["Remind me 2 days before deadlines", "Tell me when grades are posted", "Email me about timetable changes", "Weekly summary on Sunday"]),
    ],
))

B5.append(dict(
    num=52, slug="tutorly", brand="Tutorly", category="Tutor Marketplace", org="Tutorly Online", currency="$",
    tagline="Tutors, students, lessons and payouts for a tutoring marketplace.",
    auth_line="Match every learner with the right tutor.", user="Maya Adams", user_role="Marketplace manager",
    theme=dict(fonts=["Baloo 2", "Nunito", "Roboto Mono"], accent="#15803d", layout="tint", card="border", radius="14px",
               c2="#86efac", c3="#f59e0b", c4="#8b5cf6"),
    kpis=[("Lessons this week", "int", 3420, "calendar"), ("Active tutors", "int", 612, "user"), ("Booking value", "money", 128400, "dollar"), ("Lesson rating", "rating", 4.8, "star")],
    chart=dict(title="Lessons booked", names=["Lessons", "Trial lessons"], base=2900),
    mix=dict(title="Lessons by subject", parts=["Maths", "English", "Science", "Languages", "Music"]),
    activity=["New tutor approved: Kenji Ito", "Trial lesson booked in Maths", "Payout sent to 180 tutors", "Complaint resolved", "Review: 5 stars for Sara Diaz", "Referral bonus paid"],
    entities=[
        dict(singular="Tutor", plural="Tutors", prefix="", icon="user", desc="Tutors on the marketplace.",
             fields=[("Tutor", "person"), ("Subject", "choice:Maths|English|Science|Spanish|Piano|Chemistry"), ("Hourly rate", "money:15-90"), ("Rating", "rating"), ("Status", "status:Active|Pending review|Paused")]),
        dict(singular="Student", plural="Students", prefix="", icon="users", desc="Learners and their parents.",
             fields=[("Student", "person"), ("Level", "choice:Primary|Secondary|University|Adult"), ("Lessons", "int:1-80"), ("Spent", "money:20-3000"), ("Status", "status:Active|Trial|Inactive")]),
        dict(singular="Lesson", plural="Lessons", prefix="L-", icon="calendar", desc="Booked lessons.",
             fields=[("Lesson", "id"), ("Tutor", "person"), ("Student", "person"), ("Date", "date:future"), ("Status", "status:Booked|Completed|Cancelled|No show")]),
        dict(singular="Payout", plural="Payouts", prefix="PO-", icon="card", desc="Money paid to tutors.",
             fields=[("Payout", "id"), ("Tutor", "person"), ("Lessons", "int:2-60"), ("Amount", "money:40-4000"), ("Status", "status:Paid|Scheduled|Held")]),
        dict(singular="Review", plural="Reviews", prefix="", icon="star", desc="What students say about tutors.",
             fields=[("Student", "person"), ("Tutor", "person"), ("Rating", "rating"), ("Date", "date"), ("Status", "status:Published|Reported|Hidden")]),
    ],
    specials=[
        dict(title="Tutor applications", type="kanban", icon="kanban", desc="New tutors from sign up to approved.", items=["Applied", "ID check", "Demo lesson", "Approved", "Declined"], cards=["Maths tutor", "Spanish tutor", "Piano teacher", "Chemistry tutor"]),
        dict(title="Marketplace report", type="report", icon="chart", desc="Bookings, revenue and quality.", items=["Booking value", "Take rate", "Repeat students", "Rating"], rows=["Maths", "English", "Science", "Languages", "Music"]),
        dict(title="Top tutors", type="ranking", icon="star", desc="Tutors with the most lessons.", items=["Sara Diaz", "Kenji Ito", "Amara Chen", "Liam Walsh", "Priya Singh", "Omar Novak"], metric="Lessons", scale=2),
        dict(title="Lesson calendar", type="calendar", icon="calendar", desc="Lessons booked this month.", items=["Maths lesson", "Spanish lesson", "Piano lesson", "Trial lesson", "Exam prep"]),
        dict(title="Students by city", type="map", icon="map", desc="Where your students are.", items=["London", "Manchester", "Birmingham", "Leeds", "Online only"]),
        dict(title="Support inbox", type="split", icon="inbox", desc="Messages from tutors and parents.", items=["Tutor did not join the lesson", "How do I change my rate?", "Refund for a cancelled lesson", "Can I book weekly lessons?", "Payout question"]),
        dict(title="Marketplace rules", type="config", icon="shield", desc="Keep lessons safe and fair.", items=["Check ID for every new tutor", "Refund students for tutor no-shows", "Hold payouts for 3 days", "Hide contact details in messages"]),
    ],
))

B5.append(dict(
    num=53, slug="stacks", brand="Stacks", category="Library", org="Millbrook Public Library", currency="$",
    tagline="Books, members, loans and events for a public library.",
    auth_line="Every book in the right hands.", user="Isaac Moreau", user_role="Head librarian",
    theme=dict(fonts=["Crimson Pro", "Lato", "Courier Prime", "Crimson Pro"], accent="#92400e", layout="light", card="flat", radius="6px",
               bg="#fbf8f3", surface="#fffdf9", surface2="#f3ece2", line="#e6dccd", c2="#d6a77a", c3="#1e3a8a", c4="#15803d"),
    kpis=[("Books on loan", "int", 4820, "book"), ("Members", "int", 12640, "users"), ("Overdue", "int", 214, "alert"), ("Visits today", "int", 842, "building")],
    chart=dict(title="Loans", names=["Loans", "Returns"], base=4200),
    mix=dict(title="Loans by section", parts=["Fiction", "Children", "Non-fiction", "Audiobooks", "Other"]),
    activity=["120 new books catalogued", "Story time booked for Saturday", "Overdue reminders sent", "New member joined", "Reservation ready for pickup", "Book club meeting added"],
    entities=[
        dict(singular="Book", plural="Catalogue", slug="catalogue", prefix="", icon="book", desc="Every item in the library.",
             fields=[("Title", "words:The Quiet River|A History of Maps|Small Brave Things|Cooking at Home|The Glass Garden|Learning to Code"), ("Author", "person"), ("Section", "choice:Fiction|Children|Non-fiction|Audiobook"), ("Copies", "int:1-8"), ("Status", "status:Available|On loan|Reserved")]),
        dict(singular="Member", plural="Members", prefix="", icon="users", desc="People with a library card.",
             fields=[("Member", "person"), ("Card", "code:MB"), ("Loans", "int:0-12"), ("Joined", "date"), ("Status", "status:Active|Fines due|Expired")]),
        dict(singular="Loan", plural="Loans", prefix="LN-", icon="list", desc="Books out right now.",
             fields=[("Loan", "id"), ("Title", "words:The Quiet River|A History of Maps|Small Brave Things|The Glass Garden"), ("Member", "person"), ("Due", "date:future"), ("Status", "status:On time|Due soon|Overdue")]),
        dict(singular="Reservation", plural="Reservations", prefix="", icon="bell", desc="Books people are waiting for.",
             fields=[("Title", "words:The Quiet River|Learning to Code|Cooking at Home|The Glass Garden"), ("Member", "person"), ("Placed", "date"), ("Queue", "int:1-12"), ("Status", "status:Ready|Waiting|Collected")]),
        dict(singular="Event", plural="Events", prefix="", icon="calendar", desc="Talks, clubs and story times.",
             fields=[("Event", "words:Story time|Book club|Author talk|Coding club|Local history walk"), ("Date", "date:future"), ("Places", "int:10-80"), ("Booked", "int:4-80"), ("Status", "status:Open|Full|Cancelled")]),
    ],
    specials=[
        dict(title="Events calendar", type="calendar", icon="calendar", desc="What is on at the library.", items=["Story time", "Book club", "Author talk", "Coding club", "Craft session"]),
        dict(title="Most borrowed", type="ranking", icon="star", desc="The most popular books this month.", items=["The Quiet River", "Small Brave Things", "The Glass Garden", "Cooking at Home", "A History of Maps", "Learning to Code"], metric="Loans", scale=2),
        dict(title="Library report", type="report", icon="chart", desc="Loans, visits and members.", items=["Loans", "Visits", "New members", "Overdue rate"], rows=["Fiction", "Children", "Non-fiction", "Audiobooks", "Magazines"]),
        dict(title="New arrivals", type="gallery", icon="book", desc="Books added to the shelves this week.", items=["The Quiet River", "Small Brave Things", "The Glass Garden", "A History of Maps", "Cooking at Home", "Learning to Code"]),
        dict(title="Branches", type="map", icon="map", desc="Loans by branch.", items=["Central library", "Northside", "Riverside", "Old Town", "Mobile library"]),
        dict(title="Overdue notice", type="document", icon="file", desc="A printable overdue notice.", doc="Overdue notice", num="Card MB20418", items=["The Quiet River", "A History of Maps", "Late fee"], note="Please return or renew these items. You can renew online or at any branch."),
        dict(title="Loan rules", type="config", icon="settings", desc="How lending works.", items=["Lend books for 3 weeks", "Allow 2 renewals", "Send reminders 2 days before the due date", "No fines for children's books"]),
    ],
))

B5.append(dict(
    num=54, slug="quizzly", brand="Quizzly", category="Exams and Quizzes", org="Maple Grove Secondary", currency="$",
    tagline="Build exams, run quizzes and see results for every class.",
    auth_line="Test what students know, fairly and fast.", user="Paula Singh", user_role="Head of assessment",
    theme=dict(fonts=["Exo 2", "Exo 2", "Share Tech Mono"], accent="#db2777", layout="dark", card="shadow", radius="10px", sidebar="#1b0d1a",
               c2="#f9a8d4", c3="#8b5cf6", c4="#22c55e"),
    kpis=[("Quizzes this term", "int", 186, "file"), ("Average score", "pct", 71.8, "star"), ("Pass rate", "pct", 88.4, "check"), ("Students tested", "int", 1240, "users")],
    chart=dict(title="Average scores", names=["This term", "Last term"], base=68),
    mix=dict(title="Questions by type", parts=["Multiple choice", "Short answer", "Essay", "True or false", "Matching"]),
    activity=["Quiz published: Algebra basics", "Results released for Year 9 science", "Question bank updated", "Exam room booked", "Retake scheduled for 12 students", "Marking finished for History essays"],
    entities=[
        dict(singular="Quiz", plural="Quizzes", prefix="", icon="file", desc="Quizzes and exams.",
             fields=[("Quiz", "words:Algebra basics|Cell biology|World War One|French verbs|Chemical reactions|Poetry analysis"), ("Class", "choice:Year 7|Year 8|Year 9|Year 10|Year 11"), ("Questions", "int:10-60"), ("Average", "pct:48-92"), ("Status", "status:Published|Draft|Closed")]),
        dict(singular="Question", plural="Question bank", slug="question-bank", prefix="Q-", icon="help", desc="Questions you can reuse.",
             fields=[("Question", "id"), ("Topic", "words:Fractions|Photosynthesis|Forces|Grammar|Timelines"), ("Type", "choice:Multiple choice|Short answer|Essay|True or false"), ("Used", "int:1-40"), ("Status", "status:Approved|Draft|Retired")]),
        dict(singular="Result", plural="Results", prefix="", icon="star", desc="Scores for each student.",
             fields=[("Student", "person"), ("Quiz", "words:Algebra basics|Cell biology|French verbs|Poetry analysis"), ("Score", "pct:30-100"), ("Time", "duration"), ("Status", "status:Passed|Failed|Retake")]),
        dict(singular="Class", plural="Classes", slug="classes", prefix="", icon="users", desc="Classes and their results.",
             fields=[("Class", "words:7A|8B|9C|10A|11D"), ("Teacher", "person"), ("Students", "int:22-32"), ("Average", "pct:55-88"), ("Status", "status:On track|Needs support")]),
        dict(singular="Exam session", plural="Exam sessions", slug="exam-sessions", prefix="", icon="calendar", desc="Scheduled exams.",
             fields=[("Exam", "words:Maths paper 1|Science mock|English mock|History final|French oral"), ("Room", "code:Hall "), ("Date", "date:future"), ("Students", "int:20-180"), ("Status", "status:Scheduled|Running|Finished")]),
    ],
    specials=[
        dict(title="Live quiz", type="monitor", icon="activity", desc="Students taking a quiz right now.", items=["Started", "Finished", "Average so far", "Hardest question", "Time left", "Flagged answers"], unit=""),
        dict(title="Results report", type="report", icon="chart", desc="Scores by class and topic.", items=["Average score", "Pass rate", "Improvement", "Retakes"], rows=["7A", "8B", "9C", "10A", "11D"]),
        dict(title="Hardest questions", type="ranking", icon="alert", desc="Questions most students got wrong.", items=["Dividing fractions", "Balancing equations", "Poem themes", "Irregular verbs", "Photosynthesis steps"], metric="Wrong answers", scale=1),
        dict(title="Exam calendar", type="calendar", icon="calendar", desc="Exams and mock tests.", items=["Mock exam", "End of topic quiz", "Retake", "Oral exam", "Results day"]),
        dict(title="Marking queue", type="kanban", icon="kanban", desc="Essays and answers waiting to be marked.", items=["To mark", "Marking", "Second check", "Released"], cards=["History essays", "English mock", "Science long answers", "Poetry analysis"]),
        dict(title="Exam paper", type="document", icon="file", desc="A printable exam cover sheet.", doc="Maths paper 1", num="Year 11 mock exam", items=["Section A: number", "Section B: algebra", "Section C: geometry", "Section D: statistics"], note="Time allowed: 1 hour 30 minutes. Calculators are not allowed in Section A."),
        dict(title="Quiz settings", type="config", icon="settings", desc="How quizzes work.", items=["Shuffle questions for each student", "Show answers after the quiz closes", "Allow one retake", "Lock the quiz in full screen"]),
    ],
))

B5.append(dict(
    num=55, slug="brightsmile", brand="Brightsmile", category="Dental Clinic", org="Brightsmile Dental Care", currency="$",
    tagline="Appointments, patients, treatments and billing for a dental practice.",
    auth_line="A calm day at the practice.", user="Dr. Elena Rossi", user_role="Practice owner",
    theme=dict(fonts=["Jost", "Jost", "DM Mono"], accent="#0891b2", layout="light", card="shadow", radius="14px",
               c2="#67e8f9", c3="#f59e0b", c4="#8b5cf6"),
    kpis=[("Appointments today", "int", 42, "calendar"), ("New patients", "int", 18, "users"), ("Revenue this month", "money", 84200, "dollar"), ("Chair use", "pct", 86.4, "pie")],
    chart=dict(title="Appointments", names=["Booked", "Completed"], base=720),
    mix=dict(title="Treatments", parts=["Check-ups", "Cleaning", "Fillings", "Whitening", "Implants"]),
    activity=["Reminder texts sent for tomorrow", "New patient registered: Ben Walsh", "Treatment plan approved", "Insurance claim paid", "X-ray uploaded", "Cancellation filled from the waiting list"],
    entities=[
        dict(singular="Patient", plural="Patients", prefix="", icon="users", desc="Everyone registered at the practice.",
             fields=[("Patient", "person"), ("Dentist", "person"), ("Last visit", "date"), ("Plan", "choice:Pay as you go|Monthly plan|Insurance"), ("Status", "status:Active|Recall due|Inactive")]),
        dict(singular="Appointment", plural="Appointments", prefix="", icon="calendar", desc="Today's and upcoming visits.",
             fields=[("Patient", "person"), ("Treatment", "choice:Check-up|Cleaning|Filling|Whitening|Root canal"), ("Date", "date:future"), ("Time", "time"), ("Status", "status:Confirmed|Booked|Cancelled|No show")]),
        dict(singular="Treatment plan", plural="Treatment plans", slug="treatment-plans", prefix="TP-", icon="file", desc="Planned care for patients.",
             fields=[("Plan", "id"), ("Patient", "person"), ("Visits", "int:1-8"), ("Cost", "money:80-6000"), ("Status", "status:Approved|Proposed|Completed")]),
        dict(singular="Invoice", plural="Invoices", prefix="INV-", icon="receipt", desc="Bills for treatment.",
             fields=[("Invoice", "id"), ("Patient", "person"), ("Date", "date"), ("Amount", "money:40-3000"), ("Status", "status:Paid|Insurance pending|Overdue")]),
        dict(singular="Supply", plural="Supplies", prefix="", icon="box", desc="Materials and stock.",
             fields=[("Item", "words:Gloves|Masks|Filling material|Anaesthetic|Whitening gel|Impression trays"), ("In stock", "int:0-900"), ("Reorder at", "int:10-200"), ("Supplier", "company"), ("Status", "status:In stock|Low|Out of stock")]),
    ],
    specials=[
        dict(title="Day planner", type="calendar", icon="calendar", desc="Appointments across every chair.", items=["Check-up", "Cleaning", "Filling", "Whitening", "Emergency"]),
        dict(title="Chair status", type="monitor", icon="activity", desc="What is happening in each room.", items=["Room 1", "Room 2", "Room 3", "Hygienist", "X-ray", "Waiting room"], unit=" min"),
        dict(title="Practice report", type="report", icon="chart", desc="Revenue, visits and recalls.", items=["Revenue", "New patients", "Recall rate", "No-show rate"], rows=["Check-ups", "Cleaning", "Fillings", "Whitening", "Implants"]),
        dict(title="Treatment plan", type="document", icon="file", desc="A printable plan and estimate.", doc="Treatment plan and estimate", num="TP-1047", items=["Examination and X-rays", "Two fillings", "Hygienist cleaning", "Whitening trays"], note="This estimate is valid for 60 days. Please ask us about payment plans."),
        dict(title="Recall list", type="kanban", icon="kanban", desc="Patients due for a check-up.", items=["Due", "Reminder sent", "Booked", "Seen"], cards=["Six month check-up", "Hygienist visit", "Orthodontic review", "X-ray due"]),
        dict(title="Patient messages", type="split", icon="message", desc="Messages and booking requests.", items=["Can I move my appointment?", "Toothache since last night", "Cost of whitening?", "Insurance form request", "Thank you, Dr. Rossi"]),
        dict(title="Reminder settings", type="config", icon="bell", desc="How patients are reminded.", items=["Text patients 24 hours before a visit", "Email recall reminders every 6 months", "Offer cancelled slots to the waiting list", "Ask for a review after each visit"]),
    ],
))
