"""Batch 2: Sales and marketing dashboards (numbers 16 to 25)."""

B2 = []

B2.append(dict(
    num=16, slug="rapport", brand="Rapport", category="CRM", org="Northbeam Software", currency="$",
    tagline="Contacts, companies and deals for a growing sales team.",
    auth_line="Know every customer. Close more deals.", user="Hugo Fischer", user_role="Head of sales",
    theme=dict(fonts=["Urbanist", "Inter", "JetBrains Mono", "Urbanist"], accent="#2563eb", layout="light", card="shadow", radius="12px",
               c2="#93c5fd", c3="#f59e0b", c4="#10b981"),
    kpis=[("Open pipeline", "money", 1260000, "trend"), ("Won this month", "money", 184000, "check"), ("New contacts", "int", 342, "users"), ("Win rate", "pct", 27.5, "star")],
    chart=dict(title="Deals won", names=["Won", "Lost"], base=160000),
    mix=dict(title="Deals by source", parts=["Website", "Referral", "Outbound", "Events", "Partners"]),
    activity=["Deal moved to Proposal: Summit Labs", "Call logged with Grace Hughes", "New company added: Cedar Health", "Meeting booked for Thursday", "Deal won: Beacon Retail", "Email sequence started for 24 leads"],
    entities=[
        dict(singular="Contact", plural="Contacts", prefix="", icon="user", desc="People you are talking to.",
             fields=[("Contact", "person"), ("Company", "company"), ("Email", "email"), ("Last contact", "date"), ("Stage", "status:Lead|Qualified|Customer|Lost")]),
        dict(singular="Company", plural="Companies", slug="companies", prefix="", icon="building", desc="Businesses in your CRM.",
             fields=[("Company", "company"), ("Industry", "choice:Software|Retail|Health|Finance|Manufacturing"), ("Employees", "int:10-4000"), ("Deal value", "money:2000-400000"), ("Status", "status:Customer|Prospect|Churned")]),
        dict(singular="Deal", plural="Deals", prefix="D-", icon="briefcase", desc="Opportunities in your pipeline.",
             fields=[("Deal", "id"), ("Company", "company"), ("Owner", "person"), ("Value", "money:3000-250000"), ("Stage", "status:Won|Proposal|Negotiation|Lost")]),
        dict(singular="Task", plural="Tasks", prefix="", icon="check", desc="Follow-ups and to-dos.",
             fields=[("Task", "words:Send proposal|Call back|Book demo|Update contract|Share pricing|Intro call"), ("Contact", "person"), ("Due", "date:future"), ("Priority", "choice:High|Medium|Low"), ("Status", "status:Open|Done|Overdue")]),
        dict(singular="Meeting", plural="Meetings", prefix="", icon="calendar", desc="Calls and demos on the calendar.",
             fields=[("Meeting", "words:Discovery call|Product demo|Contract review|Quarterly check-in|Kick-off"), ("With", "company"), ("Date", "date:future"), ("Time", "time"), ("Status", "status:Booked|Confirmed|Cancelled")]),
    ],
    specials=[
        dict(title="Pipeline", type="kanban", icon="kanban", desc="Drag deals through your sales stages.", items=["Lead", "Qualified", "Proposal", "Negotiation", "Won"], cards=["New website", "Annual licence", "Team upgrade", "Pilot project"], money=True, who="company"),
        dict(title="Sales report", type="report", icon="chart", desc="Revenue, win rate and cycle length.", items=["Revenue won", "Win rate", "Average deal", "Sales cycle"], rows=["Website", "Referral", "Outbound", "Events", "Partners"]),
        dict(title="Leaderboard", type="ranking", icon="star", desc="Top sellers this quarter.", items=["Hugo Fischer", "Amara Silva", "Ben Walsh", "Chloe Chen", "Daniel Diaz", "Elena Novak"], metric="Revenue", scale=4000),
        dict(title="Sales calendar", type="calendar", icon="calendar", desc="Calls, demos and follow-ups.", items=["Demo", "Discovery call", "Follow-up", "Contract review", "Team standup"]),
        dict(title="Inbox", type="split", icon="inbox", desc="Emails from contacts, linked to deals.", items=["Re: pricing for 50 seats", "Contract signed", "Can we move the demo?", "Questions about security", "Intro from Oak Studio"]),
        dict(title="Quote", type="document", icon="file", desc="A printable quote for a customer.", doc="Quote", num="Q-2026-0342", items=["Annual licence, 50 seats", "Onboarding package", "Priority support", "Data import"]),
        dict(title="Automations", type="config", icon="zap", desc="Rules that save your team time.", items=["Assign new leads by region", "Create a task when a deal goes quiet for 7 days", "Notify the owner when a deal is won", "Add website signups as leads"]),
    ],
))

B2.append(dict(
    num=17, slug="closer", brand="Closer", category="Sales Pipeline", org="Ironbridge Solar", currency="$",
    tagline="A focused pipeline for field sales teams selling big-ticket projects.",
    auth_line="Every deal, every stage, one board.", user="Carlos Diaz", user_role="Sales manager",
    theme=dict(fonts=["Archivo", "Archivo", "IBM Plex Mono", "Archivo"], accent="#ea580c", layout="dark", card="border", radius="8px", sidebar="#1c1917",
               c2="#fdba74", c3="#0ea5e9", c4="#84cc16"),
    kpis=[("Pipeline value", "money", 3420000, "trend"), ("Forecast this quarter", "money", 920000, "chart"), ("Deals in play", "int", 86, "briefcase"), ("Avg days to close", "int", 38, "clock")],
    chart=dict(title="Forecast versus target", names=["Forecast", "Target"], base=800000),
    mix=dict(title="Pipeline by stage", parts=["Lead", "Site visit", "Proposal", "Negotiation", "Contract"]),
    activity=["Site visit completed at Maple Farm", "Proposal sent to River Logistics", "Deal lost: price too high", "Contract signed with Oak School", "Forecast updated for Q4", "New lead from trade show"],
    entities=[
        dict(singular="Deal", plural="Deals", prefix="DL-", icon="briefcase", desc="Every open and closed deal.",
             fields=[("Deal", "id"), ("Customer", "company"), ("Rep", "person"), ("Value", "money:12000-400000"), ("Stage", "status:Won|Proposal|Site visit|Lost")]),
        dict(singular="Lead", plural="Leads", prefix="", icon="user", desc="New interest waiting for a first call.",
             fields=[("Lead", "person"), ("Source", "choice:Website|Trade show|Referral|Cold call"), ("City", "city"), ("Est. value", "money:8000-200000"), ("Status", "status:New|Contacted|Qualified|Lost")]),
        dict(singular="Rep", plural="Sales reps", slug="sales-reps", prefix="", icon="users", desc="Your team and their targets.",
             fields=[("Rep", "person"), ("Region", "choice:North|South|East|West"), ("Deals", "int:4-30"), ("Quota met", "pct:40-130"), ("Status", "status:On track|At risk|Behind")]),
        dict(singular="Proposal", plural="Proposals", prefix="PR-", icon="file", desc="Proposals sent to customers.",
             fields=[("Proposal", "id"), ("Customer", "company"), ("Sent", "date"), ("Value", "money:10000-380000"), ("Status", "status:Viewed|Sent|Accepted|Declined")]),
        dict(singular="Product", plural="Products", prefix="", icon="box", desc="What you sell and how it performs.",
             fields=[("Product", "words:Rooftop panels|Battery pack|Solar carport|Inverter upgrade|Maintenance plan"), ("Price from", "money:900-60000"), ("Sold", "int:4-240"), ("Margin", "pct:12-40"), ("Status", "status:Available|Limited|Discontinued")]),
    ],
    specials=[
        dict(title="Deal board", type="kanban", icon="kanban", desc="The pipeline, stage by stage.", items=["Lead", "Site visit", "Proposal", "Negotiation", "Won"], cards=["Rooftop install", "Battery pack", "Solar carport", "Farm project"], money=True, who="company"),
        dict(title="Forecast", type="report", icon="chart", desc="What will close this quarter.", items=["Committed", "Best case", "Pipeline", "Coverage"], rows=["North", "South", "East", "West", "Key accounts"]),
        dict(title="Territory map", type="map", icon="map", desc="Deals by region.", items=["North", "South", "East", "West", "Coast"]),
        dict(title="Rep ranking", type="ranking", icon="star", desc="Who closed the most this quarter.", items=["Carlos Diaz", "Fatima Khan", "Gabriel Rossi", "Hana Sato", "Isaac Larsen", "Julia Moreau"], metric="Closed", scale=6000),
        dict(title="Site visits", type="calendar", icon="calendar", desc="Visits booked with customers.", items=["Site visit", "Roof survey", "Contract signing", "Follow-up call", "Install check"]),
        dict(title="Deal history", type="timeline", icon="clock", desc="What happened on your biggest deal.", items=["First call with the owner", "Site visit and roof survey", "Proposal sent", "Price negotiation", "Contract signed"]),
        dict(title="Stage rules", type="config", icon="settings", desc="What must happen before a deal moves on.", items=["Require a site visit before a proposal", "Manager approval for discounts over 10 percent", "Alert when a deal has no activity for 14 days", "Lock deals once a contract is signed"]),
    ],
))

B2.append(dict(
    num=18, slug="mailroom", brand="Mailroom", category="Email Marketing", org="Fernleaf Coffee", currency="$",
    tagline="Campaigns, lists and automations for an email newsletter that sells.",
    auth_line="Emails people actually want to open.", user="Julia Larsen", user_role="Marketing lead",
    theme=dict(fonts=["Lexend", "Lexend", "Fira Code", "Lexend"], accent="#db2777", layout="tint", card="shadow", radius="16px",
               c2="#f9a8d4", c3="#8b5cf6", c4="#14b8a6"),
    kpis=[("Subscribers", "int", 48200, "users"), ("Open rate", "pct", 41.8, "inbox"), ("Click rate", "pct", 6.4, "zap"), ("Email revenue", "money", 38400, "dollar")],
    chart=dict(title="Subscriber growth", names=["Subscribers", "Unsubscribes"], base=42000),
    mix=dict(title="Where subscribers come from", parts=["Website form", "Checkout", "Pop-up", "Social", "Other"]),
    activity=["Campaign sent: Autumn roast launch", "412 new subscribers this week", "Welcome series updated", "A/B test winner picked", "List cleaned: 230 inactive removed", "Template saved: Product drop"],
    entities=[
        dict(singular="Campaign", plural="Campaigns", prefix="", icon="inbox", desc="Emails you sent or scheduled.",
             fields=[("Campaign", "words:Autumn roast launch|Weekly brew notes|Flash sale|New cafe opening|Subscriber thank you|Holiday gift guide"), ("Sent", "date"), ("Recipients", "int:5000-48000"), ("Open rate", "pct:22-58"), ("Status", "status:Sent|Scheduled|Draft")]),
        dict(singular="Subscriber", plural="Subscribers", prefix="", icon="users", desc="People on your lists.",
             fields=[("Subscriber", "email"), ("Name", "person"), ("Joined", "date"), ("Orders", "int:0-24"), ("Status", "status:Subscribed|Unsubscribed|Bounced")]),
        dict(singular="List", plural="Lists", prefix="", icon="list", desc="Groups of subscribers.",
             fields=[("List", "words:Newsletter|Customers|VIP|Wholesale|Cafe regulars|Lapsed buyers"), ("Subscribers", "int:400-42000"), ("Growth", "pct:1-18"), ("Created", "date"), ("Status", "status:Active|Archived")]),
        dict(singular="Automation", plural="Automations", prefix="", icon="zap", desc="Emails that send themselves.",
             fields=[("Automation", "words:Welcome series|Abandoned cart|Win back|Birthday treat|Post purchase|Review request"), ("Emails", "int:1-6"), ("Sent this month", "int:100-9000"), ("Revenue", "money:200-12000"), ("Status", "status:Running|Paused|Draft")]),
        dict(singular="Template", plural="Templates", prefix="", icon="file", desc="Designs you reuse.",
             fields=[("Template", "words:Product drop|Newsletter|Sale banner|Plain letter|Event invite|Receipt"), ("Used", "int:1-40"), ("Updated", "date"), ("Blocks", "int:4-16"), ("Status", "status:Ready|Draft")]),
    ],
    specials=[
        dict(title="Campaign report", type="report", icon="chart", desc="Opens, clicks and sales from each email.", items=["Opens", "Click rate", "Revenue", "Unsubscribe rate"], rows=["Autumn roast launch", "Weekly brew notes", "Flash sale", "Holiday gift guide", "Welcome series"]),
        dict(title="Send calendar", type="calendar", icon="calendar", desc="What goes out and when.", items=["Newsletter", "Flash sale", "Product drop", "Welcome series", "Holiday email"]),
        dict(title="Email preview", type="document", icon="file", desc="Preview of the next campaign.", doc="Autumn roast launch", num="Scheduled for Friday 09:00", items=["Hero banner", "Single origin Ethiopia", "House blend", "Free shipping block"], note="Preview only. Prices shown are the product prices used in the email."),
        dict(title="Top links", type="ranking", icon="trend", desc="The most clicked links this month.", items=["Shop autumn roast", "Brewing guide", "Subscription offer", "Find a cafe", "Gift cards", "Our story"], metric="Clicks", scale=40),
        dict(title="Subscribers by country", type="map", icon="globe", desc="Where your readers are.", items=["United Kingdom", "United States", "Germany", "Australia", "Canada"]),
        dict(title="Replies", type="split", icon="message", desc="People who replied to your emails.", items=["Love the new roast!", "Please change my address", "Do you ship to Ireland?", "Question about my subscription", "Unsubscribe me please"]),
        dict(title="Sending settings", type="config", icon="settings", desc="Keep your emails out of spam.", items=["Send from a verified domain", "Remove addresses after 3 bounces", "Stop sending to people inactive for 6 months", "Add an unsubscribe link to every email"]),
    ],
))

B2.append(dict(
    num=19, slug="postwise", brand="Postwise", category="Social Media Management", org="Wildflower Studio", currency="$",
    tagline="Plan, publish and measure posts across every social channel.",
    auth_line="Plan a month of posts in an afternoon.", user="Zoe Evans", user_role="Social media manager",
    theme=dict(fonts=["Poppins", "Poppins", "DM Mono", "Poppins"], accent="#7c3aed", layout="accent", card="border", radius="14px",
               c2="#c4b5fd", c3="#f472b6", c4="#22d3ee"),
    kpis=[("Followers", "int", 128400, "users"), ("Engagement rate", "pct", 4.8, "heart"), ("Posts this month", "int", 64, "grid"), ("Link clicks", "int", 9420, "zap")],
    chart=dict(title="Followers", names=["Followers", "Reach"], base=110000),
    mix=dict(title="Followers by channel", parts=["Instagram", "TikTok", "LinkedIn", "Facebook", "YouTube"]),
    activity=["Post published on Instagram", "Comment replied by Zoe", "Reel scheduled for Friday", "Weekly report shared with client", "New hashtag set saved", "Story reached 12k people"],
    entities=[
        dict(singular="Post", plural="Posts", prefix="", icon="grid", desc="Everything you published or scheduled.",
             fields=[("Post", "words:Behind the scenes reel|New collection carousel|Customer story|Tips thread|Giveaway|Team intro"), ("Channel", "choice:Instagram|TikTok|LinkedIn|Facebook"), ("Date", "date"), ("Engagement", "int:80-9000"), ("Status", "status:Published|Scheduled|Draft")]),
        dict(singular="Channel", plural="Channels", prefix="", icon="globe", desc="Accounts you manage.",
             fields=[("Channel", "words:Instagram|TikTok|LinkedIn|Facebook|YouTube|Pinterest"), ("Followers", "int:2000-80000"), ("Growth", "pct:1-22"), ("Posts", "int:10-120"), ("Status", "status:Connected|Needs login")]),
        dict(singular="Campaign", plural="Campaigns", prefix="", icon="star", desc="Themed groups of posts.",
             fields=[("Campaign", "words:Spring launch|Summer sale|Brand refresh|Holiday gifts|Back to school"), ("Posts", "int:4-40"), ("Reach", "int:10000-400000"), ("Budget", "money:0-8000"), ("Status", "status:Live|Planned|Done")]),
        dict(singular="Comment", plural="Comments", prefix="", icon="message", desc="Comments waiting for a reply.",
             fields=[("From", "person"), ("Channel", "choice:Instagram|TikTok|Facebook|LinkedIn"), ("Comment", "words:Where can I buy this?|Love it!|Do you ship abroad?|Price please|So beautiful"), ("Received", "date"), ("Status", "status:New|Replied|Hidden")]),
        dict(singular="Asset", plural="Media library", slug="media-library", prefix="", icon="folder", desc="Photos and videos ready to post.",
             fields=[("Asset", "words:Studio shoot 01|Product flat lay|Team photo|Reel cut 3|Logo animation|Event photos"), ("Type", "choice:Photo|Video|Graphic"), ("Uploaded", "date"), ("Used", "int:0-12"), ("Status", "status:Approved|In review")]),
    ],
    specials=[
        dict(title="Content calendar", type="calendar", icon="calendar", desc="Every post planned for this month.", items=["Instagram reel", "LinkedIn post", "TikTok video", "Story", "Carousel"]),
        dict(title="Approval board", type="kanban", icon="kanban", desc="Posts moving from idea to published.", items=["Ideas", "Writing", "Client review", "Scheduled", "Published"], cards=["Behind the scenes", "Product carousel", "Customer story", "Tips post"]),
        dict(title="Analytics", type="report", icon="chart", desc="Reach and engagement for every channel.", items=["Reach", "Engagement rate", "Profile visits", "Link clicks"], rows=["Instagram", "TikTok", "LinkedIn", "Facebook", "YouTube"]),
        dict(title="Top posts", type="ranking", icon="trend", desc="Posts that did best this month.", items=["Behind the scenes reel", "New collection carousel", "Customer story", "Giveaway", "Tips thread", "Team intro"], metric="Engagement", scale=120),
        dict(title="Social inbox", type="split", icon="inbox", desc="Messages from every channel in one place.", items=["Do you have this in blue?", "Collaboration request", "My order has not arrived", "Can I use your photo?", "Love your work"]),
        dict(title="Brand assets", type="gallery", icon="folder", desc="Approved photos, videos and graphics.", items=["Spring shoot", "Product photos", "Team portraits", "Logo pack", "Reel covers", "Story templates"]),
        dict(title="Publishing rules", type="config", icon="settings", desc="Guardrails for your team.", items=["Require client approval before posting", "Post at the best time for each channel", "Add alt text to every image", "Hide comments with blocked words"]),
    ],
))

B2.append(dict(
    num=20, slug="climb", brand="Climb", category="SEO Rank Tracker", org="Greenleaf Gardening", currency="$",
    tagline="Track keyword rankings, backlinks and site health for better search traffic.",
    auth_line="See every keyword move, every day.", user="Farid Rahman", user_role="SEO lead",
    theme=dict(fonts=["Onest", "Onest", "JetBrains Mono", "Onest"], accent="#059669", layout="light", card="flat", radius="8px",
               c2="#6ee7b7", c3="#f59e0b", c4="#6366f1"),
    kpis=[("Keywords in top 10", "int", 184, "trend"), ("Organic visits", "int", 64200, "users"), ("Average position", "int", 14, "chart"), ("New backlinks", "int", 96, "globe")],
    chart=dict(title="Organic visits", names=["Visits", "Last year"], base=52000),
    mix=dict(title="Keywords by position", parts=["Top 3", "4 to 10", "11 to 20", "21 to 50", "Not ranking"]),
    activity=["Keyword 'raised bed kit' moved to position 3", "12 new backlinks found", "Site audit finished: 4 new issues", "Competitor added: Rootwise", "Rank report emailed", "Page title updated on /compost-guide"],
    entities=[
        dict(singular="Keyword", plural="Keywords", prefix="", icon="search", desc="Search terms you track every day.",
             fields=[("Keyword", "words:raised bed kit|how to compost|best garden hose|tomato plant care|organic fertiliser|garden tools set|lawn seed"), ("Position", "int:1-48"), ("Search volume", "int:300-40000"), ("Change", "int:0-12"), ("Trend", "status:Up|Flat|Down")]),
        dict(singular="Page", plural="Pages", prefix="", icon="file", desc="Pages that get search traffic.",
             fields=[("Page", "words:/compost-guide|/raised-beds|/garden-tools|/lawn-care|/blog/tomatoes|/shop/seeds"), ("Visits", "int:200-12000"), ("Keywords", "int:3-240"), ("Top position", "int:1-20"), ("Status", "status:Healthy|Needs work|Critical")]),
        dict(singular="Backlink", plural="Backlinks", prefix="", icon="globe", desc="Sites that link to you.",
             fields=[("Linking site", "words:gardenersweekly.com|homesteadblog.net|greenliving.org|diyhub.io|localnews.co|plantforum.com"), ("Authority", "int:12-88"), ("Found", "date"), ("Links", "int:1-40"), ("Status", "status:Live|New|Lost")]),
        dict(singular="Competitor", plural="Competitors", prefix="", icon="users", desc="Sites you compete with in search.",
             fields=[("Competitor", "words:rootwise.com|leafandloam.com|gardenly.co|soilsmith.net|bloomhub.com"), ("Shared keywords", "int:40-900"), ("Visibility", "pct:5-60"), ("Backlinks", "int:200-20000"), ("Status", "status:Tracking|Paused")]),
        dict(singular="Issue", plural="Site issues", slug="site-issues", prefix="", icon="alert", desc="Problems found in the last site audit.",
             fields=[("Issue", "words:Missing meta description|Broken internal link|Slow page|Duplicate title|Image without alt text|Redirect chain"), ("Pages", "int:1-60"), ("Found", "date"), ("Impact", "choice:High|Medium|Low"), ("Status", "status:Open|Fixed|Ignored")]),
    ],
    specials=[
        dict(title="Rank report", type="report", icon="chart", desc="How your rankings changed this month.", items=["Visibility", "Top 10 keywords", "Organic traffic", "Click-through rate"], rows=["raised bed kit", "how to compost", "garden tools set", "lawn seed", "tomato plant care"]),
        dict(title="Biggest movers", type="ranking", icon="trend", desc="Keywords that moved the most this week.", items=["raised bed kit", "compost bin", "garden hose", "lawn seed", "tomato cages", "pruning shears"], metric="Positions gained", scale=0.12),
        dict(title="Site health", type="monitor", icon="activity", desc="Speed and crawl checks for key pages.", items=["Home page", "Compost guide", "Raised beds", "Shop", "Blog", "Checkout", "Sitemap", "Robots file"], unit=" score"),
        dict(title="Rankings by city", type="map", icon="map", desc="Local rankings in your main cities.", items=["London", "Manchester", "Bristol", "Leeds", "Glasgow"]),
        dict(title="Fix list", type="kanban", icon="kanban", desc="SEO tasks from the audit.", items=["To do", "In progress", "Waiting on dev", "Done"], cards=["Fix broken links", "Add meta descriptions", "Compress images", "Merge duplicate pages"]),
        dict(title="Change log", type="timeline", icon="clock", desc="SEO changes and what happened after.", items=["Rewrote title on /raised-beds", "Added FAQ schema to compost guide", "Fixed 14 broken links", "Launched new tools category page"]),
        dict(title="Tracking settings", type="config", icon="settings", desc="How and where rankings are checked.", items=["Check rankings every day", "Track mobile and desktop separately", "Email me when a keyword drops 5 places", "Include local results"]),
    ],
))

B2.append(dict(
    num=21, slug="bidwell", brand="Bidwell", category="Ad Campaigns", org="Summit Outdoor Gear", currency="$",
    tagline="Paid search and social ads, budgets and returns in one view.",
    auth_line="Spend less per sale on every ad.", user="Nadia Varga", user_role="Performance marketer",
    theme=dict(fonts=["Red Hat Display", "Red Hat Text", "Red Hat Mono", "Red Hat Display"], accent="#dc2626", layout="dark", card="shadow", radius="10px", sidebar="#18181b",
               c2="#fca5a5", c3="#2563eb", c4="#16a34a"),
    kpis=[("Ad spend", "money", 42600, "dollar"), ("Revenue from ads", "money", 196000, "trend"), ("Return on ad spend", "ratio", 4.6, "chart"), ("Cost per sale", "money", 18.4, "tag")],
    chart=dict(title="Spend and revenue", names=["Revenue", "Spend"], base=160000),
    mix=dict(title="Spend by platform", parts=["Search", "Social", "Shopping", "Video", "Display"]),
    activity=["Budget raised on Autumn hiking", "Ad paused: low click rate", "New audience created: past buyers", "Bid strategy changed to target ROAS", "Weekly report sent", "Creative test started"],
    entities=[
        dict(singular="Campaign", plural="Campaigns", prefix="", icon="zap", desc="All paid campaigns.",
             fields=[("Campaign", "words:Autumn hiking|Brand search|Winter jackets|Retargeting|Tents sale|Trail shoes"), ("Platform", "choice:Search|Social|Shopping|Video"), ("Spend", "money:500-12000"), ("ROAS", "ratio:1-9"), ("Status", "status:Active|Paused|Ended")]),
        dict(singular="Ad group", plural="Ad groups", slug="ad-groups", prefix="", icon="layers", desc="Groups of ads that share targeting.",
             fields=[("Ad group", "words:Hiking boots|Rain jackets|Camping stoves|Sleeping bags|Backpacks"), ("Campaign", "words:Autumn hiking|Winter jackets|Tents sale"), ("Clicks", "int:200-9000"), ("Cost", "money:100-5000"), ("Status", "status:Active|Paused")]),
        dict(singular="Ad", plural="Ads", prefix="AD-", icon="grid", desc="Individual ads and how they perform.",
             fields=[("Ad", "id"), ("Headline", "words:Built for the trail|Stay dry this winter|Up to 30% off tents|Free returns|Gear that lasts"), ("Clicks", "int:50-4000"), ("CTR", "pct:0.5-8"), ("Status", "status:Active|Learning|Rejected")]),
        dict(singular="Audience", plural="Audiences", prefix="", icon="users", desc="Groups of people you target.",
             fields=[("Audience", "words:Past buyers|Site visitors|Newsletter list|Lookalike 1%|Hiking fans|Cart abandoners"), ("Size", "int:2000-900000"), ("Campaigns", "int:1-8"), ("Conversion rate", "pct:1-9"), ("Status", "status:Ready|Building")]),
        dict(singular="Conversion", plural="Conversions", prefix="CV-", icon="check", desc="Sales and sign-ups from ads.",
             fields=[("Conversion", "id"), ("Campaign", "words:Autumn hiking|Brand search|Retargeting|Tents sale"), ("Date", "date"), ("Value", "money:20-900"), ("Status", "status:Attributed|Pending")]),
    ],
    specials=[
        dict(title="Performance", type="report", icon="chart", desc="Spend, clicks and returns by platform.", items=["Spend", "Clicks", "Conversions", "Cost per click"], rows=["Search", "Social", "Shopping", "Video", "Display"]),
        dict(title="Budget pacing", type="monitor", icon="activity", desc="How fast each campaign spends its budget.", items=["Autumn hiking", "Brand search", "Winter jackets", "Retargeting", "Tents sale", "Trail shoes"], unit="%"),
        dict(title="Best ads", type="ranking", icon="star", desc="Ads with the best return this month.", items=["Built for the trail", "Stay dry this winter", "Up to 30% off tents", "Free returns", "Gear that lasts", "Pack light"], metric="Revenue", scale=400),
        dict(title="Sales by region", type="map", icon="map", desc="Where your ad sales come from.", items=["Pacific North West", "Rockies", "New England", "California", "Midwest"]),
        dict(title="Creative tests", type="kanban", icon="kanban", desc="Ad ideas from brief to winner.", items=["Ideas", "In design", "Testing", "Winner", "Retired"], cards=["Video: trail run", "Carousel: jackets", "Image: tent at sunset", "UGC review"]),
        dict(title="Launch calendar", type="calendar", icon="calendar", desc="Campaign starts and sales.", items=["Campaign launch", "Sale starts", "Creative refresh", "Budget review", "Report due"]),
        dict(title="Budget rules", type="config", icon="shield", desc="Automatic limits on spend.", items=["Pause ads with no sales after $200", "Cap daily spend at $2,000", "Raise bids on best sellers", "Email me when ROAS drops below 3"]),
    ],
))

B2.append(dict(
    num=22, slug="referra", brand="Referra", category="Affiliate Program", org="Loomcraft Yarns", currency="$",
    tagline="Affiliates, referrals, commissions and payouts for a partner program.",
    auth_line="Grow sales with people who love your brand.", user="Leila Moreau", user_role="Partnerships manager",
    theme=dict(fonts=["Albert Sans", "Albert Sans", "Space Mono", "Albert Sans"], accent="#0d9488", layout="tint", card="border", radius="12px",
               c2="#5eead4", c3="#f97316", c4="#8b5cf6"),
    kpis=[("Affiliate revenue", "money", 84200, "dollar"), ("Commissions owed", "money", 9860, "receipt"), ("Active affiliates", "int", 312, "users"), ("Conversion rate", "pct", 3.9, "trend")],
    chart=dict(title="Referred revenue", names=["Revenue", "Commissions"], base=70000),
    mix=dict(title="Revenue by affiliate type", parts=["Bloggers", "YouTubers", "Instagram", "Coupon sites", "Other"]),
    activity=["New affiliate approved: Knit with Mia", "Payout of $4,120 sent", "Commission rate raised for top tier", "Fraud check flagged 3 orders", "New creative uploaded", "Monthly newsletter sent to affiliates"],
    entities=[
        dict(singular="Affiliate", plural="Affiliates", prefix="", icon="users", desc="People who promote your products.",
             fields=[("Affiliate", "person"), ("Tier", "choice:Starter|Silver|Gold|Partner"), ("Clicks", "int:100-40000"), ("Earned", "money:20-12000"), ("Status", "status:Active|Pending|Paused")]),
        dict(singular="Referral", plural="Referrals", prefix="R-", icon="zap", desc="Orders that came from affiliates.",
             fields=[("Referral", "id"), ("Affiliate", "person"), ("Order", "code:#"), ("Value", "money:18-420"), ("Status", "status:Approved|Pending|Rejected")]),
        dict(singular="Commission", plural="Commissions", prefix="CM-", icon="dollar", desc="What each affiliate earned.",
             fields=[("Commission", "id"), ("Affiliate", "person"), ("Rate", "pct:8-25"), ("Amount", "money:2-120"), ("Status", "status:Approved|Pending|Paid")]),
        dict(singular="Payout", plural="Payouts", prefix="PO-", icon="card", desc="Money paid to affiliates.",
             fields=[("Payout", "id"), ("Affiliate", "person"), ("Method", "choice:Bank transfer|PayPal|Store credit"), ("Amount", "money:50-4000"), ("Status", "status:Paid|Scheduled|Failed")]),
        dict(singular="Link", plural="Links", prefix="", icon="globe", desc="Tracking links and coupon codes.",
             fields=[("Link", "words:/r/mia|/r/knitclub|/r/yarnlove|MIA10|CRAFT15|/r/purlpro"), ("Affiliate", "person"), ("Clicks", "int:50-20000"), ("Sales", "int:0-600"), ("Status", "status:Active|Expired")]),
    ],
    specials=[
        dict(title="Program report", type="report", icon="chart", desc="Revenue, commissions and growth.", items=["Revenue", "Commissions", "New affiliates", "Average order"], rows=["Bloggers", "YouTubers", "Instagram", "Coupon sites", "Podcasts"]),
        dict(title="Top affiliates", type="ranking", icon="star", desc="Your best partners this month.", items=["Knit with Mia", "The Yarn Club", "Purl Pro", "Cozy Crafts", "Stitch Diaries", "Wool Weekly"], metric="Revenue", scale=180),
        dict(title="Applications", type="kanban", icon="kanban", desc="New affiliates waiting for a decision.", items=["New", "Reviewing", "Approved", "Declined"], cards=["Craft blogger", "YouTube channel", "Instagram creator", "Podcast host"]),
        dict(title="Payout run", type="document", icon="receipt", desc="This month's payout summary.", doc="Payout summary", num="September 2026", items=["Gold tier payouts", "Silver tier payouts", "Starter tier payouts", "Bonuses"]),
        dict(title="Promo calendar", type="calendar", icon="calendar", desc="Launches affiliates should know about.", items=["New yarn launch", "Affiliate bonus week", "Newsletter to affiliates", "Payout day", "Holiday sale"]),
        dict(title="Creative library", type="gallery", icon="folder", desc="Banners and photos affiliates can use.", items=["Autumn banner", "Product photos", "Pattern previews", "Logo pack", "Story templates", "Email graphics"]),
        dict(title="Program rules", type="config", icon="settings", desc="Commission and fraud settings.", items=["Pay 15 percent on the first order", "Hold commissions for 30 days", "Block self-referrals", "Give Gold tier a 5 percent bonus"]),
    ],
))

B2.append(dict(
    num=23, slug="collab", brand="Collab", category="Influencer Marketing", org="Glowlab Skincare", currency="$",
    tagline="Find creators, run campaigns and measure every sponsored post.",
    auth_line="Work with creators your customers already trust.", user="Aisha Mensah", user_role="Influencer lead",
    theme=dict(fonts=["Syne", "DM Sans", "DM Mono", "Syne"], accent="#c026d3", layout="light", card="shadow", radius="18px",
               c2="#f0abfc", c3="#f59e0b", c4="#06b6d4"),
    kpis=[("Campaign reach", "int", 2840000, "globe"), ("Creators live", "int", 46, "users"), ("Sales from codes", "money", 62400, "dollar"), ("Cost per view", "money", 0.02, "tag")],
    chart=dict(title="Reach from creators", names=["Reach", "Engagement"], base=2400000),
    mix=dict(title="Spend by platform", parts=["Instagram", "TikTok", "YouTube", "Pinterest", "Blogs"]),
    activity=["Contract signed with Maya Chen", "Post approved for the Glow serum launch", "Creator shipped samples", "Code GLOW15 used 84 times", "Invoice paid to Rohan Patel", "New creator shortlist shared"],
    entities=[
        dict(singular="Creator", plural="Creators", prefix="", icon="user", desc="Creators you work with or want to.",
             fields=[("Creator", "person"), ("Platform", "choice:Instagram|TikTok|YouTube|Pinterest"), ("Followers", "int:8000-900000"), ("Engagement", "pct:1-12"), ("Status", "status:Active|Shortlisted|Declined")]),
        dict(singular="Campaign", plural="Campaigns", prefix="", icon="star", desc="Sponsored campaigns.",
             fields=[("Campaign", "words:Glow serum launch|Summer SPF|Night cream|Holiday gift sets|Clean beauty week"), ("Creators", "int:3-30"), ("Budget", "money:2000-60000"), ("Reach", "int:40000-2000000"), ("Status", "status:Live|Planned|Done")]),
        dict(singular="Post", plural="Posts", prefix="", icon="grid", desc="Sponsored posts and how they did.",
             fields=[("Post", "words:Morning routine reel|Unboxing video|Before and after|Get ready with me|Honest review"), ("Creator", "person"), ("Views", "int:2000-600000"), ("Likes", "int:100-40000"), ("Status", "status:Live|Awaiting approval|Draft")]),
        dict(singular="Contract", plural="Contracts", prefix="CT-", icon="file", desc="Agreements with creators.",
             fields=[("Contract", "id"), ("Creator", "person"), ("Fee", "money:200-18000"), ("Deliverables", "int:1-8"), ("Status", "status:Signed|Sent|Expired")]),
        dict(singular="Shipment", plural="Shipments", prefix="SH-", icon="truck", desc="Product samples sent to creators.",
             fields=[("Shipment", "id"), ("Creator", "person"), ("Products", "int:1-6"), ("Sent", "date"), ("Status", "status:Delivered|Shipped|Returned")]),
    ],
    specials=[
        dict(title="Campaign board", type="kanban", icon="kanban", desc="Creators from outreach to live post.", items=["Outreach", "Negotiating", "Contracted", "Content review", "Live"], cards=["Morning routine reel", "Unboxing video", "Honest review", "Get ready with me"]),
        dict(title="Results", type="report", icon="chart", desc="Reach, engagement and sales from creators.", items=["Reach", "Engagement rate", "Code sales", "Cost per view"], rows=["Instagram", "TikTok", "YouTube", "Pinterest", "Blogs"]),
        dict(title="Top creators", type="ranking", icon="star", desc="Creators who drove the most sales.", items=["Maya Chen", "Rohan Patel", "Sara Silva", "Leo Nguyen", "Kavya Rao", "Tom Walsh"], metric="Code sales", scale=160),
        dict(title="Content review", type="split", icon="inbox", desc="Drafts creators sent for approval.", items=["Draft: morning routine reel", "Draft: unboxing video", "Caption for approval", "Revised draft with product close-up", "Final cut ready"]),
        dict(title="Posting calendar", type="calendar", icon="calendar", desc="When each creator posts.", items=["Instagram reel", "TikTok video", "YouTube review", "Story set", "Live stream"]),
        dict(title="Creator brief", type="document", icon="file", desc="The brief shared with creators.", doc="Creator brief: Glow serum launch", num="Campaign GS-26", items=["One reel, 30 to 60 seconds", "Three stories with link", "Use code GLOW15", "Tag the brand account"], note="Fees are listed per deliverable. Please share drafts 3 days before posting."),
        dict(title="Brand rules", type="config", icon="shield", desc="What every sponsored post must include.", items=["Label posts as paid partnership", "Get approval before posting", "No medical claims", "Share results within 7 days"]),
    ],
))

B2.append(dict(
    num=24, slug="assist", brand="Assist", category="Customer Support Helpdesk", org="Parcelpoint Delivery", currency="$",
    tagline="Tickets, customers and help articles for a support team.",
    auth_line="Answer faster. Keep customers happy.", user="Isaac Ferreira", user_role="Support lead",
    theme=dict(fonts=["Nunito", "Nunito", "Roboto Mono", "Nunito"], accent="#0284c7", layout="dark", card="border", radius="10px", sidebar="#0c1a2b",
               c2="#7dd3fc", c3="#f59e0b", c4="#22c55e"),
    kpis=[("Open tickets", "int", 214, "inbox"), ("First reply time", "int", 18, "clock"), ("Solved today", "int", 386, "check"), ("Customer happiness", "pct", 94.1, "heart")],
    chart=dict(title="Tickets created and solved", names=["Solved", "Created"], base=380),
    mix=dict(title="Tickets by topic", parts=["Where is my parcel", "Returns", "Damaged item", "Billing", "Other"]),
    activity=["Ticket T-5521 solved by Wen", "New macro: late delivery apology", "Help article updated: returns", "SLA warning on 6 tickets", "Customer rated 5 stars", "Ticket escalated to billing team"],
    entities=[
        dict(singular="Ticket", plural="Tickets", prefix="T-", icon="inbox", desc="Customer questions and problems.",
             fields=[("Ticket", "id"), ("Subject", "words:Where is my parcel?|Item arrived damaged|Change delivery address|Refund request|Driver left parcel outside"), ("Customer", "person"), ("Priority", "choice:Urgent|High|Normal|Low"), ("Status", "status:Open|Pending|Solved|Closed")]),
        dict(singular="Customer", plural="Customers", prefix="", icon="users", desc="People who contacted support.",
             fields=[("Customer", "person"), ("Email", "email"), ("Tickets", "int:1-18"), ("Last contact", "date"), ("Status", "status:Happy|Neutral|Unhappy")]),
        dict(singular="Agent", plural="Agents", prefix="", icon="user", desc="Your support team.",
             fields=[("Agent", "person"), ("Team", "choice:Delivery|Returns|Billing|VIP"), ("Solved today", "int:5-60"), ("Happiness", "pct:80-100"), ("Status", "status:Online|Busy|Offline")]),
        dict(singular="Article", plural="Help articles", slug="help-articles", prefix="", icon="book", desc="Answers customers can find themselves.",
             fields=[("Article", "words:Track your parcel|How to return an item|Change your address|Delivery times|Report damage|Refund timelines"), ("Views", "int:200-40000"), ("Helpful", "pct:60-98"), ("Updated", "date"), ("Status", "status:Published|Draft")]),
        dict(singular="Macro", plural="Macros", prefix="", icon="zap", desc="Saved replies for common questions.",
             fields=[("Macro", "words:Late delivery apology|Return label sent|Refund processed|Ask for photo|Address changed"), ("Used", "int:10-3000"), ("Team", "choice:Delivery|Returns|Billing"), ("Updated", "date"), ("Status", "status:Active|Retired")]),
    ],
    specials=[
        dict(title="Ticket inbox", type="split", icon="inbox", desc="Work through tickets one by one.", items=["Where is my parcel?", "Item arrived damaged", "Refund not received", "Driver was rude", "Change delivery day"], body="Hi, my parcel was due yesterday but the tracking has not changed for two days. Can you tell me where it is? Thanks."),
        dict(title="Service levels", type="monitor", icon="activity", desc="Live view of reply and wait times.", items=["First reply", "Chat wait", "Phone wait", "Email backlog", "Urgent tickets", "VIP queue", "Returns queue", "Billing queue"], unit=" min"),
        dict(title="Support report", type="report", icon="chart", desc="Volume, speed and happiness.", items=["Tickets solved", "Happiness", "First reply time", "Tickets per agent"], rows=["Where is my parcel", "Returns", "Damaged item", "Billing", "Address change"]),
        dict(title="Agent ranking", type="ranking", icon="star", desc="Tickets solved this week.", items=["Wen Zhang", "Isaac Ferreira", "Maya Okafor", "Ben Larsen", "Chloe Ito", "Dina Haddad"], metric="Solved", scale=4),
        dict(title="Escalations", type="kanban", icon="kanban", desc="Tickets that need another team.", items=["New", "Billing", "Operations", "Management", "Resolved"], cards=["Lost parcel claim", "Repeated late delivery", "Damaged fridge", "Chargeback"]),
        dict(title="Shift calendar", type="calendar", icon="calendar", desc="Who covers support and when.", items=["Morning shift", "Evening shift", "Weekend cover", "Training", "Team meeting"]),
        dict(title="Routing rules", type="config", icon="settings", desc="Send tickets to the right team.", items=["Send refund requests to Billing", "Mark tickets from VIP customers as urgent", "Auto-reply outside working hours", "Close solved tickets after 4 days"]),
    ],
))

B2.append(dict(
    num=25, slug="chatter", brand="Chatter", category="Live Chat", org="Bloomhouse Plants", currency="$",
    tagline="Live chat, visitors and chat bots for an online store.",
    auth_line="Talk to shoppers while they are still shopping.", user="Rohan Sato", user_role="Customer care manager",
    theme=dict(fonts=["Rubik", "Rubik", "Ubuntu Mono", "Rubik"], accent="#4d7c0f", layout="light", card="border", radius="20px",
               c2="#bef264", c3="#f59e0b", c4="#0ea5e9"),
    kpis=[("Chats today", "int", 482, "message"), ("Visitors online", "int", 136, "users"), ("Chat sales", "money", 12800, "cart"), ("Avg wait", "int", 42, "clock")],
    chart=dict(title="Chats per day", names=["Chats", "Sales from chat"], base=420),
    mix=dict(title="Chats by page", parts=["Product pages", "Cart", "Checkout", "Home", "Help"]),
    activity=["Chat with Olivia ended: sale", "Bot answered 64 questions", "New canned reply: plant care", "Visitor from Berlin started a chat", "Offline message received", "Chat rated 5 stars"],
    entities=[
        dict(singular="Conversation", plural="Conversations", prefix="C-", icon="message", desc="Every chat with a visitor.",
             fields=[("Conversation", "id"), ("Visitor", "person"), ("Topic", "words:Plant care|Delivery time|Pot sizes|Order status|Gift wrapping"), ("Duration", "duration"), ("Status", "status:Resolved|Active|Missed")]),
        dict(singular="Visitor", plural="Visitors", prefix="", icon="users", desc="People on your site right now.",
             fields=[("Visitor", "person"), ("Page", "words:/monstera|/cart|/checkout|/gift-cards|/care-guides"), ("City", "city"), ("Time on site", "duration"), ("Status", "status:Browsing|In chat|Idle")]),
        dict(singular="Agent", plural="Agents", prefix="", icon="user", desc="People answering chats.",
             fields=[("Agent", "person"), ("Chats today", "int:5-80"), ("Rating", "rating"), ("Avg reply", "duration"), ("Status", "status:Online|Busy|Offline")]),
        dict(singular="Bot flow", plural="Bot flows", slug="bot-flows", prefix="", icon="zap", desc="Automatic answers from the chat bot.",
             fields=[("Flow", "words:Order tracking|Plant care tips|Delivery areas|Returns|Discount code"), ("Chats", "int:100-6000"), ("Solved by bot", "pct:30-85"), ("Updated", "date"), ("Status", "status:Live|Draft")]),
        dict(singular="Canned reply", plural="Canned replies", slug="canned-replies", prefix="", icon="list", desc="Saved answers agents can send quickly.",
             fields=[("Reply", "words:Care for a monstera|Delivery takes 2 to 3 days|We ship in eco pots|Your order is on the way|Here is 10 percent off"), ("Shortcut", "code:/"), ("Used", "int:10-4000"), ("Author", "person"), ("Status", "status:Active|Retired")]),
    ],
    specials=[
        dict(title="Live chats", type="split", icon="inbox", desc="Chats happening right now.", items=["Is this plant safe for cats?", "When will my order arrive?", "Do you have bigger pots?", "Can I add a gift note?", "My plant has yellow leaves"], body="Hi! I am looking at the monstera. Is it safe for cats? And how big is it when it arrives?"),
        dict(title="Visitors now", type="monitor", icon="monitor", desc="Live activity on your store.", items=["Home page", "Monstera", "Fiddle leaf fig", "Cart", "Checkout", "Care guides", "Gift cards", "Sale"], unit=" people"),
        dict(title="Chat report", type="report", icon="chart", desc="Volume, speed and sales from chat.", items=["Chats", "Sales from chat", "Wait time", "Rating"], rows=["Product pages", "Cart", "Checkout", "Home", "Help"]),
        dict(title="Visitor map", type="map", icon="globe", desc="Where your visitors are.", items=["Germany", "Netherlands", "France", "Belgium", "Austria"]),
        dict(title="Top agents", type="ranking", icon="star", desc="Best rated agents this month.", items=["Rohan Sato", "Emma Novak", "Liam Costa", "Nadia Rahman", "Oscar Adams"], metric="Chats", scale=5),
        dict(title="Chat hours", type="calendar", icon="calendar", desc="When the chat team is online.", items=["Morning shift", "Afternoon shift", "Weekend cover", "Holiday hours", "Training"]),
        dict(title="Widget settings", type="config", icon="settings", desc="How the chat box looks and behaves.", items=["Show the chat box on product pages", "Greet visitors after 30 seconds", "Show the bot first outside working hours", "Ask for a rating when a chat ends"]),
    ],
))
