"""Batch 7: Travel and media dashboards (numbers 66 to 75)."""

B7 = []

B7.append(dict(
    num=66, slug="wayfare", brand="Wayfare", category="Travel Agency", org="Wayfare Journeys", currency="$",
    tagline="Trips, bookings, travellers and suppliers for a travel agency.",
    auth_line="Plan trips people remember.", user="Amara Costa", user_role="Agency director",
    theme=dict(fonts=["Josefin Sans", "Lato", "Roboto Mono"], accent="#0e7490", layout="tint", card="shadow", radius="16px",
               c2="#67e8f9", c3="#f59e0b", c4="#f43f5e"),
    kpis=[("Bookings this month", "int", 284, "calendar"), ("Travellers abroad now", "int", 412, "globe"), ("Sales this month", "money", 486000, "dollar"), ("Repeat customers", "pct", 46.0, "heart")],
    chart=dict(title="Bookings value", names=["This year", "Last year"], base=420000),
    mix=dict(title="Trips by region", parts=["Europe", "Asia", "Americas", "Africa", "Oceania"]),
    activity=["Honeymoon package booked for Bali", "Flight change handled for the Diaz family", "New supplier: Coastline Villas", "Visa reminder sent to 18 travellers", "Group tour to Japan sold out", "Review: 5 stars for Iceland trip"],
    entities=[
        dict(singular="Booking", plural="Bookings", prefix="BK-", icon="calendar", desc="Trips your customers booked.",
             fields=[("Booking", "id"), ("Traveller", "person"), ("Destination", "words:Lisbon|Kyoto|Bali|Reykjavik|Cape Town|Lima|Marrakech"), ("Value", "money:600-18000"), ("Status", "status:Confirmed|Deposit paid|Pending|Cancelled")]),
        dict(singular="Traveller", plural="Travellers", prefix="", icon="users", desc="Customers and their trips.",
             fields=[("Traveller", "person"), ("Trips", "int:1-12"), ("Passport expires", "date:future"), ("Spent", "money:800-40000"), ("Status", "status:Travelling|Upcoming|Past")]),
        dict(singular="Package", plural="Packages", prefix="", icon="box", desc="Trips you sell.",
             fields=[("Package", "words:Iceland northern lights|Japan in spring|Bali honeymoon|Peru and Machu Picchu|Morocco desert tour|Lisbon city break"), ("Nights", "int:3-16"), ("From", "money:700-9000"), ("Booked", "int:4-120"), ("Status", "status:On sale|Sold out|Draft")]),
        dict(singular="Supplier", plural="Suppliers", prefix="", icon="building", desc="Hotels, airlines and tour partners.",
             fields=[("Supplier", "company"), ("Type", "choice:Hotel|Airline|Tour guide|Transfer|Cruise"), ("Bookings", "int:4-300"), ("Commission", "pct:5-18"), ("Status", "status:Active|On review")]),
        dict(singular="Enquiry", plural="Enquiries", prefix="", icon="message", desc="People asking about trips.",
             fields=[("Name", "person"), ("Interest", "words:Safari|Beach holiday|City break|Honeymoon|Family trip"), ("Budget", "money:1000-20000"), ("Received", "date"), ("Status", "status:New|Quote sent|Booked|Lost")]),
    ],
    specials=[
        dict(title="Trip map", type="map", icon="globe", desc="Where your travellers are right now.", items=["Europe", "Asia", "Americas", "Africa", "Oceania"], dots=20),
        dict(title="Departures", type="calendar", icon="calendar", desc="Trips leaving and returning.", items=["Departure", "Return", "Group tour", "Visa deadline", "Final payment"]),
        dict(title="Sales pipeline", type="kanban", icon="kanban", desc="Enquiries from first contact to booked.", items=["New enquiry", "Planning", "Quote sent", "Deposit paid", "Booked"], cards=["Bali honeymoon", "Japan in spring", "Safari trip", "Iceland break"], money=True),
        dict(title="Sales report", type="report", icon="chart", desc="Bookings, margins and regions.", items=["Sales", "Margin", "Average trip", "Repeat rate"], rows=["Europe", "Asia", "Americas", "Africa", "Oceania"]),
        dict(title="Top destinations", type="ranking", icon="star", desc="The most booked places this year.", items=["Lisbon", "Kyoto", "Bali", "Reykjavik", "Cape Town", "Marrakech"], metric="Bookings", scale=1.5),
        dict(title="Itinerary", type="document", icon="file", desc="A printable trip plan for a customer.", doc="Your trip itinerary", num="BK-1047, Japan in spring", items=["Return flights", "Tokyo hotel, 4 nights", "Kyoto ryokan, 3 nights", "Rail pass", "Tea ceremony"], note="Please check your passport is valid for 6 months after your return date."),
        dict(title="Traveller messages", type="split", icon="inbox", desc="Questions from customers.", items=["Can we add a night in Osaka?", "Flight delayed, what now?", "Do I need a visa?", "Vegetarian meals please", "Thank you for a great trip"]),
    ],
))

B7.append(dict(
    num=67, slug="skyline", brand="Skyline", category="Airline Operations", org="Skyline Regional Air", currency="$",
    tagline="Flights, fleet, crew and delays for a regional airline.",
    auth_line="Every flight on time, every crew in place.", user="Ethan Novak", user_role="Operations controller",
    theme=dict(fonts=["Titillium Web", "Titillium Web", "Roboto Mono"], accent="#1e40af", layout="dark", card="border", radius="6px", sidebar="#0b1530",
               c2="#93c5fd", c3="#f59e0b", c4="#10b981"),
    kpis=[("Flights today", "int", 184, "globe"), ("On-time departures", "pct", 88.6, "clock"), ("Aircraft flying", "int", 26, "zap"), ("Passengers today", "int", 14200, "users")],
    chart=dict(title="Passengers", names=["This year", "Last year"], base=380000),
    mix=dict(title="Delay causes", parts=["Weather", "Late aircraft", "Crew", "Air traffic", "Technical"]),
    activity=["Flight SR 214 departed on time", "Aircraft SR-A06 back from maintenance", "Crew swap on SR 330", "Weather delay at Denver", "Extra flight added for Friday", "Gate change for SR 118"],
    entities=[
        dict(singular="Flight", plural="Flights", prefix="SR ", icon="globe", desc="Today's flights.",
             fields=[("Flight", "id"), ("Route", "words:DEN to SLC|SLC to BOI|DEN to ABQ|PHX to DEN|BOI to SEA|SEA to DEN"), ("Departs", "time"), ("Load", "pct:40-100"), ("Status", "status:On time|Boarding|Delayed|Cancelled")]),
        dict(singular="Aircraft", plural="Fleet", slug="fleet", prefix="SR-A", icon="zap", desc="Your aircraft.",
             fields=[("Aircraft", "id"), ("Type", "choice:Regional jet 76|Regional jet 90|Turboprop 70"), ("Hours today", "int:0-12"), ("Next check", "date:future"), ("Status", "status:Flying|On ground|Maintenance")]),
        dict(singular="Crew member", plural="Crew", slug="crew", prefix="", icon="users", desc="Pilots and cabin crew.",
             fields=[("Name", "person"), ("Role", "choice:Captain|First officer|Cabin crew"), ("Base", "choice:Denver|Salt Lake City|Phoenix|Seattle"), ("Hours this month", "int:20-90"), ("Status", "status:On duty|Rest|Standby")]),
        dict(singular="Route", plural="Routes", prefix="", icon="map", desc="Routes you fly.",
             fields=[("Route", "words:DEN to SLC|SLC to BOI|DEN to ABQ|PHX to DEN|BOI to SEA"), ("Flights a week", "int:7-42"), ("Average load", "pct:55-95"), ("Revenue", "money:40000-600000"), ("Status", "status:Active|Seasonal|Paused")]),
        dict(singular="Delay", plural="Delays", prefix="", icon="alert", desc="Delays and their causes.",
             fields=[("Flight", "code:SR "), ("Cause", "choice:Weather|Late aircraft|Crew|Air traffic|Technical"), ("Minutes", "int:15-240"), ("Date", "date"), ("Status", "status:Recovered|Ongoing|Cancelled")]),
    ],
    specials=[
        dict(title="Operations board", type="monitor", icon="monitor", desc="Live status of the network.", items=["Denver hub", "Salt Lake City", "Phoenix", "Seattle", "Boise", "Albuquerque", "Maintenance base", "Crew control"]),
        dict(title="Route map", type="map", icon="map", desc="Aircraft in the air right now.", items=["Denver", "Salt Lake City", "Phoenix", "Seattle", "Boise"], dots=24),
        dict(title="Crew roster", type="calendar", icon="calendar", desc="Crew duties this month.", items=["Early duty", "Late duty", "Standby", "Training", "Rest day"]),
        dict(title="Performance", type="report", icon="chart", desc="Punctuality, load and revenue.", items=["On-time rate", "Load factor", "Revenue per seat", "Cancellations"], rows=["DEN to SLC", "SLC to BOI", "DEN to ABQ", "PHX to DEN", "BOI to SEA"]),
        dict(title="Disruptions", type="kanban", icon="kanban", desc="Problems being handled right now.", items=["Reported", "Plan ready", "Passengers told", "Recovered"], cards=["Weather hold", "Crew timed out", "Aircraft swap", "Gate conflict"]),
        dict(title="Busiest routes", type="ranking", icon="trend", desc="Routes with the most passengers.", items=["DEN to SLC", "PHX to DEN", "SEA to DEN", "DEN to ABQ", "SLC to BOI", "BOI to SEA"], metric="Passengers", scale=300),
        dict(title="Day log", type="timeline", icon="clock", desc="What happened today.", items=["Snow at Denver, de-icing started", "SR 214 departed 12 minutes late", "Crew swap on SR 330", "All flights back on schedule"]),
    ],
))

B7.append(dict(
    num=68, slug="keyride", brand="Keyride", category="Car Rental", org="Keyride Car Hire", currency="$",
    tagline="Cars, bookings, branches and returns for a car rental company.",
    auth_line="The right car, ready when they land.", user="Nadia Walsh", user_role="Branch network manager",
    theme=dict(fonts=["Saira", "Saira", "Space Mono"], accent="#e11d48", layout="light", card="shadow", radius="10px",
               c2="#fda4af", c3="#0ea5e9", c4="#22c55e"),
    kpis=[("Cars out now", "int", 612, "truck"), ("Fleet use", "pct", 81.4, "pie"), ("Pickups today", "int", 148, "calendar"), ("Revenue this month", "money", 684000, "dollar")],
    chart=dict(title="Rental days", names=["This year", "Last year"], base=14000),
    mix=dict(title="Fleet by class", parts=["Economy", "Compact", "SUV", "Electric", "Van"]),
    activity=["Car KR-221 returned with a scratch", "Airport branch low on SUVs", "Booking upgraded to electric", "Car moved from Downtown to Airport", "Service done on 12 cars", "Damage claim sent to customer"],
    entities=[
        dict(singular="Booking", plural="Bookings", prefix="RB-", icon="calendar", desc="Rentals booked and running.",
             fields=[("Booking", "id"), ("Customer", "person"), ("Class", "choice:Economy|Compact|SUV|Electric|Van"), ("Pickup", "date:future"), ("Status", "status:Booked|On rent|Returned|Cancelled")]),
        dict(singular="Car", plural="Fleet", slug="fleet", prefix="KR-", icon="truck", desc="Every car you rent out.",
             fields=[("Car", "id"), ("Model", "words:City hatchback|Family SUV|Electric saloon|Compact estate|Cargo van"), ("Mileage", "int:2000-80000"), ("Branch", "choice:Airport|Downtown|Station|Harbour"), ("Status", "status:Available|On rent|Cleaning|Repair")]),
        dict(singular="Branch", plural="Branches", prefix="", icon="building", desc="Pickup and return locations.",
             fields=[("Branch", "words:Airport|Downtown|Station|Harbour|University"), ("Cars", "int:20-240"), ("Pickups today", "int:4-80"), ("Rating", "rating"), ("Status", "status:Open|Busy|Closed")]),
        dict(singular="Customer", plural="Customers", prefix="", icon="users", desc="Drivers and their rentals.",
             fields=[("Customer", "person"), ("Rentals", "int:1-24"), ("Licence checked", "choice:Yes|No"), ("Spent", "money:80-9000"), ("Status", "status:Active|Blocked|New")]),
        dict(singular="Damage report", plural="Damage reports", slug="damage-reports", prefix="DR-", icon="alert", desc="Damage found on return.",
             fields=[("Report", "id"), ("Car", "code:KR-"), ("Damage", "choice:Scratch|Dent|Chipped glass|Interior stain|Tyre damage"), ("Cost", "money:60-2400"), ("Status", "status:Open|Charged|Waived")]),
    ],
    specials=[
        dict(title="Fleet map", type="map", icon="map", desc="Cars at each branch right now.", items=["Airport", "Downtown", "Station", "Harbour", "University"]),
        dict(title="Pickups and returns", type="calendar", icon="calendar", desc="Handovers booked this month.", items=["Pickup", "Return", "One way drop", "Delivery to hotel", "Service"]),
        dict(title="Car prep board", type="kanban", icon="kanban", desc="Cars from return to ready.", items=["Returned", "Inspecting", "Cleaning", "Charging", "Ready"], cards=["City hatchback", "Family SUV", "Electric saloon", "Cargo van"]),
        dict(title="Rental report", type="report", icon="chart", desc="Use, revenue and damage.", items=["Fleet use", "Revenue per car", "Average rental days", "Damage cost"], rows=["Economy", "Compact", "SUV", "Electric", "Van"]),
        dict(title="Rental agreement", type="document", icon="file", desc="A printable rental agreement.", doc="Rental agreement", num="RB-1047", items=["Family SUV, 5 days", "Full insurance", "Child seat", "Extra driver"], note="Return with a full tank. Late returns are charged by the hour."),
        dict(title="Charging status", type="monitor", icon="zap", desc="Electric cars on charge.", items=["KR-301", "KR-304", "KR-309", "KR-312", "KR-318", "KR-322"], unit="%"),
        dict(title="Rental rules", type="config", icon="settings", desc="Policies for every branch.", items=["Check the licence before every rental", "Take photos at pickup and return", "Charge a fee for late returns", "Block drivers with unpaid damage"]),
    ],
))

B7.append(dict(
    num=69, slug="glowbook", brand="Glowbook", category="Salon Booking", org="Glow Hair and Beauty", currency="$",
    tagline="Appointments, clients, stylists and products for a hair and beauty salon.",
    auth_line="A full diary and happy clients.", user="Zoe Rahman", user_role="Salon owner",
    theme=dict(fonts=["Italiana", "Raleway", "DM Mono", "Raleway"], accent="#be185d", layout="light", card="flat", radius="18px",
               bg="#fdf8f9", surface2="#f8edf1", line="#f0dfe6", c2="#f9a8d4", c3="#a16207", c4="#7c3aed"),
    kpis=[("Appointments today", "int", 46, "calendar"), ("Chairs booked", "pct", 88.0, "pie"), ("Takings this week", "money", 9840, "dollar"), ("Rebooking rate", "pct", 64.0, "heart")],
    chart=dict(title="Takings", names=["This year", "Last year"], base=36000),
    mix=dict(title="Services", parts=["Cut and style", "Colour", "Nails", "Brows and lashes", "Treatments"]),
    activity=["Balayage booked with Mia for Saturday", "New client: Hana Silva", "Product sold: repair mask", "Stylist Lena running 10 minutes late", "Gift card bought for $80", "Review: 5 stars for Mia"],
    entities=[
        dict(singular="Appointment", plural="Appointments", prefix="", icon="calendar", desc="Today's and upcoming appointments.",
             fields=[("Client", "person"), ("Service", "choice:Cut and style|Colour|Balayage|Gel nails|Brow shape"), ("Stylist", "person"), ("Time", "time"), ("Status", "status:Confirmed|Booked|Checked in|No show")]),
        dict(singular="Client", plural="Clients", prefix="", icon="users", desc="People who visit the salon.",
             fields=[("Client", "person"), ("Visits", "int:1-40"), ("Last visit", "date"), ("Spent", "money:40-4000"), ("Status", "status:Regular|New|Lapsed")]),
        dict(singular="Stylist", plural="Team", slug="stylists", prefix="", icon="user", desc="Stylists and therapists.",
             fields=[("Stylist", "person"), ("Skills", "choice:Colour|Cutting|Nails|Brows|Treatments"), ("Booked today", "pct:40-100"), ("Rating", "rating"), ("Status", "status:Working|Break|Day off")]),
        dict(singular="Service", plural="Services", prefix="", icon="list", desc="Your service menu.",
             fields=[("Service", "words:Cut and style|Full colour|Balayage|Gel nails|Brow shape|Lash lift"), ("Time", "duration"), ("Price", "money:20-220"), ("Booked this month", "int:4-160"), ("Status", "status:Available|Paused")]),
        dict(singular="Product", plural="Retail", slug="retail", prefix="", icon="box", desc="Products you sell.",
             fields=[("Product", "words:Repair mask|Shine serum|Colour shampoo|Heat spray|Nail oil"), ("In stock", "int:0-60"), ("Price", "money:12-48"), ("Sold this month", "int:0-80"), ("Status", "status:In stock|Low|Out of stock")]),
    ],
    specials=[
        dict(title="Diary", type="calendar", icon="calendar", desc="Every chair, every day.", items=["Cut and style", "Colour", "Balayage", "Nails", "Brows"]),
        dict(title="Stylist ranking", type="ranking", icon="star", desc="Takings by stylist this month.", items=["Mia Chen", "Lena Rossi", "Kavya Adams", "Sofia Diaz", "Grace Kim"], metric="Takings", scale=90),
        dict(title="Salon report", type="report", icon="chart", desc="Takings, rebooking and retail.", items=["Takings", "Rebooking rate", "Retail sales", "Average ticket"], rows=["Cut and style", "Colour", "Nails", "Brows and lashes", "Treatments"]),
        dict(title="Waitlist", type="kanban", icon="kanban", desc="Clients waiting for a slot.", items=["Waiting", "Offered a slot", "Booked"], cards=["Balayage", "Cut and style", "Gel nails", "Lash lift"]),
        dict(title="Look book", type="gallery", icon="grid", desc="Photos of recent work.", items=["Soft balayage", "Copper colour", "Short bob", "Bridal updo", "Nail art", "Brow lamination"]),
        dict(title="Client messages", type="split", icon="message", desc="Booking requests and questions.", items=["Can I book with Mia on Friday?", "Running 10 minutes late", "Price for a full colour?", "Can I bring my daughter?", "Love my new hair!"]),
        dict(title="Booking rules", type="config", icon="settings", desc="Settings for online booking.", items=["Take a deposit for colour services", "Charge for no-shows", "Text reminders 24 hours before", "Allow online booking up to 6 weeks ahead"]),
    ],
))

B7.append(dict(
    num=70, slug="deskhub", brand="Deskhub", category="Coworking Space", org="Commons Coworking", currency="$",
    tagline="Members, desks, rooms and billing for a coworking space.",
    auth_line="A workspace that runs itself.", user="Ben Okafor", user_role="Community manager",
    theme=dict(fonts=["Kumbh Sans", "Kumbh Sans", "JetBrains Mono"], accent="#0f766e", layout="accent", card="border", radius="12px",
               c2="#5eead4", c3="#f59e0b", c4="#8b5cf6"),
    kpis=[("Members", "int", 342, "users"), ("Desks in use", "pct", 78.4, "grid"), ("Room bookings today", "int", 36, "calendar"), ("Monthly revenue", "money", 96400, "dollar")],
    chart=dict(title="Daily visitors", names=["Visitors", "Last month"], base=210),
    mix=dict(title="Members by plan", parts=["Hot desk", "Fixed desk", "Private office", "Day pass", "Virtual office"]),
    activity=["Meeting room 3 booked for 2 hours", "New member: Oak Studio team of 4", "Coffee machine fixed", "Invoice run finished", "Community lunch on Friday", "Private office 7 is free from next month"],
    entities=[
        dict(singular="Member", plural="Members", prefix="", icon="users", desc="People and teams in the space.",
             fields=[("Member", "person"), ("Company", "company"), ("Plan", "choice:Hot desk|Fixed desk|Private office|Day pass"), ("Since", "date"), ("Status", "status:Active|Paused|Leaving")]),
        dict(singular="Desk", plural="Desks", prefix="D-", icon="grid", desc="Desks on every floor.",
             fields=[("Desk", "id"), ("Floor", "choice:Ground|First|Second"), ("Type", "choice:Hot desk|Fixed desk|Standing desk"), ("Assigned to", "person"), ("Status", "status:Taken|Free|Reserved")]),
        dict(singular="Room booking", plural="Room bookings", slug="room-bookings", prefix="", icon="calendar", desc="Meeting rooms booked.",
             fields=[("Room", "words:Room 1, Oak|Room 2, Cedar|Room 3, Maple|Phone booth A|Event space"), ("Booked by", "person"), ("Date", "date:future"), ("Time", "time"), ("Status", "status:Confirmed|Pending|Cancelled")]),
        dict(singular="Invoice", plural="Invoices", prefix="INV-", icon="receipt", desc="Member bills.",
             fields=[("Invoice", "id"), ("Member", "company"), ("Plan", "choice:Hot desk|Fixed desk|Private office"), ("Amount", "money:150-4800"), ("Status", "status:Paid|Due|Overdue")]),
        dict(singular="Visitor", plural="Visitors", prefix="", icon="user", desc="Guests signed in today.",
             fields=[("Visitor", "person"), ("Host", "person"), ("Arrived", "time"), ("Purpose", "choice:Meeting|Interview|Tour|Delivery"), ("Status", "status:Signed in|Left|Expected")]),
    ],
    specials=[
        dict(title="Floor plan", type="map", icon="map", desc="Desks and rooms in use right now.", items=["Ground floor", "First floor", "Second floor", "Meeting rooms", "Kitchen"], dots=18),
        dict(title="Room calendar", type="calendar", icon="calendar", desc="Meeting rooms and events.", items=["Room 1 booking", "Room 2 booking", "Workshop", "Community lunch", "Event space"]),
        dict(title="Occupancy now", type="monitor", icon="activity", desc="How busy each area is.", items=["Hot desks", "Fixed desks", "Private offices", "Meeting rooms", "Phone booths", "Kitchen"], unit="%"),
        dict(title="Membership report", type="report", icon="chart", desc="Members, revenue and use.", items=["Revenue", "New members", "Desk use", "Churn"], rows=["Hot desk", "Fixed desk", "Private office", "Day pass", "Virtual office"]),
        dict(title="Tour pipeline", type="kanban", icon="kanban", desc="Leads from tour to member.", items=["Enquiry", "Tour booked", "Trial day", "Joined", "Lost"], cards=["Team of 4", "Freelancer", "Startup team", "Remote worker"]),
        dict(title="Community board", type="timeline", icon="bell", desc="News for members.", items=["Community lunch on Friday", "New phone booths on the first floor", "Printer upgraded", "Welcome to Oak Studio"]),
        dict(title="Space rules", type="config", icon="settings", desc="How the space runs.", items=["Hot desk members can book rooms for 2 hours a day", "Let members in 24 hours a day", "Charge for room no-shows", "Send guests a welcome text"]),
    ],
))

B7.append(dict(
    num=71, slug="inkwell", brand="Inkwell", category="Blog CMS", org="The Field Notes Journal", currency="$",
    tagline="Posts, authors, comments and traffic for a blog or online magazine.",
    auth_line="Write, publish and grow your readers.", user="Julia Hughes", user_role="Editor",
    theme=dict(fonts=["Newsreader", "Inter", "IBM Plex Mono", "Inter"], accent="#b91c1c", layout="light", card="border", radius="6px",
               bg="#fcfbf9", surface2="#f5f3ef", line="#e8e4dc", c2="#fca5a5", c3="#1e3a8a", c4="#15803d"),
    kpis=[("Page views this month", "int", 842000, "users"), ("Posts published", "int", 38, "file"), ("Newsletter readers", "int", 24800, "inbox"), ("Comments", "int", 1240, "message")],
    chart=dict(title="Page views", names=["This year", "Last year"], base=720000),
    mix=dict(title="Traffic sources", parts=["Search", "Newsletter", "Social", "Direct", "Other"]),
    activity=["Post published: A slow week in the hills", "Draft sent for review by Kenji", "12 comments waiting for approval", "Newsletter sent to 24,800 readers", "New author invited", "Post updated: Best winter walks"],
    entities=[
        dict(singular="Post", plural="Posts", prefix="", icon="file", desc="Articles on your site.",
             fields=[("Post", "words:A slow week in the hills|Best winter walks|How to pack light|The quiet coast|Notes from a night train|Ten small towns worth a visit"), ("Author", "person"), ("Published", "date"), ("Views", "int:800-80000"), ("Status", "status:Published|Draft|In review|Scheduled")]),
        dict(singular="Author", plural="Authors", prefix="", icon="user", desc="Writers and editors.",
             fields=[("Author", "person"), ("Role", "choice:Editor|Staff writer|Contributor"), ("Posts", "int:2-120"), ("Views this month", "int:1000-200000"), ("Status", "status:Active|Invited|Inactive")]),
        dict(singular="Comment", plural="Comments", prefix="", icon="message", desc="Reader comments.",
             fields=[("Reader", "person"), ("Post", "words:A slow week in the hills|Best winter walks|How to pack light|The quiet coast"), ("Comment", "words:Lovely piece|I did this walk last year|Great tips, thanks|Where was the photo taken?|Beautiful writing"), ("Date", "date"), ("Status", "status:Approved|Pending|Spam")]),
        dict(singular="Category", plural="Categories", slug="categories", prefix="", icon="tag", desc="Sections of the magazine.",
             fields=[("Category", "words:Walks|Travel|Food|Gear|Essays|Guides"), ("Posts", "int:4-120"), ("Views", "int:2000-300000"), ("Updated", "date"), ("Status", "status:Visible|Hidden")]),
        dict(singular="Media", plural="Media library", slug="media-library", prefix="", icon="folder", desc="Photos and files.",
             fields=[("File", "words:hills-sunrise.jpg|coast-path.jpg|night-train.jpg|packing-list.pdf|town-square.jpg"), ("Type", "choice:Photo|PDF|Video"), ("Uploaded", "date"), ("Used in", "int:0-12"), ("Status", "status:In use|Unused")]),
    ],
    specials=[
        dict(title="Editorial board", type="kanban", icon="kanban", desc="Stories from pitch to published.", items=["Pitch", "Writing", "Editing", "Scheduled", "Published"], cards=["Winter walks guide", "Night train essay", "Coast photo story", "Gear review"]),
        dict(title="Editorial calendar", type="calendar", icon="calendar", desc="What goes out and when.", items=["Essay", "Guide", "Photo story", "Newsletter", "Interview"]),
        dict(title="Traffic report", type="report", icon="chart", desc="Views, readers and sources.", items=["Page views", "Readers", "Time on page", "Newsletter signups"], rows=["Walks", "Travel", "Food", "Gear", "Essays"]),
        dict(title="Top posts", type="ranking", icon="trend", desc="The most read posts this month.", items=["Best winter walks", "How to pack light", "Ten small towns worth a visit", "A slow week in the hills", "The quiet coast", "Notes from a night train"], metric="Views", scale=800),
        dict(title="Post preview", type="document", icon="file", desc="How a post looks before publishing.", doc="A slow week in the hills", num="By Julia Hughes, 8 minute read", items=["Opening photo", "Main text", "Map of the route", "Packing list"], note="Preview only. The table shows the costs of the trip described in the post."),
        dict(title="Comment queue", type="split", icon="inbox", desc="Approve or remove reader comments.", items=["Lovely piece, thank you", "I did this walk last year", "Where was the photo taken?", "Check out my website", "Great tips for packing"]),
        dict(title="Publishing settings", type="config", icon="settings", desc="How posts go live.", items=["Require an editor review before publishing", "Hold comments with links for approval", "Send new posts to newsletter readers", "Add an author box to every post"]),
    ],
))

B7.append(dict(
    num=72, slug="airwave", brand="Airwave", category="Podcast Analytics", org="The Long Table Podcast", currency="$",
    tagline="Downloads, listeners, episodes and sponsors for a podcast.",
    auth_line="Know who is listening, and why.", user="Rohan Silva", user_role="Host and producer",
    theme=dict(fonts=["Lexend Deca", "Lexend Deca", "Fira Code"], accent="#9333ea", layout="dark", card="shadow", radius="14px", sidebar="#140a1f",
               c2="#d8b4fe", c3="#f59e0b", c4="#22d3ee"),
    kpis=[("Downloads this month", "int", 184000, "download"), ("Listeners", "int", 42800, "users"), ("Average listen", "pct", 68.0, "clock"), ("Sponsor revenue", "money", 12400, "dollar")],
    chart=dict(title="Downloads", names=["Downloads", "Last year"], base=160000),
    mix=dict(title="Listening apps", parts=["Apple Podcasts", "Spotify", "YouTube", "Web player", "Other"]),
    activity=["Episode 142 published", "Sponsor slot sold for October", "Downloads passed 3 million", "Guest booked for next week", "Transcript uploaded for episode 141", "Review: 5 stars on Apple Podcasts"],
    entities=[
        dict(singular="Episode", plural="Episodes", prefix="Ep. ", icon="activity", desc="Every episode and how it did.",
             fields=[("Episode", "id"), ("Title", "words:Cooking with grandma|The last bakery in town|Street food stories|A chef's first job|Why we eat together"), ("Published", "date"), ("Downloads", "int:2000-40000"), ("Status", "status:Published|Scheduled|Editing")]),
        dict(singular="Guest", plural="Guests", prefix="", icon="user", desc="People who came on the show.",
             fields=[("Guest", "person"), ("Episode", "code:Ep. "), ("Topic", "choice:Chefs|Farmers|Food writers|Bakers"), ("Recorded", "date"), ("Status", "status:Published|Booked|Recorded")]),
        dict(singular="Sponsor", plural="Sponsors", prefix="", icon="briefcase", desc="Brands that pay for ad slots.",
             fields=[("Sponsor", "company"), ("Slots", "int:1-12"), ("Rate per slot", "money:200-1800"), ("Ends", "date:future"), ("Status", "status:Active|Proposal|Ended")]),
        dict(singular="Review", plural="Reviews", prefix="", icon="star", desc="Listener reviews.",
             fields=[("Listener", "person"), ("App", "choice:Apple Podcasts|Spotify|YouTube"), ("Rating", "rating"), ("Date", "date"), ("Status", "status:New|Read")]),
        dict(singular="Country", plural="Countries", slug="countries", prefix="", icon="globe", desc="Where listeners are.",
             fields=[("Country", "choice:United States|United Kingdom|Canada|Australia|Germany|India"), ("Downloads", "int:2000-90000"), ("Growth", "pct:1-30"), ("Top app", "choice:Apple Podcasts|Spotify"), ("Status", "status:Growing|Stable")]),
    ],
    specials=[
        dict(title="Episode performance", type="report", icon="chart", desc="How each episode did in its first 30 days.", items=["Downloads", "Average listen", "New listeners", "Shares"], rows=["Ep. 142", "Ep. 141", "Ep. 140", "Ep. 139", "Ep. 138"]),
        dict(title="Top episodes", type="ranking", icon="star", desc="The most downloaded episodes of all time.", items=["Why we eat together", "The last bakery in town", "Cooking with grandma", "Street food stories", "A chef's first job", "Soup season"], metric="Downloads", scale=900),
        dict(title="Listener map", type="map", icon="globe", desc="Where people listen from.", items=["United States", "United Kingdom", "Canada", "Australia", "Germany"]),
        dict(title="Production board", type="kanban", icon="kanban", desc="Episodes from idea to published.", items=["Ideas", "Guest booked", "Recorded", "Editing", "Published"], cards=["Farmers market episode", "Baker interview", "Food writer chat", "Holiday special"]),
        dict(title="Release schedule", type="calendar", icon="calendar", desc="Recording and release days.", items=["Recording", "Release day", "Sponsor read", "Guest call", "Edit session"]),
        dict(title="Sponsor report", type="document", icon="file", desc="A report to send a sponsor.", doc="Sponsor report", num="September 2026", items=["Episode 139 mid-roll", "Episode 140 mid-roll", "Episode 141 pre-roll", "Episode 142 mid-roll"], note="Downloads are counted in the first 30 days after release."),
        dict(title="Listener messages", type="split", icon="message", desc="Emails from listeners.", items=["Loved the bakery episode", "Guest suggestion", "Can you do a vegan episode?", "Audio was quiet on Ep. 140", "Sponsor question"]),
    ],
))

B7.append(dict(
    num=73, slug="reelhouse", brand="Reelhouse", category="Video Creator Studio", org="Maker Mia Channel", currency="$",
    tagline="Videos, views, income and ideas for a video creator.",
    auth_line="Make videos. Grow your channel.", user="Mia Tanaka", user_role="Creator",
    theme=dict(fonts=["Rethink Sans", "Rethink Sans", "JetBrains Mono"], accent="#dc2626", layout="dark", card="border", radius="10px", sidebar="#121212",
               c2="#fca5a5", c3="#f59e0b", c4="#3b82f6"),
    kpis=[("Views this month", "int", 2840000, "activity"), ("Subscribers", "int", 486000, "users"), ("Watch time hours", "int", 142000, "clock"), ("Income this month", "money", 18400, "dollar")],
    chart=dict(title="Views", names=["Views", "Last year"], base=2400000),
    mix=dict(title="Traffic sources", parts=["Recommended", "Search", "Shorts feed", "External", "Other"]),
    activity=["Video published: Building a tiny desk", "Short passed 1 million views", "Brand deal signed with Cedar Tools", "Comment pinned on latest video", "Thumbnail test finished", "Membership tier added"],
    entities=[
        dict(singular="Video", plural="Videos", prefix="", icon="monitor", desc="Everything you uploaded.",
             fields=[("Video", "words:Building a tiny desk|Room makeover in 48 hours|My desk setup 2026|Fixing a thrift store chair|DIY shelves for 20 dollars"), ("Published", "date"), ("Views", "int:20000-900000"), ("Watch time", "pct:30-70"), ("Status", "status:Public|Scheduled|Draft")]),
        dict(singular="Short", plural="Shorts", prefix="", icon="zap", desc="Short vertical videos.",
             fields=[("Short", "words:30 second desk tidy|One tool I love|Before and after|Paint hack|Quick shelf"), ("Published", "date"), ("Views", "int:10000-2000000"), ("Likes", "int:500-90000"), ("Status", "status:Public|Scheduled")]),
        dict(singular="Brand deal", plural="Brand deals", slug="brand-deals", prefix="", icon="briefcase", desc="Sponsors and partnerships.",
             fields=[("Brand", "company"), ("Deliverable", "choice:Dedicated video|Mention|Short|Series"), ("Fee", "money:800-24000"), ("Due", "date:future"), ("Status", "status:Signed|Negotiating|Delivered")]),
        dict(singular="Comment", plural="Comments", prefix="", icon="message", desc="Comments on your videos.",
             fields=[("Viewer", "person"), ("Video", "words:Building a tiny desk|Room makeover|My desk setup 2026"), ("Comment", "words:Where is the lamp from?|This inspired me|Please do a part two|Love the music|What wood is that?"), ("Date", "date"), ("Status", "status:New|Replied|Hidden")]),
        dict(singular="Payout", plural="Income", slug="income", prefix="", icon="dollar", desc="Money from ads, members and deals.",
             fields=[("Source", "words:Ad revenue|Memberships|Brand deal|Affiliate links|Merch"), ("Month", "words:September|August|July|June"), ("Amount", "money:200-12000"), ("Paid", "date"), ("Status", "status:Paid|Pending")]),
    ],
    specials=[
        dict(title="Content pipeline", type="kanban", icon="kanban", desc="Videos from idea to upload.", items=["Ideas", "Scripting", "Filming", "Editing", "Published"], cards=["Garage workshop tour", "Budget office makeover", "Tool review", "Desk setup short"]),
        dict(title="Channel analytics", type="report", icon="chart", desc="Views, watch time and income.", items=["Views", "Watch time", "Click rate", "Income"], rows=["Recommended", "Search", "Shorts feed", "External", "Playlists"]),
        dict(title="Top videos", type="ranking", icon="star", desc="Videos with the most views this year.", items=["Room makeover in 48 hours", "Building a tiny desk", "DIY shelves for 20 dollars", "My desk setup 2026", "Fixing a thrift store chair"], metric="Views", scale=9000),
        dict(title="Upload calendar", type="calendar", icon="calendar", desc="Planned uploads and shoots.", items=["Long video", "Short", "Filming day", "Brand deadline", "Live stream"]),
        dict(title="Thumbnails", type="gallery", icon="grid", desc="Thumbnail options being tested.", items=["Tiny desk A", "Tiny desk B", "Makeover A", "Makeover B", "Shelves A", "Chair fix A"]),
        dict(title="Live now", type="monitor", icon="activity", desc="Real-time views on recent uploads.", items=["Building a tiny desk", "30 second desk tidy", "Room makeover", "Paint hack", "One tool I love", "DIY shelves"], unit=" views/min"),
        dict(title="Channel settings", type="config", icon="settings", desc="Defaults for every upload.", items=["Add chapters automatically", "Hold comments with links", "Post uploads to the community tab", "Add end screens to long videos"]),
    ],
))

B7.append(dict(
    num=74, slug="encore", brand="Encore", category="Music Artist", org="Lena Rae, independent artist", currency="$",
    tagline="Streams, fans, tours and releases for an independent musician.",
    auth_line="Your music, your fans, your numbers.", user="Lena Rae", user_role="Artist",
    theme=dict(fonts=["Abril Fatface", "Nunito Sans", "Roboto Mono", "Nunito Sans"], accent="#f59e0b", on_accent="#1c1917", layout="accent", card="shadow", radius="12px",
               c2="#fcd34d", c3="#e11d48", c4="#8b5cf6"),
    kpis=[("Streams this month", "int", 1240000, "activity"), ("Monthly listeners", "int", 186000, "users"), ("Tickets sold", "int", 4820, "tag"), ("Income this month", "money", 14200, "dollar")],
    chart=dict(title="Streams", names=["Streams", "Last year"], base=1100000),
    mix=dict(title="Streams by platform", parts=["Spotify", "Apple Music", "YouTube", "Bandcamp", "Other"]),
    activity=["New single out: Summer Static", "Berlin show sold out", "Song added to a big playlist", "Vinyl pre-orders passed 800", "Tour poster approved", "Fan mail from Brazil"],
    entities=[
        dict(singular="Release", plural="Releases", prefix="", icon="star", desc="Singles, EPs and albums.",
             fields=[("Release", "words:Summer Static|Paper Moon EP|Night Bus|Harbour Lights|Slow Motion"), ("Type", "choice:Single|EP|Album"), ("Released", "date"), ("Streams", "int:20000-2000000"), ("Status", "status:Out now|Pre-save|In production")]),
        dict(singular="Track", plural="Tracks", prefix="", icon="list", desc="Every song and how it streams.",
             fields=[("Track", "words:Summer Static|Paper Moon|Night Bus|Harbour Lights|Slow Motion|Glass House"), ("Streams", "int:10000-900000"), ("Saves", "int:500-60000"), ("Playlists", "int:4-800"), ("Trend", "status:Up|Flat|Down")]),
        dict(singular="Show", plural="Shows", prefix="", icon="calendar", desc="Tour dates and ticket sales.",
             fields=[("City", "city"), ("Venue", "words:The Roundhouse|Club Luna|Harbour Hall|The Loft|Arena Nord"), ("Date", "date:future"), ("Sold", "pct:30-100"), ("Status", "status:On sale|Sold out|Announced")]),
        dict(singular="Fan", plural="Fans", prefix="", icon="users", desc="Your mailing list and top fans.",
             fields=[("Fan", "person"), ("Country", "choice:United States|United Kingdom|Germany|Brazil|Japan"), ("Joined", "date"), ("Spent", "money:0-400"), ("Status", "status:Subscribed|Top fan|Unsubscribed")]),
        dict(singular="Merch item", plural="Merch", slug="merch", prefix="", icon="box", desc="Things fans can buy.",
             fields=[("Item", "words:Tour t-shirt|Vinyl, Paper Moon|Tote bag|Signed poster|Hoodie"), ("In stock", "int:0-400"), ("Price", "money:12-60"), ("Sold", "int:0-900"), ("Status", "status:In stock|Low|Sold out")]),
    ],
    specials=[
        dict(title="Tour calendar", type="calendar", icon="calendar", desc="Shows, rehearsals and travel.", items=["Show", "Rehearsal", "Travel day", "Radio interview", "Studio day"]),
        dict(title="Fans by city", type="map", icon="globe", desc="Where your listeners are.", items=["Berlin", "London", "Sao Paulo", "Tokyo", "New York"]),
        dict(title="Top tracks", type="ranking", icon="star", desc="Songs with the most streams.", items=["Summer Static", "Night Bus", "Paper Moon", "Harbour Lights", "Glass House", "Slow Motion"], metric="Streams", scale=9000),
        dict(title="Release plan", type="kanban", icon="kanban", desc="Next release, step by step.", items=["Writing", "Recording", "Mixing", "Artwork", "Release"], cards=["New single", "Music video", "Vinyl pressing", "Press photos"]),
        dict(title="Income report", type="report", icon="chart", desc="Money from streams, shows and merch.", items=["Streaming", "Live shows", "Merch", "Sync licences"], rows=["Spotify", "Apple Music", "YouTube", "Bandcamp", "Shows"]),
        dict(title="Show settlement", type="document", icon="receipt", desc="Money from one show, explained.", doc="Show settlement", num="Berlin, Club Luna", items=["Ticket sales", "Merch sales", "Venue fee", "Sound engineer", "Travel"], note="Settlement agreed with the promoter on the night of the show."),
        dict(title="Fan messages", type="split", icon="message", desc="Messages from fans.", items=["Please come to Lisbon!", "Your song got me through a hard year", "When is the vinyl shipping?", "Can I use your song in my video?", "See you in Berlin"]),
    ],
))

B7.append(dict(
    num=75, slug="aperture", brand="Aperture", category="Photography Studio", org="Aperture Studio", currency="$",
    tagline="Shoots, clients, galleries and invoices for a photography studio.",
    auth_line="Book the shoot. Deliver the gallery.", user="Hugo Larsen", user_role="Photographer and owner",
    theme=dict(fonts=["Tenor Sans", "Inter", "DM Mono", "Inter"], accent="#1c1917", d_accent="#e7e5e4", d_on_accent="#1c1917", layout="light", card="flat", radius="2px",
               bg="#fafaf9", surface2="#f5f5f4", line="#e7e5e4", c2="#a8a29e", c3="#b45309", c4="#0f766e"),
    kpis=[("Shoots this month", "int", 24, "calendar"), ("Galleries delivered", "int", 18, "grid"), ("Bookings value", "money", 32400, "dollar"), ("Client rating", "rating", 4.9, "star")],
    chart=dict(title="Bookings value", names=["This year", "Last year"], base=26000),
    mix=dict(title="Shoots by type", parts=["Weddings", "Portraits", "Brands", "Events", "Products"]),
    activity=["Gallery delivered to the Chen wedding", "Deposit paid for a June wedding", "Product shoot booked for Oak Studio", "Contract signed", "Photos picked for print by client", "Review: 5 stars on Google"],
    entities=[
        dict(singular="Shoot", plural="Shoots", prefix="", icon="calendar", desc="Booked and past shoots.",
             fields=[("Shoot", "words:Chen wedding|Family portraits|Oak Studio products|Summit Labs team headshots|Harbor gala|Engagement session"), ("Client", "person"), ("Date", "date:future"), ("Fee", "money:300-6000"), ("Status", "status:Booked|Deposit paid|Shot|Delivered")]),
        dict(singular="Client", plural="Clients", prefix="", icon="users", desc="People and brands you shoot for.",
             fields=[("Client", "person"), ("Type", "choice:Couple|Family|Brand|Event"), ("Shoots", "int:1-8"), ("Spent", "money:300-18000"), ("Status", "status:Active|Enquiry|Past")]),
        dict(singular="Gallery", plural="Galleries", prefix="", icon="grid", desc="Online photo galleries for clients.",
             fields=[("Gallery", "words:Chen wedding|Family portraits|Oak products|Team headshots|Harbor gala"), ("Photos", "int:40-900"), ("Views", "int:10-2000"), ("Delivered", "date"), ("Status", "status:Delivered|Editing|Expired")]),
        dict(singular="Invoice", plural="Invoices", prefix="INV-", icon="receipt", desc="Deposits and final payments.",
             fields=[("Invoice", "id"), ("Client", "person"), ("For", "choice:Deposit|Final payment|Prints|Album"), ("Amount", "money:100-5000"), ("Status", "status:Paid|Due|Overdue")]),
        dict(singular="Contract", plural="Contracts", prefix="CT-", icon="file", desc="Signed agreements.",
             fields=[("Contract", "id"), ("Client", "person"), ("Shoot", "words:Wedding|Portraits|Brand shoot|Event"), ("Sent", "date"), ("Status", "status:Signed|Sent|Draft")]),
    ],
    specials=[
        dict(title="Shoot calendar", type="calendar", icon="calendar", desc="Shoots and editing days.", items=["Wedding", "Portrait session", "Brand shoot", "Editing day", "Client meeting"]),
        dict(title="Client galleries", type="gallery", icon="grid", desc="Recent galleries you delivered.", items=["Chen wedding", "Family portraits", "Oak products", "Team headshots", "Harbor gala", "Engagement session"]),
        dict(title="Booking pipeline", type="kanban", icon="kanban", desc="From enquiry to delivered gallery.", items=["Enquiry", "Contract sent", "Booked", "Editing", "Delivered"], cards=["Wedding", "Family portraits", "Brand shoot", "Event"], money=True),
        dict(title="Studio report", type="report", icon="chart", desc="Bookings, income and delivery times.", items=["Income", "Shoots", "Days to deliver", "Print sales"], rows=["Weddings", "Portraits", "Brands", "Events", "Products"]),
        dict(title="Wedding quote", type="document", icon="file", desc="A printable quote for a couple.", doc="Wedding photography quote", num="June 2027", items=["Full day coverage", "Second photographer", "Engagement session", "Printed album"], note="A 30 percent deposit holds the date. The rest is due 2 weeks before the wedding."),
        dict(title="Client messages", type="split", icon="message", desc="Enquiries and client questions.", items=["Are you free on 14 June?", "Can we add an hour?", "When will the gallery be ready?", "Print sizes question", "Thank you, the photos are perfect"]),
        dict(title="Studio settings", type="config", icon="settings", desc="How your studio runs.", items=["Take a 30 percent deposit to book", "Send galleries within 4 weeks", "Expire galleries after 90 days", "Ask for a review when a gallery is delivered"]),
    ],
))
