"""Batch 4: Tech and developer dashboards (numbers 36 to 45)."""

B4 = []

B4.append(dict(
    num=36, slug="uptimer", brand="Uptimer", category="Server Monitoring", org="Northstack Cloud", currency="$",
    tagline="Servers, uptime, alerts and incidents for an operations team.",
    auth_line="Know about problems before your users do.", user="Omar Jensen", user_role="Site reliability engineer",
    theme=dict(fonts=["Geist", "Geist", "Geist Mono"], accent="#16a34a", layout="dark", card="border", radius="8px", sidebar="#09090b",
               c2="#86efac", c3="#f59e0b", c4="#3b82f6"),
    kpis=[("Uptime this month", "pct", 99.2, "check"), ("Servers online", "int", 184, "monitor"), ("Open incidents", "int", 3, "alert"), ("Avg response ms", "int", 142, "clock")],
    chart=dict(title="Requests per minute", names=["Requests", "Errors x100"], base=48000),
    mix=dict(title="Servers by region", parts=["US East", "US West", "Europe", "Asia", "Other"]),
    activity=["Incident resolved: API latency", "Disk alert on db-04 cleared", "Deploy 2.14.0 finished", "New server added: web-22", "On-call handed to Maya", "Status page updated"],
    entities=[
        dict(singular="Server", plural="Servers", prefix="", icon="monitor", desc="Every machine you watch.",
             fields=[("Server", "words:web-01|web-07|api-03|db-04|cache-02|worker-11|queue-01"), ("Region", "choice:US East|US West|Europe|Asia"), ("CPU", "pct:4-96"), ("Memory", "pct:20-94"), ("Status", "status:Healthy|Warning|Down")]),
        dict(singular="Incident", plural="Incidents", prefix="INC-", icon="alert", desc="Outages and slowdowns.",
             fields=[("Incident", "id"), ("Title", "words:API latency high|Login errors|Database failover|Disk nearly full|Certificate expiring"), ("Started", "date"), ("Duration", "duration"), ("Status", "status:Resolved|Investigating|Monitoring")]),
        dict(singular="Alert", plural="Alerts", prefix="", icon="bell", desc="Rules that page your team.",
             fields=[("Alert", "words:CPU over 90%|Disk over 85%|Error rate over 2%|Response over 1s|Service down"), ("Service", "words:API|Web|Database|Queue|Cache"), ("Fired this week", "int:0-40"), ("Channel", "choice:Pager|Email|Chat"), ("Status", "status:Active|Muted")]),
        dict(singular="Service", plural="Services", prefix="", icon="layers", desc="The services that make up your app.",
             fields=[("Service", "words:Public API|Web app|Auth|Payments|Search|Notifications"), ("Owner", "person"), ("Uptime", "pct:97-100"), ("Latency ms", "int:40-900"), ("Status", "status:Operational|Degraded|Outage")]),
        dict(singular="Check", plural="Uptime checks", slug="uptime-checks", prefix="", icon="globe", desc="Pings from around the world.",
             fields=[("Check", "words:https://app.example.com|https://api.example.com/health|https://example.com|https://status.example.com"), ("Interval", "choice:30 sec|1 min|5 min"), ("Response ms", "int:60-1200"), ("Last check", "date"), ("Status", "status:Up|Down|Paused")]),
    ],
    specials=[
        dict(title="Live status", type="monitor", icon="activity", desc="Real-time health of every service.", items=["Public API", "Web app", "Auth", "Payments", "Search", "Notifications", "Database", "Queue"]),
        dict(title="Incident board", type="kanban", icon="kanban", desc="Incidents from alert to post-mortem.", items=["Triggered", "Investigating", "Fix deployed", "Monitoring", "Post-mortem"], cards=["API latency", "Login errors", "Disk full", "Queue backlog"]),
        dict(title="Performance", type="report", icon="chart", desc="Latency, errors and throughput.", items=["P95 latency", "Error rate", "Throughput", "Apdex"], rows=["Public API", "Web app", "Auth", "Payments", "Search"]),
        dict(title="Regions", type="map", icon="globe", desc="Servers and traffic by region.", items=["US East", "US West", "Europe", "Asia", "South America"]),
        dict(title="On-call", type="calendar", icon="calendar", desc="Who is on call and when.", items=["Primary on-call", "Secondary on-call", "Maintenance window", "Handover", "Game day"]),
        dict(title="Incident timeline", type="timeline", icon="clock", desc="What happened during the last outage.", items=["Error rate alert fired", "On-call engineer joined", "Bad deploy found", "Rollback started", "Service back to normal"]),
        dict(title="Notification rules", type="config", icon="bell", desc="Who gets woken up, and when.", items=["Page on-call for any outage", "Email the team for warnings", "Post incidents in the team chat", "Update the status page automatically"]),
    ],
))

B4.append(dict(
    num=37, slug="cloudspend", brand="Cloudspend", category="Cloud Cost", org="Fernway Apps", currency="$",
    tagline="See what your cloud bill is made of and where to save.",
    auth_line="Spend less on cloud without slowing down.", user="Isaac Park", user_role="Platform lead",
    theme=dict(fonts=["Epilogue", "Inter", "JetBrains Mono"], accent="#0284c7", layout="light", card="shadow", radius="12px",
               c2="#7dd3fc", c3="#f97316", c4="#10b981"),
    kpis=[("Spend this month", "money", 84200, "dollar"), ("Forecast", "money", 96400, "trend"), ("Possible savings", "money", 18600, "zap"), ("Budget used", "pct", 71.4, "pie")],
    chart=dict(title="Daily cloud spend", names=["This month", "Last month"], base=2600),
    mix=dict(title="Spend by service", parts=["Compute", "Storage", "Database", "Network", "Other"]),
    activity=["Budget alert: data team at 90 percent", "Idle servers shut down, saving $1,200", "Reserved instance bought", "New tag rule added", "Anomaly: storage up 40 percent", "Monthly report sent"],
    entities=[
        dict(singular="Resource", plural="Resources", prefix="", icon="layers", desc="Everything you pay for.",
             fields=[("Resource", "words:prod-web-cluster|analytics-db|backup-bucket|staging-vm|cdn-edge|ml-gpu-node"), ("Service", "choice:Compute|Storage|Database|Network"), ("Team", "choice:Platform|Data|Web|ML"), ("Monthly cost", "money:40-18000"), ("Status", "status:Used|Idle|Oversized")]),
        dict(singular="Account", plural="Cloud accounts", slug="cloud-accounts", prefix="", icon="building", desc="Accounts across providers.",
             fields=[("Account", "words:Production|Staging|Data|Sandbox|Shared services"), ("Provider", "choice:Cloud A|Cloud B|Cloud C"), ("Spend", "money:500-40000"), ("Change", "pct:0-40"), ("Status", "status:Connected|Needs access")]),
        dict(singular="Budget", plural="Budgets", prefix="", icon="pie", desc="Spending limits for each team.",
             fields=[("Budget", "words:Platform|Data|Web|ML|Marketing site"), ("Limit", "money:2000-40000"), ("Spent", "money:1000-38000"), ("Used", "pct:30-110"), ("Status", "status:On track|At risk|Over")]),
        dict(singular="Saving", plural="Savings", prefix="", icon="zap", desc="Ways to cut your bill.",
             fields=[("Saving", "words:Shut down idle VMs|Buy reserved capacity|Move old files to archive|Right-size database|Delete unused volumes"), ("Resource", "words:staging-vm|analytics-db|backup-bucket|ml-gpu-node"), ("Per month", "money:40-6000"), ("Effort", "choice:Easy|Medium|Hard"), ("Status", "status:New|Applied|Dismissed")]),
        dict(singular="Anomaly", plural="Anomalies", prefix="", icon="alert", desc="Unusual jumps in spend.",
             fields=[("Anomaly", "words:Storage spike|Network egress jump|GPU hours doubled|New region spend|Logging costs up"), ("Account", "words:Production|Data|Sandbox"), ("Detected", "date"), ("Extra cost", "money:100-9000"), ("Status", "status:Open|Explained|Resolved")]),
    ],
    specials=[
        dict(title="Cost report", type="report", icon="chart", desc="Where the money went this month.", items=["Total spend", "Unit cost", "Savings made", "Waste"], rows=["Compute", "Storage", "Database", "Network", "Monitoring"]),
        dict(title="Top spenders", type="ranking", icon="trend", desc="Resources that cost the most.", items=["prod-web-cluster", "analytics-db", "ml-gpu-node", "cdn-edge", "backup-bucket", "staging-vm"], metric="Monthly cost", scale=180),
        dict(title="Savings plan", type="kanban", icon="kanban", desc="Savings from idea to done.", items=["Found", "Reviewing", "Scheduled", "Applied"], cards=["Shut down idle VMs", "Right-size database", "Archive old files", "Reserved capacity"], money=True),
        dict(title="Spend by region", type="map", icon="globe", desc="Cloud costs around the world.", items=["US East", "Europe", "Asia", "US West", "South America"]),
        dict(title="Budget alerts", type="monitor", icon="activity", desc="Live budget use by team.", items=["Platform", "Data", "Web", "ML", "Marketing site", "Shared"], unit="%"),
        dict(title="Invoice breakdown", type="document", icon="receipt", desc="This month's cloud invoice, explained.", doc="Cloud invoice summary", num="September 2026", items=["Compute hours", "Storage", "Database", "Data transfer", "Support plan"]),
        dict(title="Cost rules", type="config", icon="settings", desc="Keep costs under control.", items=["Shut down staging servers at night", "Require a team tag on every resource", "Alert at 80 percent of any budget", "Block new GPU nodes without approval"]),
    ],
))

B4.append(dict(
    num=38, slug="endpoint", brand="Endpoint", category="API Analytics", org="Sendwell API", currency="$",
    tagline="Requests, errors, keys and usage for a public API.",
    auth_line="Every request, measured.", user="Julia Chen", user_role="API product manager",
    theme=dict(fonts=["Schibsted Grotesk", "Schibsted Grotesk", "Fira Code"], accent="#4f46e5", layout="tint", card="border", radius="10px",
               c2="#a5b4fc", c3="#f59e0b", c4="#14b8a6"),
    kpis=[("Requests today", "int", 4820000, "zap"), ("Error rate", "pct", 0.4, "alert"), ("P95 latency ms", "int", 186, "clock"), ("Active keys", "int", 1284, "key")],
    chart=dict(title="Requests", names=["Requests", "Errors"], base=4200000),
    mix=dict(title="Requests by endpoint", parts=["/messages", "/contacts", "/webhooks", "/auth", "Other"]),
    activity=["Rate limit raised for Maple Foods", "New key created by Beacon Retail", "Error spike on /webhooks", "Version 3 docs published", "Deprecated endpoint turned off", "Usage report emailed"],
    entities=[
        dict(singular="Endpoint", plural="Endpoints", prefix="", icon="globe", desc="Every route in your API.",
             fields=[("Endpoint", "words:POST /messages|GET /contacts|POST /webhooks|POST /auth/token|GET /usage|DELETE /contacts"), ("Requests", "int:10000-2000000"), ("P95 ms", "int:40-900"), ("Errors", "pct:0-4"), ("Status", "status:Healthy|Slow|Failing")]),
        dict(singular="API key", plural="API keys", slug="api-keys", prefix="key_", icon="key", desc="Keys your customers use.",
             fields=[("Key", "id"), ("Customer", "company"), ("Created", "date"), ("Requests", "int:1000-900000"), ("Status", "status:Active|Revoked|Expired")]),
        dict(singular="Consumer", plural="Consumers", prefix="", icon="users", desc="Companies calling your API.",
             fields=[("Consumer", "company"), ("Plan", "choice:Free|Starter|Growth|Enterprise"), ("Requests", "int:1000-2000000"), ("Errors", "pct:0-5"), ("Status", "status:Active|Throttled|Suspended")]),
        dict(singular="Error", plural="Errors", prefix="", icon="alert", desc="Failed requests grouped by cause.",
             fields=[("Error", "words:401 Unauthorized|429 Too many requests|500 Server error|400 Bad request|404 Not found"), ("Endpoint", "words:POST /messages|POST /webhooks|GET /contacts"), ("Count", "int:10-40000"), ("First seen", "date"), ("Status", "status:Open|Fixed|Ignored")]),
        dict(singular="Webhook", plural="Webhooks", prefix="", icon="zap", desc="Events you send to customers.",
             fields=[("Event", "words:message.sent|message.failed|contact.created|invoice.paid"), ("Customer", "company"), ("Delivered", "pct:80-100"), ("Last sent", "date"), ("Status", "status:Healthy|Failing|Disabled")]),
    ],
    specials=[
        dict(title="Traffic", type="report", icon="chart", desc="Requests, errors and speed over time.", items=["Requests", "Error rate", "Latency", "Bandwidth"], rows=["POST /messages", "GET /contacts", "POST /webhooks", "POST /auth/token", "GET /usage"]),
        dict(title="Live requests", type="monitor", icon="activity", desc="Traffic on each endpoint right now.", items=["POST /messages", "GET /contacts", "POST /webhooks", "POST /auth/token", "GET /usage", "DELETE /contacts"], unit=" rps"),
        dict(title="Top consumers", type="ranking", icon="trend", desc="Customers sending the most requests.", items=["Maple Foods", "Beacon Retail", "Harbor Health", "Oak Studio", "Summit Labs", "Cedar Logistics"], metric="Requests", scale=18000),
        dict(title="Request log", type="timeline", icon="list", desc="The latest requests, newest first.", items=["POST /messages 201 in 84 ms", "GET /contacts 200 in 42 ms", "POST /webhooks 500 in 1,204 ms", "POST /auth/token 200 in 61 ms", "GET /usage 200 in 38 ms"]),
        dict(title="Traffic by country", type="map", icon="globe", desc="Where requests come from.", items=["United States", "Germany", "India", "Brazil", "Japan"]),
        dict(title="Usage invoice", type="document", icon="receipt", desc="A usage-based invoice for a customer.", doc="Usage invoice", num="Maple Foods, September 2026", items=["Base plan", "Messages over quota", "Premium support", "Extra webhooks"]),
        dict(title="Rate limits", type="config", icon="shield", desc="Protect your API from overload.", items=["100 requests per second on the Free plan", "Block keys after 5 failed logins", "Warn customers at 80 percent of quota", "Retry failed webhooks 3 times"]),
    ],
))

B4.append(dict(
    num=39, slug="sentinel", brand="Sentinel", category="Cyber Security", org="Bastion Security Operations", currency="$",
    tagline="Threats, alerts and investigations for a security operations team.",
    auth_line="See threats early. Act fast.", user="Nadia Ibrahim", user_role="Security analyst",
    theme=dict(fonts=["Rajdhani", "Inter", "JetBrains Mono", "Rajdhani"], accent="#ef4444", layout="dark", card="border", radius="4px", sidebar="#0a0a0f",
               c2="#fca5a5", c3="#f59e0b", c4="#22c55e"),
    kpis=[("Open alerts", "int", 64, "alert"), ("Critical", "int", 4, "shield"), ("Mean time to respond", "int", 18, "clock"), ("Devices protected", "int", 2840, "monitor")],
    chart=dict(title="Alerts", names=["Alerts", "Resolved"], base=420),
    mix=dict(title="Alerts by type", parts=["Phishing", "Malware", "Login anomaly", "Data leak", "Other"]),
    activity=["Phishing email quarantined for 42 users", "Laptop LT-221 isolated", "Critical alert escalated", "Firewall rule updated", "Password reset forced for 3 accounts", "Weekly threat report shared"],
    entities=[
        dict(singular="Alert", plural="Alerts", prefix="AL-", icon="alert", desc="Security alerts from every tool.",
             fields=[("Alert", "id"), ("Type", "choice:Phishing|Malware|Login anomaly|Data leak|Port scan"), ("Asset", "words:LT-221|srv-db-02|mail gateway|vpn-01|wks-114"), ("Severity", "choice:Critical|High|Medium|Low"), ("Status", "status:Open|Investigating|Resolved|False positive")]),
        dict(singular="Incident", plural="Incidents", prefix="IR-", icon="shield", desc="Confirmed security incidents.",
             fields=[("Incident", "id"), ("Title", "words:Credential phishing|Ransomware attempt|Suspicious admin login|Data sent to unknown host"), ("Owner", "person"), ("Opened", "date"), ("Status", "status:Contained|Investigating|Closed")]),
        dict(singular="Asset", plural="Assets", prefix="", icon="monitor", desc="Devices and servers you protect.",
             fields=[("Asset", "words:LT-221|LT-305|srv-db-02|srv-web-01|vpn-01|wks-114"), ("Type", "choice:Laptop|Server|Network|Cloud"), ("Owner", "person"), ("Risk score", "int:1-100"), ("Status", "status:Protected|At risk|Isolated")]),
        dict(singular="Vulnerability", plural="Vulnerabilities", prefix="VULN-", icon="tool", desc="Weak spots to patch.",
             fields=[("Vulnerability", "id"), ("Software", "words:Web server|VPN client|Office suite|Browser|Database"), ("Affected", "int:1-400"), ("Severity", "choice:Critical|High|Medium|Low"), ("Status", "status:Open|Patching|Fixed")]),
        dict(singular="User", plural="Risky users", slug="risky-users", prefix="", icon="users", desc="Accounts showing unusual behaviour.",
             fields=[("User", "person"), ("Department", "choice:Finance|Sales|Engineering|HR"), ("Signals", "int:1-12"), ("Last seen", "date"), ("Status", "status:Watching|Reset required|Cleared")]),
    ],
    specials=[
        dict(title="Threat monitor", type="monitor", icon="activity", desc="Live signals from your security tools.", items=["Email gateway", "Endpoint agents", "Firewall", "VPN", "Cloud logs", "Identity", "DNS filter", "Backups"], unit=" events"),
        dict(title="Investigations", type="kanban", icon="kanban", desc="Alerts moving through triage.", items=["New", "Triage", "Investigating", "Contained", "Closed"], cards=["Phishing report", "Malware on laptop", "Impossible travel login", "Data upload spike"]),
        dict(title="Attack map", type="map", icon="globe", desc="Where attacks come from.", items=["Eastern Europe", "South East Asia", "North America", "South America", "Unknown"]),
        dict(title="Security report", type="report", icon="chart", desc="Alerts, response times and risk.", items=["Alerts handled", "Response time", "Patch rate", "Phishing clicks"], rows=["Phishing", "Malware", "Login anomaly", "Data leak", "Port scan"]),
        dict(title="Incident timeline", type="timeline", icon="clock", desc="Steps taken during the last incident.", items=["Phishing email reported by user", "Sender blocked at the gateway", "42 copies removed from inboxes", "Affected passwords reset", "Incident closed"]),
        dict(title="Riskiest assets", type="ranking", icon="alert", desc="Devices with the highest risk score.", items=["srv-db-02", "vpn-01", "LT-221", "wks-114", "srv-web-01", "LT-305"], metric="Risk score", scale=1),
        dict(title="Response playbooks", type="config", icon="shield", desc="Automatic actions for common threats.", items=["Isolate laptops with confirmed malware", "Force password reset after a phishing click", "Block logins from blocked countries", "Open an incident for every critical alert"]),
    ],
))

B4.append(dict(
    num=40, slug="deskside", brand="Deskside", category="IT Helpdesk", org="Crestview College IT", currency="$",
    tagline="IT tickets, devices and software licences for an internal IT team.",
    auth_line="Keep everyone working, every day.", user="Ben Morris", user_role="IT manager",
    theme=dict(fonts=["Mulish", "Mulish", "Roboto Mono"], accent="#2563eb", layout="accent", card="shadow", radius="12px",
               c2="#93c5fd", c3="#f59e0b", c4="#10b981"),
    kpis=[("Open tickets", "int", 86, "inbox"), ("Solved this week", "int", 312, "check"), ("Devices", "int", 1640, "monitor"), ("Licences expiring", "int", 12, "key")],
    chart=dict(title="Tickets", names=["Solved", "Opened"], base=300),
    mix=dict(title="Tickets by category", parts=["Password reset", "Laptop", "Wi-Fi", "Software", "Printer"]),
    activity=["Laptop issued to new starter", "Ticket IT-4421 solved", "Wi-Fi fixed in Library", "Licence renewed: design suite", "Printer toner replaced", "Password reset for 14 students"],
    entities=[
        dict(singular="Ticket", plural="Tickets", prefix="IT-", icon="inbox", desc="Requests from staff and students.",
             fields=[("Ticket", "id"), ("Subject", "words:Cannot log in|Laptop is slow|No Wi-Fi in room 204|Need new software|Printer jam"), ("Requester", "person"), ("Priority", "choice:Urgent|High|Normal|Low"), ("Status", "status:Open|In progress|Waiting|Solved")]),
        dict(singular="Device", plural="Devices", prefix="DEV-", icon="monitor", desc="Laptops, desktops and phones.",
             fields=[("Device", "id"), ("Type", "choice:Laptop|Desktop|Tablet|Phone"), ("Assigned to", "person"), ("Purchased", "date"), ("Status", "status:In use|Spare|Repair|Retired")]),
        dict(singular="Licence", plural="Licences", prefix="", icon="key", desc="Software you pay for.",
             fields=[("Software", "words:Office suite|Design suite|Antivirus|Video calls|Maths package|Survey tool"), ("Seats", "int:10-2000"), ("Used", "pct:30-100"), ("Renews", "date:future"), ("Status", "status:Active|Renewal due|Expired")]),
        dict(singular="User", plural="Users", prefix="", icon="users", desc="Staff and student accounts.",
             fields=[("User", "person"), ("Type", "choice:Staff|Student|Contractor"), ("Devices", "int:0-3"), ("Last login", "date"), ("Status", "status:Active|Locked|Disabled")]),
        dict(singular="Article", plural="Knowledge base", slug="knowledge-base", prefix="", icon="book", desc="How-to guides for common problems.",
             fields=[("Article", "words:Reset your password|Connect to Wi-Fi|Set up email on your phone|Print from your laptop|Join a video call"), ("Views", "int:100-9000"), ("Helpful", "pct:60-98"), ("Updated", "date"), ("Status", "status:Published|Draft")]),
    ],
    specials=[
        dict(title="Ticket queue", type="split", icon="inbox", desc="Work through requests one by one.", items=["Cannot log in to email", "Projector not working in Hall B", "Need access to shared drive", "Laptop screen cracked", "Wi-Fi drops every hour"], body="Hi, I cannot log in to my email since this morning. It says my password is wrong but I have not changed it. Can you help?"),
        dict(title="Device map", type="map", icon="map", desc="Devices by building.", items=["Main building", "Library", "Science block", "Sports hall", "Admin office"]),
        dict(title="Asset lifecycle", type="kanban", icon="kanban", desc="Devices from order to retirement.", items=["Ordered", "Set up", "Issued", "Repair", "Retired"], cards=["Laptop", "Desktop", "Tablet", "Projector"]),
        dict(title="IT report", type="report", icon="chart", desc="Tickets, speed and satisfaction.", items=["Tickets solved", "First response", "Satisfaction", "Tickets per user"], rows=["Password reset", "Laptop", "Wi-Fi", "Software", "Printer"]),
        dict(title="Maintenance calendar", type="calendar", icon="calendar", desc="Updates and planned work.", items=["Server updates", "Wi-Fi upgrade", "Laptop refresh", "Backup test", "Licence renewal"]),
        dict(title="Network health", type="monitor", icon="activity", desc="Live status of core systems.", items=["Wi-Fi", "Email", "File server", "Printers", "Internet link", "Phones", "Student portal", "Backups"]),
        dict(title="Helpdesk rules", type="config", icon="settings", desc="How tickets are handled.", items=["Unlock accounts automatically after identity check", "Assign Wi-Fi tickets to the network team", "Close solved tickets after 3 days", "Ask for feedback when a ticket is solved"]),
    ],
))

B4.append(dict(
    num=41, slug="shipyard", brand="Shipyard", category="CI/CD Pipelines", org="Codefield Engineering", currency="$",
    tagline="Builds, tests and deployments for an engineering team.",
    auth_line="Ship small changes, often and safely.", user="Liam Novak", user_role="Engineering manager",
    theme=dict(fonts=["Familjen Grotesk", "Inter", "JetBrains Mono"], accent="#15803d", layout="light", card="flat", radius="8px",
               c2="#86efac", c3="#dc2626", c4="#2563eb"),
    kpis=[("Deploys this week", "int", 142, "zap"), ("Build success", "pct", 93.8, "check"), ("Avg build time min", "int", 7, "clock"), ("Failed today", "int", 4, "alert")],
    chart=dict(title="Deploys per day", names=["Deploys", "Rollbacks"], base=24),
    mix=dict(title="Build time by stage", parts=["Install", "Test", "Build", "Deploy", "Other"]),
    activity=["main deployed to production", "Build failed on feature/search", "Flaky test quarantined", "New runner added", "Release v4.2.0 tagged", "Rollback on api-service"],
    entities=[
        dict(singular="Pipeline run", plural="Pipeline runs", slug="pipeline-runs", prefix="#", icon="activity", desc="Every build and deploy.",
             fields=[("Run", "id"), ("Branch", "words:main|feature/search|fix/login|release/4.2|feature/billing"), ("Author", "person"), ("Duration", "duration"), ("Status", "status:Passed|Running|Failed|Cancelled")]),
        dict(singular="Repository", plural="Repositories", prefix="", icon="folder", desc="Code repositories with pipelines.",
             fields=[("Repository", "words:web-app|api-service|mobile-app|infra|design-system|docs"), ("Language", "choice:TypeScript|Go|Python|Kotlin"), ("Runs this week", "int:10-400"), ("Success", "pct:70-100"), ("Status", "status:Healthy|Flaky|Failing")]),
        dict(singular="Deployment", plural="Deployments", prefix="DEP-", icon="zap", desc="What went to which environment.",
             fields=[("Deployment", "id"), ("Service", "words:web-app|api-service|worker|auth"), ("Environment", "choice:Production|Staging|Preview"), ("Version", "words:v4.2.0|v4.1.3|v4.1.2|v4.0.9"), ("Status", "status:Live|Rolled back|Failed")]),
        dict(singular="Test suite", plural="Test suites", slug="test-suites", prefix="", icon="check", desc="Automated tests and how stable they are.",
             fields=[("Suite", "words:Unit tests|API tests|End to end|Visual tests|Load tests"), ("Tests", "int:40-4000"), ("Pass rate", "pct:80-100"), ("Duration", "duration"), ("Status", "status:Stable|Flaky|Broken")]),
        dict(singular="Runner", plural="Runners", prefix="", icon="monitor", desc="Machines that run your jobs.",
             fields=[("Runner", "words:linux-large-01|linux-large-02|mac-arm-01|linux-gpu-01|windows-01"), ("Jobs today", "int:10-300"), ("Queue", "int:0-20"), ("CPU", "pct:10-95"), ("Status", "status:Online|Busy|Offline")]),
    ],
    specials=[
        dict(title="Pipeline view", type="kanban", icon="kanban", desc="Runs moving through each stage.", items=["Queued", "Install", "Test", "Build", "Deploy"], cards=["main", "feature/search", "fix/login", "release/4.2"]),
        dict(title="Build health", type="monitor", icon="activity", desc="Live status of every repository.", items=["web-app", "api-service", "mobile-app", "infra", "design-system", "docs"]),
        dict(title="Delivery report", type="report", icon="chart", desc="Speed and stability of delivery.", items=["Deploy frequency", "Lead time", "Change fail rate", "Time to restore"], rows=["web-app", "api-service", "mobile-app", "infra", "docs"]),
        dict(title="Flaky tests", type="ranking", icon="alert", desc="Tests that fail the most without reason.", items=["checkout flow e2e", "search results api", "login redirect", "image upload", "billing webhook", "profile page visual"], metric="Flaky runs", scale=0.5),
        dict(title="Release log", type="timeline", icon="clock", desc="The latest releases.", items=["v4.2.0 released to production", "v4.1.3 hotfix for login", "v4.1.2 search improvements", "v4.1.0 billing page", "v4.0.9 performance fixes"]),
        dict(title="Release calendar", type="calendar", icon="calendar", desc="Planned releases and freezes.", items=["Release", "Code freeze", "Hotfix window", "Retro", "Infra upgrade"]),
        dict(title="Pipeline settings", type="config", icon="settings", desc="Rules for merging and deploying.", items=["Require all tests to pass before merge", "Deploy main to staging automatically", "Ask for approval before production", "Cancel old runs on new commits"]),
    ],
))

B4.append(dict(
    num=42, slug="querybase", brand="Querybase", category="Database Admin", org="Relay Data Platform", currency="$",
    tagline="Databases, slow queries, backups and access for a data team.",
    auth_line="Healthy databases, quiet nights.", user="Sara Kowalski", user_role="Database administrator",
    theme=dict(fonts=["DM Sans", "DM Sans", "DM Mono"], accent="#0891b2", layout="dark", card="border", radius="6px", sidebar="#06141b",
               c2="#67e8f9", c3="#f59e0b", c4="#a78bfa"),
    kpis=[("Databases", "int", 38, "layers"), ("Queries per second", "int", 12400, "zap"), ("Slow queries today", "int", 142, "clock"), ("Storage used", "pct", 67.2, "pie")],
    chart=dict(title="Queries per second", names=["Reads", "Writes"], base=9000),
    mix=dict(title="Storage by database", parts=["orders", "analytics", "users", "logs", "Other"]),
    activity=["Backup finished: orders-prod", "Index added on users.email", "Slow query fixed in reports", "Replica lag back to normal", "Access granted to data team", "Storage alert on logs-db"],
    entities=[
        dict(singular="Database", plural="Databases", prefix="", icon="layers", desc="Every database you run.",
             fields=[("Database", "words:orders-prod|users-prod|analytics|logs-db|billing|staging"), ("Engine", "choice:Postgres|MySQL|Redis|Mongo"), ("Size GB", "int:4-2400"), ("Connections", "int:4-900"), ("Status", "status:Healthy|Warning|Down")]),
        dict(singular="Query", plural="Slow queries", slug="slow-queries", prefix="Q-", icon="clock", desc="Queries taking too long.",
             fields=[("Query", "id"), ("Table", "words:orders|users|events|invoices|sessions"), ("Avg ms", "int:200-9000"), ("Calls", "int:10-40000"), ("Status", "status:Open|Fixed|Ignored")]),
        dict(singular="Backup", plural="Backups", prefix="BK-", icon="box", desc="Snapshots and restore points.",
             fields=[("Backup", "id"), ("Database", "words:orders-prod|users-prod|analytics|billing"), ("Taken", "date"), ("Size GB", "int:4-2400"), ("Status", "status:Complete|Running|Failed")]),
        dict(singular="Table", plural="Tables", prefix="", icon="grid", desc="Largest tables and their growth.",
             fields=[("Table", "words:orders|order_items|users|events|invoices|sessions"), ("Rows", "int:10000-900000"), ("Size GB", "int:1-400"), ("Growth", "pct:0-30"), ("Status", "status:Normal|Needs vacuum|Bloated")]),
        dict(singular="Access grant", plural="Access", slug="access", prefix="", icon="key", desc="Who can read or change data.",
             fields=[("Person", "person"), ("Database", "words:orders-prod|analytics|billing|staging"), ("Role", "choice:Read only|Read and write|Admin"), ("Granted", "date"), ("Status", "status:Active|Expiring|Revoked")]),
    ],
    specials=[
        dict(title="Live metrics", type="monitor", icon="activity", desc="Load on each database right now.", items=["orders-prod", "users-prod", "analytics", "logs-db", "billing", "staging"]),
        dict(title="Query report", type="report", icon="chart", desc="Speed and load over time.", items=["Queries per second", "P95 latency", "Cache hit rate", "Replica lag"], rows=["orders-prod", "users-prod", "analytics", "billing", "logs-db"]),
        dict(title="Heaviest queries", type="ranking", icon="trend", desc="Queries using the most total time.", items=["orders by customer", "daily revenue report", "user search", "event export", "invoice lookup", "session cleanup"], metric="Total seconds", scale=40),
        dict(title="Migrations", type="kanban", icon="kanban", desc="Schema changes from draft to live.", items=["Draft", "Reviewed", "Staging", "Production"], cards=["Add index on email", "Split events table", "New invoices column", "Drop old sessions"]),
        dict(title="Backup calendar", type="calendar", icon="calendar", desc="Backups, restores and upgrades.", items=["Full backup", "Restore test", "Engine upgrade", "Failover drill", "Vacuum"]),
        dict(title="Change history", type="timeline", icon="clock", desc="Recent changes to your databases.", items=["Index added on users.email", "Replica promoted in Europe", "Storage expanded for logs-db", "Read access given to data team"]),
        dict(title="Safety settings", type="config", icon="shield", desc="Protect your data.", items=["Take a backup every 6 hours", "Block writes to production from laptops", "Alert when replica lag passes 10 seconds", "Expire access grants after 90 days"]),
    ],
))

B4.append(dict(
    num=43, slug="parley", brand="Parley", category="AI Chatbot Analytics", org="Mira Assistant", currency="$",
    tagline="Conversations, answer quality and handoffs for an AI support assistant.",
    auth_line="See what your AI assistant is really saying.", user="Kavya Rao", user_role="AI product lead",
    theme=dict(fonts=["Unbounded", "Inter", "JetBrains Mono"], accent="#7c3aed", layout="tint", card="shadow", radius="16px",
               c2="#c4b5fd", c3="#f59e0b", c4="#10b981"),
    kpis=[("Conversations today", "int", 8420, "message"), ("Solved by AI", "pct", 71.4, "check"), ("Handed to humans", "int", 612, "users"), ("Answer rating", "pct", 88.2, "star")],
    chart=dict(title="Conversations", names=["Conversations", "Handoffs"], base=7600),
    mix=dict(title="Topics", parts=["Billing", "Account", "Shipping", "Product", "Other"]),
    activity=["New answer source added: pricing page", "Handoff rate dropped 4 percent", "Wrong answer flagged by an agent", "Prompt updated for refunds", "Weekly quality review done", "New language turned on: Spanish"],
    entities=[
        dict(singular="Conversation", plural="Conversations", prefix="CV-", icon="message", desc="Chats with the assistant.",
             fields=[("Conversation", "id"), ("Topic", "choice:Billing|Account|Shipping|Product|Refund"), ("Messages", "int:2-24"), ("Rating", "choice:Helpful|Not helpful|No rating"), ("Status", "status:Solved|Handed off|Abandoned")]),
        dict(singular="Intent", plural="Intents", prefix="", icon="grid", desc="What people ask about most.",
             fields=[("Intent", "words:Change my plan|Where is my order|Reset password|Request a refund|Cancel subscription|Update card"), ("Conversations", "int:100-9000"), ("Solved", "pct:40-95"), ("Trend", "status:Up|Flat|Down"), ("Owner", "person")]),
        dict(singular="Source", plural="Knowledge sources", slug="knowledge-sources", prefix="", icon="book", desc="Pages the assistant learns from.",
             fields=[("Source", "words:Help center|Pricing page|Refund policy|Shipping guide|API docs|Release notes"), ("Pages", "int:4-400"), ("Used in answers", "pct:5-60"), ("Synced", "date"), ("Status", "status:Synced|Syncing|Error")]),
        dict(singular="Flagged answer", plural="Flagged answers", slug="flagged-answers", prefix="FA-", icon="alert", desc="Answers someone marked as wrong.",
             fields=[("Answer", "id"), ("Question", "words:Can I get a refund after 30 days?|Do you ship to Canada?|How do I change my email?|Is there a student discount?"), ("Flagged by", "person"), ("Date", "date"), ("Status", "status:Open|Fixed|Won't fix")]),
        dict(singular="Handoff", plural="Handoffs", prefix="", icon="users", desc="Chats passed to a human agent.",
             fields=[("Customer", "person"), ("Reason", "choice:Asked for a human|Low confidence|Angry customer|Refund over limit"), ("Agent", "person"), ("Wait", "duration"), ("Status", "status:Resolved|Waiting|In progress")]),
    ],
    specials=[
        dict(title="Quality report", type="report", icon="chart", desc="How good the answers are.", items=["Solved by AI", "Answer rating", "Handoff rate", "Wrong answers"], rows=["Billing", "Account", "Shipping", "Product", "Refund"]),
        dict(title="Conversation review", type="split", icon="inbox", desc="Read chats and mark them good or bad.", items=["Can I pause my plan?", "My order is late", "Refund for a double charge", "How do I add a user?", "Is my data safe?"], body="Customer: Can I pause my plan for two months? Assistant: Yes. Go to Settings, then Billing, and choose Pause plan. Your data is kept while paused."),
        dict(title="Top questions", type="ranking", icon="trend", desc="The most common questions this week.", items=["Where is my order", "Change my plan", "Reset password", "Request a refund", "Update card", "Cancel subscription"], metric="Conversations", scale=80),
        dict(title="Fix queue", type="kanban", icon="kanban", desc="Wrong answers from report to fixed.", items=["Reported", "Checking", "Updating source", "Fixed"], cards=["Refund window", "Canada shipping", "Student discount", "Email change"]),
        dict(title="Live chats", type="monitor", icon="activity", desc="Assistant activity right now.", items=["Chats open", "Waiting for human", "Average reply", "Confidence", "Billing chats", "Shipping chats"], unit=""),
        dict(title="Change log", type="timeline", icon="clock", desc="Changes to prompts and sources.", items=["Refund policy page re-synced", "Tone changed to shorter answers", "Spanish turned on", "Handoff rule added for angry customers"]),
        dict(title="Assistant settings", type="config", icon="settings", desc="How the assistant behaves.", items=["Hand off when confidence is below 60 percent", "Always offer a human for refunds over $200", "Show sources under every answer", "Ask for a rating at the end"]),
    ],
))

B4.append(dict(
    num=44, slug="tokenwise", brand="Tokenwise", category="AI Usage and Cost", org="Lumen AI Team", currency="$",
    tagline="Model usage, token costs and budgets for teams building with AI.",
    auth_line="Know what every AI call costs.", user="Rafael Ito", user_role="AI platform lead",
    theme=dict(fonts=["Gantari", "Gantari", "Martian Mono"], accent="#ea580c", layout="light", card="border", radius="10px",
               c2="#fdba74", c3="#6366f1", c4="#10b981"),
    kpis=[("Spend this month", "money", 28400, "dollar"), ("Tokens used", "int", 1840000000, "zap"), ("Requests", "int", 2400000, "activity"), ("Budget used", "pct", 68.4, "pie")],
    chart=dict(title="Daily AI spend", names=["Spend", "Budget line"], base=900),
    mix=dict(title="Spend by model", parts=["Large model", "Fast model", "Embeddings", "Image model", "Other"]),
    activity=["Budget alert: support bot at 90 percent", "Cache hit rate up to 42 percent", "New project added: search", "Key rotated for the web app", "Prompt shortened, saving 18 percent", "Monthly report sent"],
    entities=[
        dict(singular="Project", plural="Projects", prefix="", icon="folder", desc="Apps and features that use AI.",
             fields=[("Project", "words:Support bot|Search|Email writer|Doc summaries|Image tags|Sales notes"), ("Team", "choice:Support|Product|Marketing|Data"), ("Spend", "money:200-12000"), ("Requests", "int:1000-900000"), ("Status", "status:On budget|Near limit|Over")]),
        dict(singular="Model", plural="Models", prefix="", icon="layers", desc="Models you use and what they cost.",
             fields=[("Model", "words:Large model|Fast model|Embeddings|Image model|Speech model"), ("Requests", "int:1000-1400000"), ("Avg tokens", "int:120-9000"), ("Cost", "money:100-16000"), ("Status", "status:Active|Testing|Retired")]),
        dict(singular="API key", plural="API keys", slug="api-keys", prefix="key_", icon="key", desc="Keys and who uses them.",
             fields=[("Key", "id"), ("Project", "words:Support bot|Search|Email writer|Doc summaries"), ("Created", "date"), ("Spend", "money:20-9000"), ("Status", "status:Active|Revoked")]),
        dict(singular="Request", plural="Requests", prefix="req_", icon="activity", desc="Recent calls with their cost.",
             fields=[("Request", "id"), ("Model", "choice:Large model|Fast model|Embeddings"), ("Tokens", "int:80-12000"), ("Cost", "money:0.01-1.2"), ("Status", "status:Success|Cached|Error")]),
        dict(singular="Budget", plural="Budgets", prefix="", icon="pie", desc="Monthly limits per team.",
             fields=[("Team", "words:Support|Product|Marketing|Data|Research"), ("Limit", "money:1000-20000"), ("Spent", "money:500-19000"), ("Used", "pct:20-110"), ("Status", "status:On track|At risk|Over")]),
    ],
    specials=[
        dict(title="Cost report", type="report", icon="chart", desc="Where your AI spend goes.", items=["Total spend", "Cost per request", "Cache savings", "Error rate"], rows=["Support bot", "Search", "Email writer", "Doc summaries", "Image tags"]),
        dict(title="Top projects", type="ranking", icon="trend", desc="Projects that spend the most.", items=["Support bot", "Search", "Doc summaries", "Email writer", "Sales notes", "Image tags"], metric="Spend", scale=120),
        dict(title="Live usage", type="monitor", icon="activity", desc="Requests per minute by model.", items=["Large model", "Fast model", "Embeddings", "Image model", "Speech model", "Cache"], unit=" rpm"),
        dict(title="Savings ideas", type="kanban", icon="kanban", desc="Ways to cut cost, from idea to done.", items=["Ideas", "Testing", "Rolling out", "Done"], cards=["Cache repeat questions", "Use the fast model for tags", "Shorter system prompt", "Batch night jobs"], money=True),
        dict(title="Usage by region", type="map", icon="globe", desc="Where requests come from.", items=["North America", "Europe", "Asia", "South America", "Africa"]),
        dict(title="Monthly invoice", type="document", icon="receipt", desc="AI usage invoice for this month.", doc="AI usage invoice", num="September 2026", items=["Large model tokens", "Fast model tokens", "Embeddings", "Image generation"]),
        dict(title="Spend limits", type="config", icon="shield", desc="Stop surprise bills.", items=["Stop requests when a team passes its budget", "Alert at 80 percent of any budget", "Block the large model on test keys", "Cache identical requests for 24 hours"]),
    ],
))

B4.append(dict(
    num=45, slug="appscope", brand="Appscope", category="Mobile App Analytics", org="Habitly Apps", currency="$",
    tagline="Installs, users, crashes and reviews for a mobile app.",
    auth_line="Understand how people use your app.", user="Chloe Walsh", user_role="Mobile product lead",
    theme=dict(fonts=["Readex Pro", "Readex Pro", "Roboto Mono"], accent="#f43f5e", layout="dark", card="shadow", radius="14px", sidebar="#1a1020",
               c2="#fda4af", c3="#8b5cf6", c4="#22c55e"),
    kpis=[("Daily active users", "int", 84200, "users"), ("New installs", "int", 6420, "download"), ("Crash-free sessions", "pct", 99.1, "check"), ("App rating", "rating", 4.7, "star")],
    chart=dict(title="Active users", names=["Daily users", "New installs x10"], base=76000),
    mix=dict(title="Users by platform", parts=["iOS", "Android", "Tablet", "Web", "Other"]),
    activity=["Version 5.2 released to 100 percent", "Crash spike on Android 14 fixed", "Push campaign sent to 40k users", "New 5 star review", "Onboarding funnel improved", "A/B test finished"],
    entities=[
        dict(singular="Release", plural="Releases", prefix="", icon="zap", desc="App versions and how they perform.",
             fields=[("Version", "words:5.2.0|5.1.4|5.1.3|5.1.0|5.0.2"), ("Platform", "choice:iOS|Android"), ("Users", "int:2000-60000"), ("Crash-free", "pct:95-100"), ("Status", "status:Live|Rolling out|Halted")]),
        dict(singular="Crash", plural="Crashes", prefix="CR-", icon="alert", desc="Crashes grouped by cause.",
             fields=[("Crash", "id"), ("Where", "words:Login screen|Habit list|Streak widget|Settings|Payment sheet"), ("Users affected", "int:4-2400"), ("Version", "words:5.2.0|5.1.4|5.1.3"), ("Status", "status:Open|Fixed|Ignored")]),
        dict(singular="Event", plural="Events", prefix="", icon="activity", desc="Things users do in the app.",
             fields=[("Event", "words:habit_created|streak_completed|reminder_opened|premium_started|share_tapped"), ("Count today", "int:400-90000"), ("Users", "int:200-40000"), ("Change", "pct:0-30"), ("Trend", "status:Up|Flat|Down")]),
        dict(singular="Review", plural="Reviews", prefix="", icon="star", desc="What people say in the app stores.",
             fields=[("Reviewer", "person"), ("Store", "choice:App Store|Play Store"), ("Rating", "rating"), ("Date", "date"), ("Status", "status:Replied|New|Hidden")]),
        dict(singular="Campaign", plural="Push campaigns", slug="push-campaigns", prefix="", icon="bell", desc="Push notifications you sent.",
             fields=[("Campaign", "words:Streak reminder|Weekly recap|Premium trial|New feature|Win back"), ("Sent to", "int:2000-80000"), ("Open rate", "pct:4-40"), ("Sent", "date"), ("Status", "status:Sent|Scheduled|Draft")]),
    ],
    specials=[
        dict(title="Funnel", type="report", icon="chart", desc="From install to paying user.", items=["Installs", "Signed up", "Day 7 retention", "Paying users"], rows=["Install", "Sign up", "First habit", "Day 7", "Premium"]),
        dict(title="Live users", type="monitor", icon="activity", desc="Activity in the app right now.", items=["Users online", "Sessions", "Habits logged", "Crashes", "Premium starts", "Push opens"], unit=""),
        dict(title="Users by country", type="map", icon="globe", desc="Where your users are.", items=["United States", "Brazil", "Germany", "India", "Japan"]),
        dict(title="Top screens", type="ranking", icon="trend", desc="Screens people spend the most time on.", items=["Habit list", "Streak calendar", "Stats", "Add habit", "Settings", "Premium"], metric="Minutes", scale=400),
        dict(title="Review inbox", type="split", icon="inbox", desc="Reply to app store reviews.", items=["Love the streaks!", "App crashes on login", "Please add dark mode", "Worth the premium", "Reminders stopped working"]),
        dict(title="Release plan", type="kanban", icon="kanban", desc="Features from idea to store.", items=["Ideas", "Building", "Testing", "In review", "Released"], cards=["Home screen widget", "Dark mode", "Habit groups", "Apple Watch app"]),
        dict(title="Tracking settings", type="config", icon="settings", desc="What the app measures.", items=["Ask users before tracking", "Send crash reports automatically", "Hide user names in reports", "Keep raw data for 90 days"]),
    ],
))
