"""Batch 10: The final five dashboards (numbers 96 to 100)."""

B10 = []

B10.append(dict(
    num=96, slug="verdict", brand="Verdict", category="Surveys and NPS", org="Harborline Software", currency="$",
    tagline="Surveys, responses and customer loyalty scores in one place.",
    auth_line="Ask better questions. Act on the answers.", user="Chloe Rahman", user_role="Customer insights lead",
    theme=dict(fonts=["Gloock", "Inter", "JetBrains Mono", "Inter"], accent="#0d9488", layout="light", card="border", radius="12px",
               c2="#5eead4", c3="#f59e0b", c4="#e11d48"),
    kpis=[("Net promoter score", "int", 46, "star"), ("Responses this month", "int", 4820, "message"), ("Response rate", "pct", 32.4, "inbox"), ("Customer satisfaction", "pct", 88.6, "heart")],
    chart=dict(title="Responses", names=["Responses", "Last year"], base=4200),
    mix=dict(title="Customers by score", parts=["Promoters", "Passives", "Detractors", "No answer", "Other"]),
    activity=["Survey sent to 12,000 customers", "Detractor follow-up assigned to Ben", "New question added: onboarding", "Monthly insight report shared", "Response rate up 4 percent", "Survey closed: pricing feedback"],
    entities=[
        dict(singular="Survey", plural="Surveys", prefix="", icon="list", desc="Surveys you run.",
             fields=[("Survey", "words:Quarterly NPS|Onboarding feedback|Pricing survey|Support satisfaction|Feature wishlist|Churn reasons"), ("Sent to", "int:500-12000"), ("Responses", "int:80-4000"), ("Response rate", "pct:8-60"), ("Status", "status:Live|Draft|Closed")]),
        dict(singular="Response", plural="Responses", prefix="R-", icon="message", desc="Answers from customers.",
             fields=[("Response", "id"), ("Customer", "person"), ("Survey", "words:Quarterly NPS|Onboarding feedback|Support satisfaction"), ("Score", "int:0-10"), ("Status", "status:New|Read|Followed up")]),
        dict(singular="Question", plural="Questions", prefix="", icon="help", desc="Questions in your surveys.",
             fields=[("Question", "words:How likely are you to recommend us?|How easy was setup?|What should we build next?|How was your support chat?|Why did you cancel?"), ("Type", "choice:Score 0 to 10|Rating|Multiple choice|Open text"), ("Answers", "int:100-9000"), ("Surveys", "int:1-6"), ("Status", "status:Active|Retired")]),
        dict(singular="Segment", plural="Segments", prefix="", icon="users", desc="Groups of customers.",
             fields=[("Segment", "words:New customers|Enterprise|Small business|Trial users|Long-term customers"), ("Customers", "int:200-9000"), ("NPS", "int:10-70"), ("Responses", "int:40-2000"), ("Trend", "status:Up|Flat|Down")]),
        dict(singular="Follow-up", plural="Follow-ups", prefix="", icon="check", desc="Actions after unhappy answers.",
             fields=[("Customer", "person"), ("Score", "int:0-6"), ("Owner", "person"), ("Due", "date:future"), ("Status", "status:Open|Contacted|Resolved")]),
    ],
    specials=[
        dict(title="NPS report", type="report", icon="chart", desc="Loyalty scores by segment and month.", items=["NPS", "Promoters", "Detractors", "Response rate"], rows=["New customers", "Enterprise", "Small business", "Trial users", "Long-term customers"]),
        dict(title="Read responses", type="split", icon="inbox", desc="Read open text answers one by one.", items=["Setup took too long", "Love the new dashboard", "Pricing is confusing", "Support was very quick", "Please add dark mode"], body="Score 6 of 10. The product works well, but setup took us two weeks and the docs were hard to follow. A setup call would have helped."),
        dict(title="Top themes", type="ranking", icon="trend", desc="What customers mention most.", items=["Ease of use", "Support speed", "Pricing", "Missing features", "Performance", "Onboarding"], metric="Mentions", scale=12),
        dict(title="Follow-up board", type="kanban", icon="kanban", desc="Close the loop with unhappy customers.", items=["New detractor", "Contacted", "Fix in progress", "Resolved"], cards=["Setup problems", "Billing confusion", "Missing feature", "Slow support"]),
        dict(title="Survey calendar", type="calendar", icon="calendar", desc="When each survey goes out.", items=["NPS survey", "Onboarding survey", "Pricing survey", "Report due", "Team review"]),
        dict(title="Survey preview", type="document", icon="file", desc="How the survey looks to customers.", doc="Quarterly NPS survey", num="Q3 2026", items=["Recommend score", "Main reason", "Ease of use rating", "Anything else"], note="Preview only. The table shows how many answers each question received."),
        dict(title="Survey settings", type="config", icon="settings", desc="How surveys are sent.", items=["Send each customer at most one survey a month", "Alert the account owner on scores of 6 or below", "Close surveys after 14 days", "Hide names in shared reports"]),
    ],
))

B10.append(dict(
    num=97, slug="gatepass", brand="Gatepass", category="Events and Ticketing", org="Northside Live", currency="$",
    tagline="Events, tickets, check-ins and payouts for a live events company.",
    auth_line="Sell out the night. Get everyone in fast.", user="Leo Mensah", user_role="Events director",
    theme=dict(fonts=["Anton", "Barlow", "Space Mono", "Barlow"], accent="#db2777", layout="dark", card="shadow", radius="10px", sidebar="#150a12",
               c2="#f9a8d4", c3="#f59e0b", c4="#22d3ee"),
    kpis=[("Tickets sold this month", "int", 18400, "tag"), ("Ticket revenue", "money", 642000, "dollar"), ("Events this month", "int", 24, "calendar"), ("Check-in rate", "pct", 92.4, "check")],
    chart=dict(title="Tickets sold", names=["This year", "Last year"], base=16000),
    mix=dict(title="Sales by channel", parts=["Website", "App", "Box office", "Partners", "Other"]),
    activity=["Friday concert sold out", "VIP upgrades sold: 120", "Door staff briefed for Saturday", "Payout sent for the jazz night", "Presale code shared with members", "Refunds issued for the moved show"],
    entities=[
        dict(singular="Event", plural="Events", prefix="", icon="calendar", desc="Shows and events on sale.",
             fields=[("Event", "words:Friday night concert|Jazz in the park|Comedy club night|Food festival|Indie showcase|New year party"), ("Venue", "words:Harbour Hall|City Arena|The Loft|Riverside Park|Club Luna"), ("Date", "date:future"), ("Sold", "pct:20-100"), ("Status", "status:On sale|Sold out|Announced|Cancelled")]),
        dict(singular="Order", plural="Orders", prefix="ORD-", icon="cart", desc="Ticket orders.",
             fields=[("Order", "id"), ("Buyer", "person"), ("Tickets", "int:1-8"), ("Total", "money:20-900"), ("Status", "status:Paid|Refunded|Pending")]),
        dict(singular="Ticket type", plural="Ticket types", slug="ticket-types", prefix="", icon="tag", desc="Prices and allocations.",
             fields=[("Ticket", "words:Early bird|General admission|VIP|Student|Group of 4|Balcony seat"), ("Price", "money:15-240"), ("Allocation", "int:50-4000"), ("Sold", "pct:10-100"), ("Status", "status:On sale|Sold out|Hidden")]),
        dict(singular="Venue", plural="Venues", prefix="", icon="building", desc="Places you run events.",
             fields=[("Venue", "words:Harbour Hall|City Arena|The Loft|Riverside Park|Club Luna"), ("Capacity", "int:200-12000"), ("Events this year", "int:2-60"), ("City", "city"), ("Status", "status:Available|Booked|Closed")]),
        dict(singular="Attendee", plural="Attendees", prefix="", icon="users", desc="People with tickets.",
             fields=[("Attendee", "person"), ("Event", "words:Friday night concert|Jazz in the park|Comedy club night"), ("Ticket", "choice:General admission|VIP|Student"), ("Checked in", "time"), ("Status", "status:Checked in|Not arrived|Refunded")]),
    ],
    specials=[
        dict(title="Door check-in", type="monitor", icon="activity", desc="Live entry numbers at each gate.", items=["Main gate", "VIP entrance", "Box office", "Side door", "Accessible entrance", "Staff entrance"], unit=" people"),
        dict(title="Event calendar", type="calendar", icon="calendar", desc="Shows, on-sale dates and load-ins.", items=["Concert", "Comedy night", "On sale date", "Load in", "Festival"]),
        dict(title="Sales report", type="report", icon="chart", desc="Tickets, revenue and fees.", items=["Tickets sold", "Revenue", "Average order", "Refund rate"], rows=["Website", "App", "Box office", "Partners", "Resale"]),
        dict(title="Best sellers", type="ranking", icon="star", desc="Events that sold the most tickets.", items=["Friday night concert", "Food festival", "New year party", "Jazz in the park", "Indie showcase", "Comedy club night"], metric="Tickets", scale=40),
        dict(title="Seat map", type="map", icon="map", desc="Sold and open sections.", items=["Floor", "Lower tier", "Upper tier", "Balcony", "VIP boxes"], dots=20),
        dict(title="Event settlement", type="document", icon="receipt", desc="Money from one event, explained.", doc="Event settlement", num="Friday night concert", items=["Ticket sales", "Booking fees", "Venue hire", "Security", "Artist fee"], note="Settlement agreed with the promoter after the show."),
        dict(title="Ticketing rules", type="config", icon="shield", desc="Protect sales and entry.", items=["Limit 6 tickets per order", "Show QR codes only on the day of the event", "Allow refunds up to 7 days before", "Block resale above face value"]),
    ],
))

B10.append(dict(
    num=98, slug="buildcare", brand="Buildcare", category="Facility Management", org="Crescent Office Park", currency="$",
    tagline="Buildings, work orders, assets and energy for a facilities team.",
    auth_line="Buildings that just work.", user="Omar Larsen", user_role="Facilities manager",
    theme=dict(fonts=["PT Sans", "PT Sans", "PT Mono"], accent="#0369a1", layout="tint", card="border", radius="8px",
               c2="#7dd3fc", c3="#f59e0b", c4="#10b981"),
    kpis=[("Open work orders", "int", 64, "tool"), ("Solved this week", "int", 142, "check"), ("Energy this month kWh", "int", 184000, "zap"), ("Desk use", "pct", 68.4, "grid")],
    chart=dict(title="Work orders", names=["Opened", "Closed"], base=180),
    mix=dict(title="Work orders by trade", parts=["Heating and cooling", "Electrical", "Plumbing", "Cleaning", "Security"]),
    activity=["Lift 2 back in service", "Air handling unit serviced in Block B", "Leak fixed in the 3rd floor kitchen", "Fire alarm test passed", "New cleaning contract started", "Meeting room screen replaced"],
    entities=[
        dict(singular="Work order", plural="Work orders", slug="work-orders", prefix="WO-", icon="tool", desc="Repairs and jobs.",
             fields=[("Work order", "id"), ("Issue", "choice:Too hot|Too cold|Leak|Light out|Door fault|Lift fault"), ("Building", "choice:Block A|Block B|Block C|Car park"), ("Priority", "choice:Urgent|High|Normal|Low"), ("Status", "status:Open|Assigned|In progress|Done")]),
        dict(singular="Asset", plural="Assets", prefix="AS-", icon="box", desc="Equipment you look after.",
             fields=[("Asset", "id"), ("Type", "choice:Boiler|Air handling unit|Lift|Generator|Fire panel"), ("Building", "choice:Block A|Block B|Block C"), ("Next service", "date:future"), ("Status", "status:Working|Needs service|Fault")]),
        dict(singular="Building", plural="Buildings", prefix="", icon="building", desc="Buildings on the site.",
             fields=[("Building", "words:Block A|Block B|Block C|Conference centre|Car park"), ("Floors", "int:1-8"), ("People today", "int:20-900"), ("Open jobs", "int:0-24"), ("Status", "status:Open|Partly closed|Closed")]),
        dict(singular="Contractor", plural="Contractors", prefix="", icon="users", desc="Companies that do the work.",
             fields=[("Contractor", "company"), ("Trade", "choice:Heating|Electrical|Plumbing|Cleaning|Security"), ("Jobs this month", "int:2-60"), ("On time", "pct:70-99"), ("Status", "status:Approved|On review")]),
        dict(singular="Room booking", plural="Room bookings", slug="room-bookings", prefix="", icon="calendar", desc="Meeting rooms and spaces.",
             fields=[("Room", "words:Board room|Room 2.1|Room 3.4|Training room|Quiet room"), ("Booked by", "person"), ("Date", "date:future"), ("Time", "time"), ("Status", "status:Confirmed|Cancelled|No show")]),
    ],
    specials=[
        dict(title="Building systems", type="monitor", icon="activity", desc="Live status of key systems.", items=["Heating", "Cooling", "Lifts", "Fire alarms", "Access control", "Water", "Generator", "Lighting"]),
        dict(title="Job board", type="kanban", icon="kanban", desc="Work orders from report to done.", items=["Reported", "Assigned", "In progress", "Waiting for parts", "Done"], cards=["Too hot in 3.4", "Leak in kitchen", "Light out in stairwell", "Door not closing"]),
        dict(title="Site map", type="map", icon="map", desc="Open jobs across the site.", items=["Block A", "Block B", "Block C", "Conference centre", "Car park"], dots=18),
        dict(title="Service calendar", type="calendar", icon="calendar", desc="Planned maintenance and tests.", items=["Boiler service", "Fire alarm test", "Lift inspection", "Window cleaning", "Generator test"]),
        dict(title="Facilities report", type="report", icon="chart", desc="Jobs, costs and energy.", items=["Jobs closed", "Time to fix", "Energy use", "Maintenance cost"], rows=["Heating and cooling", "Electrical", "Plumbing", "Cleaning", "Security"]),
        dict(title="Energy by building", type="ranking", icon="zap", desc="Which buildings use the most power.", items=["Block B", "Block A", "Conference centre", "Block C", "Car park"], metric="kWh", scale=700),
        dict(title="Site rules", type="config", icon="settings", desc="Rules for the facilities team.", items=["Reply to urgent jobs within 1 hour", "Book lift inspections every 6 months", "Turn off lights after 8pm in empty rooms", "Text people when their job is done"]),
    ],
))

B10.append(dict(
    num=99, slug="fieldhand", brand="Fieldhand", category="Field Service", org="Brightfix Home Services", currency="$",
    tagline="Jobs, technicians, routes and invoices for a home services company.",
    auth_line="The right technician, at the right door.", user="Sofia Walsh", user_role="Service manager",
    theme=dict(fonts=["Barlow Condensed", "Barlow", "Roboto Mono", "Barlow"], accent="#ea580c", layout="light", card="shadow", radius="10px",
               c2="#fdba74", c3="#0ea5e9", c4="#22c55e"),
    kpis=[("Jobs today", "int", 86, "tool"), ("Technicians out", "int", 24, "truck"), ("First visit fix", "pct", 84.2, "check"), ("Revenue this week", "money", 48200, "dollar")],
    chart=dict(title="Jobs completed", names=["Completed", "Booked"], base=380),
    mix=dict(title="Jobs by type", parts=["Heating", "Plumbing", "Electrical", "Appliances", "Other"]),
    activity=["Job J-4412 completed by Luis", "Emergency call: burst pipe", "Route updated for the north team", "Part ordered: boiler fan", "Invoice paid by the Chen family", "New technician started"],
    entities=[
        dict(singular="Job", plural="Jobs", prefix="J-", icon="tool", desc="Every visit booked.",
             fields=[("Job", "id"), ("Customer", "person"), ("Type", "choice:Boiler service|Leak repair|Socket fault|Washing machine|Heat pump check"), ("Time", "time"), ("Status", "status:Scheduled|On the way|In progress|Completed")]),
        dict(singular="Technician", plural="Technicians", prefix="", icon="user", desc="Your team in the field.",
             fields=[("Technician", "person"), ("Skill", "choice:Heating|Plumbing|Electrical|Appliances"), ("Jobs today", "int:1-8"), ("Rating", "rating"), ("Status", "status:On a job|Driving|Available|Off")]),
        dict(singular="Customer", plural="Customers", prefix="", icon="users", desc="Homes and businesses you serve.",
             fields=[("Customer", "person"), ("Area", "choice:North|South|East|West|City centre"), ("Jobs", "int:1-24"), ("Plan", "choice:Pay per visit|Care plan|Business contract"), ("Status", "status:Active|New|Inactive")]),
        dict(singular="Part", plural="Parts", prefix="", icon="box", desc="Stock in vans and the warehouse.",
             fields=[("Part", "words:Boiler fan|Pressure valve|Washer seals|Thermostat|Socket kit|Fuse set"), ("In stock", "int:0-200"), ("In vans", "int:0-40"), ("Price", "money:4-180"), ("Status", "status:In stock|Low|Out of stock")]),
        dict(singular="Invoice", plural="Invoices", prefix="INV-", icon="receipt", desc="Bills for finished jobs.",
             fields=[("Invoice", "id"), ("Customer", "person"), ("Job", "code:J-"), ("Amount", "money:60-1800"), ("Status", "status:Paid|Sent|Overdue")]),
    ],
    specials=[
        dict(title="Dispatch board", type="kanban", icon="kanban", desc="Today's jobs by stage.", items=["Unassigned", "Scheduled", "On the way", "In progress", "Completed"], cards=["Boiler service", "Leak repair", "Socket fault", "Washing machine"]),
        dict(title="Live map", type="map", icon="map", desc="Technicians and jobs right now.", items=["North", "South", "East", "West", "City centre"], dots=22),
        dict(title="Schedule", type="calendar", icon="calendar", desc="Jobs across the week.", items=["Boiler service", "Emergency call", "Installation", "Annual check", "Training"]),
        dict(title="Service report", type="report", icon="chart", desc="Jobs, speed and revenue.", items=["Jobs completed", "First visit fix", "Time on site", "Revenue per job"], rows=["Heating", "Plumbing", "Electrical", "Appliances", "Other"]),
        dict(title="Top technicians", type="ranking", icon="star", desc="Jobs completed this month.", items=["Luis Garcia", "Maya Chen", "Tom Novak", "Aisha Khan", "Ben Walsh", "Sara Diaz"], metric="Jobs", scale=1.2),
        dict(title="Job sheet", type="document", icon="file", desc="A printable job sheet and invoice.", doc="Job sheet", num="J-1047, boiler repair", items=["Call out", "Labour, 1.5 hours", "Boiler fan", "Pressure valve"], note="Work tested and signed off by the customer."),
        dict(title="Dispatch rules", type="config", icon="settings", desc="How jobs are assigned.", items=["Send the nearest free technician to emergencies", "Text customers when the technician is on the way", "Book follow-up visits within 3 days", "Ask for a rating after every job"]),
    ],
))

B10.append(dict(
    num=100, slug="wrench", brand="Wrench", category="Auto Repair Workshop", org="Wrench and Co. Garage", currency="$",
    tagline="Bookings, repairs, parts and invoices for a car repair workshop.",
    auth_line="Fixed right, first time.", user="Carlos Kim", user_role="Workshop manager",
    theme=dict(fonts=["Russo One", "Inter", "Share Tech Mono", "Inter"], accent="#facc15", on_accent="#111827", layout="dark", card="border", radius="4px", sidebar="#111111",
               c2="#fde68a", c3="#ef4444", c4="#38bdf8"),
    kpis=[("Cars in today", "int", 18, "truck"), ("Bays in use", "pct", 83.0, "tool"), ("Jobs waiting for parts", "int", 4, "box"), ("Revenue this week", "money", 24800, "dollar")],
    chart=dict(title="Cars serviced", names=["Serviced", "Last year"], base=320),
    mix=dict(title="Work by type", parts=["Service", "Brakes", "Tyres", "Diagnostics", "Bodywork"]),
    activity=["MOT passed for the Chen family car", "Brake pads fitted on bay 2", "Parts delivered: oil filters", "Customer approved extra work", "Car ready for collection", "Tyre stock updated"],
    entities=[
        dict(singular="Job", plural="Jobs", prefix="JB-", icon="tool", desc="Repairs in the workshop.",
             fields=[("Job", "id"), ("Car", "words:2019 hatchback|2021 SUV|2017 estate|2022 electric|2016 van|2020 saloon"), ("Work", "choice:Full service|Brake pads|New tyres|Diagnostics|Clutch|Air con"), ("Mechanic", "person"), ("Status", "status:Waiting|In the bay|Waiting for parts|Ready")]),
        dict(singular="Booking", plural="Bookings", prefix="", icon="calendar", desc="Cars booked in.",
             fields=[("Customer", "person"), ("Car", "words:2019 hatchback|2021 SUV|2017 estate|2022 electric"), ("Date", "date:future"), ("Time", "time"), ("Status", "status:Booked|Confirmed|Cancelled")]),
        dict(singular="Customer", plural="Customers", prefix="", icon="users", desc="Drivers and their cars.",
             fields=[("Customer", "person"), ("Cars", "int:1-3"), ("Visits", "int:1-20"), ("Spent", "money:80-6000"), ("Status", "status:Regular|New|Lapsed")]),
        dict(singular="Part", plural="Parts", prefix="", icon="box", desc="Parts in stock.",
             fields=[("Part", "words:Oil filter|Brake pads|Air filter|Wiper blades|Battery|Spark plugs"), ("In stock", "int:0-120"), ("Reorder at", "int:4-30"), ("Price", "money:6-240"), ("Status", "status:In stock|Low|Out of stock")]),
        dict(singular="Invoice", plural="Invoices", prefix="INV-", icon="receipt", desc="Bills for finished work.",
             fields=[("Invoice", "id"), ("Customer", "person"), ("Work", "choice:Full service|Brakes|Tyres|Diagnostics|MOT"), ("Amount", "money:60-2400"), ("Status", "status:Paid|Due|Overdue")]),
    ],
    specials=[
        dict(title="Workshop board", type="kanban", icon="kanban", desc="Cars from check-in to collection.", items=["Checked in", "Inspecting", "In the bay", "Waiting for parts", "Ready"], cards=["Full service", "Brake pads", "Diagnostics", "Clutch repair"]),
        dict(title="Bay status", type="monitor", icon="activity", desc="What is happening in each bay.", items=["Bay 1", "Bay 2", "Bay 3", "Bay 4", "MOT bay", "Tyre bay"], unit=" min"),
        dict(title="Booking calendar", type="calendar", icon="calendar", desc="Cars booked in this month.", items=["Service", "MOT", "Tyres", "Diagnostics", "Collection"]),
        dict(title="Workshop report", type="report", icon="chart", desc="Jobs, hours and revenue.", items=["Jobs completed", "Labour hours", "Parts sales", "Comebacks"], rows=["Service", "Brakes", "Tyres", "Diagnostics", "Bodywork"]),
        dict(title="Repair quote", type="document", icon="file", desc="A printable quote for a customer.", doc="Repair quote", num="JB-1047, 2021 SUV", items=["Front brake pads", "Front brake discs", "Labour, 2 hours", "Brake fluid"], note="Quote valid for 14 days. We will call you before doing any extra work."),
        dict(title="Top mechanics", type="ranking", icon="star", desc="Jobs completed this month.", items=["Carlos Kim", "Sam Rossi", "Nadia Evans", "Omar Silva", "Leo Park"], metric="Jobs", scale=0.8),
        dict(title="Workshop rules", type="config", icon="shield", desc="How the workshop runs.", items=["Call customers before any extra work", "Text customers when the car is ready", "Road test every car after brake work", "Remind customers when their MOT is due"]),
    ],
))
