"""Batch 6: Health and hospitality dashboards (numbers 56 to 65)."""

B6 = []

B6.append(dict(
    num=56, slug="dispensa", brand="Dispensa", category="Pharmacy", org="Greenway Pharmacy", currency="$",
    tagline="Prescriptions, stock and patients for a community pharmacy.",
    auth_line="Every prescription ready on time.", user="Farid Novak", user_role="Lead pharmacist",
    theme=dict(fonts=["Inclusive Sans", "Inclusive Sans", "Roboto Mono"], accent="#047857", layout="light", card="border", radius="10px",
               c2="#6ee7b7", c3="#f59e0b", c4="#6366f1"),
    kpis=[("Prescriptions today", "int", 386, "file"), ("Ready for pickup", "int", 64, "check"), ("Items low on stock", "int", 22, "alert"), ("Sales this week", "money", 42800, "dollar")],
    chart=dict(title="Prescriptions filled", names=["Filled", "Received"], base=340),
    mix=dict(title="Sales by type", parts=["Prescriptions", "Over the counter", "Health and beauty", "Vaccines", "Other"]),
    activity=["Prescription RX-4412 ready for pickup", "Flu vaccine clinic fully booked", "Delivery from wholesaler received", "Stock alert: allergy tablets", "Repeat prescription requested online", "Controlled drugs register checked"],
    entities=[
        dict(singular="Prescription", plural="Prescriptions", prefix="RX-", icon="file", desc="Prescriptions received and filled.",
             fields=[("Prescription", "id"), ("Patient", "person"), ("Prescriber", "person"), ("Items", "int:1-6"), ("Status", "status:Ready|In progress|Waiting for stock|Collected")]),
        dict(singular="Patient", plural="Patients", prefix="", icon="users", desc="People who use your pharmacy.",
             fields=[("Patient", "person"), ("Phone", "phone"), ("Repeat items", "int:0-8"), ("Last visit", "date"), ("Status", "status:Active|Delivery|Inactive")]),
        dict(singular="Product", plural="Stock", slug="stock", prefix="", icon="box", desc="Medicines and products on the shelves.",
             fields=[("Product", "words:Allergy tablets|Pain relief gel|Cough syrup|Vitamin D|Sunscreen|Hand sanitiser"), ("In stock", "int:0-400"), ("Reorder at", "int:10-80"), ("Price", "money:2-40"), ("Status", "status:In stock|Low|Out of stock")]),
        dict(singular="Order", plural="Supplier orders", slug="supplier-orders", prefix="PO-", icon="truck", desc="Orders from wholesalers.",
             fields=[("Order", "id"), ("Supplier", "company"), ("Lines", "int:4-120"), ("Value", "money:200-9000"), ("Status", "status:Delivered|Ordered|Delayed")]),
        dict(singular="Appointment", plural="Services", slug="services", prefix="", icon="calendar", desc="Vaccines and health checks.",
             fields=[("Patient", "person"), ("Service", "choice:Flu vaccine|Blood pressure check|Travel vaccine|Medicine review"), ("Date", "date:future"), ("Time", "time"), ("Status", "status:Booked|Done|Cancelled")]),
    ],
    specials=[
        dict(title="Dispensing queue", type="kanban", icon="kanban", desc="Prescriptions from received to collected.", items=["Received", "Checking", "Dispensing", "Final check", "Ready"], cards=["Repeat prescription", "New prescription", "Delivery order", "Urgent item"]),
        dict(title="Clinic calendar", type="calendar", icon="calendar", desc="Vaccines and health checks booked.", items=["Flu vaccine", "Blood pressure check", "Travel clinic", "Medicine review", "Delivery run"]),
        dict(title="Pharmacy report", type="report", icon="chart", desc="Sales, prescriptions and stock.", items=["Prescriptions", "Retail sales", "Stock turn", "Waste"], rows=["Prescriptions", "Over the counter", "Health and beauty", "Vaccines", "Delivery"]),
        dict(title="Fridge monitor", type="monitor", icon="activity", desc="Live temperatures in medicine fridges.", items=["Vaccine fridge", "Insulin fridge", "Backup fridge", "Stock room", "Shop floor", "Delivery van"], unit=" C"),
        dict(title="Delivery routes", type="map", icon="map", desc="Home deliveries today.", items=["North", "Town centre", "Riverside", "East estate", "Villages"]),
        dict(title="Patient messages", type="split", icon="message", desc="Questions and repeat requests.", items=["Is my prescription ready?", "Can I get a flu jab today?", "Repeat request for my inhaler", "Delivery time question", "Side effects question"]),
        dict(title="Pharmacy settings", type="config", icon="settings", desc="How the pharmacy runs.", items=["Text patients when items are ready", "Require a second check for every item", "Alert when fridge temperature is out of range", "Reorder stock automatically"]),
    ],
))

B6.append(dict(
    num=57, slug="liftoff", brand="Liftoff", category="Gym and Fitness", org="Liftoff Strength Club", currency="$",
    tagline="Members, classes, trainers and check-ins for a busy gym.",
    auth_line="A full gym, running smoothly.", user="Marco Walsh", user_role="Gym manager",
    theme=dict(fonts=["Bebas Neue", "Inter", "JetBrains Mono", "Bebas Neue"], accent="#f97316", layout="dark", card="shadow", radius="8px", sidebar="#111111",
               c2="#fdba74", c3="#22d3ee", c4="#a3e635"),
    kpis=[("Active members", "int", 1840, "users"), ("Check-ins today", "int", 612, "check"), ("Classes this week", "int", 96, "calendar"), ("Monthly revenue", "money", 84200, "dollar")],
    chart=dict(title="Check-ins", names=["Check-ins", "Class bookings"], base=560),
    mix=dict(title="Members by plan", parts=["Monthly", "Annual", "Student", "Off-peak", "Class pack"]),
    activity=["HIIT class at 6pm is full", "New member joined: Priya Adams", "Trainer shift swapped", "Treadmill 4 marked for repair", "Membership frozen for 1 month", "Personal training package sold"],
    entities=[
        dict(singular="Member", plural="Members", prefix="", icon="users", desc="Everyone with a membership.",
             fields=[("Member", "person"), ("Plan", "choice:Monthly|Annual|Student|Off-peak"), ("Visits this month", "int:0-28"), ("Joined", "date"), ("Status", "status:Active|Frozen|Cancelled")]),
        dict(singular="Class", plural="Classes", slug="classes", prefix="", icon="calendar", desc="Group classes on the timetable.",
             fields=[("Class", "words:HIIT|Spin|Yoga|Boxing|Pilates|Strength basics"), ("Trainer", "person"), ("Time", "time"), ("Booked", "int:4-30"), ("Status", "status:Open|Full|Cancelled")]),
        dict(singular="Trainer", plural="Trainers", prefix="", icon="user", desc="Coaches and instructors.",
             fields=[("Trainer", "person"), ("Speciality", "choice:Strength|Cardio|Yoga|Boxing|Rehab"), ("Clients", "int:4-30"), ("Rating", "rating"), ("Status", "status:On shift|Off|Holiday")]),
        dict(singular="Check-in", plural="Check-ins", prefix="", icon="check", desc="Door entries today.",
             fields=[("Member", "person"), ("Time", "time"), ("Area", "choice:Gym floor|Studio|Pool|Sauna"), ("Plan", "choice:Monthly|Annual|Student|Off-peak"), ("Status", "status:Allowed|Denied")]),
        dict(singular="Equipment", plural="Equipment", slug="equipment", prefix="EQ-", icon="tool", desc="Machines and their condition.",
             fields=[("Item", "words:Treadmill 4|Rowing machine 2|Squat rack 1|Bike 7|Cable machine|Leg press"), ("Area", "choice:Cardio|Weights|Studio"), ("Last service", "date"), ("Uses today", "int:4-120"), ("Status", "status:Working|Repair|Out of order")]),
    ],
    specials=[
        dict(title="Class timetable", type="calendar", icon="calendar", desc="Every class this month.", items=["HIIT", "Spin", "Yoga", "Boxing", "Pilates"]),
        dict(title="Gym floor now", type="monitor", icon="activity", desc="How busy each area is right now.", items=["Gym floor", "Cardio zone", "Free weights", "Studio 1", "Studio 2", "Pool", "Sauna", "Changing rooms"], unit=" people"),
        dict(title="Membership report", type="report", icon="chart", desc="Joins, leavers and revenue.", items=["New members", "Cancellations", "Revenue", "Visits per member"], rows=["Monthly", "Annual", "Student", "Off-peak", "Class pack"]),
        dict(title="Top attendees", type="ranking", icon="star", desc="Members who came most this month.", items=["Priya Adams", "Leo Costa", "Zoe Kim", "Omar Ali", "Sara Novak", "Ben Ito"], metric="Visits", scale=0.3),
        dict(title="Sales pipeline", type="kanban", icon="kanban", desc="Leads from first visit to member.", items=["Enquiry", "Tour booked", "Free trial", "Joined", "Lost"], cards=["Monthly plan", "Annual plan", "PT package", "Student plan"]),
        dict(title="Membership invoice", type="document", icon="receipt", desc="A member's monthly invoice.", doc="Membership invoice", num="September 2026", items=["Monthly membership", "Personal training, 4 sessions", "Locker hire", "Protein shake bar"]),
        dict(title="Gym rules", type="config", icon="settings", desc="Settings for access and bookings.", items=["Allow class booking 7 days ahead", "Charge for late cancellations", "Let off-peak members in before 4pm only", "Text members about full classes"]),
    ],
))

B6.append(dict(
    num=58, slug="wellnote", brand="Wellnote", category="Personal Health", org="Personal health log", currency="$",
    tagline="Sleep, steps, heart rate and habits in one friendly health log.",
    auth_line="Small habits. Better days.", user="Sara Chen", user_role="Personal account",
    theme=dict(fonts=["M PLUS Rounded 1c", "Nunito Sans", "Roboto Mono"], accent="#e11d48", layout="tint", card="shadow", radius="20px",
               c2="#fda4af", c3="#6366f1", c4="#14b8a6"),
    kpis=[("Steps today", "int", 8420, "activity"), ("Sleep last night", "int", 7, "clock"), ("Resting heart rate", "int", 62, "heart"), ("Water today", "pct", 75.0, "check")],
    chart=dict(title="Daily steps", names=["Steps", "Goal"], base=8000),
    mix=dict(title="Activity this week", parts=["Walking", "Running", "Cycling", "Yoga", "Other"]),
    activity=["Reached 10,000 steps", "Logged 30 minute yoga", "Slept 7 hours 40 minutes", "Drank 8 glasses of water", "Weekly goal reached: 4 workouts", "Doctor visit added to calendar"],
    entities=[
        dict(singular="Workout", plural="Workouts", prefix="", icon="activity", desc="Exercise you logged.",
             fields=[("Workout", "words:Morning run|Evening walk|Yoga|Bike ride|Swim|Strength training"), ("Date", "date"), ("Duration", "duration"), ("Calories", "int:80-800"), ("Status", "status:Done|Planned|Skipped")]),
        dict(singular="Sleep", plural="Sleep log", slug="sleep-log", prefix="", icon="moon", desc="How you slept each night.",
             fields=[("Night", "date"), ("Hours", "int:5-9"), ("Deep sleep", "pct:10-30"), ("Woke up", "time"), ("Status", "status:Good|Okay|Poor")]),
        dict(singular="Meal", plural="Meals", prefix="", icon="heart", desc="Food and drink you logged.",
             fields=[("Meal", "words:Oats with berries|Chicken salad|Lentil soup|Salmon and rice|Greek yogurt|Veggie wrap"), ("Type", "choice:Breakfast|Lunch|Dinner|Snack"), ("Date", "date"), ("Calories", "int:150-800"), ("Status", "status:Logged|Planned")]),
        dict(singular="Measurement", plural="Measurements", prefix="", icon="chart", desc="Numbers you track over time.",
             fields=[("Measurement", "words:Resting heart rate|Blood pressure|Weight|Steps|Water"), ("Value", "words:62 bpm|118/76|64 kg|8,420|2.1 litres"), ("Date", "date"), ("Source", "choice:Watch|Phone|Manual"), ("Status", "status:Normal|Check")]),
        dict(singular="Appointment", plural="Appointments", prefix="", icon="calendar", desc="Health appointments.",
             fields=[("Appointment", "words:GP check-up|Dentist|Eye test|Physio|Blood test"), ("Where", "city"), ("Date", "date:future"), ("Time", "time"), ("Status", "status:Booked|Done|Cancelled")]),
    ],
    specials=[
        dict(title="Habits", type="kanban", icon="kanban", desc="Habits you are building.", items=["To start", "Building", "Most days", "Every day"], cards=["Walk after lunch", "Drink 8 glasses", "Stretch before bed", "No screens after 10pm"]),
        dict(title="Weekly summary", type="report", icon="chart", desc="How your week compares with the last.", items=["Steps", "Sleep", "Workouts", "Water"], rows=["Monday", "Tuesday", "Wednesday", "Thursday", "Friday"]),
        dict(title="Health calendar", type="calendar", icon="calendar", desc="Workouts and appointments.", items=["Run", "Yoga", "Doctor visit", "Swim", "Rest day"]),
        dict(title="Today", type="monitor", icon="activity", desc="Your numbers so far today.", items=["Steps", "Active minutes", "Water", "Heart rate", "Stand hours", "Mindful minutes"], unit=""),
        dict(title="Personal bests", type="ranking", icon="star", desc="Your best days this year.", items=["Most steps", "Longest run", "Longest sleep", "Most active minutes", "Most water"], metric="Score", scale=1),
        dict(title="Health journal", type="timeline", icon="book", desc="Notes about how you feel.", items=["Felt great after the morning run", "Slept badly, too much coffee", "Started stretching before bed", "Knee felt fine on the long walk"]),
        dict(title="Reminders", type="config", icon="bell", desc="Gentle nudges during the day.", items=["Remind me to drink water every 2 hours", "Nudge me to stand every hour", "Bedtime reminder at 10:30pm", "Weekly summary on Sunday"]),
    ],
    faq=[("Is this medical advice?", "No. This is a demo template. Talk to a doctor about any health questions.")],
))

B6.append(dict(
    num=59, slug="pawpoint", brand="Pawpoint", category="Veterinary Clinic", org="Pawpoint Animal Hospital", currency="$",
    tagline="Pets, owners, appointments and treatments for a vet clinic.",
    auth_line="Happy pets, organised clinic.", user="Dr. Hugo Silva", user_role="Head vet",
    theme=dict(fonts=["Lilita One", "Nunito", "Roboto Mono", "Nunito"], accent="#6d28d9", layout="accent", card="border", radius="16px",
               c2="#c4b5fd", c3="#f59e0b", c4="#10b981"),
    kpis=[("Appointments today", "int", 38, "calendar"), ("Pets in care", "int", 7, "heart"), ("Vaccines due", "int", 64, "bell"), ("Revenue this month", "money", 62400, "dollar")],
    chart=dict(title="Appointments", names=["Booked", "Walk-ins"], base=640),
    mix=dict(title="Patients by species", parts=["Dogs", "Cats", "Rabbits", "Birds", "Other"]),
    activity=["Bella (dog) discharged after surgery", "Vaccine reminders sent to 40 owners", "New patient: Milo the cat", "Lab results in for Charlie", "Kennel 3 cleaned", "Invoice paid by the Garcia family"],
    entities=[
        dict(singular="Patient", plural="Patients", prefix="", icon="heart", desc="Pets registered at the clinic.",
             fields=[("Pet", "words:Bella|Milo|Charlie|Luna|Max|Coco|Oscar|Daisy"), ("Species", "choice:Dog|Cat|Rabbit|Bird"), ("Owner", "person"), ("Last visit", "date"), ("Status", "status:Healthy|Under treatment|Vaccine due")]),
        dict(singular="Owner", plural="Owners", prefix="", icon="users", desc="Pet owners and their contact details.",
             fields=[("Owner", "person"), ("Phone", "phone"), ("Pets", "int:1-4"), ("Balance", "money:0-800"), ("Status", "status:Active|Balance due")]),
        dict(singular="Appointment", plural="Appointments", prefix="", icon="calendar", desc="Visits booked today and ahead.",
             fields=[("Pet", "words:Bella|Milo|Charlie|Luna|Max|Coco"), ("Reason", "choice:Vaccine|Check-up|Dental|Surgery|Limping"), ("Date", "date:future"), ("Time", "time"), ("Status", "status:Confirmed|Booked|Checked in|Cancelled")]),
        dict(singular="Treatment", plural="Treatments", prefix="TR-", icon="file", desc="Care given to each pet.",
             fields=[("Treatment", "id"), ("Pet", "words:Bella|Milo|Charlie|Luna|Max"), ("Type", "choice:Vaccination|Dental clean|Neutering|X-ray|Wound care"), ("Cost", "money:30-1800"), ("Status", "status:Done|Planned|In progress")]),
        dict(singular="Kennel", plural="Kennels", prefix="", icon="building", desc="Pets staying overnight.",
             fields=[("Kennel", "words:Kennel 1|Kennel 2|Kennel 3|Cat room A|Cat room B|Recovery"), ("Pet", "words:Bella|Oscar|Luna|Daisy"), ("Since", "date"), ("Checks today", "int:1-8"), ("Status", "status:Occupied|Free|Cleaning")]),
    ],
    specials=[
        dict(title="Day schedule", type="calendar", icon="calendar", desc="Consults and surgeries.", items=["Vaccine", "Check-up", "Surgery", "Dental", "Emergency"]),
        dict(title="Ward board", type="kanban", icon="kanban", desc="Pets in the clinic today.", items=["Checked in", "Waiting", "In surgery", "Recovering", "Ready to go home"], cards=["Bella, dog", "Milo, cat", "Charlie, dog", "Coco, rabbit"]),
        dict(title="Clinic report", type="report", icon="chart", desc="Visits, revenue and vaccines.", items=["Visits", "Revenue", "Vaccines given", "New patients"], rows=["Dogs", "Cats", "Rabbits", "Birds", "Exotics"]),
        dict(title="Vaccine reminders", type="timeline", icon="bell", desc="Reminders sent to owners.", items=["Bella: booster due next week", "Milo: first vaccine due", "Luna: rabies booster overdue", "Max: annual check-up due"]),
        dict(title="Treatment estimate", type="document", icon="file", desc="A printable estimate for an owner.", doc="Treatment estimate", num="TR-1047, Bella", items=["Consultation", "Dental clean under anaesthetic", "Blood test", "Pain relief to take home"], note="This estimate is valid for 30 days. Please call us with any questions."),
        dict(title="Owner messages", type="split", icon="message", desc="Messages from pet owners.", items=["How is Bella doing?", "Can I bring Milo in today?", "Price of a dental clean?", "Repeat flea treatment", "Thank you for looking after Coco"]),
        dict(title="Clinic settings", type="config", icon="settings", desc="How the clinic runs.", items=["Text owners 24 hours before a visit", "Send vaccine reminders 2 weeks early", "Send photos of pets after surgery", "Ask for a review after each visit"]),
    ],
))

B6.append(dict(
    num=60, slug="haven", brand="Haven", category="Therapy Practice", org="Haven Counselling Rooms", currency="$",
    tagline="Clients, sessions, notes and billing for a small therapy practice.",
    auth_line="Less admin, more time for clients.", user="Julia Moreau", user_role="Counsellor and practice owner",
    theme=dict(fonts=["Lora", "Karla", "IBM Plex Mono", "Karla"], accent="#3f6f5e", layout="light", card="flat", radius="12px",
               bg="#f7f5f1", surface="#fffdfa", surface2="#efece6", line="#e3ded5", c2="#a3c4b5", c3="#c08552", c4="#7c8db5"),
    kpis=[("Sessions this week", "int", 42, "calendar"), ("Active clients", "int", 36, "users"), ("Notes to finish", "int", 5, "file"), ("Invoices unpaid", "money", 1240, "dollar")],
    chart=dict(title="Sessions per week", names=["Sessions", "Cancellations"], base=40),
    mix=dict(title="Sessions by type", parts=["Individual", "Couples", "Online", "Group", "First meeting"]),
    activity=["Session note finished for client A.R.", "New enquiry from the website", "Room 2 booked for Thursday", "Invoice paid", "Supervision session added", "Reminder texts sent for tomorrow"],
    entities=[
        dict(singular="Client", plural="Clients", prefix="", icon="users", desc="People you are working with.",
             fields=[("Client", "person"), ("Counsellor", "person"), ("Sessions", "int:1-40"), ("Started", "date"), ("Status", "status:Active|Waiting list|Finished")]),
        dict(singular="Session", plural="Sessions", prefix="", icon="calendar", desc="Booked and past sessions.",
             fields=[("Client", "person"), ("Type", "choice:Individual|Couples|Online|Group"), ("Date", "date:future"), ("Time", "time"), ("Status", "status:Booked|Done|Cancelled")]),
        dict(singular="Note", plural="Session notes", slug="session-notes", prefix="", icon="file", desc="Private notes after each session.",
             fields=[("Client", "person"), ("Session date", "date"), ("Length", "duration"), ("Author", "person"), ("Status", "status:Finished|Draft")]),
        dict(singular="Invoice", plural="Invoices", prefix="INV-", icon="receipt", desc="Bills for sessions.",
             fields=[("Invoice", "id"), ("Client", "person"), ("Sessions", "int:1-4"), ("Amount", "money:60-320"), ("Status", "status:Paid|Sent|Overdue")]),
        dict(singular="Room", plural="Rooms", prefix="", icon="building", desc="Rooms you book for sessions.",
             fields=[("Room", "words:Room 1, garden view|Room 2, quiet room|Room 3, group room|Online room"), ("Bookings this week", "int:4-30"), ("Capacity", "int:1-10"), ("Last cleaned", "date"), ("Status", "status:Free|Booked|Closed")]),
    ],
    specials=[
        dict(title="Week diary", type="calendar", icon="calendar", desc="Sessions and supervision.", items=["Individual session", "Couples session", "Online session", "Supervision", "Group session"]),
        dict(title="Enquiries", type="kanban", icon="kanban", desc="New people from first contact to first session.", items=["New enquiry", "Call booked", "Waiting list", "First session booked"], cards=["Website form", "Phone enquiry", "GP referral", "Email enquiry"]),
        dict(title="Practice report", type="report", icon="chart", desc="Sessions, income and room use.", items=["Sessions", "Income", "Cancellation rate", "Room use"], rows=["Individual", "Couples", "Online", "Group", "First meeting"]),
        dict(title="Messages", type="split", icon="inbox", desc="Secure messages from clients.", items=["Can we move Thursday's session?", "Receipt for my insurance", "Running late today", "Question about fees", "Thank you for last week"]),
        dict(title="Session invoice", type="document", icon="receipt", desc="A printable invoice for a client.", doc="Invoice", num="INV-2026-0142", items=["Individual session, 50 minutes", "Individual session, 50 minutes", "Missed session fee"], note="Thank you. Please pay within 14 days."),
        dict(title="Room use", type="ranking", icon="building", desc="How often each room is booked.", items=["Room 1, garden view", "Room 2, quiet room", "Online room", "Room 3, group room"], metric="Hours", scale=0.4),
        dict(title="Privacy settings", type="config", icon="shield", desc="Keep client information safe.", items=["Lock notes 24 hours after a session", "Hide client names on the diary view", "Sign out after 10 minutes without activity", "Text reminders without session details"]),
    ],
))

B6.append(dict(
    num=61, slug="assay", brand="Assay", category="Diagnostic Lab", org="Clearview Diagnostics", currency="$",
    tagline="Samples, tests, results and machines for a diagnostic lab.",
    auth_line="Accurate results, on time, every time.", user="Kenji Haddad", user_role="Lab manager",
    theme=dict(fonts=["Roboto Condensed", "Roboto", "Roboto Mono"], accent="#1d4ed8", layout="dark", card="border", radius="4px", sidebar="#0f172a",
               c2="#93c5fd", c3="#f59e0b", c4="#10b981"),
    kpis=[("Samples today", "int", 1840, "box"), ("Results released", "int", 1520, "check"), ("Average turnaround hours", "int", 6, "clock"), ("Machines online", "int", 22, "monitor")],
    chart=dict(title="Samples received", names=["Received", "Completed"], base=1700),
    mix=dict(title="Tests by department", parts=["Blood tests", "Urine tests", "Microbiology", "Pathology", "Other"]),
    activity=["Batch 214 results released", "Analyser 3 calibrated", "Urgent sample from Ward 6 received", "Reagent stock low: glucose kit", "Quality control passed", "Courier pickup completed"],
    entities=[
        dict(singular="Sample", plural="Samples", prefix="S-", icon="box", desc="Samples received in the lab.",
             fields=[("Sample", "id"), ("Type", "choice:Blood|Urine|Swab|Tissue"), ("From", "choice:Ward 6|GP surgery|Outpatients|Emergency"), ("Received", "date"), ("Status", "status:Testing|Received|Completed|Rejected")]),
        dict(singular="Test", plural="Tests", prefix="", icon="list", desc="Tests the lab runs.",
             fields=[("Test", "words:Full blood count|Liver function|Glucose|Cholesterol|Urine culture|Vitamin D"), ("Today", "int:10-600"), ("Turnaround hours", "int:1-48"), ("Machine", "choice:Analyser 1|Analyser 2|Analyser 3|Manual"), ("Status", "status:Running|Paused")]),
        dict(singular="Result", plural="Results", prefix="R-", icon="file", desc="Results waiting for release.",
             fields=[("Result", "id"), ("Test", "words:Full blood count|Liver function|Glucose|Cholesterol"), ("Checked by", "person"), ("Ready", "date"), ("Status", "status:Released|Awaiting check|Repeat needed")]),
        dict(singular="Machine", plural="Machines", prefix="", icon="monitor", desc="Analysers and equipment.",
             fields=[("Machine", "words:Analyser 1|Analyser 2|Analyser 3|Centrifuge A|Microscope 2|Fridge 4"), ("Tests today", "int:0-900"), ("Last calibrated", "date"), ("Uptime", "pct:80-100"), ("Status", "status:Online|Maintenance|Offline")]),
        dict(singular="Reagent", plural="Reagents", prefix="", icon="layers", desc="Test kits and chemicals.",
             fields=[("Reagent", "words:Glucose kit|Cholesterol kit|Blood count reagent|Culture plates|Control serum"), ("In stock", "int:0-120"), ("Expires", "date:future"), ("Supplier", "company"), ("Status", "status:In stock|Low|Expired")]),
    ],
    specials=[
        dict(title="Machine status", type="monitor", icon="activity", desc="Live status of lab equipment.", items=["Analyser 1", "Analyser 2", "Analyser 3", "Centrifuge A", "Centrifuge B", "Microscope 2", "Fridge 4", "Incubator"]),
        dict(title="Sample tracker", type="kanban", icon="kanban", desc="Samples from arrival to result.", items=["Received", "Prepared", "Testing", "Checking", "Released"], cards=["Blood sample", "Urine sample", "Swab", "Urgent sample"]),
        dict(title="Turnaround report", type="report", icon="chart", desc="Speed and quality by department.", items=["Turnaround", "Samples", "Repeat rate", "Quality control"], rows=["Blood tests", "Urine tests", "Microbiology", "Pathology", "Urgent"]),
        dict(title="Collection points", type="map", icon="map", desc="Where samples come from.", items=["City hospital", "North GP", "South GP", "Outpatients", "Home visits"]),
        dict(title="Busiest tests", type="ranking", icon="trend", desc="Tests ordered most this week.", items=["Full blood count", "Glucose", "Cholesterol", "Liver function", "Vitamin D", "Urine culture"], metric="Tests", scale=30),
        dict(title="Lab report", type="document", icon="file", desc="A printable results report layout.", doc="Laboratory report", num="S-1047", items=["Full blood count", "Liver function panel", "Glucose", "Cholesterol"], note="Demo layout only. Values and prices are invented."),
        dict(title="Quality rules", type="config", icon="shield", desc="Quality checks in the lab.", items=["Run controls at the start of every shift", "Require a second check for urgent results", "Reject samples without two labels", "Alert when a fridge goes above 8 degrees"]),
    ],
))

B6.append(dict(
    num=62, slug="sprout", brand="Sprout", category="Nutrition Coach", org="Sprout Nutrition", currency="$",
    tagline="Clients, meal plans, check-ins and progress for a nutrition coach.",
    auth_line="Help clients eat well and feel better.", user="Leila Park", user_role="Nutrition coach",
    theme=dict(fonts=["DM Serif Display", "DM Sans", "DM Mono", "DM Sans"], accent="#4d7c0f", layout="tint", card="shadow", radius="16px",
               c2="#bef264", c3="#f97316", c4="#0ea5e9"),
    kpis=[("Active clients", "int", 48, "users"), ("Check-ins this week", "int", 41, "check"), ("Plans sent", "int", 12, "file"), ("Monthly income", "money", 8400, "dollar")],
    chart=dict(title="Client check-ins", names=["Check-ins", "Missed"], base=38),
    mix=dict(title="Client goals", parts=["More energy", "Better digestion", "Sports", "Healthy weight", "Other"]),
    activity=["Meal plan sent to Maya", "Check-in from Ben: feeling great", "New client booked a first call", "Recipe added: lentil curry", "Invoice paid", "Group workshop booked"],
    entities=[
        dict(singular="Client", plural="Clients", prefix="", icon="users", desc="People you coach.",
             fields=[("Client", "person"), ("Goal", "choice:More energy|Better digestion|Sports|Healthy weight"), ("Plan", "choice:Monthly|3 months|6 months"), ("Started", "date"), ("Status", "status:Active|Paused|Finished")]),
        dict(singular="Meal plan", plural="Meal plans", slug="meal-plans", prefix="", icon="file", desc="Weekly plans for clients.",
             fields=[("Plan", "words:High protein week|Plant based week|Easy lunches|Busy week plan|Family meals"), ("Client", "person"), ("Meals", "int:10-28"), ("Sent", "date"), ("Status", "status:Sent|Draft|Viewed")]),
        dict(singular="Recipe", plural="Recipes", prefix="", icon="book", desc="Recipes you share with clients.",
             fields=[("Recipe", "words:Lentil curry|Overnight oats|Salmon traybake|Chickpea salad|Veggie stir fry|Berry smoothie"), ("Time", "duration"), ("Used in plans", "int:1-30"), ("Added", "date"), ("Status", "status:Published|Draft")]),
        dict(singular="Check-in", plural="Check-ins", prefix="", icon="check", desc="Weekly updates from clients.",
             fields=[("Client", "person"), ("Energy", "choice:Great|Good|Okay|Low"), ("Plan followed", "pct:40-100"), ("Date", "date"), ("Status", "status:Reviewed|New")]),
        dict(singular="Session", plural="Sessions", prefix="", icon="calendar", desc="Coaching calls.",
             fields=[("Client", "person"), ("Type", "choice:First call|Follow-up|Group workshop"), ("Date", "date:future"), ("Time", "time"), ("Status", "status:Booked|Done|Cancelled")]),
    ],
    specials=[
        dict(title="Coaching calendar", type="calendar", icon="calendar", desc="Calls and workshops.", items=["First call", "Follow-up", "Group workshop", "Plan review", "Admin time"]),
        dict(title="Client progress", type="kanban", icon="kanban", desc="Clients from enquiry to finished.", items=["Enquiry", "First call", "Plan sent", "Coaching", "Finished"], cards=["More energy", "Sports nutrition", "Healthy weight", "Better digestion"]),
        dict(title="Progress report", type="report", icon="chart", desc="How clients are doing.", items=["Check-in rate", "Plan followed", "Energy score", "Renewals"], rows=["More energy", "Better digestion", "Sports", "Healthy weight", "Other"]),
        dict(title="Recipe library", type="gallery", icon="book", desc="Your favourite recipes.", items=["Lentil curry", "Overnight oats", "Salmon traybake", "Chickpea salad", "Veggie stir fry", "Berry smoothie"]),
        dict(title="Weekly plan", type="document", icon="file", desc="A printable meal plan layout.", doc="Weekly meal plan", num="Week 38, Maya", items=["Breakfasts", "Lunches", "Dinners", "Snacks", "Shopping list extras"], note="Swap any meal for one from your recipe list. Prices are a rough shopping estimate."),
        dict(title="Client messages", type="split", icon="message", desc="Messages between check-ins.", items=["Can I swap Tuesday's dinner?", "Eating out on Friday, tips?", "Felt so much better this week", "Question about snacks", "Can we move our call?"]),
        dict(title="Coaching settings", type="config", icon="settings", desc="How your coaching runs.", items=["Ask for check-ins every Sunday", "Send meal plans on Friday", "Remind clients before calls", "Share recipes by email"]),
    ],
))

B6.append(dict(
    num=63, slug="lodgewise", brand="Lodgewise", category="Hotel", org="The Harbour House Hotel", currency="$",
    tagline="Rooms, bookings, guests and housekeeping for a boutique hotel.",
    auth_line="Every guest, every room, looked after.", user="Olivia Ferreira", user_role="General manager",
    theme=dict(fonts=["Cormorant Garamond", "Montserrat", "Roboto Mono", "Montserrat"], accent="#a16207", layout="dark", card="shadow", radius="6px", sidebar="#1c1917",
               c2="#e7c98f", c3="#0f766e", c4="#6366f1"),
    kpis=[("Occupancy tonight", "pct", 86.4, "building"), ("Arrivals today", "int", 24, "users"), ("Average room rate", "money", 214, "dollar"), ("Revenue this month", "money", 412000, "trend")],
    chart=dict(title="Occupancy", names=["This year", "Last year"], base=78),
    mix=dict(title="Bookings by channel", parts=["Direct", "Travel sites", "Corporate", "Phone", "Walk-in"]),
    activity=["Guest checked in: Room 204", "Room 311 ready after cleaning", "Wedding group booking confirmed", "Late checkout approved", "Review: 5 stars on travel site", "Minibar restocked on floor 3"],
    entities=[
        dict(singular="Booking", plural="Bookings", prefix="BK-", icon="calendar", desc="Reservations for every room.",
             fields=[("Booking", "id"), ("Guest", "person"), ("Room", "choice:Standard|Deluxe|Suite|Family"), ("Arrival", "date:future"), ("Status", "status:Confirmed|Checked in|Cancelled|No show")]),
        dict(singular="Room", plural="Rooms", prefix="", icon="building", desc="All rooms and their state.",
             fields=[("Room", "code:"), ("Type", "choice:Standard|Deluxe|Suite|Family"), ("Rate", "money:140-620"), ("Floor", "int:1-5"), ("Status", "status:Occupied|Clean|Dirty|Out of order")]),
        dict(singular="Guest", plural="Guests", prefix="", icon="users", desc="Guests and their preferences.",
             fields=[("Guest", "person"), ("Country", "choice:United Kingdom|United States|France|Germany|Japan"), ("Stays", "int:1-14"), ("Spend", "money:200-9000"), ("Status", "status:In house|Arriving|Past guest")]),
        dict(singular="Housekeeping task", plural="Housekeeping", slug="housekeeping", prefix="", icon="check", desc="Cleaning and room checks.",
             fields=[("Room", "code:"), ("Task", "choice:Full clean|Stayover clean|Turn down|Deep clean"), ("Assigned to", "person"), ("Time", "time"), ("Status", "status:Done|In progress|Waiting")]),
        dict(singular="Folio", plural="Guest bills", slug="guest-bills", prefix="F-", icon="receipt", desc="Charges for each stay.",
             fields=[("Folio", "id"), ("Guest", "person"), ("Nights", "int:1-8"), ("Total", "money:150-6000"), ("Status", "status:Settled|Open|Disputed")]),
    ],
    specials=[
        dict(title="Room calendar", type="calendar", icon="calendar", desc="Arrivals, departures and events.", items=["Arrival", "Departure", "Wedding", "Conference", "Maintenance"]),
        dict(title="Room status", type="monitor", icon="activity", desc="Live room status by floor.", items=["Floor 1", "Floor 2", "Floor 3", "Floor 4", "Suites", "Family rooms"], unit="%"),
        dict(title="Housekeeping board", type="kanban", icon="kanban", desc="Rooms from checkout to ready.", items=["Checked out", "Cleaning", "Inspection", "Ready"], cards=["Room 204", "Room 311", "Suite 5", "Room 118"]),
        dict(title="Revenue report", type="report", icon="chart", desc="Occupancy, rates and revenue.", items=["Occupancy", "Average rate", "Revenue per room", "Direct bookings"], rows=["Standard", "Deluxe", "Suite", "Family", "Events"]),
        dict(title="Guest bill", type="document", icon="receipt", desc="A printable guest bill.", doc="Guest folio", num="F-1047, Room 204", items=["Deluxe room, 3 nights", "Breakfast", "Room service", "Spa treatment"], note="Thank you for staying with us. We hope to welcome you back soon."),
        dict(title="Guest requests", type="split", icon="message", desc="Messages from guests.", items=["Can I check in early?", "Extra pillows for room 311", "Airport taxi for tomorrow", "Dinner reservation for two", "Lost property question"]),
        dict(title="Booking rules", type="config", icon="settings", desc="Rates and policies.", items=["Free cancellation up to 48 hours before arrival", "Charge the first night on no-shows", "Offer late checkout to returning guests", "Raise rates when occupancy passes 90 percent"]),
    ],
))

B6.append(dict(
    num=64, slug="tabletop", brand="Tabletop", category="Restaurant POS", org="Olive and Ember Kitchen", currency="$",
    tagline="Orders, tables, menu and staff for a busy restaurant.",
    auth_line="From order to table, without the chaos.", user="Carlos Rossi", user_role="Restaurant manager",
    theme=dict(fonts=["Archivo Black", "Archivo", "Space Mono", "Archivo"], accent="#dc2626", layout="light", card="border", radius="10px",
               c2="#fca5a5", c3="#f59e0b", c4="#16a34a"),
    kpis=[("Sales today", "money", 8420, "dollar"), ("Covers", "int", 186, "users"), ("Average bill", "money", 45, "receipt"), ("Tables open", "int", 14, "grid")],
    chart=dict(title="Sales by hour", names=["Today", "Last week"], base=900),
    mix=dict(title="Sales by category", parts=["Mains", "Starters", "Drinks", "Desserts", "Sides"]),
    activity=["Table 12 paid $184", "Order sent to kitchen: table 6", "Special added: wild mushroom risotto", "Stock low: burrata", "Staff clocked in: Nadia", "Booking for 8 at 7:30pm"],
    entities=[
        dict(singular="Order", plural="Orders", prefix="#", icon="receipt", desc="Every order today.",
             fields=[("Order", "id"), ("Table", "code:T"), ("Server", "person"), ("Total", "money:18-420"), ("Status", "status:Paid|Open|Sent to kitchen|Void")]),
        dict(singular="Table", plural="Tables", prefix="", icon="grid", desc="Tables on the floor.",
             fields=[("Table", "code:T"), ("Seats", "int:2-10"), ("Server", "person"), ("Time seated", "duration"), ("Status", "status:Occupied|Free|Reserved|Cleaning")]),
        dict(singular="Menu item", plural="Menu", slug="menu", prefix="", icon="list", desc="Dishes and drinks.",
             fields=[("Item", "words:Wood fired pizza|Burrata salad|Lamb shoulder|Wild mushroom risotto|Tiramisu|House lemonade"), ("Category", "choice:Starters|Mains|Desserts|Drinks"), ("Price", "money:6-38"), ("Sold today", "int:0-80"), ("Status", "status:Available|Low stock|Off menu")]),
        dict(singular="Reservation", plural="Reservations", prefix="", icon="calendar", desc="Tables booked ahead.",
             fields=[("Guest", "person"), ("Party", "int:2-12"), ("Date", "date:future"), ("Time", "time"), ("Status", "status:Confirmed|Waiting|Cancelled")]),
        dict(singular="Staff member", plural="Staff", slug="staff", prefix="", icon="users", desc="Servers, chefs and bar staff.",
             fields=[("Name", "person"), ("Role", "choice:Server|Chef|Bartender|Host|Kitchen porter"), ("Shift", "choice:Lunch|Dinner|Double"), ("Sales today", "money:0-3000"), ("Status", "status:On shift|Break|Off")]),
    ],
    specials=[
        dict(title="Kitchen display", type="kanban", icon="kanban", desc="Orders as the kitchen sees them.", items=["New", "Cooking", "Ready", "Served"], cards=["Table 6: 2 pizzas", "Table 12: lamb x2", "Table 3: risotto", "Table 9: starters"], who="company"),
        dict(title="Floor plan", type="map", icon="map", desc="Tables and how busy they are.", items=["Main room", "Window tables", "Terrace", "Bar", "Private room"], dots=16),
        dict(title="Sales report", type="report", icon="chart", desc="Sales, covers and best sellers.", items=["Sales", "Covers", "Average bill", "Tips"], rows=["Mains", "Starters", "Drinks", "Desserts", "Sides"]),
        dict(title="Best sellers", type="ranking", icon="star", desc="Dishes sold most this week.", items=["Wood fired pizza", "Burrata salad", "Lamb shoulder", "Tiramisu", "Wild mushroom risotto", "House lemonade"], metric="Sold", scale=4),
        dict(title="Booking calendar", type="calendar", icon="calendar", desc="Reservations and private events.", items=["Table for 2", "Table for 6", "Private dinner", "Birthday", "Wine tasting"]),
        dict(title="Receipt", type="document", icon="receipt", desc="A printable table receipt.", doc="Receipt", num="Order #1047, table 12", items=["Burrata salad", "Wood fired pizza", "Lamb shoulder", "House lemonade", "Tiramisu"], note="Service is not included. Thank you for dining with us."),
        dict(title="POS settings", type="config", icon="settings", desc="How the till works.", items=["Send orders to the kitchen screen", "Ask for a manager code to void items", "Add a service charge for tables of 8 or more", "Print a receipt for every card payment"]),
    ],
))

B6.append(dict(
    num=65, slug="dashcart", brand="Dashcart", category="Food Delivery", org="Dashcart Delivery", currency="$",
    tagline="Orders, riders, restaurants and delivery times for a delivery service.",
    auth_line="Hot food, delivered fast.", user="Yusuf Kim", user_role="City operations lead",
    theme=dict(fonts=["Chivo", "Chivo", "Chivo Mono"], accent="#16a34a", layout="dark", card="shadow", radius="14px", sidebar="#0c1a12",
               c2="#86efac", c3="#f97316", c4="#3b82f6"),
    kpis=[("Orders today", "int", 6420, "cart"), ("Riders online", "int", 284, "truck"), ("Average delivery min", "int", 27, "clock"), ("Order value", "money", 162000, "dollar")],
    chart=dict(title="Orders per hour", names=["Today", "Last week"], base=520),
    mix=dict(title="Orders by cuisine", parts=["Pizza", "Burgers", "Asian", "Healthy", "Other"]),
    activity=["Rush hour started: 480 orders in 30 minutes", "Restaurant paused: kitchen busy", "Rider bonus zone added downtown", "Refund issued for late order", "New restaurant joined: Green Bowl", "Promo code LUNCH20 used 812 times"],
    entities=[
        dict(singular="Order", plural="Orders", prefix="D-", icon="cart", desc="Orders placed today.",
             fields=[("Order", "id"), ("Restaurant", "company"), ("Customer", "person"), ("Total", "money:8-120"), ("Status", "status:Delivered|On the way|Preparing|Cancelled")]),
        dict(singular="Rider", plural="Riders", prefix="", icon="truck", desc="Riders and their shifts.",
             fields=[("Rider", "person"), ("Vehicle", "choice:Bike|E-bike|Scooter|Car"), ("Deliveries today", "int:0-32"), ("Rating", "rating"), ("Status", "status:Online|Delivering|Offline")]),
        dict(singular="Restaurant", plural="Restaurants", prefix="", icon="building", desc="Partner restaurants.",
             fields=[("Restaurant", "company"), ("Cuisine", "choice:Pizza|Burgers|Asian|Healthy|Mexican"), ("Orders today", "int:4-400"), ("Prep time min", "int:8-35"), ("Status", "status:Open|Busy|Paused|Closed")]),
        dict(singular="Customer", plural="Customers", prefix="", icon="users", desc="People ordering food.",
             fields=[("Customer", "person"), ("City", "city"), ("Orders", "int:1-120"), ("Spent", "money:10-4000"), ("Status", "status:Active|New|Inactive")]),
        dict(singular="Promo", plural="Promotions", slug="promotions", prefix="", icon="tag", desc="Discount codes and offers.",
             fields=[("Code", "words:LUNCH20|FREEDEL|NEWUSER|PIZZAFRI|HEALTHY10"), ("Uses", "int:20-4000"), ("Discount", "pct:5-30"), ("Ends", "date:future"), ("Status", "status:Live|Scheduled|Ended")]),
    ],
    specials=[
        dict(title="Live map", type="map", icon="map", desc="Riders and orders across the city.", items=["Downtown", "University", "Riverside", "Old Town", "Business park"], dots=26),
        dict(title="Order board", type="kanban", icon="kanban", desc="Orders from placed to delivered.", items=["Placed", "Accepted", "Preparing", "Picked up", "Delivered"], cards=["Pizza order", "Burger meal", "Sushi box", "Salad bowl"], money=True, who="company"),
        dict(title="City health", type="monitor", icon="activity", desc="Live delivery times by zone.", items=["Downtown", "University", "Riverside", "Old Town", "Business park", "Airport", "North hills", "Harbour"], unit=" min"),
        dict(title="Delivery report", type="report", icon="chart", desc="Speed, volume and refunds.", items=["Orders", "Delivery time", "Refund rate", "Rider pay"], rows=["Pizza", "Burgers", "Asian", "Healthy", "Mexican"]),
        dict(title="Top restaurants", type="ranking", icon="star", desc="Restaurants with the most orders.", items=["Green Bowl", "Slice House", "Wok Street", "Burger Barn", "Taco Loco", "Sushi Go"], metric="Orders", scale=6),
        dict(title="Support chats", type="split", icon="inbox", desc="Customer and rider messages.", items=["My order is late", "Missing item: drink", "Rider cannot find the address", "Wrong order delivered", "Great service, thank you"]),
        dict(title="Delivery rules", type="config", icon="settings", desc="Settings for the city.", items=["Pause restaurants when prep time passes 40 minutes", "Add surge pay for riders when it rains", "Refund automatically for orders over 60 minutes late", "Limit each rider to 2 orders at once"]),
    ],
))
